add encryption
PaddlePaddle/FastDeploy pull request #1002
Opened 2022-12-28 14:31 UTC by HexToString

### PR types(PR类型)

Other
### Description

add encryption module (3 function):
        encrypt
        decrypt
        generate_key

add test_encryption.py

2022-12-29 02:30 UTC, jiangjiajun requested changes

2022-12-29 02:30 UTC, jiangjiajun commented on cmake/openssl.cmake
> +endfunction()
Download and extract在FD里面已经有现成的函数，可以参考下opencv.cmake，它也需要下载和解压，直接复用即可

2022-12-29 02:30 UTC, jiangjiajun commented on cmake/openssl.cmake
> +        SET(OPENSSL_INCLUDE_DIR "${OPENSSL_INSTALL_DIR}/include" CACHE PATH "openssl include directory." FORCE)
这个只有.a， Windows及其它平台上是否可以支持

2022-12-29 02:30 UTC, jiangjiajun commented on fastdeploy/encryption/include/model_code.h
> +//   Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
encryption目录下的copyright都更新下到2022

2022-12-29 02:30 UTC, jiangjiajun commented on fastdeploy/encryption/include/decrypt.h
> +                  const std::string& key);
encryption有不少代码来源于PaddleX，那些命名暂且不管了。 新增的接口都按照FD中的规范采用驼峰命名，即DecryptStream/Decrypt ，并且新增加的接口添加代码注释

2022-12-29 02:30 UTC, jiangjiajun commented on fastdeploy/encryption/include/encrypt.h
> +                  const std::string& key = generate_random_key());
同上， 注释+命名

2022-12-29 02:30 UTC, jiangjiajun commented on fastdeploy/encryption/include/encrypt.h
> +                                 std::ostream &out_stream);
指针引用符靠左对齐

2022-12-29 06:38 UTC, HexToString commented on cmake/openssl.cmake
> +endfunction()
ok

2022-12-29 06:39 UTC, HexToString commented on fastdeploy/encryption/include/decrypt.h
> +                  const std::string& key);
ok

2023-01-03 01:46 UTC, jiangjiajun approved these changes

2023-01-03 01:46 UTC, jiangjiajun commented
需要解决一下冲突 @HexToString HexToString

2023-01-03 07:57 UTC, merged

2023-01-06 05:25 UTC, felixhjh commented
resolved #699