add sophgo backend
PaddlePaddle/FastDeploy pull request #1015
Opened 2022-12-29 09:56 UTC by fnavigate84

### PR types(PR类型)

### Description

2022-12-29 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1015) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1015) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: KhantiInNaraka<br/>:x: fnavigate84<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=1015) it.</sub>

2022-12-30 05:55 UTC, jiangjiajun requested changes

2022-12-30 05:55 UTC, jiangjiajun commented on cmake/sophgo.cmake
> +#endif ()
注释的debug代码需要删除

2022-12-30 05:55 UTC, jiangjiajun commented on docs/cn/build_and_install/sophgo.md
> +SOPHGO支持linux下进行编译,系统为Debian/Ubuntu
Python不能支持么？

2022-12-30 05:55 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/sophgo/cpp/README.md
> +# paddleclas C++部署示例
PaddleClas

2022-12-30 05:55 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/sophgo/cpp/preprocess_config.yaml
> +Global:
这个yaml文件跟模型里面自带的inference_cls.yaml是重复的么，是否可以移除

2022-12-30 05:55 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/sophgo/cpp/run_with_adb.sh
> +#!/bin/bash
这个文件在README.md中没提到怎么使用

2022-12-30 05:55 UTC, jiangjiajun commented on examples/vision/detection/yolov5/sophgo/README.md
> +# PaddleDetection SOPHGO部署示例
YOLOv5 SOPHGO部署示例

2022-12-30 05:55 UTC, jiangjiajun commented on examples/vision/detection/yolov5/sophgo/cpp/README.md
> +# PaddleDetection C++部署示例
YOLOv5 C++部署示例

2022-12-30 05:55 UTC, jiangjiajun commented on examples/vision/detection/yolov5/sophgo/cpp/run_with_adb.sh
> +HOST_SPACE=${PWD}
同上，这个脚本没看到怎么使用

2022-12-30 05:55 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/sophgo/cpp/run_with_adb.sh
> +#!/bin/bash
同上

2022-12-30 05:55 UTC, jiangjiajun commented on docs/cn/build_and_install/sophgo.md
> +# SOPHGO部署库编译
文档需同时在docs/en/build_and_install提供英文版本

2022-12-30 05:55 UTC, jiangjiajun commented on fastdeploy/backends/sophgo/sophgo_backend.h
> +struct SophgoBackendOption{
没有任何配置参数吗？

2022-12-30 05:55 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +  }else if (model_format == ModelFormat::SOPHGO) {
花括号后需要空格

2022-12-30 05:55 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/model.cc
> +    valid_cpu_backends = {Backend::SOPHGONPU2};
SOPHOGONPU2还支持CPU吗？ 另外这个后面加的2是表示2代吗

2022-12-30 07:09 UTC, fnavigate84 commented on examples/vision/classification/paddleclas/sophgo/cpp/preprocess_config.yaml
> +Global:
已经移除

2022-12-30 07:09 UTC, fnavigate84 commented on examples/vision/classification/paddleclas/sophgo/cpp/README.md
> +# paddleclas C++部署示例
已经修改

2022-12-30 07:09 UTC, fnavigate84 commented on cmake/sophgo.cmake
> +#endif ()
已经去掉注释

2022-12-30 07:10 UTC, fnavigate84 commented on examples/vision/classification/paddleclas/sophgo/cpp/run_with_adb.sh
> +#!/bin/bash
这个文件没有用，已经移除了

2022-12-30 07:54 UTC, fnavigate84 commented on docs/cn/build_and_install/sophgo.md
> +# SOPHGO部署库编译
已经添加英文版本。

2022-12-30 07:55 UTC, fnavigate84 commented on fastdeploy/runtime.cc
> +  }else if (model_format == ModelFormat::SOPHGO) {
已加

2022-12-30 08:54 UTC, fnavigate84 commented on fastdeploy/vision/classification/ppcls/model.cc
> +    valid_cpu_backends = {Backend::SOPHGONPU2};
这里写的有问题，已经做了修改。

2023-01-04 03:14 UTC, jiangjiajun requested changes

2023-01-04 03:14 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/sophgo/cpp/CMakeLists.txt
> +target_link_libraries(infer_demo ${FASTDEPLOY_LIBS})
17-18行不需要

2023-01-04 03:14 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/sophgo/cpp/CMakeLists.txt
> +install(PROGRAMS ${TIMVX_LIBS} DESTINATION lib)
20~39行与sophgo也无关系，可以移除

2023-01-04 03:14 UTC, jiangjiajun commented on examples/vision/detection/yolov5/sophgo/README.md
> +# PaddleDetection SOPHGO部署示例
这个标题需要修改，当前目录为YOLOv5

2023-01-04 03:14 UTC, jiangjiajun commented on examples/vision/detection/yolov5/sophgo/cpp/CMakeLists.txt
> +install(PROGRAMS ${TIMVX_LIBS} DESTINATION lib)
同Clas中的CMAKE，移除不必要的代码

2023-01-04 03:14 UTC, jiangjiajun commented on examples/vision/detection/yolov5/sophgo/cpp/README.md
> +# PaddleDetection C++部署示例
同上

2023-01-04 03:14 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/sophgo/cpp/CMakeLists.txt
> +install(PROGRAMS ${TIMVX_LIBS} DESTINATION lib)
同前面的CMAKE问题

2023-01-04 03:14 UTC, jiangjiajun commented on fastdeploy/backends/sophgo/sophgo_backend.cc
> +#include "fastdeploy/backends/sophgo/sophgo_backend.h"
参照其它代码添加copyright在代码开头

2023-01-04 03:44 UTC, fnavigate84 commented on examples/vision/classification/paddleclas/sophgo/cpp/CMakeLists.txt
> +target_link_libraries(infer_demo ${FASTDEPLOY_LIBS})
已经修改

2023-01-04 03:51 UTC, fnavigate84 commented on examples/vision/classification/paddleclas/sophgo/cpp/CMakeLists.txt
> +install(PROGRAMS ${TIMVX_LIBS} DESTINATION lib)
已经删除

2023-01-04 03:55 UTC, fnavigate84 commented on examples/vision/detection/yolov5/sophgo/cpp/CMakeLists.txt
> +install(PROGRAMS ${TIMVX_LIBS} DESTINATION lib)
已经修改

2023-01-04 03:57 UTC, fnavigate84 commented on fastdeploy/backends/sophgo/sophgo_backend.cc
> +#include "fastdeploy/backends/sophgo/sophgo_backend.h"
已经添加

2023-01-04 07:49 UTC, jiangjiajun approved these changes

2023-01-04 07:49 UTC, merged