Add external model's example code and Docs.
PaddlePaddle/FastDeploy pull request #102
Opened 2022-08-11 14:52 UTC by ziqi-jin

- nanodet_plus code
- yolor code
- yolov6 code
- yolov5lite code
- yolox code
- scaled yolov4 code
- retinaface code
- scrfd code
- ultraface code
- yolov5face code
- arcface code
- cosface code
- partial_fc code
- vpl code
- modnet code

2022-08-12 06:49 UTC, DefTruth requested changes

2022-08-12 06:49 UTC, DefTruth commented on examples/vision/detection/nanodet_plus/python/infer.py
> +result = model.predict(im)
改成predict(im.copy())，其他案例同理

2022-08-12 06:49 UTC, DefTruth commented on examples/vision/detection/nanodet_plus/python/infer.py
> +result = model.predict(im)
在predict之后加一句print(result)，其他案例同理

2022-08-12 09:29 UTC, jiangjiajun commented
![f0d213d3bbf4b008f5ee3eb4127be787](https://user-images.githubusercontent.com/19339784/184326520-7075e907-10ed-4fad-93f8-52d0e35d4964.jpg)

2022-08-12 12:13 UTC, merged

2022-08-24 08:25 UTC, DefTruth commented
## YOLOv7End2EndORT  
<img width="639" alt="image" src="https://user-images.githubusercontent.com/31974251/186369053-1b578d61-ca70-4755-9671-c9fccf6314a0.png">

2022-08-25 07:45 UTC, DefTruth commented
## YOLOv7End2EndTRT
<img width="640" alt="image" src="https://user-images.githubusercontent.com/31974251/186605967-ad0c53f2-3ce8-4032-a90f-6f5c1238e7f4.png">