Yolov7Face 增加predict的python接口
PaddlePaddle/FastDeploy pull request #1039
Opened 2023-01-03 09:13 UTC by CoolKbh

### PR types(PR类型)

### Description
在/fast deploy/vision.h中class YOLOv7Face(FastDeployModel):下增加predict接口

2023-01-03 10:23 UTC, jiangjiajun requested changes

2023-01-03 10:23 UTC, jiangjiajun commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image, conf_threshold=0.5, nms_iou_threshold=0.45):
先前已经确认后面predict只接收image，不再附加其它参数。 conf_threshold, nms_iou_threshold都改为调用preprocessor和postprocessor来修改

2023-01-03 10:36 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image, conf_threshold=0.5, nms_iou_threshold=0.45):
好的

2023-01-03 13:33 UTC, wjj19950828 requested changes

2023-01-03 13:33 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image,):
逗号去掉

2023-01-04 02:57 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image,):
done

2023-01-04 05:20 UTC, wjj19950828 approved these changes

2023-01-04 05:25 UTC, merged