[CVCUDA] CMake integration, vison processor CV-CUDA integration, resize op
PaddlePaddle/FastDeploy pull request #1074
Opened 2023-01-05 12:55 UTC by wang-xinyu

### PR types(PR类型)

CV-CUDA

### Description

- CMake CV-CUDA integration
- Vision processor CV-CUDA integration
- Support first CV-CUDA op -- Resize

2023-01-13 06:31 UTC, wang-xinyu commented
Tested the model Predict(), warmup 100 rounds，tested 1000 rounds and get avg. latency.
CPU: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
GPU: T4

```
ResNet50 224x224,  Image size: 2560x1440

Paddle GPU FP32
OpenCV -> CV-CUDA
13.6342ms  -> 13.8725ms

TRT FP16
OpenCV -> CV-CUDA
2.07771ms -> 2.68854ms   (CPU is faster, due to large image size, the H2D memcpy is slower)
```

```
ResNet50 224x224,  Image size: 640x480

Paddle GPU FP32
OpenCV -> CV-CUDA
12.9268ms -> 12.6009ms

TRT FP16
OpenCV -> CV-CUDA
1.74122ms -> 1.34564ms  Improved by 22.72%
```

```
PP-YOLOE 640x640, Image size: 1920x1080

TRT FP16
OpenCV -> CV-CUDA
14.6225ms -> 13.1827ms    Improved by 9.85%
```

```
PP-YOLOE 640x640, Image size: 640x480

TRT FP16
OpenCV -> CV-CUDA
14.4329ms -> 12.4032ms    Improved by 14.06%
```

2023-01-17 07:55 UTC, jiangjiajun requested changes

2023-01-17 07:55 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +    if (WithGpu()) SetStream(&((*images)[i]));
在FD里面，所有的if后面代码都用花括号括起来吧，不使用这种简写的方式。

2023-01-17 07:55 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +  if (WithGpu()) SyncStream();
同上

2023-01-17 07:55 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/base.cc
> +FDTensor* Processor::UpdateAndGetCachedTensor(
这部分是不是得放在Manager里面

2023-01-17 07:55 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/mat.h
> +#endif
先前讨论这个是在manager里面？

2023-01-17 08:17 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +    if (WithGpu()) SetStream(&((*images)[i]));
Fixed

2023-01-17 08:17 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +  if (WithGpu()) SyncStream();
Fixed

2023-01-17 08:59 UTC, jiangjiajun requested changes

2023-01-17 08:59 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/center_crop.cc
> +  std::cout << Name() << " cvcuda" << std::endl;
debug代码

2023-01-17 08:59 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/base.h
> +
virtual bool InferShape(in_shape) {
   return out_shape;
}

2023-01-17 08:59 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/base.cc
> +             "CV-CUDA requires cuda stream, please set stream for Mat");
InferShape 然后 ReallocteBuffer()

2023-01-17 08:59 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/base.h
> +  FDTensor* UpdateAndGetCachedTensor(
加下注释说明

2023-01-17 08:59 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/preprocessor.h
>    bool Run(std::vector<FDMat>* images, std::vector<FDTensor>* outputs);
ProcessorManager::Run(std::vector<FDMat>* images, std::vector<FDTensor>* outputs) {
   SetStream();
   Apply(images, outputs);
   syncStream();
}

ProcessorManager提供纯虚函数Apply

2023-01-17 08:59 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/manager.h
> +  void UseCuda(int gpu_id = -1);
```
void UseCuda(bool enable_cv_cuda = false, int gpu_id=-1);
bool CudaUsed()
```

2023-01-17 09:30 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/base.h
> +  FDTensor* UpdateAndGetCachedTensor(
Added

2023-01-17 10:48 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/preprocessor.h
>    bool Run(std::vector<FDMat>* images, std::vector<FDTensor>* outputs);
Done

2023-01-17 10:48 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/manager.h
> +  void UseCuda(int gpu_id = -1);
Done

2023-01-28 07:24 UTC, DefTruth commented on fastdeploy/vision/classification/ppcls/preprocessor.h
> +  virtual bool Apply(std::vector<FDMat>* images,
这里变成了Apply接口，看起来似乎没有和之前的Run接口统一，是否有可能会造成后续的使用混乱？是否有可能保持Run接口？

2023-01-28 07:24 UTC, DefTruth commented on fastdeploy/vision/common/processors/base.h
> +  FDTensor* UpdateAndGetCachedTensor(
这里我理解是想要在Processor的基类里边挂一个缓存池？然后后续各个子类可以复用这个池子

2023-01-28 07:24 UTC, DefTruth commented on fastdeploy/vision/common/processors/cvcuda_utils.h
> +#include "fastdeploy/utils/utils.h"
这个头文件是不是可以考虑放在源文件中？

2023-01-28 07:24 UTC, DefTruth commented on fastdeploy/vision/common/processors/manager.h
> +  bool Run(std::vector<FDMat>* images, std::vector<FDTensor>* outputs);
看到这里实现了Run，关于Run的接口暂时没问题了

2023-01-28 07:24 UTC, DefTruth commented on fastdeploy/vision/common/processors/manager.h
> +class FASTDEPLOY_DECL ProcessorManager {
有个疑问是，这个类的设计是只用于CUDA/CVCUDA？还是说是后续可能一个通用的呢？可以用于opencv或flycv的管理？

2023-01-28 07:24 UTC, DefTruth commented on fastdeploy/vision/common/processors/mat.h
> +  FDTensor* Tensor() {
这个mat.h里边的函数实现其实可以考虑都统一移到mat.cc中（历史遗留问题），看到目前只有部分移到了mat.cc，另一部分还是在mat.h。

2023-01-28 08:59 UTC, DefTruth approved these changes

2023-01-28 09:28 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/preprocessor.h
> +  virtual bool Apply(std::vector<FDMat>* images,
是的，Run接口保留了，定义在ProcessorManager中

2023-01-28 09:30 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/base.h
> +  FDTensor* UpdateAndGetCachedTensor(
目前每个继承自Processor类的预处理算子都会维护一个自己的缓存池子，没有复用，而是每个算子一个池子

2023-01-28 09:30 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/cvcuda_utils.h
> +#include "fastdeploy/utils/utils.h"
Done

2023-01-28 09:32 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/manager.h
> +class FASTDEPLOY_DECL ProcessorManager {
是通用的，通过ProcessorManager的UseCuda接口来打开CUDA/CVCUDA，不打开的情况下还是使用OpenCV/FlyCV

2023-01-28 09:33 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/mat.h
> +  FDTensor* Tensor() {
是的，新加的几个函数已经挪到了.cc中，其他的后续再逐步挪过去吧

2023-01-30 01:33 UTC, jiangjiajun approved these changes

2023-01-30 01:33 UTC, merged