add yolov7face example readme file
PaddlePaddle/FastDeploy pull request #1075
Opened 2023-01-05 17:05 UTC by CoolKbh

### PR types(PR类型)

### Description
add yolov7face example readme file

2023-01-06 02:36 UTC, wjj19950828 requested changes

2023-01-06 02:36 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/README.md
> +链接：[百度网盘](https://pan.baidu.com/s/1oIj3QgOohKpHGwJDxNvDsw) 提取码：ebv8
上面的pt文件去掉，直接提供已经导出好的ONNX模型，目前bos上已有的是这两个

https://bj.bcebos.com/paddlehub/fastdeploy/yolov7-lite-e.onnx

https://bj.bcebos.com/paddlehub/fastdeploy/yolov7-tiny-face.onnx

2023-01-17 08:50 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/README.md
> +链接：[百度网盘](https://pan.baidu.com/s/1oIj3QgOohKpHGwJDxNvDsw) 提取码：ebv8
done

2023-01-17 09:12 UTC, wjj19950828 approved these changes

2023-01-17 11:19 UTC, merged