add ocr, ppyoloe, picodet examples
PaddlePaddle/FastDeploy pull request #1076
Opened 2023-01-06 02:08 UTC by fnavigate84

### PR types(PR类型)

### Description

2023-01-06 02:13 UTC, jiangjiajun requested changes

2023-01-06 02:13 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
文档中没看到哪里写如何将NMS的部分去除？

2023-01-06 02:15 UTC, fnavigate84 commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
#由于TPU-MLIR当前不支持后处理算法，所以需要查看后处理的输入作为网络的输出
#具体方法为：output_names需要通过 https://netron.app/ 查看，搜索NonMaxSuppression节点
#查看INPUTS中boxes和scores的名字，这个两个名字就是我们所需的output_names

2023-01-06 02:15 UTC, fnavigate84 commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
84行

2023-01-06 02:21 UTC, fnavigate84 commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
要不这里加粗注明下

2023-01-06 03:06 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
了解，那确实得说明下output_names的设定方式

2023-01-06 03:29 UTC, fnavigate84 commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
这样写还不够详细是吧？

2023-01-06 03:54 UTC, fnavigate84 commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
> 

已经添加了图片说明

2023-01-06 05:46 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
图片文件直接在此PR下comment，然后获得链接贴在PR文档里，避免放其它的链接，如果第三方地址失败，文档图片对应失败

2023-01-06 05:57 UTC, fnavigate84 commented
how to find the output names of ppyoloe model.
![ppyoloe_output_names](https://user-images.githubusercontent.com/120167928/210939488-a37e6c8b-474c-4948-8362-2066ee7a2ecb.png)

2023-01-06 05:59 UTC, fnavigate84 commented on examples/vision/detection/paddledetection/sophgo/README.md
> +python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_s_300e_coco.pdparams
好的，已经修改链接

2023-01-10 08:34 UTC, jiangjiajun approved these changes

2023-01-10 08:34 UTC, merged