[Model] Support Insightface model inferenceing on RKNPU
PaddlePaddle/FastDeploy pull request #1113
Opened 2023-01-11 03:43 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Description

2023-01-11 03:46 UTC, Zheng-Bicheng commented
# 更新简介
* 更新模型转换方式，现在RKNPU导出的模型的名称能体现是否进行了量化
* 更新了insightface的rknpu2支持
* preprocess和其他模型一样同步DisableNormalize和DisablePermute操作
* preprocess删除permute变量，替换为disable_permute_变量
* 更新python example

2023-01-12 12:07 UTC, wjj19950828 requested changes

2023-01-12 12:07 UTC, wjj19950828 commented on examples/vision/faceid/insightface/rknpu2/cpp/CMakeLists.txt
> +# 指定下载解压后的fastdeploy库路径
现在统一用英文注释，所以代码以及cmake中如果有中文注释统一改下

2023-01-12 12:07 UTC, wjj19950828 commented on examples/vision/faceid/insightface/rknpu2/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-x.x.x.tgz
x.x.x还是注明下，现在FD是1.0.2版本，所以应该>=1.0.3

2023-01-12 12:07 UTC, wjj19950828 commented on examples/vision/faceid/insightface/rknpu2/cpp/README.md
> +> ArcFace::Predict(cv::Mat* im, FaceRecognitionResult* result)
现在传入都改为```const cv::Mat& im```，不传入指针了

2023-01-12 12:07 UTC, wjj19950828 commented on examples/vision/faceid/insightface/rknpu2/cpp/infer_arcface.cc
> +  tc.Start();
example中还是把计时部分代码去掉

2023-01-12 12:07 UTC, wjj19950828 commented on examples/vision/faceid/insightface/rknpu2/cpp/infer_arcface.cc
> +  fastdeploy::TimeCounter tc;
同上

2023-01-12 12:07 UTC, wjj19950828 commented on examples/vision/faceid/insightface/rknpu2/python/infer_arcface.py
> +# 余弦相似度
中文注释转为英文，下面同上

2023-01-12 12:07 UTC, wjj19950828 commented on fastdeploy/vision/faceid/contrib/insightface/preprocessor.h
> +  bool GetPermute() { return disable_permute_; }
增加api注释：/// get permute

2023-01-12 12:07 UTC, wjj19950828 commented on fastdeploy/vision/faceid/contrib/insightface/preprocessor.h
> +  void DisablePermute() { disable_permute_ = true; }
这个跟```SetPermute(false)```有什么区别呢，可以统一成一个吗

我看你把```permute_```去掉了，要不把对应获取以及修改permute的api全部去掉

只保留DisablePermute

2023-01-12 12:28 UTC, Zheng-Bicheng commented
@wjj19950828 更新了麻烦再看一下

2023-01-13 02:53 UTC, wjj19950828 approved these changes

2023-01-13 02:53 UTC, wjj19950828 commented on examples/vision/faceid/insightface/rknpu2/python/infer_arcface.py
> +# 配置runtime，加载模型
中文注释换成英文，下面同上，不要删掉，翻译一下即可

2023-01-13 09:01 UTC, Zheng-Bicheng commented
@jiangjiajun 大佬看一下还有没有问题

2023-01-14 12:40 UTC, jiangjiajun approved these changes

2023-01-14 12:40 UTC, merged