[Other] Add Function For Aligning Face With Five Points
PaddlePaddle/FastDeploy pull request #1124
Opened 2023-01-12 02:01 UTC by Zheng-Bicheng

### PR types(PR类型)
Other

### Description
更新5点人脸对齐代码

2023-01-12 02:03 UTC, Zheng-Bicheng commented
## 简介
更新人脸对齐代码，参考[InsightFace的人脸对齐代码](https://github.com/deepinsight/insightface/blob/master/recognition/_tools_/cpp_align/face_align.h)。由于FastDeploy中的人脸识别模型大部分都是112x112的输入，因此对人脸对齐模版做了针对性的修改，x坐标全部加8。

2023-01-12 07:20 UTC, Zheng-Bicheng commented
@DefTruth 需要写pybind吗?

2023-01-13 03:17 UTC, DefTruth requested changes
LGTM ~  可以提供一个转换的示例到PR的comment中吗，以便确认函数的效果

2023-01-13 03:17 UTC, DefTruth commented on fastdeploy/vision/utils/utils.h
> +    std::vector<std::array<float, 2>> std_landmarks = {{38.2946f, 51.6963f},
nice ~ 但这个函数需要增加函数注释，说明下每个参数的作用以及返回的结果。比如这个std_landmarks应该指的是标准脸的参考的5个点，并且按照函数的实现，目前应该是只能支持5个点。

2023-01-13 03:17 UTC, DefTruth commented on fastdeploy/vision/utils/face_align.cc
> +FASTDEPLOY_DECL std::vector<cv::Mat> AlignFaceWithFivePoints(
源文件中不需要加 FASTDEPLOY_DECL，在头文件中加即可

2023-01-13 03:17 UTC, DefTruth commented on fastdeploy/vision/utils/face_align.cc
> +  cv::Mat src(5, 2, CV_32FC1, std_landmarks.data());
我看SimilarTransform变换函数并没有对参考点位数量限制为5点，那AlignFaceWithFivePoints是否有肯能写成支持>=5的任意参考点位数量呢？

2023-01-13 03:24 UTC, Zheng-Bicheng commented on fastdeploy/vision/utils/face_align.cc
> +  cv::Mat src(5, 2, CV_32FC1, std_landmarks.data());
我查了一下，一般带关键点的FaceDetection模型分为5点和72点，理论上一样的方法是可以支持其他模型的。但是有个问题是72点的模版我目前没有，后续如果找到了我再提一个PR更新吧

2023-01-13 03:31 UTC, Zheng-Bicheng commented
![372d242bcc39ff6a6ee2eb0426e3a626](https://user-images.githubusercontent.com/58363586/212230824-049ac315-1b49-4089-82c7-02b0d31ea662.jpeg)

2023-01-13 03:33 UTC, DefTruth commented on fastdeploy/vision/utils/face_align.cc
> +  cv::Mat src(5, 2, CV_32FC1, std_landmarks.data());
ok，那先实现5点的，这样也没问题

2023-01-13 03:35 UTC, DefTruth commented
> @DefTruth 需要写pybind吗?

目前utils模块还不成熟，所以暂时可以先不用写pybind

2023-01-13 09:00 UTC, Zheng-Bicheng commented
@jiangjiajun 大佬看一下还有没有问题哦

2023-01-13 11:47 UTC, DefTruth requested changes

2023-01-13 11:47 UTC, DefTruth commented on fastdeploy/vision/utils/utils.h
> +/***************************************************************
函数注释风格需要和主库一致，参考：  
- https://github.com/PaddlePaddle/FastDeploy/blob/release/1.0.2/fastdeploy/vision/detection/ppdet/model.h

2023-01-14 08:14 UTC, Zheng-Bicheng commented on fastdeploy/vision/utils/utils.h
> +/***************************************************************
done

2023-01-14 12:41 UTC, merged