[Model] 重构PPOCR代码已支持固定shape推理
PaddlePaddle/FastDeploy pull request #1147
Opened 2023-01-14 12:32 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Description
重构PPOCR代码已支持固定shape推理

2023-01-14 12:42 UTC, Zheng-Bicheng commented
## 修改内容

* 新增PPOCR对固定shape推理设备的支持
* 重构代码

## 重构代码详情
* 重构代码，preprocess Run的部分两个循环可以合并放一个循环做
* 类似images->size() == 0 改为 images->empty()
* start_index < 0 永远为 false删除这个条件
* `SingleBatchPostprocessor`函数 永远返回true 删除对 `SingleBatchPostprocessor` 错误的判断
* push_back 改为 emplace_back

2023-01-14 12:46 UTC, Zheng-Bicheng commented
## 输出结果展示

### 检测部分
![vis_result](https://user-images.githubusercontent.com/58363586/212472212-7ec7f757-ef75-4e03-a7dd-0949f0dd7262.jpg)

### 识别部分
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/58363586/212472198-9cf5b8c6-688a-4fbc-bb83-28dc2e2bfc04.png">

2023-01-14 12:47 UTC, Zheng-Bicheng commented
目前仅测试了PPOCRV2

2023-01-16 12:12 UTC, yunyaoXYY requested changes

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +  if (fixed_shape_) {
rec提供了静态shape的适配，为什么这里又多了一个fixed_shape，能否用下面的static_shape_infer_达到同样的目的呢

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +    if (!indices.empty()) {
为什么要做这种修改呢

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.h
> +  void SetMean(std::vector<float> mean) { mean_ = std::move(mean); }
多处添加了 std::move用法，是RK必须这么做吗？ 使用std::move前后有性能对比吗，是否有提升呢

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.h
> +  void SetFixedShape(bool fixed_shape) { fixed_shape_ = fixed_shape; }
这里可以复用SetStaticShapeInfer吗

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  m_vec.emplace_back(" ");
为什么要这么改，有性能提升吗

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  score /= static_cast<float>(count + 1e-6);
为什么要加一个cast呢，不加的话，RK这里会出错吗

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  const auto* tensor_data = reinterpret_cast<const float*>(tensor.Data());
这里为什么要 float改auto呢

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.cc
> +  if (fixed_shape_) {
建议和rec改成同样的名字, static_shape_infer

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/cls_postprocessor.cc
> +  const auto* tensor_data = reinterpret_cast<const float*>(tensor.Data());
为什么float改auto

2023-01-16 12:12 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  if (fixed_shape_) {
cls模型这里本来就是固定shape推理，为什么这里要增加这个呢

2023-01-16 12:14 UTC, yunyaoXYY commented
同时建议, 改一下PR的名字.  1. 突出是给det模型匹配静态shape推理( cls本来就是静态shape，rec模型已经提供静态shape支持） 2. PR标题用英文

2023-01-17 01:18 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.h
> +  void SetMean(std::vector<float> mean) { mean_ = std::move(mean); }
避免拷贝

2023-01-17 01:18 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +    if (!indices.empty()) {
让代码更直观，性能上没改变

2023-01-17 01:23 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  const auto* tensor_data = reinterpret_cast<const float*>(tensor.Data());
优化器自动优化了

2023-01-17 01:26 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/cls_postprocessor.cc
> +  const auto* tensor_data = reinterpret_cast<const float*>(tensor.Data());
优化器自动优化了

2023-01-17 01:28 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  m_vec.emplace_back(" ");
省去拷贝的过程，性能有提升

2023-01-17 01:29 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  m_vec.emplace_back(" ");
emplace_back比push_back性能更优

2023-01-17 01:29 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  score /= static_cast<float>(count + 1e-6);
代码规范，更加直观这里转成了float

2023-01-17 02:17 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  const auto* tensor_data = reinterpret_cast<const float*>(tensor.Data());
这里不建议修改，能不用auto就不要用auto，可读性不好。（本质上没区别）

2023-01-17 02:20 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  const auto* tensor_data = reinterpret_cast<const float*>(tensor.Data());
了解

2023-01-17 05:57 UTC, yunyaoXYY commented
OCR的CI没有过, 预测结果存在diff

2023-01-17 06:32 UTC, jiangjiajun requested changes

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_postprocessor.cc
> +    SingleBatchPostprocessor(tensor_data + i_batch * length, length,
这里为什么需要修改？

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.h
> +  void SetMean(std::vector<float> mean) { mean_ = std::move(mean); }
这里改成`SetMean(const std::vector<float>&)`， 下面同理

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.h
> +  void OcrClassifierResizeImage(FDMat* mat);
mark: 这个函数是从哪里来的

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_postprocessor.cc
> +                             &results->at(i_batch));
这里为什么要去除return false的判断

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_postprocessor.h
> +  void SetDetDBScoreMode(std::string det_db_score_mode) {
这里要改成const std::string&

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.cc
> +                           max_resize_h);
Mark: 这里的逻辑需要说明清楚

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetMean(std::vector<float> mean) { mean_ = std::move(mean); }
同上，改为const std::vector<float>&

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(std::vector<int> det_image_shape) {
const std::vector<int>&
另外此处逻辑需要说明清楚

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +        cv::imwrite(file_name + ".jpg", image_list[i_box]);
此处的debug代码需要删除

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
>      if (nullptr != classifier_) {
这里的改动逻辑需要说明清楚

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
>      std::vector<float> width_list;
逻辑需要说明清楚

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +    OcrRecognizerResizeImage(mat, max_wh_ratio);
Mark， 逻辑需要说明清楚

2023-01-17 06:32 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.h
> +  void SetMean(std::vector<float> mean) { mean_ = std::move(mean); }
同上，改为const std::vector<float>&

2023-01-17 06:54 UTC, jiangjiajun requested changes

2023-01-17 06:54 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  if (fixed_shape_) {
那这里本来就是固定的，可以删除现在的逻辑判断

2023-01-17 06:54 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.h
> +  void OcrClassifierResizeImage(FDMat* mat);
因为函数需要读取类成员函数，从外部独立函数移到类内实现

2023-01-17 06:54 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.cc
> +  if (fixed_shape_) {
这里复用之前已有的静态推理方法

2023-01-17 06:54 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +  if (fixed_shape_) {
确认跟原先逻辑是否可以复用

2023-01-17 06:54 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.h
> +  void SetFixedShape(bool fixed_shape) { fixed_shape_ = fixed_shape; }
确认是否可以复用

2023-01-17 07:03 UTC, closed without merging