[Android] support fastdeploy build with static deps(67Mb->17~19Mb)
PaddlePaddle/FastDeploy pull request #1176
Opened 2023-01-22 17:18 UTC by DefTruth

### PR types(PR类型)

Android

### Description

- [x] 支持FastDeploy Android库静态链接所有依赖库（opencv、flycv、paddle lite）, 最终可获得不依赖第三方库的libfastdeploy.so
- [x] 增加fastdeploy_jni.cmake支持编译主库时联编JNI so库（-DWITH_JAVA=ON）
- [x] c++库体积优化：67Mb->17~19Mb（arm64-v8a: 10-11Mb, armeabi-v7a: 7-8Mb）
- [ ] 支持编译fastdeploy静态库：libfastdeploy_static.a (30%)
- [ ] aar库体积优化（基于fastdeploy静态库或联编的libfastdeploy_jni.so）
- [ ] case测试

2023-01-23 10:00 UTC, jiangjiajun approved these changes

2023-01-24 14:54 UTC, ZeyuChen commented
支持合入，安卓应用库体积是关键问题 这条线可以持续告诉迭代 现在我理解移动端应用还未大规模铺开 所以可以快速优化

2023-01-24 14:54 UTC, ZeyuChen commented
支持合入，安卓应用库体积是关键问题 这条线可以持续告诉迭代 现在我理解移动端应用还未大规模铺开 所以可以快速优化

2023-01-30 01:49 UTC, jiangjiajun requested changes

2023-01-30 01:49 UTC, jiangjiajun commented on cmake/opencv.cmake
> +      list(APPEND DEPEND_LIBS opencv_core opencv_video opencv_highgui opencv_imgproc opencv_imgcodecs)
在动态库时改成使用OpenCV_LIBS。 对于用户在编译FastDeploy并集成OpenCV时（特别是在用户自定义OpenCV路径时），由于并不确认用户需要使用哪些功能（只知道FD需要哪些库），所以默认将所有opencv的lib都依赖

2023-01-30 01:49 UTC, jiangjiajun commented on fastdeploy/api_helpers.h
> +#if !defined(WITH_STATIC_LIB_AT_COMPILING)
这里引入这个标志的作用是什么，为什么不是判断ENABLE_LITE_BACKEND && WITH_STATIC_LIB来判断

2023-01-30 01:49 UTC, jiangjiajun commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +#endif
这里的判断方式跟上面不同

2023-01-30 02:35 UTC, DefTruth commented on cmake/opencv.cmake
> +      list(APPEND DEPEND_LIBS opencv_core opencv_video opencv_highgui opencv_imgproc opencv_imgcodecs)
这里是由于在编译Android库，并链接Paddle Lite静态库时，Lite里边也包含一份libprotobuf.a（已经合并在lite中），同时opencv的opencv_dnn, opencv_ml中也包含一份libprotobuf.a，如果链接全部的opencv模块，就会导致符号冲突。虽然能够指定链接器的flag来强制链接，但并不能确保ld能一定链接到lite的libprotobuf.a。如果此时是编译一个FD动态库，可以正常链接，但会有风险，因为ocv和lite中包含的libprotobuf.a版本不一样。如果是编译FD静态库，则会导致lite无法使用，这个已经验证过。所以，在Android平台下，如果是使用opencv静态库，则只链接需要的库，其他的库一般用不到，比如opencv_videoio，Android有自己的编解码模块，opencv_dnn, opencv_ml这些也用不到。这个修改只会影响Android。

2023-01-30 02:48 UTC, DefTruth commented on fastdeploy/api_helpers.h
> +#if !defined(WITH_STATIC_LIB_AT_COMPILING)
这个宏WITH_STATIC_LIB_AT_COMPILING是用来判断，当前是否处于编译FD静态库的编译期。
```cmake
target_compile_definitions(fastdelpoy_dummy PRIVATE WITH_STATIC_LIB_AT_COMPILING)
```
这里要区分FD静态库的编译期，以及FD静态库的使用期。这个头文件在runtime.h中有include。在FD静态库的编译期，由于编译的是静态库，所以不需要include这几个头文件，否则所有使用了runtime的.o文件中都会包含一份重复的定义，编译静态库时，编译期不会去调用ld链接器来检查，只是简单使用ar来合并.o文件。在FD静态库的使用期，则必须include这几个头文件，来执行lite op注册，否则会出现"使用静态库时全局变量未初始化"的问题。这个问题和paddle2onnx的静态库无法使用是一样的。

2023-01-30 02:57 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +#endif
是的，这里是必须不一样的。当使用静态库来编译FD库时，情况会变得复杂一些，我们要考虑至少两种情况。

|编译FD动态库|编译FD静态库|  
|---|---|   
|(defined(WITH_LITE_STATIC) && (!defined(WITH_STATIC_LIB))|(defined(WITH_LITE_STATIC) && (defined(WITH_STATIC_LIB))|  

WITH_STATIC_LIB代表是否在编译FD静态库。根据链接特性的不同，这两种情况需要分开处理。  
- 编译FD动态库：若此时链接lite静态库，参考lite的文档，需要在lite_backend.cc引入这几个头文件，确保op和kernel能被初始化。引入之后，这段逻辑也被编译FD的动态库中了，之后就不再需要使用这几个头文件。
- 编译FD静态库：若此时链接lite静态库，则op和kernel的注册必须延迟到用户使用时进行，并且不能在lite_backend.cc中引入，否则lite_backend.cc的.o文件中都会包含一份重复的op和kernel注册定义。因此，这几个头文件的引入是留到用户使用FD静态库时引入。

2023-01-30 10:02 UTC, jiangjiajun requested changes

2023-01-30 10:02 UTC, jiangjiajun commented on CMakeLists.txt
> +option(WITH_OPENCV_STATIC "Whether to use OpenCV static lib for Android." OFF)
if(ANDROID)

2023-01-30 11:39 UTC, merged