Add uie cpp deploy
PaddlePaddle/FastDeploy pull request #120
Opened 2022-08-16 07:43 UTC by joey12300

Add uie cpp deploy

2022-08-19 05:14 UTC, ZeyuChen reviewed
examples/text/uie/
按模型铺下来即可。
nlp不适合一个场景一类，因为很多是一个预训练模型能支持很多场景

2022-08-24 08:16 UTC, joey12300 commented
> examples/text/uie/ 按模型铺下来即可。 nlp不适合一个场景一类，因为很多是一个预训练模型能支持很多场景

Done

2022-08-24 08:17 UTC, joey12300 commented on FastDeploy.cmake.in
> +   # TODO (zhoushunjie): Will remove it later.
这里需要升级FasterTokenizer的目录结构。

2022-08-24 08:17 UTC, joey12300 commented on external/faster_tokenizer.cmake
> +    "${FASTERTOKENIZER_INSTALL_DIR}/third_party/include/faster_tokenizer" # TODO (zhoushunjie): Will remove it later.
同上，需要升级

2022-08-24 09:03 UTC, jiangjiajun requested changes

2022-08-24 09:03 UTC, jiangjiajun commented on examples/text/uie/cpp/README.md
> +tar xvf fastdeploy-linux-x64-gpu-0.2.0.tgz
这里先改成自行编译吧，下载上面这个，按这个文档也跑不通

UIE目前还未发布，当前需开发者自行编译FastDeploy，通过如下脚本编译得到部署库`fastdeploy-linux-x64-dev`
```
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd FastDeploy
mkdir build && cd build
cmake .. -DENABLE_ORT_BACKEND=ON  \
               -DENABLE_VISION=ON \
               -DENABLE_PADDLE_BACKEND=ON \
               -DENABLE_TEXT=ON \
               -DWITH_GPU=ON \
               -DCMAKE_INSTALL_PREFIX=${PWD}/fastdeploy-linux-x64-gpu-dev

make -j8
make install
```

编译UIE示例代码
```
cd ../examples/text/uie/cpp
mkdir build && cd build
cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/../../../../../build/fastdeploy-linux-x64-gpu-dev
make -j8
```

2022-08-24 09:06 UTC, joey12300 commented on examples/text/uie/cpp/README.md
> +tar xvf fastdeploy-linux-x64-gpu-0.2.0.tgz
OK，这里我改改。开始的时候想先占坑，就把vision的一些readme搞过来了。

2022-08-24 09:45 UTC, joey12300 commented on examples/text/uie/cpp/README.md
> +tar xvf fastdeploy-linux-x64-gpu-0.2.0.tgz
Done

2022-08-24 12:20 UTC, merged