[Backend] support bechmark mode for runtime and backend
PaddlePaddle/FastDeploy pull request #1201
Opened 2023-01-31 11:29 UTC by DefTruth

### PR types(PR类型)

Backend  

### Description
  
- 增加benchmark模式，通过-DENABLE_BENCHMARK=ON开启
  - [x] 支持统计不带H2D和D2H的纯推理引擎耗时  
  - [x] 支持benchmark模式下，取消各个模型hardcode的xxx_valid_backends限制 
  - [ ] 增加对应的pybind接口，支持python benchmark测试
  - [ ] 各个推理后端测试

2023-02-03 03:34 UTC, jiangjiajun commented on fastdeploy/fastdeploy_model.cc
> +#else
```
runtime_option.enable_profle();
runtime.infer()
runtime.get_profile_result()
···

```
model.get_profile_result()
```

1. 编译时EnableBenchmark不影响FastDeploy原有逻辑

2023-02-03 03:34 UTC, jiangjiajun commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +  FDASSERT(repeat > 0, "repeat param must > 0, but got %d", repeat);
Runtime::GetProfile


Runtime::BenchmarkResult

BaseBackend里面新增BenchmarkResult

2023-02-03 03:34 UTC, jiangjiajun commented on fastdeploy/runtime/backends/lite/lite_backend.h
> +#endif
删除

2023-02-03 03:34 UTC, jiangjiajun commented on fastdeploy/runtime/runtime.cc
> +#endif
删除

2023-02-03 03:34 UTC, jiangjiajun commented on fastdeploy/runtime/runtime.h
> +#endif
删除

2023-02-04 08:12 UTC, jiangjiajun requested changes

2023-02-04 08:12 UTC, jiangjiajun commented on fastdeploy/benchmark/option.h
> +  bool enable_profile = false;  ///< Wheter to use profile or not.
Whether

2023-02-04 08:12 UTC, jiangjiajun commented on python/fastdeploy/runtime.py
> +    def enable_profiling(self,
添加注释，C++代码头文件同样也需添加注释

2023-02-04 11:41 UTC, DefTruth commented on fastdeploy/benchmark/option.h
> +  bool enable_profile = false;  ///< Wheter to use profile or not.
done

2023-02-04 11:41 UTC, DefTruth commented on python/fastdeploy/runtime.py
> +    def enable_profiling(self,
done

2023-02-04 11:41 UTC, DefTruth commented on fastdeploy/fastdeploy_model.cc
> +#else
done

2023-02-04 11:42 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +  FDASSERT(repeat > 0, "repeat param must > 0, but got %d", repeat);
done

2023-02-04 11:42 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/lite_backend.h
> +#endif
done

2023-02-04 11:42 UTC, DefTruth commented on fastdeploy/runtime/runtime.cc
> +#endif
done

2023-02-04 11:42 UTC, DefTruth commented on fastdeploy/runtime/runtime.h
> +#endif
done

2023-02-06 01:51 UTC, jiangjiajun requested changes

2023-02-06 01:51 UTC, jiangjiajun commented on fastdeploy/benchmark/option.h
> +struct BenchmarkOption {
同样需要添加注释在struct上方，参照RuntimeOption

2023-02-06 01:51 UTC, jiangjiajun commented on fastdeploy/benchmark/results.h
> +struct BenchmarkResult {
同上

2023-02-06 02:56 UTC, DefTruth commented on fastdeploy/benchmark/results.h
> +struct BenchmarkResult {
done

2023-02-06 02:57 UTC, DefTruth commented on fastdeploy/benchmark/option.h
> +struct BenchmarkOption {
done

2023-02-06 02:57 UTC, DefTruth commented on fastdeploy/benchmark/results.h
> +struct BenchmarkResult {
done

2023-02-06 06:29 UTC, merged