[DOC]Renew how to develop a new model file
PaddlePaddle/FastDeploy pull request #1204
Opened 2023-02-01 06:11 UTC by CoolKbh

### PR types(PR类型)
 | Doc | 

### Description
更新Fastdeploy/fastdeploy/docs/cn/faq/develop_a_new_model.md

2023-02-02 11:44 UTC, wjj19950828 requested changes

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +| [1](#step2)    |  在fastdeploy/vision相应任务模块增加模型实现       | yolov7face.h、yolov7face.cc、preprocessor.h、preprocess.cc、postprocessor.h、postprocessor.cc、vision.h                     |
上面```以torchvision v0.12.0中的ResNet50```修改为YOLOv7Face，全局搜下全部替换

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +## 1 模型准备  <span id="step1"></span>
1、模型准备

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +在集成外部模型之前，先要将训练好的模型（.pt，.pdparams 等）转换成FastDeploy支持部署的模型格式（.onnx，.pdmodel）。多数开源仓库会提供模型转换脚本，可以直接利用脚本做模型的转换。例如yolov7face官方库提供的[export.py](https://github.com/derronqi/yolov7-face/blob/main/models/export
以yolov7face为例的话，给出yolov7face的onnx导出方式？

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +## 2 CPP代码实现  <span id="step2"></span>
2、CPP代码实现

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +### 2.1 前处理类实现
同上

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/preprocess.h (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/precessor.h)
FastDeploy/fastdeploy/vision/facedet/contrib/yolov7face/preprocess.h(FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/模型名/precessor.h)

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/preprocessor.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/preprocessor.cc)
修改同上

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +  // 执行前处理
```
// 执行前处理
Preprocess()
// 根据传入图片数量对每张图片处理，并返回结果
```

体现Run和Preprocess两者的关系

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/postprocessor.h (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/postprocessor.h)
同上

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/postprocessor.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/postprocessor.cc)
加上模型名

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/yolov7face.h (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/模型名.h)
加上模型名

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * 首先在yolov7face.h中创建 YOLOv7Face 类并继承FastDeployModel父类，之后声明`Predict`、`BatchPredict`、`Initialize`和`构造函数`，以及必要的变量及其`set`和`get`方法，具体的代码细节请参考[yolov7face.h](https://github.com/PaddlePaddle/FastDeploy/t
模型类YOLOv7Face无`set`方法

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/yolov7face.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/模型名.cc)
加上模型名

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +bool YOLOv7Face::Predict(cv::Mat& im, FaceDetectionResult* result) {
const cv::Mat&

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +bool YOLOv7Face::BatchPredict(cv::Mat& images, std::vector<FaceDetectionResult>* result) {
说明下```Predict ```与```BatchPredict ```的关系

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +#include "fastdeploy/vision/facedeet/contrib/yolov7face.h"
facedet

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +## 3 Python接口封装
3、Python接口封装

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +### 3.1 Pybind部分  <span id="step4"></span>
同上

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/yolov7face_pybind.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/模型名_pybind.cc)
加模型名

2023-02-02 11:44 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +virtual bool Predict(cv::Mat& im, FaceDetectionResult* result);
const cv::Mat&

2023-02-03 07:24 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +| [1](#step2)    |  在fastdeploy/vision相应任务模块增加模型实现       | yolov7face.h、yolov7face.cc、preprocessor.h、preprocess.cc、postprocessor.h、postprocessor.cc、vision.h                     |
done

2023-02-03 07:25 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +## 1 模型准备  <span id="step1"></span>
done

2023-02-03 07:25 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +## 2 CPP代码实现  <span id="step2"></span>
done

2023-02-03 07:31 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +### 2.1 前处理类实现
done

2023-02-03 07:32 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/preprocess.h (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/precessor.h)
done

2023-02-03 07:33 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/preprocessor.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/preprocessor.cc)
done

2023-02-03 07:36 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +  // 执行前处理
done

2023-02-03 07:36 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/postprocessor.h (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/postprocessor.h)
done

2023-02-03 07:37 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/postprocessor.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/postprocessor.cc)
done

2023-02-03 07:38 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/yolov7face.h (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/模型名.h)
done

2023-02-03 07:38 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * 首先在yolov7face.h中创建 YOLOv7Face 类并继承FastDeployModel父类，之后声明`Predict`、`BatchPredict`、`Initialize`和`构造函数`，以及必要的变量及其`set`和`get`方法，具体的代码细节请参考[yolov7face.h](https://github.com/PaddlePaddle/FastDeploy/t
done

2023-02-03 07:39 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/yolov7face.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/模型名.cc)
done

2023-02-03 07:40 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +bool YOLOv7Face::Predict(cv::Mat& im, FaceDetectionResult* result) {
done

2023-02-03 07:45 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +bool YOLOv7Face::BatchPredict(cv::Mat& images, std::vector<FaceDetectionResult>* result) {
done

2023-02-03 07:46 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +#include "fastdeploy/vision/facedeet/contrib/yolov7face.h"
done

2023-02-03 07:46 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +## 3 Python接口封装
done

2023-02-03 07:47 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +### 3.1 Pybind部分  <span id="step4"></span>
done

2023-02-03 07:48 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    * FastDeploy/fastdeploy/vision/facedet/contrib/yolov7face_pybind.cc (FastDeploy/C++代码存放位置/视觉模型/任务名称/外部模型/模型名_pybind.cc)
done

2023-02-03 07:49 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +virtual bool Predict(cv::Mat& im, FaceDetectionResult* result);
done

2023-02-06 06:28 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +在FastDeploy里面新增一个模型，包括增加C++/Python的部署支持。 本文以torchvision v0.12.0中的YOLOv7Face模型为例，介绍使用FastDeploy做外部[模型集成](#modelsupport)，具体包括如下3步。
以YOLOv7Face模型为例

2023-02-06 06:32 UTC, wjj19950828 approved these changes

2023-02-06 06:46 UTC, wjj19950828 requested changes

2023-02-06 06:46 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    .def_property_readonly("is_scale_up", ...);
readonly去掉

2023-02-06 06:46 UTC, wjj19950828 commented on docs/cn/faq/develop_a_new_model.md
> +    .def_property_readonly("nms_threshold", ...);
readonly去掉

2023-02-06 06:50 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +在FastDeploy里面新增一个模型，包括增加C++/Python的部署支持。 本文以torchvision v0.12.0中的YOLOv7Face模型为例，介绍使用FastDeploy做外部[模型集成](#modelsupport)，具体包括如下3步。
done

2023-02-06 06:51 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    .def_property_readonly("is_scale_up", ...);
done

2023-02-06 06:51 UTC, CoolKbh commented on docs/cn/faq/develop_a_new_model.md
> +    .def_property_readonly("nms_threshold", ...);
done

2023-02-07 12:10 UTC, wjj19950828 approved these changes

2023-02-08 11:46 UTC, merged