[CVCUDA] Utilize CV-CUDA batch processing function
PaddlePaddle/FastDeploy pull request #1223
Opened 2023-02-02 07:53 UTC by wang-xinyu

### PR types(PR类型)

### Description

2023-02-02 12:24 UTC, wang-xinyu commented
Tested accuracy on the CI data(50 images) with CI script https://github.com/felixhjh/fastdeploy_ci/blob/main/scripts_ci/test_resnet50_vd.py.

When using CV-CUDA, the top1 and top5 accuracy are same as OpenCV.

But the scores are slightly different.

OpenCV | CV-CUDA
<img width="853" alt="image" src="https://user-images.githubusercontent.com/15235574/216323655-e21c78ed-1b9b-497e-b6dc-e18779349fc1.png">

2023-02-02 13:29 UTC, wang-xinyu commented
Tested the model Predict() function, warmup 100 rounds，tested 1000 rounds and get avg. latency.
CPU: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
GPU: T4
Model: ResNet50 224x224
Backend: TensorRT FP16

|Image Shape| Batch Size | OpenCV | CV-CUDA | Gain |
|-|-|-|-|-|
| 640x480 | 1 | 1.81578ms | 1.46613ms |  19.3% |
| 640x480 | 4 | 5.1151ms | 3.47895ms | 32.0% | 
| 640x480 | 16 | 19.7402ms | 12.4244ms | 37.1% |

2023-02-04 08:32 UTC, jiangjiajun requested changes

2023-02-04 08:32 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/ppcls_pybind.cc
>             [](vision::classification::PaddleClasPreprocessor& self,
这个是继承的基类的函数，应该给基类绑定一个python接口，这样之后改造的各模型就无需再单独绑定`use_cuda`这个函数了

2023-02-04 08:32 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +    }
这个initial_resize_on_cpu_的参数是属于基类的，是否能够放到基类中去控制。否则后面所有继承这个基类的预处理，都得自行处理intialize_resize_on_cpu_的逻辑，影响预处理模块的通用性

2023-02-04 08:32 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/base.h
> +      if (ImplByCvCuda(&(*(mat_batch->mats))[i]) != true) {
这里看起来仍然是按照单张来处理的吗？

2023-02-06 02:20 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/base.h
> +      if (ImplByCvCuda(&(*(mat_batch->mats))[i]) != true) {
这里是基类的函数，如果没有重载，就按单张来处理的

2023-02-06 02:43 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/ppcls_pybind.cc
>             [](vision::classification::PaddleClasPreprocessor& self,
有道理，我改一下

2023-02-07 05:44 UTC, jiangjiajun approved these changes

2023-02-07 05:44 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/resize_by_short.cc
> +    Mat* mat = &(*(mat_batch->mats))[i];
Mat改名为FDMat, MatBatch改名为FDMatBatch

2023-02-07 05:44 UTC, merged