[Model] Refactoring code of YOLOv5Cls with new model type
PaddlePaddle/FastDeploy pull request #1237
Opened 2023-02-06 07:45 UTC by GodIsBoom

### PR types(PR类型)

Model
### Description

将YOLOv5Cls重构为分离前后处理的新方式，并添加了batch_predict支持
关联issue：https://github.com/PaddlePaddle/FastDeploy/issues/1225

2023-02-07 07:38 UTC, wjj19950828 requested changes

2023-02-07 07:38 UTC, wjj19950828 commented on fastdeploy/vision/classification/contrib/yolov5cls/preprocessor.cc
> +  HWC2CHW::Run(mat);
能否直接换成```NormalizeAndPermute```

2023-02-07 07:38 UTC, wjj19950828 commented on fastdeploy/vision/classification/contrib/yolov5cls/preprocessor.h
> +  /// Set target size, tuple of (width, height), default size = {352, 352}
默认值对齐，下面统一修改

2023-02-07 07:38 UTC, wjj19950828 commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        Argument for image preprocessing step, the preprocess image size, tuple of (width, height), default size = [352, 352]
默认值对齐

2023-02-07 07:38 UTC, wjj19950828 commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        """Detect an input image
YOLOv5Cls为一个分类模型，Detect->Classify

2023-02-07 07:38 UTC, wjj19950828 commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        :return: DetectionResult
同上

2023-02-07 07:38 UTC, wjj19950828 commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        assert len(images) == 1,"YOLOv5Cls is only support 1 image in batch_predict"
支持batch的话就把assert去掉

2023-02-07 07:40 UTC, jiangjiajun requested changes

2023-02-07 07:40 UTC, jiangjiajun commented on examples/vision/classification/yolov5cls/cpp/infer.cc
>    auto im_bak = im.clone();
这个demo也改下，删除im_bak = im.clone

2023-02-07 07:58 UTC, GodIsBoom commented on fastdeploy/vision/classification/contrib/yolov5cls/preprocessor.cc
> +  HWC2CHW::Run(mat);
尝试替换后，分类结果出错了，所以就先不替换了

2023-02-07 08:04 UTC, GodIsBoom commented on fastdeploy/vision/classification/contrib/yolov5cls/preprocessor.h
> +  /// Set target size, tuple of (width, height), default size = {352, 352}
done

2023-02-07 08:05 UTC, GodIsBoom commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        Argument for image preprocessing step, the preprocess image size, tuple of (width, height), default size = [352, 352]
done

2023-02-07 08:05 UTC, GodIsBoom commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        """Detect an input image
done

2023-02-07 08:07 UTC, GodIsBoom commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        :return: DetectionResult
done

2023-02-07 08:09 UTC, GodIsBoom commented on python/fastdeploy/vision/classification/contrib/yolov5cls.py
> +        assert len(images) == 1,"YOLOv5Cls is only support 1 image in batch_predict"
done

2023-02-07 08:15 UTC, GodIsBoom commented on examples/vision/classification/yolov5cls/cpp/infer.cc
>    auto im_bak = im.clone();
done

2023-02-08 03:16 UTC, wjj19950828 approved these changes

2023-02-08 03:19 UTC, merged