[Backend] Add fp16 support for ONNXRuntime-GPU
PaddlePaddle/FastDeploy pull request #1239
Opened 2023-02-06 13:14 UTC by yeliang2258

### PR types(PR类型)

Backend

### Description

Add fp16 support for ONNXRuntime-GPU

2023-03-14 03:47 UTC, jiangjiajun requested changes

2023-03-14 03:47 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +    FDWARNING << "FP16 only support on CPU, while the compiled fastdeploy with "
only support on GPU

2023-03-14 03:47 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +}
不加这段代码逻辑应该也不影响运行？

2023-03-14 03:47 UTC, jiangjiajun commented on fastdeploy/runtime/runtime_option.cc
> +void RuntimeOption::DisableOrtFP16() { ort_option.enable_fp16 = false; }
不加这俩函数了，直接让用option.ort_option.enable_fp16 = true或false即可，与trt保持一致

2023-03-14 03:47 UTC, jiangjiajun commented on fastdeploy/runtime/runtime_option.h
> +  void DisableOrtFP16();
同上

2023-03-14 03:47 UTC, jiangjiajun commented on python/fastdeploy/runtime.py
> +        self._option.ort_option.enable_fp16 = False
同上

2023-03-14 03:47 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.h
> +  bool use_fp16();
同上

2023-03-14 03:47 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.h
> +  bool convert_to_fp16 = false;
已经有option.enable_fp16了，就不用添加convert_to_fp16了

2023-03-14 08:21 UTC, yeliang2258 commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +}
不影响，但是会导致运行变慢，里面几乎每一个OP都加了cast

2023-03-14 12:05 UTC, yeliang2258 commented on fastdeploy/runtime/backends/ort/ort_backend.h
> +  bool convert_to_fp16 = false;
option是一个const，无法改变。convert_to_fp16是用来辅助判断的，比如，CPU上不开FP16，已经转换为FP16的模型，也不再开

2023-03-15 02:13 UTC, jiangjiajun requested changes

2023-03-15 02:13 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/option.h
> +  /// @brief  use fp16 on GPU
这里无需添加@brief

2023-03-15 02:13 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +}
这里这个逻辑不用添加，就在OrtBackend的Init里面判断。 如若device是CPU，又为option.enable_fp16的情况下，提示fp16仅支持在GPU上加速，其它情况下可能性能会变慢

2023-03-15 02:13 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +  }
上面的逻辑在此处判断即可

2023-03-15 02:13 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +          nullptr, 0, "", &save_external, convert_to_fp16)) {
这里直接使用option.enable_fp16，无需新增convert_to_fp16

2023-03-15 02:13 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +  }
看这里的逻辑，那在Export时无需转为fp16，而是在InitOnnx时再统一转即可

2023-03-15 02:13 UTC, jiangjiajun commented on fastdeploy/runtime/backends/ort/ort_backend.h
> +  bool convert_to_fp16 = false;
同上面的判断，不用添加这个逻辑了。 例如在arm cpu上可能也可以使用fp16

2023-03-16 02:05 UTC, jiangjiajun approved these changes

2023-03-22 12:29 UTC, jiangjiajun approved these changes

2023-03-23 10:23 UTC, merged