Update PaddleSeg example directory
PaddlePaddle/FastDeploy pull request #1245
Opened 2023-02-07 09:08 UTC by felixhjh

### PR types(PR类型)

Doc

### Description

- 重构FastDeploy PaddleSeg目录
- 增加vision_result/faq.md文档

2023-02-08 06:02 UTC, DefTruth commented on docs/api/vision_results/faq_CN.md
> +```
可以加markdown语言风格格式化tag

2023-02-08 06:02 UTC, DefTruth commented on examples/vision/segmentation/paddleseg/README_CN.md
> +- [升腾](ascend)
错别字，应该是 -> Ascend: 昇腾 ?

2023-02-09 07:49 UTC, Zheng-Bicheng commented
@jiangjiajun 大佬，这个pr先合入完，我merge一下然后再合入我那个pr吧？

2023-02-10 07:11 UTC, DefTruth requested changes

2023-02-10 07:11 UTC, DefTruth commented on docs/api_docs/cpp/vision_results_en.md
> +``fastdeploy::vision::MattingResult`''
看到这里的md语法不是统一，这些result类都用 c++ 的md语法包住吧

2023-02-10 07:11 UTC, DefTruth commented on docs/cn/build_and_install/huawei_ascend.md
> +模型端到端推理中, 预处理和后处理阶段为CPU计算, 当用户使用ARM CPU + 昇腾的硬件平台时, 我们推荐用户使用FlyCV, 可以实现端到端的推理性能加速, 详见[FLyCV使用文档](../faq/boost_cv_by_flycv.md).
错别字，FLyCV -> FlyCV

2023-02-10 07:11 UTC, DefTruth commented on docs/cn/faq/vision_result_related_problems.md
> +```
这段代码用md的python语法包住

2023-02-10 07:11 UTC, DefTruth commented on docs/api_docs/cpp/vision_results_en.md
> +本文档的中文版本参考[视觉模型预测结果说明](./vision_results_cn.md)
采用这种语法：[English](README.md) | 简体中文

2023-02-10 07:11 UTC, DefTruth commented on examples/vision/segmentation/paddleseg/android/README_CN.md
> +1. 目标检测 PaddleSeg Demo 位于 `path/to/paddleseg/android` 目录
原来的有错别字：“目标检测” -> "语义分割"

2023-02-10 07:11 UTC, DefTruth commented on examples/vision/segmentation/paddleseg/rockchip/rknpu2/python/README.md
> +## 快速链接
快速链接的含义是？改成其他文档是否更好？

2023-02-13 06:58 UTC, felixhjh commented on examples/vision/segmentation/paddleseg/rockchip/rknpu2/python/README.md
> +## 快速链接
快速链接的含义就是，跟本文档相关性高的文档，快速的索引。其他文档感觉就是与本文档不相关的文档，所以我感觉快速链接更好

2023-02-13 11:36 UTC, yunyaoXYY commented on examples/vision/segmentation/paddleseg/README.md
> +| 硬件支持列表 |  |   |   |
这个可否再做个分类，会好看一些
比如CPU一类，GPU一类，其他的加速器又一类

2023-02-13 11:36 UTC, yunyaoXYY commented on examples/vision/segmentation/paddleseg/README.md
> +- [模型自动化压缩工具](quantize)
模型自动化压缩工具 看起来不属于部署方式,  改成量化模型部署？

2023-02-13 11:36 UTC, yunyaoXYY commented on examples/vision/segmentation/paddleseg/quantize/README.md
> +用户也可以直接下载下表中的量化模型进行部署.(点击模型名字即可下载)
表格有问题，网站显示不正常

2023-02-13 12:03 UTC, yeliang2258 approved these changes
LGTM

2023-02-13 14:07 UTC, Harryoung commented on docs/api/vision_results/segmentation_result_CN.md
>  - **score_map**: 成员变量，与label_map一一对应的所预测的分割类别概率值(当导出模型时指定`--output_op argmax`)或者经过softmax归一化化后的概率值(当导出模型时指定`--output_op softmax`或者导出模型时指定`--output_op none`同时模型初始化的时候设置模型[类成员属性](../../../examples/visi
“与label_map一一对应的所预测的分割类别概率值(当导出模型时指定`--output_op argmax`)”，应删除此处括号内的内容，后面的“或者经过softmax归一化化后的概率值”也一并去掉。
原因：当导出模型时指定`--output_op argmax`时，将不输出score_map.

2023-02-13 14:07 UTC, Harryoung commented on docs/api_docs/cpp/vision_results_cn.md
> +- **score_map**: 成员变量，与label_map一一对应的所预测的分割类别概率值(当导出模型时指定`--output_op argmax`)或者经过softmax归一化化后的概率值(当导出模型时指定`--output_op softmax`或者导出模型时指定`--output_op none`同时模型初始化的时候设置模型[类成员属性](../../../examples/visi
“与label_map一一对应的所预测的分割类别概率值(当导出模型时指定--output_op argmax)”，应删除此处括号内的内容，后面的“或者经过softmax归一化化后的概率值”也一并去掉。
原因：当导出模型时指定--output_op argmax时，将不输出score_map.

2023-02-13 14:07 UTC, Harryoung commented on examples/vision/segmentation/paddleseg/serving/simple_serving/README_CN.md
> +# PaddleSeg Python轻量服务化部署示例
需要说明一下轻量服务化部署和服务化部署的区别

2023-02-14 04:08 UTC, leiqing1 commented on examples/vision/segmentation/paddleseg/README.md
> +| [Intel GPU(独立显卡/集成显卡)](cpu-gpu) | [昆仑](kunlun) | [昇腾](ascend) | [瑞芯微](rockchip) |
1.昆仑芯
2.昆仑芯-昇腾-瑞芯微-晶晨，支持的型号说明需要说明下。不说明，就默认我们都支持。
3.标注下NPU（瑞芯微、晶晨端侧设备，有很多事纯cpu的soc）
这个直接看Lite的文档，Lite支持的FastDeploy都全部列出来。

2023-02-14 04:08 UTC, leiqing1 commented on examples/vision/segmentation/paddleseg/README.md
> +| [晶晨](amlogic) | [算能](sophgo) |
[算能1684X](sophgo)
算能能有好2套工具链，1648是旧产品，市面上应用最多的1648，未来会导流到1684X。

2023-02-14 04:08 UTC, leiqing1 commented on examples/vision/segmentation/paddleseg/serving/README_CN.md
> +- fastdeploy_serving基于Triton Inference Server框架，是一套完备且性能卓越的服务化部署框架，可用于实际生产。
（这里的描述需要换一下用户使用角度出发，有些用户都不知道triton是干啥的）
simple_serving： 适用于只需要通过http等调用AI推理任务，没有高并发需求的场景。simple_serving基于Flask框架具有简单高效的特点，可以快速验证线上部署模型的可行性。
fastdeploy_serving：适用于高并发、高吞吐量请求的场景。基于Triton Inference Server框架，是一套完备且性能卓越的服务化部署框架，可用于实际生产。

2023-02-14 09:42 UTC, felixhjh commented on examples/vision/segmentation/paddleseg/README.md
> +- [模型自动化压缩工具](quantize)
这个之前讨论过，还是用模型自动化压缩工具

2023-02-14 09:42 UTC, felixhjh commented on examples/vision/segmentation/paddleseg/quantize/README.md
> +用户也可以直接下载下表中的量化模型进行部署.(点击模型名字即可下载)
Done

2023-02-14 11:19 UTC, DefTruth approved these changes

2023-02-15 05:21 UTC, felixhjh commented on docs/api_docs/cpp/vision_results_cn.md
> +- **score_map**: 成员变量，与label_map一一对应的所预测的分割类别概率值(当导出模型时指定`--output_op argmax`)或者经过softmax归一化化后的概率值(当导出模型时指定`--output_op softmax`或者导出模型时指定`--output_op none`同时模型初始化的时候设置模型[类成员属性](../../../examples/visi
Done

2023-02-15 05:23 UTC, felixhjh commented on docs/api/vision_results/segmentation_result_CN.md
>  - **score_map**: 成员变量，与label_map一一对应的所预测的分割类别概率值(当导出模型时指定`--output_op argmax`)或者经过softmax归一化化后的概率值(当导出模型时指定`--output_op softmax`或者导出模型时指定`--output_op none`同时模型初始化的时候设置模型[类成员属性](../../../examples/visi
Done

2023-02-15 05:34 UTC, felixhjh commented on examples/vision/segmentation/paddleseg/serving/README_CN.md
> +- fastdeploy_serving基于Triton Inference Server框架，是一套完备且性能卓越的服务化部署框架，可用于实际生产。
Done

2023-02-15 06:31 UTC, felixhjh commented on examples/vision/segmentation/paddleseg/serving/simple_serving/README_CN.md
> +# PaddleSeg Python轻量服务化部署示例
Done

2023-02-15 08:05 UTC, merged