[Bug fix]add yolov7face benchmark
PaddlePaddle/FastDeploy pull request #1297
Opened 2023-02-10 07:57 UTC by CoolKbh

### Description
补充yolov7face预测图片的landmarks
solved: https://github.com/PaddlePaddle/FastDeploy/issues/1292
solved: https://github.com/PaddlePaddle/FastDeploy/issues/1281

2023-02-10 09:39 UTC, wjj19950828 requested changes

2023-02-10 09:39 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def nms_threshold(self, landmarks_per_face):
nms_threshold？

2023-02-10 09:39 UTC, wjj19950828 commented on fastdeploy/vision/facedet/contrib/yolov7face/postprocessor.cc
> +              std::array<float, 2>{landmarks_ptr[j], landmarks_ptr[j + 1]});
这里为什么是每隔三个取一次，但是只用到了前两个？

2023-02-13 01:18 UTC, CoolKbh commented on fastdeploy/vision/facedet/contrib/yolov7face/postprocessor.cc
> +              std::array<float, 2>{landmarks_ptr[j], landmarks_ptr[j + 1]});
`
    def extract_boxes(self, predictions):
        # Extract boxes from predictions
        # print(predictions[:, :4])
        boxes = predictions[:, :4] #* self.scale
        kpts = predictions[:, 6:]  ###x1,y1,score1, ...., x5,y5,score5
        kpts *= np.tile(np.array([self.scale[0], self.scale[1], 1], dtype=np.float32), (1, 5))`
repo里写的是x,y,score

2023-02-13 04:10 UTC, wjj19950828 requested changes

2023-02-13 04:10 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        assert isinstance(landmarks_per_face, float),\
log是int，但是判断是float

2023-02-13 04:13 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        assert isinstance(landmarks_per_face, float),\
done

2023-02-13 06:07 UTC, wjj19950828 approved these changes

2023-02-13 09:00 UTC, jiangjiajun approved these changes

2023-02-14 10:36 UTC, merged