[Backend] Support onnxruntime DirectML inference.
PaddlePaddle/FastDeploy pull request #1304
Opened 2023-02-13 02:53 UTC by yunyaoXYY

1. 支持x64 和 x86(win32) 平台程序.
2. 目前添加paddlecls和paddleseg C++部署.
3. FD的onnxruntime-directml第三方预编译库为： 官方onnxruntime-directml v1.12 + DirectML v1.10（最新)
4. 新增自编译的 x86的opencv-3.4.16

2023-02-13 08:08 UTC, jiangjiajun requested changes

2023-02-13 08:08 UTC, jiangjiajun commented on cmake/opencv.cmake
> +if(ANDROID OR WITH_DIRECTML)
Opencv里面不引用DIRECTML的选项，如果是平台判断，则按系统平台的字段来

2023-02-13 08:08 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/cpp/README.md
>  # PaddleClas C++ Deployment Example
增加一个examples/runtime/inference_paddle_dml.cc

2023-02-13 08:08 UTC, jiangjiajun commented on fastdeploy/fastdeploy_model.cc
> +  if (valid_directml_backends.size() == 0) {
复用CreateORTBackend

2023-02-13 12:04 UTC, yunyaoXYY commented on cmake/opencv.cmake
> +if(ANDROID OR WITH_DIRECTML)
Done

2023-02-13 12:04 UTC, yunyaoXYY commented on examples/vision/classification/paddleclas/cpp/README.md
>  # PaddleClas C++ Deployment Example
Done

2023-02-14 11:02 UTC, jiangjiajun approved these changes

2023-02-16 11:40 UTC, jiangjiajun approved these changes

2023-02-17 02:53 UTC, merged

2024-11-20 06:42 UTC, MistEO commented on fastdeploy/runtime/backends/ort/ort_backend.cc
> +      session_options_.SetExecutionMode(ExecutionMode(0));
请教一下，这两行的作用是？