[Bug Fix] Fix the bug reported by RK3568 Runtime under the latest driver
PaddlePaddle/FastDeploy pull request #1311
Opened 2023-02-13 10:48 UTC by Zheng-Bicheng

### PR types(PR类型)
Bug Fix

### Description
Fix the bug reported by RK3568 Runtime under the latest driver

2023-02-13 10:48 UTC, Zheng-Bicheng commented
修复RK3568在最新驱动下报错的BUg

2023-02-14 02:29 UTC, jiangjiajun requested changes

2023-02-14 02:29 UTC, jiangjiajun commented on fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc
> +  std::cout << "option.core_mask is " << option.core_mask << std::endl;
删除debug日志

2023-02-14 02:29 UTC, jiangjiajun commented on fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc
> +    std::cout << "Device is RK3588" << std::endl;
同上

2023-02-14 02:50 UTC, Zheng-Bicheng commented
@jiangjiajun Done.

2023-02-14 07:40 UTC, jiangjiajun approved these changes

2023-02-14 07:40 UTC, merged