[Other] Update VisMatting function supports matting with  transparent background
PaddlePaddle/FastDeploy pull request #1313
Opened 2023-02-13 15:40 UTC by felixhjh

### PR types(PR类型)

Other

### Description

- Update VisMatting function supports matting with  transparent background

2023-02-14 09:41 UTC, felixhjh commented
resolved #1159

2023-02-15 02:28 UTC, DefTruth requested changes

2023-02-15 02:28 UTC, DefTruth commented on fastdeploy/vision/visualize/matting.cc
> +  int channel = 3;
这个channel为啥直接就等于3了，不是应该从mat.channels获取吗？如果只支持3和4channel，可以把原来的FDASSERT增加一个4的逻辑即可，应该不需要删掉

2023-02-15 02:28 UTC, DefTruth commented on fastdeploy/vision/visualize/matting.cc
> +        vis_data[i * width * channel + j * channel + 1] =
这个代码缩进看着没有对齐

2023-02-15 05:05 UTC, DefTruth approved these changes

2023-02-15 05:24 UTC, merged