[Model] Update Tiny pose for RKNPU2
PaddlePaddle/FastDeploy pull request #1339
Opened 2023-02-15 13:02 UTC by Zheng-Bicheng

### PR types(PR类型)

Model

### Description

* 更新Tiny pose在RKNPU2上的实现

2023-02-15 13:03 UTC, Zheng-Bicheng commented
## 关联Issue

* https://github.com/PaddlePaddle/FastDeploy/issues/1336#issuecomment-1431323271

2023-02-16 02:10 UTC, jiangjiajun requested changes

2023-02-16 02:10 UTC, jiangjiajun commented on fastdeploy/vision/keypointdet/pptinypose/pptinypose_pybind.cc
>        .def_readwrite("use_dark",
需同时更新python/fastdeploy下的接口

2023-02-16 02:15 UTC, jiangjiajun requested changes

2023-02-16 02:15 UTC, jiangjiajun commented on fastdeploy/vision/keypointdet/pptinypose/pptinypose.cc
> +    function::ArgMax(result_copy,&infer_result[1],-1);
提交代码时是不是没有pre-commit install安装代码风格检查的勾子，看这里运算符前后没有空格

2023-02-16 02:38 UTC, Zheng-Bicheng commented on fastdeploy/vision/keypointdet/pptinypose/pptinypose_pybind.cc
>        .def_readwrite("use_dark",
done

2023-02-16 02:38 UTC, Zheng-Bicheng commented on fastdeploy/vision/keypointdet/pptinypose/pptinypose.cc
> +    function::ArgMax(result_copy,&infer_result[1],-1);
done

2023-02-16 06:23 UTC, jiangjiajun approved these changes

2023-02-16 11:47 UTC, merged