[CVCUDA] PP-OCR detector preprocessor integrate CV-CUDA
PaddlePaddle/FastDeploy pull request #1382
Opened 2023-02-20 12:47 UTC by wang-xinyu

### PR types(PR类型)

CV-CUDA | Model

### Description

- PP-OCR detector preprocessor integrate CV-CUDA
- Optimize ProcessorManager
- Adapt PaddleClas preprocessor to use ProcessorManager register api, etc.

2023-02-21 02:18 UTC, wang-xinyu commented
## Test Environment
CPU: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
GPU: T4
Model: ResNet50 224x224
Backend: TensorRT FP16
Warmup 100 rounds，tested 1000 rounds and get avg. latency.

## OpenCV
```
DBDetector preprocess: 3.212
Classifier preprocess: 0.13
Classifier preprocess: 0.131
Classifier preprocess: 0.126
Classifier preprocess: 0.075
Recognizer preprocess: 0.974
Predict Avg.: 28.3392
det boxes: [[42,413],[483,391],[484,428],[43,450]]rec text: 上海斯格威铂尔大酒店 rec score:0.979834 cls label: 0 cls score: 1.000000
det boxes: [[187,456],[399,448],[400,480],[188,488]]rec text: 打浦路15号 rec score:0.965006 cls label: 0 cls score: 1.000000
det boxes: [[23,507],[513,488],[515,529],[24,548]]rec text: 绿洲仕格维花园公寓 rec score:0.993761 cls label: 0 cls score: 1.000000
det boxes: [[74,553],[427,542],[428,571],[75,582]]rec text: 打浦路252935号 rec score:0.948193 cls label: 0 cls score: 1.000000
```
预处理总时间：4.648ms，占端到端推理时间28.34ms的16.4%

## CV-CUDA
```
DBDetector preprocess: 0.867
Classifier preprocess: 0.146
Classifier preprocess: 0.132
Classifier preprocess: 0.091
Classifier preprocess: 0.095
Recognizer preprocess: 0.98
Predict Avg.: 24.9241

det boxes: [[42,413],[483,391],[484,428],[43,450]]rec text: 上海斯格威铂尔大酒店 rec score:0.979443 cls label: 0 cls score: 1.000000
det boxes: [[183,456],[399,448],[400,480],[184,488]]rec text: 打浦路15号 rec score:0.985840 cls label: 0 cls score: 1.000000
det boxes: [[23,507],[513,488],[515,529],[24,548]]rec text: 绿洲仕格维花园公寓 rec score:0.993652 cls label: 0 cls score: 1.000000
det boxes: [[73,553],[427,542],[428,571],[74,582]]rec text: 打浦路252935号 rec score:0.921728 cls label: 0 cls score: 1.000000
```
预处理总时间：2.31ms，占端到端推理时间24.9241ms的9.3%

端到端速度提升1.14倍

2023-02-21 07:37 UTC, jiangjiajun requested changes

2023-02-21 07:37 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  const std::vector<std::array<int, 4>>* GetBatchImgInfo() {
去除SetPreprocessor接口

2023-02-21 07:37 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.cc
> +                                               const std::vector<float>& std) {
resize_op_ = CREATE_PROCESSOR(Resize, arguments);

```
#def CREATE_PROCESSOR(op_name, arguments):
       []() {
       x = std::make_shared_ptr(#op_name)(arguments);
       register(x);
       return x;}

```

2023-02-21 07:37 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.cc
> +                                               const std::vector<float>& std) {
resize_op = CRESTE_PROCESSOR(Resize, 1, 1)
pad_op = cxxx();

2023-02-22 02:08 UTC, jiangjiajun requested changes

2023-02-22 02:08 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/dbdetector.cc
> +  auto batch_det_img_info = preprocessor_.GetBatchImgInfo();
为什么需要改成这种方式，上面的方式有啥问题吗？

2023-02-22 02:08 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/dbdetector.h
> +  /// Set DBDetectorPreprocessor
先前说到这个接口可以不用了

2023-02-22 02:17 UTC, wang-xinyu commented on fastdeploy/vision/ocr/ppocr/dbdetector.h
> +  /// Set DBDetectorPreprocessor
这个没删干净，其他地方包括python接口，删掉了，这里我删一下

2023-02-22 02:18 UTC, wang-xinyu commented on fastdeploy/vision/ocr/ppocr/dbdetector.cc
> +  auto batch_det_img_info = preprocessor_.GetBatchImgInfo();
之前的batch_det_img_info是通过Preprocessor::Run函数的参数传递的， 这里用了ProcessorManager的Run函数，就不能传递这个参数了

2023-02-22 09:26 UTC, jiangjiajun approved these changes

2023-02-22 11:39 UTC, merged