Add PaddleOCRv3 Support
PaddlePaddle/FastDeploy pull request #139
Opened 2022-08-22 02:28 UTC by yunyaoXYY

新增PaddleOCRv3系列模型的支持.

2022-08-22 06:11 UTC, jiangjiajun requested changes

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/backends/paddle/paddle_backend.cc
> +      std::cout << "Delete pass : " << option.delete_pass_names[i] << std::endl;
改成FDINFO << "Delete pass : " << option.delete_pass_names[i] << std::endl;

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/fastdeploy_runtime.cc
> +}
改成DeletePaddleBackendPass(const std::string& pass_name)

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/PPOCRSystemv3.cc
> +// Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
代码文件名命名改用小写+下划线，这里改成ppocr_system_v3.cc

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/PPOCRSystemv3.cc
> +#endif
这里的代码似乎看起来没用到，那就移除掉

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/PPOCRSystemv3.cc
> +
空行删除

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/common/result.h
> +  int cls_label = -1;
```
std::vector<std::array<float, 8>> boxes;
std::vector<std::string> text;
std::vector<float> rec_scores;  // 是指rec_score?
std::vector<float> cls_scores;
std::vector<int32_it> label_ids;
```

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/PPOCRSystemv3.h
> +           std::vector<fastdeploy::vision::OCRResult>& ocr_results);
函数定义改为驼峰命名， 这里直接改成`bool Detect(cv::Mat* img, OCRResult* result)`

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/PPOCRSystemv3.h
> +           std::vector<fastdeploy::vision::OCRResult>& ocr_results);
上两个同理

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +namespace ppocr {
命名空间改为ocr

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +    // Cls模型暂不支持ORT后端推理
这个不支持的原因是啥

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.h
> +                       std::vector<float>& cls_socres);
这里是不是可以直接用ClassifyResult

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.h
> +  double cls_thresh;
改成float？

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +#endif
先去除这些DEBUG宏包的代码，暂时没用到

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +  std::vector<int> cls_image_shape = {3, 48, 192};
这个是否能改成成员变量，这样用户可以自己修改， 给一个默认值

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +    if (!Preprocess(img_list, &input_tensors[0], cls_image_shape, ino)) {
改成成员变量后，也无需再传cls_image_shape。 至于ino也无需传，直接img_lis是多少，就一次全部推理。 如果后续有拆batch的需求，那放在这个模型外面，在system里面去拆

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +    if (!Preprocess(img_list, &input_tensors[0], cls_image_shape, ino)) {
再看了下这个接口，只支持单张图片，那就改成跟之前的接口一致吧，一次处理一张图片。

上面的代码都精简一下，所有模型每次接入一张图片，这样接口就是`Predict(cv::Mat* im, ClassifyResult* result)`

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/dbdetector.h
> +                       std::vector<std::vector<std::vector<int>>>& boxes);
这里的结果就改成`Predict(cv::Mat* im, std::vector<std::array<float, 8>>* boxes)`

在函数中，所以读的参数都是`const T&`, 所有写的参数都是`T* `

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/recognizer.cc
> +                       const std::string& params_file,
参数顺序改一下，跟其它模型一样
```
Recognizer(model_file, params_file, label_file, custom_option, model_format)
```

2022-08-22 06:11 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/recognizer.cc
> +  int end_img_no = std::min(img_num, cur_index + rec_batch_num);
这些有indices的，应该都放到system里面去处理

2022-08-22 06:11 UTC, jiangjiajun commented on examples/vision/ocr/PPOCRSystemv3/cpp/infer.cc
> +      &det_model, &cls_model, &rec_model);
PPOCRSystemv3这个接口改成传`const Model&`进去吧

2022-08-22 06:47 UTC, jiangjiajun requested changes

2022-08-22 06:47 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +    if (!Preprocess(img_list, &input_tensors[0], cls_image_shape, ino)) {
```
Predict(std::vector<cv::Mat>* images, std::vector<ClassifyResult>* results)
```

2022-08-22 06:47 UTC, jiangjiajun commented on csrc/fastdeploy/vision/common/result.h
> +  int cls_label = -1;
recognizer输入map<string, float>
classifier可以保持现有的输出


application/ocrsystem输出OCRResult

2022-08-22 06:47 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/utils/ocr_postprocess_op.h
> +#include "./clipper.h"
改成 `fastdeploy/vision/ocr/cliper.h`

2022-08-22 06:47 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/utils/resize_img.cc
> +}
改成 resize + pad

2022-08-22 06:47 UTC, jiangjiajun commented on examples/vision/ocr/PPOCRSystemv3/cpp/infer.cc
> +  auto ocrv3_app = fastdeploy::application::ocrsystem::PPOCRSystemv3(
只支持单张的，先统一接口， `Predict(cv::Mat* im, OCRResult* result)`

2022-08-22 06:47 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/recognizer.cc
> +  int end_img_no = std::min(img_num, cur_index + rec_batch_num);
顺序由system来决定。 模型只处理一张图片进来，结果出去

2022-08-23 11:50 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +    if (!Preprocess(img_list, &input_tensors[0], cls_image_shape, ino)) {
cls里直接用了 Predict(cv::Mat* im, int cls_label, float cls_scores), 然后cls_label和cls_scores拿到后直接放入OCRResult了， rec的此处同理. 就没有再多用ClassifyResut和在rec里用map{text, score}了

2022-08-23 11:56 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/dbdetector.h
> +                       std::vector<std::vector<std::vector<int>>>& boxes);
Det这里的Predict仍然使用std::vector<std::vector<std::vector<int>>>* boxes；后处理这里的读写较多; 在处理完成后 转换成 vector<std::array<int,8>>

2022-08-24 08:01 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +    // Cls模型暂不支持ORT后端推理
使用PaddleUtils把输入改成 【-1,3,48,192】后已可以成功支持ORT

2022-08-25 03:28 UTC, yunyaoXYY commented
等待Review

2022-08-27 07:09 UTC, jiangjiajun approved these changes

2022-08-27 07:09 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +bool Classifier::Predict(cv::Mat* img, int& cls_labels, float& cls_socres) {
这里改成`bool Classifier::Predict(cv::Mat* img, std::tuple<int, float>* result)`，对于要写的参数，在FastDeploy我们都约定使用`T*`的方式传参

2022-08-27 07:09 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.h
> +  virtual bool Predict(cv::Mat* img, int& cls_labels, float& cls_socres);
`cls_scores`单词拼错了，另外如果有一个score, 就直接命名成`cls_score`

2022-08-27 07:09 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/dbdetector.cc
> +bool DBDetector::Predict(
这个接口改成std::vector<std::array<float, 8>>* boxes_result

2022-08-27 07:09 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/ppocr_system_v2.cc
> +      std::cout << "Finish Rec Prediction!" << std::endl;
删除debug输出

2022-08-27 07:09 UTC, jiangjiajun commented on csrc/fastdeploy/vision/ocr/ppocr/recognizer.cc
> +                             float& rec_text_scores) {
代码中所有接口涉及写传的是引用的都检查下，如果是写参数，改成`T*`

2022-08-27 07:09 UTC, jiangjiajun commented
上面的问题，合入后需继续修改完成

2022-08-27 07:09 UTC, merged

2022-08-29 08:47 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.cc
> +bool Classifier::Predict(cv::Mat* img, int& cls_labels, float& cls_socres) {
Done

2022-08-29 08:48 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/classifier.h
> +  virtual bool Predict(cv::Mat* img, int& cls_labels, float& cls_socres);
Done

2022-08-29 08:48 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/dbdetector.cc
> +bool DBDetector::Predict(
[Done](std::vector<std::array<int, 8>>* boxes_result)

2022-08-29 08:48 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/ppocr_system_v2.cc
> +      std::cout << "Finish Rec Prediction!" << std::endl;
Done

2022-08-29 08:49 UTC, yunyaoXYY commented on csrc/fastdeploy/vision/ocr/ppocr/recognizer.cc
> +                             float& rec_text_scores) {
REC的预测接口已改成：bool Recognizer::Predict(cv::Mat* img, std::tuple<std::string, float>* rec_result)