[Other] Override ProcessorManager::Apply API
PaddlePaddle/FastDeploy pull request #1394
Opened 2023-02-21 05:36 UTC by GodIsBoom

### PR types(PR类型)

### Description

2023-03-06 11:16 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/manager_pybind.cc
> +class FASTDEPLOY_DECL PyProcessorManager : public ProcessorManager {
pybind这里我理解不需要PyProcessorManager了，因为apply是在python重新的

2023-03-06 11:18 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/normalize_and_permute_pybind.cc
> +      .def("__call__",
算子不需要在绑定call了

2023-03-06 11:18 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/resize_by_short_pybind.cc
> +      .def("__call__", [](vision::ResizeByShort& self, vision::FDMat* mat) {
算子不需要在绑定call了

2023-03-06 11:48 UTC, wang-xinyu requested changes

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/README.md
> +# Preprocessor API
readme的开头要加中英文切换，参考https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/encrypt_model/README.md

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/README_CN.md
> +# Preprocessor API
readme的开头要加中英文切换，参考https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/encrypt_model/README.md

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/python/README.md
> +# Preprocessor Python Demo
readme的开头要加中英文切换，参考https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/encrypt_model/README.md

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/python/README_CN.md
> +# Preprocessor Python 示例代码
readme的开头要加中英文切换，参考https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/encrypt_model/README.md

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/python/preprocess_cvcuda.py
> +resize_op = fd.C.vision.processors.ResizeByShort(100, 1, True, hw)
算子需要定义为类的成员变量

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/python/preprocess_cvcuda.py
> +preprocessor = Pyprocessor()
使用if __name__ == "__main__":，并添加ArgumentParser，use cv-cuda通过命令行参数配置。
文件名去掉_cvcuda后缀。


参考：https://github.com/PaddlePaddle/FastDeploy/blob/develop/tutorials/encrypt_model/encrypt.py

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/README_CN.md
> +- [Python示例](/python)
链接是否应该是./python

2023-03-06 11:48 UTC, wang-xinyu commented on tutorials/preprocessor/python/preprocess_cvcuda.py
> +class Pyprocessor(fd.vision.common.manager.PyProcessorManager):
类名定义为CustomProcessor吧

2023-03-06 11:48 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/manager.cc
> +
这个函数里面的空行都删掉吧

2023-03-06 11:48 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/manager.cc
> +
这里去掉空格

2023-03-06 12:03 UTC, GodIsBoom commented on fastdeploy/vision/common/processors/manager_pybind.cc
> +class FASTDEPLOY_DECL PyProcessorManager : public ProcessorManager {
done

2023-03-06 12:03 UTC, GodIsBoom commented on fastdeploy/vision/common/processors/normalize_and_permute_pybind.cc
> +      .def("__call__",
done

2023-03-06 12:03 UTC, GodIsBoom commented on fastdeploy/vision/common/processors/resize_by_short_pybind.cc
> +      .def("__call__", [](vision::ResizeByShort& self, vision::FDMat* mat) {
done

2023-03-06 12:05 UTC, GodIsBoom commented on tutorials/preprocessor/README.md
> +# Preprocessor API
done

2023-03-06 12:06 UTC, GodIsBoom commented on tutorials/preprocessor/README_CN.md
> +# Preprocessor API
done

2023-03-06 12:06 UTC, GodIsBoom commented on tutorials/preprocessor/python/README.md
> +# Preprocessor Python Demo
done

2023-03-06 12:06 UTC, GodIsBoom commented on tutorials/preprocessor/python/README_CN.md
> +# Preprocessor Python 示例代码
done

2023-03-07 02:56 UTC, GodIsBoom commented on tutorials/preprocessor/README_CN.md
> +- [Python示例](/python)
done

2023-03-07 03:26 UTC, GodIsBoom commented on tutorials/preprocessor/python/preprocess_cvcuda.py
> +class Pyprocessor(fd.vision.common.manager.PyProcessorManager):
done

2023-03-07 03:27 UTC, GodIsBoom commented on fastdeploy/vision/common/processors/manager.cc
> +
done

2023-03-07 03:28 UTC, GodIsBoom commented on fastdeploy/vision/common/processors/manager.cc
> +
done

2023-03-07 03:28 UTC, GodIsBoom commented on tutorials/preprocessor/python/preprocess_cvcuda.py
> +preprocessor = Pyprocessor()
done

2023-03-07 03:28 UTC, GodIsBoom commented on tutorials/preprocessor/python/preprocess_cvcuda.py
> +resize_op = fd.C.vision.processors.ResizeByShort(100, 1, True, hw)
done

2023-03-08 06:19 UTC, wang-xinyu commented
LGTM, @jiangjiajun 帮忙再Review下吧

2023-03-10 06:42 UTC, jiangjiajun approved these changes

2023-03-10 06:42 UTC, merged