[Hackathon 182 Model] Update PPOCRV3 For RKNPU2
PaddlePaddle/FastDeploy pull request #1403
Opened 2023-02-21 11:38 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Description
Update PPOCRV3 For RKNPU2

2023-02-21 11:39 UTC, Zheng-Bicheng commented
## 关联Issue

* https://github.com/PaddlePaddle/FastDeploy/issues/1343
* https://github.com/PaddlePaddle/FastDeploy/issues/1400
* https://github.com/PaddlePaddle/community/pull/363

2023-02-21 11:40 UTC, Zheng-Bicheng commented
## PPOCRV3更新细节

### FastDeploy cmake部分

* 更新RKNPU2驱动版本至1.4.2b0
* 更新RKNPU2 cmake 现在RKNPU2驱动将分为RK3588和RK356X进行下载，不再混合
* FastDeploy不在依赖rknnlib_api

### Det部分

* RKNPU2不支持Normalzie 和 Permute因此添加了DisableNormalize 和DisablePermute
* RKNPU2 不支持动态shape，因此参考Rec部分新增了固定shape推理。

### Cls部分

* RKNPU2不支持Normalzie 和 Permute因此添加了DisableNormalize 和DisablePermute

### Rec部分

* RKNPU2不支持Normalzie 和 Permute因此添加了DisableNormalize 和DisablePermute

### OCR Result部分

* 在显示result时会出现rec_score为0但是仍然被框出来的情况，这里对VisOcr函数新增了参数score_threshold

### 导出模型部分

* 新增三个模型的配置文件
* 对导出模型的代码进行了优化

2023-02-21 11:40 UTC, Zheng-Bicheng commented
## 结果展示

![vis_result](https://user-images.githubusercontent.com/58363586/220330858-0d6e5152-0901-4241-8389-45e1b6561637.jpg)

```text
det boxes: [[276,174],[285,173],[285,178],[276,179]]rec text:  rec score:0.000000 cls label: 1 cls score: 0.766602
det boxes: [[43,408],[483,390],[483,431],[44,449]]rec text: 上海斯格威铂尔曼大酒店 rec score:0.888450 cls label: 0 cls score: 1.000000
det boxes: [[186,456],[399,448],[399,480],[186,488]]rec text: 打浦路15号 rec score:0.988769 cls label: 0 cls score: 1.000000
det boxes: [[18,501],[513,485],[514,537],[18,554]]rec text: 绿洲仕格维花园公寓 rec score:0.992730 cls label: 0 cls score: 1.000000
det boxes: [[78,553],[404,541],[404,573],[78,585]]rec text: 打浦路252935号 rec score:0.983545 cls label: 0 cls score: 1.000000
Visualized result saved in ./vis_result.jpg
```

2023-02-21 11:40 UTC, Zheng-Bicheng commented
## 目前未实现要求

经过实测，使用RK静态量化工具，PPOCRV3的精度会大幅度下降，这一点可能要和RK的工程师讨论下。 @leiqing1

2023-02-21 11:47 UTC, jiangjiajun requested changes

2023-02-21 11:47 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetStaticShapeInfer(bool static_shape_infer) {
这个接口，与SetDetImageShape()，是否是有重复。 例如调用了SetDetImageShape()本身就是要求SetStaticShapeInfer()

2023-02-22 02:42 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
这个SetDetImageShape是否不需要暴露给用户使用？我看着这个SetDetImageShape如果暴露后，是由用户自己去决定这个reszie的shape. 但是他们可能也不知道resize到多少比较合适.

2023-02-22 02:42 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
还有这里的英文注释，这里不是 cls_image_shape

2023-02-22 02:48 UTC, yunyaoXYY commented
还有一个小问题，不知道为什么代码的格式，会改变这么多.  Bicheng你是否用了pre-commit， 按理说这里先前提交的代码，也应该用了pre-commit的. 😿

2023-02-22 02:49 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
SetDetImageShape是考虑到用户自己训练Det模型的情况，注释我修改下哈

2023-02-22 02:50 UTC, Zheng-Bicheng commented
> 还有一个小问题，不知道为什么代码的格式，会改变这么多. Bicheng你是否用了pre-commit， 按理说这里先前提交的代码，也应该用了pre-commit的. 😿

我用了pre-commit，有个cpp-lint执行完就这样了

2023-02-22 02:54 UTC, yunyaoXYY commented
> > 还有一个小问题，不知道为什么代码的格式，会改变这么多. Bicheng你是否用了pre-commit， 按理说这里先前提交的代码，也应该用了pre-commit的. 😿
> 
> 我用了pre-commit，有个cpp-lint执行完就这样了

Ok 好的

2023-02-22 02:57 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetStaticShapeInfer(bool static_shape_infer) {
这个是参考rec_preprocessor的api结构，如下:

```c++
/// Set static_shape_infer is true or not. When deploy PP-OCR
  /// on hardware which can not support dynamic input shape very well,
  /// like Huawei Ascned, static_shape_infer needs to to be true.
  void SetStaticShapeInfer(bool static_shape_infer) {
    static_shape_infer_ = static_shape_infer;
  }
  /// Get static_shape_infer of the recognition preprocess
  bool GetStaticShapeInfer() const { return static_shape_infer_; }

/// Set rec_image_shape for the recognition preprocess
  void SetRecImageShape(const std::vector<int>& rec_image_shape) {
    rec_image_shape_ = rec_image_shape;
  }
  /// Get rec_image_shape for the recognition preprocess
  std::vector<int> GetRecImageShape() { return rec_image_shape_; }
```

2023-02-22 02:58 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetStaticShapeInfer(bool static_shape_infer) {
api统一会不会更利于用户理解？调用SetDetImageShape()确实是在固定shape推理的情况下才有意义。

2023-02-22 02:59 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
> SetDetImageShape是考虑到用户自己训练Det模型的情况，注释我修改下哈

RK的用户，自己训OCR的用户多吗，因为之前很少有听说能超越官方PP-OCR的情况.
如果是出于这种考虑，需要把SetDetImageShape这种接口的使用情况说明白，可以在文档、或者demo代码里，添加一行，并且注释掉，说明使用情况

2023-02-22 03:01 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
有听说重新训练Det模型的，其他模型没听说过重新训练的。因为使用场景不一致，有的用户希望检测特定领域，比如发票啥的，就希望能够自己重新训练。

2023-02-22 03:02 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
之前的SetRecImageShape，主要用于区分 PP-OCRv2/v3使用的，并没有暴露给用户

2023-02-22 03:04 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
我在文档中注明一下使用场景吧，因为原先的Det是动态shape，也不一定全是resize到960这个尺寸？可能会不会还有640的情况。

2023-02-22 03:06 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
我将注释修改如下:

```c++
  /// Set det_image_shape for the detection preprocess.
  /// This api is usually used when you retrain the model.
  /// Generally, you do not need to use it.
```

2023-02-22 03:13 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
ok

2023-02-22 03:18 UTC, Zheng-Bicheng commented
@jiangjiajun @yunyaoXYY 大佬们还有需要我修改的地方吗？

2023-02-23 08:17 UTC, jiangjiajun commented
@Zheng-Bicheng 昨天有同事对DetModel的预处理进行了修改，产生了冲突，需要合并一下

2023-02-25 12:59 UTC, Zheng-Bicheng commented
已经merge了最新的修改，大佬你再看下 @jiangjiajun 
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/58363586/221358138-5295f509-3a41-42bb-9cf9-50f18fc2e187.png">

2023-02-27 02:49 UTC, yunyaoXYY requested changes

2023-02-27 02:49 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  std::vector<float> scale_ = {0.229f, 0.224f, 0.225f};
这三个Norm的参数没有用上，现在是在Det_preprocess.cc里使用. 参考https://github.com/PaddlePaddle/FastDeploy/blob/c42f9b93867d0e236faeeedf9c639bb814c92d87/fastdeploy/vision/ocr/ppocr/det_preprocessor.cc#:~:text=std%3A%3Amake_shared%3CNormalizeAndPermute%3E(mean%2C%20std%2C%20is_scale)%3B

2023-02-27 02:56 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  std::vector<float> scale_ = {0.229f, 0.224f, 0.225f};
done!

2023-02-27 02:56 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  std::vector<float> scale_ = {0.229f, 0.224f, 0.225f};
还有其他问题吗?

2023-02-27 06:19 UTC, yunyaoXYY approved these changes

2023-02-27 07:01 UTC, jiangjiajun approved these changes

2023-02-27 07:01 UTC, merged

2023-02-27 10:22 UTC, KongXCai commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
你好，我发现虽然测试例子能跑通，但是模型未做量化，最后使用npu的处理时间比使用cpu还要高很多，在cpu状态下大概1s,而使用npu需要1.4s。

2023-02-27 11:08 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
> 你好，我发现虽然测试例子能跑通，但是模型未做量化，最后使用npu的处理时间比使用cpu还要高很多，在cpu状态下大概1s,而使用npu需要1.4s。

* 量化的问题和RK的杜大佬那边讨论过。他们对Rec模型的支持度不太好，所以暂时没有做量化。这个问题已经在沟通了，将考虑使用混合量化来解决这个问题。
* 至于NPU的处理时间比CPU还多，其实这个问题出在FP32转FP16的这个过程，已经反馈到RK那边了，在等他们进行优化。

2023-02-27 15:41 UTC, 3togo commented
Could you provide an example on CI-FastDeploy-Android C++ for rknpu2?

2023-02-27 15:43 UTC, Zheng-Bicheng commented
> Could you provide an example on CI-FastDeploy-Android C++ for rknpu2?

We have only tested rknpu2 on the Linux platform for the time being

2023-03-04 22:42 UTC, Zheng-Bicheng commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  void SetDetImageShape(const std::vector<int>& det_image_shape) {
> 你好，我发现虽然测试例子能跑通，但是模型未做量化，最后使用npu的处理时间比使用cpu还要高很多，在cpu状态下大概1s,而使用npu需要1.4s。

您好，我想问以下您的板子型号是什么，目前我在RK3588上的测试结果如下:
```
# ONNX下
det: 0.52s
cls: 0.02
rec: 0.32

# RKNN下
det: 0.15
cls: 0.007
rec: 0.18
```
和您说的有出入

2023-03-06 01:51 UTC, KongXCai commented
请问您是在未量化的模型上做的测试吗？&nbsp; 我这边是跑的非量化模型，然后测的时间是你封好的pipline,三个模型一起的时间，使用npu时会有warning提示：
[WARNING] fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc(323)::Infer&nbsp; &nbsp; &nbsp; The input tensor type != model's inputs type.The input_type need FP16,but inputs[0].type is UINT8


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/FastDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月5日(星期天) 上午6:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/FastDeploy] [Hackathon 182 Model] Update PPOCRV3 For RKNPU2 (PR #1403)





 
@Zheng-Bicheng commented on this pull request.
 
 
In fastdeploy/vision/ocr/ppocr/det_preprocessor.h:
 &gt; @@ -54,11 +54,39 @@ class FASTDEPLOY_DECL DBDetectorPreprocessor {    /// Get is_scale of the image normalization in detection preprocess    bool GetIsScale() const { return is_scale_; }   +  /// This function will disable normalize in preprocessing step. +  void DisableNormalize() { disable_permute_ = true; } +  /// This function will disable hwc2chw in preprocessing step. +  void DisablePermute() { disable_normalize_ = true; } + +  /// Set cls_image_shape for the classification preprocess +  void SetDetImageShape(const std::vector<int&gt;&amp; det_image_shape) {   
你好，我发现虽然测试例子能跑通，但是模型未做量化，最后使用npu的处理时间比使用cpu还要高很多，在cpu状态下大概1s,而使用npu需要1.4s。
  
您好，我想问以下您的板子型号是什么，目前我在RK3588上的测试结果如下:
 # ONNX下 det: 0.52s cls: 0.02 rec: 0.32 # RKNN下 det: 0.15 cls: 0.007 rec: 0.18  
和您说的有出入
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;