[Other] Update set rpath
PaddlePaddle/FastDeploy pull request #1461
Opened 2023-02-28 08:19 UTC by joey12300

### PR types(PR类型)

Other
### Description

Update set rpath

2023-03-07 09:45 UTC, joey12300 commented on python/scripts/process_libraries.py.in
> -#        if filename in [
这些so都不会打包进whl包，只保留 "*.so.8"的包

2023-03-08 08:58 UTC, jiangjiajun requested changes

2023-03-08 08:58 UTC, jiangjiajun commented on python/fastdeploy/__init__.py
> +        src = os.path.join(trt_directory, trt_lib + ".8")
这里src不也是一个软链吗？

2023-03-08 09:11 UTC, joey12300 commented on python/fastdeploy/__init__.py
> +        src = os.path.join(trt_directory, trt_lib + ".8")
不是的。在setup打包的时候，所有so都会变成一个实体文件，然后在process_libraries.py会将 so 文件以及 so.8.5.2文件过滤掉。所以这里src是实体的so.8文件

2023-03-08 11:22 UTC, jiangjiajun commented on python/fastdeploy/__init__.py
> +        src = os.path.join(trt_directory, trt_lib + ".8")
那是不是打包时，除了libnvinfer.so.8.5.2需要，其余的libnvinfer.so和libnvinfer.so.8都不需要了，而是import时来创建就行

2023-03-09 02:46 UTC, joey12300 commented on python/fastdeploy/__init__.py
> +        src = os.path.join(trt_directory, trt_lib + ".8")
libnvinfer.so.8.5.2是不需要的，运行时不会链接，打包时只保留libnvinfer.so.8，这个文件在使用TensorRT后端时需要链接；而在第一次import fastdeploy时，会自行创建libnvinfer.so软链，指向 libnvinfer.so.8

2023-03-10 01:09 UTC, merged