[CVCUDA] PP-OCR Cls & Rec preprocessor support CV-CUDA
PaddlePaddle/FastDeploy pull request #1470
Opened 2023-03-01 02:48 UTC by wang-xinyu

### PR types(PR类型)

CV-CUDA | Model

### Description

- PP-OCR Cls & Rec preprocessor support CV-CUDA

2023-03-01 06:51 UTC, wang-xinyu commented
## Test Environment
CPU: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
GPU: T4
Models:
   - https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar
   - https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar
   - https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar

Model config:
```
  int cls_batch_size = 1;
  int rec_batch_size = 6;

  det_option.SetTrtInputShape("x", {1, 3, 64,64}, {1, 3, 640, 640}, {1, 3, 960, 960});
  cls_option.SetTrtInputShape("x", {1, 3, 48, 10}, {cls_batch_size, 3, 48, 320}, {cls_batch_size, 3, 48, 1024});
  rec_option.SetTrtInputShape("x", {1, 3, 48, 10}, {rec_batch_size, 3, 48, 320}, {rec_batch_size, 3, 48, 2304});
```

Test Image: https://gitee.com/paddlepaddle/PaddleOCR/raw/release/2.6/doc/imgs/12.jpg (720x1150)
Backend: TensorRT FP16
Warmup 100 rounds，tested 1000 rounds and get avg. latency.

## OpenCV
```
Predict Avg.: 28.3392
det boxes: [[42,413],[483,391],[484,428],[43,450]]rec text: 上海斯格威铂尔大酒店 rec score:0.979834 cls label: 0 cls score: 1.000000
det boxes: [[187,456],[399,448],[400,480],[188,488]]rec text: 打浦路15号 rec score:0.965006 cls label: 0 cls score: 1.000000
det boxes: [[23,507],[513,488],[515,529],[24,548]]rec text: 绿洲仕格维花园公寓 rec score:0.993761 cls label: 0 cls score: 1.000000
det boxes: [[74,553],[427,542],[428,571],[75,582]]rec text: 打浦路252935号 rec score:0.948193 cls label: 0 cls score: 1.000000
```
预处理总时间：4.648ms，占端到端推理时间28.34ms的16.4%

## CV-CUDA（所有模型的预处理均使用CV-CUDA）
```
Predict Avg.: 21.3655
det boxes: [[42,413],[483,391],[484,428],[43,450]]rec text: 上海斯格威铂尔大酒店 rec score:0.978857 cls label: 0 cls score: 1.000000
det boxes: [[187,456],[399,448],[400,480],[188,488]]rec text: 打浦路15号 rec score:0.966390 cls label: 0 cls score: 1.000000
det boxes: [[23,507],[513,488],[515,529],[24,548]]rec text: 绿洲仕格维花园公寓 rec score:0.993815 cls label: 0 cls score: 1.000000
det boxes: [[74,553],[427,542],[428,571],[75,582]]rec text: 打浦路252935号 rec score:0.947412 cls label: 0 cls score: 1.000000
```
端到端推理时间21.3655ms

端到端速度提升1.33倍

2023-03-01 07:41 UTC, jiangjiajun requested changes

2023-03-01 07:41 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  SetNormalize();
这里写法太奇怪，就改成普通的
```
make_shared吧
```

2023-03-01 07:41 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.cc
> +  SetNormalize();
```
normalize_op_ = std::make_shared<Normalize>({0.5, 0.5, 0.5}, {0.5, 0.5, 0.5}, true);
```

2023-03-01 07:41 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.h
> +  }
无需默认值

2023-03-01 07:41 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +  SetNormalize();
同上

2023-03-01 07:41 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.h
> +                    bool is_scale = true) {
同上

2023-03-01 07:41 UTC, jiangjiajun commented on python/fastdeploy/vision/ocr/ppocr/__init__.py
> +                      is_scale=True):
同上

2023-03-02 02:50 UTC, jiangjiajun approved these changes

2023-03-02 02:50 UTC, merged

2023-03-10 07:59 UTC, pineking commented
det_option.SetTrtInputShape("x", {1, 3, 64,64}, {1, 3, 640, 640}, {1, 3, 960, 960});

如果问文字检测的输入图片尺寸是变长的，怎么做 warmup？

2023-03-10 08:27 UTC, wang-xinyu commented
@pineking 以最大的shape做warmup

2023-03-10 09:12 UTC, pineking commented
@wang-xinyu 只要 warmup 一个最大的 shape，其他的 shape 不需要挨个都 warmup 一遍？

2023-03-10 10:05 UTC, wang-xinyu commented
不需要了