[Docs] Pick PPOCR fastdeploy docs from PaddleOCR
PaddlePaddle/FastDeploy pull request #1534
Opened 2023-03-07 06:21 UTC by yunyaoXYY

将PaddleOCR/deploy/fastdeploy更新到FastDeploy中的ocr examples

2023-03-07 07:13 UTC, Zheng-Bicheng commented
这个pr能稍微等下一吗？RKNPU2的OCR example 有些改动

2023-03-07 12:11 UTC, rainyfly commented on examples/vision/ocr/PP-OCR/cpu-gpu/csharp/README.md
> +- 如果用户想要更换部署后端或进行其他定制化操作, 请查看[C# Runtime API](https://github.com/PaddlePaddle/FastDeploy/blob/develop/csharp/fastdeploy/runtime_option.cs).
这个链接可以改到 https://baidu-paddle.github.io/fastdeploy-api/csharp/html/classfastdeploy_1_1RuntimeOption.html

2023-03-17 03:33 UTC, DefTruth requested changes

2023-03-17 03:33 UTC, DefTruth commented on examples/vision/ocr/PP-OCR/ascend/cpp/README.md
> +git clone https://github.com/PaddlePaddle/PaddleOCR.git
这里的部署代码下载路径，要改成FD的，可以参考下seg examples的写法
```shell
# 下载部署示例代码
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd  FastDeploy/examples/vision/segmentation/semantic_segmentation/cpp-gpu/cpp
# 如果您希望从PaddleSeg下载示例代码，请运行
# git clone https://github.com/PaddlePaddle/PaddleSeg.git
# # 注意：如果当前分支找不到下面的fastdeploy测试代码，请切换到develop分支
# # git checkout develop
# cd PaddleSeg/deploy/fastdeploy/semantic_segmentation/cpp-gpu/cpp
```   
其余文档同理

2023-03-17 03:33 UTC, DefTruth commented on examples/vision/ocr/PP-OCR/cpu-gpu/cpp/README.md
> +git clone https://github.com/PaddlePaddle/PaddleOCR.git
这里的部署代码下载路径，要改成FD的，可以参考下seg examples的写法
```shell
# 下载部署示例代码
git clone https://github.com/PaddlePaddle/FastDeploy.git
cd  FastDeploy/examples/vision/segmentation/semantic_segmentation/cpp-gpu/cpp
# 如果您希望从PaddleSeg下载示例代码，请运行
# git clone https://github.com/PaddlePaddle/PaddleSeg.git
# # 注意：如果当前分支找不到下面的fastdeploy测试代码，请切换到develop分支
# # git checkout develop
# cd PaddleSeg/deploy/fastdeploy/semantic_segmentation/cpp-gpu/cpp
```   
其余文档同理

2023-03-22 08:46 UTC, DefTruth requested changes

2023-03-22 08:46 UTC, DefTruth commented on examples/vision/ocr/PP-OCR/README.md
> +  - [Python部署示例](./kunlun/python/)
kunlunxin，链接地址修改

2023-03-23 05:03 UTC, DefTruth approved these changes

2023-03-23 05:11 UTC, merged