[PaddleX] PaddleX PaddleClas example
PaddlePaddle/FastDeploy pull request #1564
Opened 2023-03-09 06:38 UTC by wang-xinyu

### PR types(PR类型)

PaddleX

### Description

2023-03-09 12:31 UTC, leiqing1 approved these changes

2023-03-09 12:31 UTC, leiqing1 commented on .paddlex/README_CN-linux-cpp.md
> +│   ├── inference.pdiparams       # 模型标签文件
这是我写错了。是：模型参数文件

2023-03-09 12:31 UTC, leiqing1 commented on .paddlex/README_CN-linux-cpp.md
> +│   ├── inference.pdiparams.info  # 模型参数文件
“ # 模型参数文件” 这个删除。

2023-03-10 01:41 UTC, jiangjiajun requested changes

2023-03-10 01:41 UTC, jiangjiajun commented on .paddlex/paddleclas/cpu-gpu/cpp/infer.cc
> +    option.EnablePaddleToTrt();  // Paddle-TensorRT
改成
```
option.UsePaddleInferBackend()
option.paddle_infer_option.enable_trt = true;
option.paddle_infer_option.collect_trt_shape = true;
```

2023-03-10 01:41 UTC, jiangjiajun commented on .paddlex/paddleclas/cpu-gpu/cpp/infer.cc
> +    option.EnablePaddleToTrt();  // Paddle-TensorRT
Python同理

2023-03-10 02:57 UTC, wang-xinyu commented on .paddlex/paddleclas/cpu-gpu/cpp/infer.cc
> +    option.EnablePaddleToTrt();  // Paddle-TensorRT
Fixed

2023-03-10 12:44 UTC, leiqing1 approved these changes

2023-03-13 09:13 UTC, merged