Merge Download Paddle Model, Paddle to Onnx, Onnx to Mlir, Mlir to Bmodel into infer.py
PaddlePaddle/FastDeploy pull request #1622
Opened 2023-03-15 07:32 UTC by Yi-sir

### PR types(PR类型)

### Description

2023-03-15 07:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1622) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1622) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=1622) it.</sub>

2023-03-15 10:00 UTC, DefTruth requested changes

2023-03-15 10:00 UTC, DefTruth commented on examples/vision/classification/paddleclas/sophgo/python/infer.py
> +def mlirPrepare():
函数名风格，python使用小写加下划线，如mlir_prepare

2023-03-15 10:00 UTC, DefTruth commented on examples/vision/classification/paddleclas/sophgo/python/infer.py
> +    # 需要切换到TPU-MLIR目录
注释修改成英文

2023-03-15 10:00 UTC, DefTruth commented on examples/vision/classification/paddleclas/sophgo/python/infer.py
> +mlirPrepare()
这里把所有流程整合在代码里了，用户按照原先paddleclas/sophgo/python/README.md还能正常跑吗？建议通过args来兼容原来的逻辑，比如：  
```python
python infer.py --auto  # 此时则跑自动的逻辑，默认还是按照原来的文档步骤进行操作，这样用户也更更清晰每个步骤的操作
```

2023-03-16 06:14 UTC, Yi-sir commented
Optimized the function logic, changed the function name style add "--auto" into parser and modified README.md, README_CN.md documentation.

2023-03-16 07:47 UTC, DefTruth approved these changes

2023-03-16 11:47 UTC, merged