[Example] Merge Download Paddle Model, Paddle->Onnx->Mlir->Bmodel and   inference into infer.py. Modify README.md
PaddlePaddle/FastDeploy pull request #1643
Opened 2023-03-17 03:03 UTC by Yi-sir

### PR types(PR类型)

### Description

Merge Download Paddle Model, Paddle->Onnx->Mlir->Bmodel and inference into infer.py. Modify README.md

2023-03-17 03:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1643) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1643) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: DefTruth<br/>:x: Yi-sir<br/>:x: xuyizhou<br/><hr/>**xuyizhou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=1643) it.</sub>

2023-03-17 03:45 UTC, DefTruth commented
这个OCR案例的修改，需要等这个PR合入后，在新文档上进行修改才能合入：  
- https://github.com/PaddlePaddle/FastDeploy/pull/1534

2023-03-28 04:45 UTC, DefTruth requested changes

2023-03-28 04:45 UTC, DefTruth commented on examples/vision/detection/paddledetection/sophgo/python/infer_picodet.py
> +        "--PPDetect_Path", default='/workspace/PaddleDetection', help="Path of PaddleDetection folder")
参数统一用小写字母吧，如果是模型目录，则修改成 model_dir。看README中似乎并没有用到这个参数，是否有必要保留？

2023-03-28 04:45 UTC, DefTruth commented on examples/vision/detection/paddledetection/sophgo/python/infer_ppyoloe.py
> +        "--PPDetect_Path", default='/workspace/PaddleDetection', help="Path of PaddleDetection folder")
同上

2023-03-28 06:17 UTC, Yi-sir commented on examples/vision/detection/paddledetection/sophgo/python/infer_picodet.py
> +        "--PPDetect_Path", default='/workspace/PaddleDetection', help="Path of PaddleDetection folder")
PPDetect_Path是PaddleDetection仓库的目录，原始模型推理需要的yml文件需要从这里获得。由于PaddleDetection目录似乎没有方便的环境变量可以直接取到，所以采用了让用户在命令行里输入的方式。README的运行示例里有包含这个参数。

2023-03-29 03:16 UTC, Yi-sir commented on examples/vision/detection/paddledetection/sophgo/python/infer_picodet.py
> +        "--PPDetect_Path", default='/workspace/PaddleDetection', help="Path of PaddleDetection folder")
> 参数统一用小写字母吧，如果是模型目录，则修改成 model_dir。看README中似乎并没有用到这个参数，是否有必要保留？

参数小写已修改

2023-03-30 06:09 UTC, Yi-sir commented on examples/vision/detection/paddledetection/sophgo/python/infer_picodet.py
> +        "--PPDetect_Path", default='/workspace/PaddleDetection', help="Path of PaddleDetection folder")
> > 参数统一用小写字母吧，如果是模型目录，则修改成 model_dir。看README中似乎并没有用到这个参数，是否有必要保留？
> 
> 参数小写已修改

补充yolov5样例及README

2023-03-30 07:58 UTC, DefTruth approved these changes

2023-03-30 12:50 UTC, DefTruth commented
LGTM~

2023-03-30 12:53 UTC, DefTruth requested changes

2023-03-30 12:53 UTC, DefTruth commented on examples/vision/detection/paddledetection/sophgo/python/infer_picodet.py
> +    model.postprocessor.apply_nms()
C++也要修改下：ApplyDecodeAndNMS() -> ApplyNMS()

2023-03-30 12:53 UTC, DefTruth commented on examples/vision/detection/paddledetection/sophgo/python/infer_picodet.py
> +    model.postprocessor.apply_nms()
其余同理

2023-03-31 01:43 UTC, Yi-sir commented on examples/vision/detection/paddledetection/sophgo/python/infer_picodet.py
> +    model.postprocessor.apply_nms()
> C++也要修改下：ApplyDecodeAndNMS() -> ApplyNMS()

已修改

2023-03-31 03:01 UTC, DefTruth approved these changes

2023-03-31 07:08 UTC, merged