[PaddlePaddle Hackathon4 No.186] Add PaddleDetection Models Deployment Go Examples
PaddlePaddle/FastDeploy pull request #1648
Opened 2023-03-18 03:19 UTC by wanziyu

### PR types(PR类型)
Model

### PR changes
examples/application/go

### Description
在FastDeploy C API的基础上，使用go完成PaddleDetection部署 
使用Go通过调用FastDeploy C API，完成PP-YOLOE, YOLOv8, YOLOv5模型的部署适配代码，及对应的中英文文档

### 关联Issue
https://github.com/PaddlePaddle/community/pull/400

2023-03-23 07:47 UTC, DefTruth requested changes

2023-03-23 07:47 UTC, DefTruth commented on examples/application/go/yolov8/infer.go
> +// #include <fastdeploy_capi/vision.h>
删除注释代码

2023-03-23 07:48 UTC, DefTruth commented
@wanziyu 需要在PR提供下各个模型调用GO预测成功后的可视化图片哈

2023-03-23 07:58 UTC, wanziyu commented on examples/application/go/yolov8/infer.go
> +// #include <fastdeploy_capi/vision.h>
这个不是注释，是CGO链接C API的方式

2023-03-23 08:25 UTC, rainyfly commented
LGTM for calling C api

2023-03-23 08:29 UTC, rainyfly commented
Hi, 如果有余力的话，希望能够用go语言封装一下C语言的接口，给Go语言提供一组面对对象的调用方式的接口，可以参考我们C# SDK的开发方式，FastDeploy里的C#底层也是调用这些C接口，但是最终提供给用户使用的接口是封装过后的C#接口。

2023-03-26 14:24 UTC, wanziyu commented
> @wanziyu 需要在PR提供下各个模型调用GO预测成功后的可视化图片哈

PPYOLOE模型预测结果
![vis_result_ppyoloe](https://user-images.githubusercontent.com/73475321/227782248-14df4f36-0cca-461c-b939-41cc249e9d15.jpg)

YOLOv5模型预测结果
![vis_result_yolov5](https://user-images.githubusercontent.com/73475321/227782276-c87662d3-6c2a-414a-9f2c-62b610c4862c.jpg)

YOLOv8模型预测结果
![vis_result_yolov8](https://user-images.githubusercontent.com/73475321/227782288-4fec1529-43be-4c58-a6cc-88ca417dabfe.jpg)

2023-03-28 06:26 UTC, DefTruth commented
LGTM ~

2023-03-28 06:29 UTC, DefTruth approved these changes

2023-03-28 12:30 UTC, merged