add vision processor python api doc
PaddlePaddle/FastDeploy pull request #1655
Opened 2023-03-20 08:09 UTC by GodIsBoom

### PR types(PR类型)

Doc
### Description

- 添加vision processor的python api doc

2023-03-20 08:21 UTC, wang-xinyu requested changes

2023-03-20 08:21 UTC, wang-xinyu commented on python/fastdeploy/vision/common/processors.py
> -        :param mean     A list containing the mean of each channel
冒号后面的空格数量有要求吗？如果没有就统一为1个空格吧

2023-03-20 08:21 UTC, wang-xinyu commented on docs/api_docs/python/vision_processor.md
> +## fastdeploy.vision.common.processors.NormalizeAndPermute
这个顺序有影响吗？能否把同类的放在一块，比如Normalize放在一起，padding放在一起

2023-03-20 08:21 UTC, wang-xinyu commented on docs/api_docs/python/vision_processor.md
> +# Vision Processor(图像预处理库)
中文：多硬件图像处理库

2023-03-20 08:42 UTC, GodIsBoom commented on python/fastdeploy/vision/common/processors.py
> -        :param mean     A list containing the mean of each channel
done

2023-03-20 08:42 UTC, GodIsBoom commented on docs/api_docs/python/vision_processor.md
> +## fastdeploy.vision.common.processors.NormalizeAndPermute
done

2023-03-20 08:42 UTC, GodIsBoom commented on docs/api_docs/python/vision_processor.md
> +# Vision Processor(图像预处理库)
done

2023-03-21 06:19 UTC, wang-xinyu approved these changes

2023-03-21 06:20 UTC, merged