[Gstreamer]Add fdtracker plugin
PaddlePaddle/FastDeploy pull request #1668
Opened 2023-03-21 03:13 UTC by CoolKbh

### PR types(PR类型)
Gstreamer
### Description
Add gstreamer plugin fdtracker

2023-03-21 05:02 UTC, wang-xinyu requested changes

2023-03-21 05:02 UTC, wang-xinyu commented on streamer/src/gstreamer/plugin/fdtracker/include/config_parser.h
> +//   Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
我们把不需要的文件删掉吧，比如config_parser.h, main.cpp

2023-03-21 05:02 UTC, wang-xinyu commented on streamer/src/gstreamer/plugin/fdtracker/include/kalmantracker.h
> +  cv::Vec4f last_observation;
last_observation 需要赋初始值为4个-1，否则会出问题

2023-03-21 05:02 UTC, wang-xinyu commented on streamer/src/gstreamer/plugin/fdtracker/src/ocsort.cpp
> +    if(this->trackers[idx]->last_observation[0]==-1) {
这个判断改成if(this->trackers[idx]->last_observation[0] < 0)吧

2023-03-21 05:02 UTC, wang-xinyu commented on streamer/src/gstreamer/plugin/fdtracker/src/trajectory.cpp
> +	const cv::Point* ppt[] = {points[0]};
代码风格要整体修一下，需要跑一下pre-commit

2023-03-24 09:07 UTC, CoolKbh commented on streamer/src/gstreamer/plugin/fdtracker/include/config_parser.h
> +//   Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
done

2023-03-24 09:54 UTC, CoolKbh commented on streamer/src/gstreamer/plugin/fdtracker/include/kalmantracker.h
> +  cv::Vec4f last_observation;
done

2023-03-24 09:55 UTC, CoolKbh commented on streamer/src/gstreamer/plugin/fdtracker/src/ocsort.cpp
> +    if(this->trackers[idx]->last_observation[0]==-1) {
done

2023-03-27 11:54 UTC, wang-xinyu commented
@CoolKbh 还有几个点要改一下哈，

1. 参考这个PR https://github.com/PaddlePaddle/FastDeploy/pull/1716 改一下fdtracker的cmakelist，
2. gstfdtracker.cc中没有用到的函数和注释，要删掉
3. 所有文件的版权声明要改成paddle的，对于参考其他外部代码的版权声明，参考一下这个文件 https://github.com/PaddlePaddle/FastDeploy/blob/d19b85b0e150a1825838f683e86b94bb1d484eda/fastdeploy/vision/utils/yolo_preprocess.cu#L1

2023-03-29 05:51 UTC, wang-xinyu approved these changes

2023-03-29 05:56 UTC, merged