add paddle detection benchmark
PaddlePaddle/FastDeploy pull request #1675
Opened 2023-03-22 04:32 UTC by linyangshi

### PR types(PR类型)

### Description

2023-04-04 05:40 UTC, DefTruth requested changes

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_arm.sh
> +# ./benchmark_cascadercnn --model cascade_rcnn_r50_fpn_1x_coco --image 000000014439.jpg $CONFIG_PATH
这几个为什么要注释掉

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_cascadercnn.cc
> +  auto model_file = FLAGS_model + sep + "model.pdmodel";
参考下最新的写法，这里要改成调用UpdateModelResourceName接口来自动获取模型名称

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_fcos.cc
> +  auto config_file = FLAGS_model + sep + "infer_cfg.yml";
同上

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_gfl.cc
> +  auto params_file = FLAGS_model + sep + "model.pdiparams";
同上

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyolo.cc
> +  auto config_file = FLAGS_model + sep + "infer_cfg.yml";
同上

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_retinanet.cc
> +  auto config_file = FLAGS_model + sep + "infer_cfg.yml";
同上

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_tood.cc
> +  auto params_file = FLAGS_model + sep + "model.pdiparams";
其余，同理，需要修改下

2023-04-04 05:40 UTC, DefTruth commented on benchmark/cpp/benchmark_xpu.sh
> +# ./benchmark_cascadercnn --model cascade_rcnn_r50_fpn_1x_coco --image 000000014439.jpg --config_path $CONFIG_PATH
跑不通的也先不用注释

2023-04-04 08:41 UTC, linyangshi commented
已删除注释，目前无法跑通的模型有：
XPU: faster_rcnn_r50_vd_fpn_2x_coco、mask_rcnn_r50_1x_coco、cascade_rcnn_r50_fpn_1x_coco、cascade_rcnn_r50_vd_fpn_ssld_2x_coco、retinanet_r101_fpn_2x_coco、retinanet_r50_fpn_1x_coco、tood_r50_fpn_1x_coco、faster_rcnn_enhance_3x_coco、ssdlite_mobilenet_v1_300_coco
ARM：cascade_rcnn_r50_fpn_1x_coco、cascade_rcnn_r50_vd_fpn_ssld_2x_coco、tood_r50_fpn_1x_coco

2023-04-09 04:20 UTC, DefTruth commented
LGTM

2023-04-09 04:21 UTC, DefTruth approved these changes

2023-04-13 02:29 UTC, merged