[CVCUDA]update cvcuda 0.2.0 -> 0.2.1
PaddlePaddle/FastDeploy pull request #1678
Opened 2023-03-22 07:14 UTC by GodIsBoom

### PR types(PR类型)

CVCUDA
### Description

- 支持新版CVCUDA 0.2.1
- 补充vision processor Python api doc文件: index.rst

2023-03-23 03:15 UTC, wang-xinyu requested changes

2023-03-23 03:15 UTC, wang-xinyu commented on tutorials/vision_processor/cpp/main.cc
> +  auto resize_op =
op要定义为成员变量

2023-03-23 03:15 UTC, wang-xinyu commented on tutorials/vision_processor/cpp/main.cc
> + protected:
这里应该是private吧

2023-03-23 03:15 UTC, wang-xinyu commented on tutorials/vision_processor/cpp/main.cc
> +    std::cout << "Usage: image_decoder path/to/image run_option, "
这里image_decoder修改为实际的可执行程序名字

2023-03-23 03:15 UTC, wang-xinyu commented on tutorials/vision_processor/cpp/main.cc
> +    std::cout << "Run_option 0: OpenCV; 1: CVCUDA " << std::endl;
CVCUDA统一改为CV-CUDA吧

2023-03-23 03:15 UTC, wang-xinyu commented on tutorials/vision_processor/cpp/main.cc
> +  // Use CVCUDA if parameter passed and detected
CVCUDA统一改为CV-CUDA吧

2023-03-23 03:15 UTC, wang-xinyu commented on tutorials/vision_processor/cpp/main.cc
> +    outputs.at(i).PrintInfo("out");
改为：outputs[i].PrintInfo("out");

outputs.at(i)有点怪

2023-03-24 05:38 UTC, GodIsBoom commented on tutorials/vision_processor/cpp/main.cc
> +  auto resize_op =
done

2023-03-24 05:39 UTC, GodIsBoom commented on tutorials/vision_processor/cpp/main.cc
> + protected:
done

2023-03-24 05:41 UTC, GodIsBoom commented on tutorials/vision_processor/cpp/main.cc
> +    std::cout << "Usage: image_decoder path/to/image run_option, "
done

2023-03-24 05:41 UTC, GodIsBoom commented on tutorials/vision_processor/cpp/main.cc
> +    std::cout << "Run_option 0: OpenCV; 1: CVCUDA " << std::endl;
done

2023-03-24 05:41 UTC, GodIsBoom commented on tutorials/vision_processor/cpp/main.cc
> +  // Use CVCUDA if parameter passed and detected
done

2023-03-24 05:42 UTC, GodIsBoom commented on tutorials/vision_processor/cpp/main.cc
> +    outputs.at(i).PrintInfo("out");
done

2023-03-24 08:57 UTC, wang-xinyu approved these changes

2023-03-24 08:57 UTC, merged