[Streamer]Support build Python API
PaddlePaddle/FastDeploy pull request #1702
Opened 2023-03-24 08:53 UTC by CoolKbh

### Description
Support streamer build Python API

2023-03-29 06:25 UTC, wang-xinyu requested changes

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/CMakeLists.txt
> +option(PY_LIBRARY_NAME "Name of build python library name")
这个option删掉吧，写死fastdeploy_streamer_main就好

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/CMakeLists.txt
> +if(NOT CSRCS_DIR_NAME)
CSRCS_DIR_NAME如果没用到就删掉吧

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/CMakeLists.txt
> +if(NOT PY_LIBRARY_NAME)
streamer_main统一改成fastdeploy_streamer_main，应该还有其他地方需要一起修改吧

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/CMakeLists.txt
> +# find python3
没用的注释删掉吧

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/python/scripts/process_libraries.py
> +#            print("Package_data:")
没用的注释删掉吧

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/python/setup.py
> +setup_configs["PY_LIBRARY_NAME"] = PACKAGE_NAME + "_main"
fastdeploy_streamer_main

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/python/setup.py
> +USE_MSVC_STATIC_RUNTIME = bool(os.getenv('USE_MSVC_STATIC_RUNTIME', '1') == '1')
这几个变量没用到吧，可以删掉

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/python/setup.py
> +class ONNXCommand(setuptools.Command):
onnx没用到可以删掉

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/python/setup.py
> +                '-DBUILD_FASTDEPLOY_PYTHON=ON',
BUILD_FASTDEPLOY_PYTHON改成BUILD_FDSTREAMER_PYTHON

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/python/setup.py
> +                '-DONNX_NAMESPACE={}'.format(ONNX_NAMESPACE),
ONNX_NAMESPACE可以删掉吧

2023-03-29 06:25 UTC, wang-xinyu commented on streamer/src/pybind/main.cc
> +PYBIND11_MODULE(streamer_main, m) {
fastdeploy_streamer_main

2023-03-29 09:01 UTC, CoolKbh commented on streamer/CMakeLists.txt
> +option(PY_LIBRARY_NAME "Name of build python library name")
done

2023-03-30 00:48 UTC, CoolKbh commented on streamer/CMakeLists.txt
> +if(NOT CSRCS_DIR_NAME)
done

2023-03-30 01:54 UTC, CoolKbh commented on streamer/src/pybind/main.cc
> +PYBIND11_MODULE(streamer_main, m) {
done

2023-03-30 01:54 UTC, CoolKbh commented on streamer/python/setup.py
> +                '-DBUILD_FASTDEPLOY_PYTHON=ON',
done

2023-03-30 01:55 UTC, CoolKbh commented on streamer/python/setup.py
> +                '-DONNX_NAMESPACE={}'.format(ONNX_NAMESPACE),
done

2023-03-30 01:55 UTC, CoolKbh commented on streamer/python/setup.py
> +USE_MSVC_STATIC_RUNTIME = bool(os.getenv('USE_MSVC_STATIC_RUNTIME', '1') == '1')
done

2023-03-30 01:55 UTC, CoolKbh commented on streamer/python/scripts/process_libraries.py
> +#            print("Package_data:")
done

2023-03-30 01:55 UTC, CoolKbh commented on streamer/CMakeLists.txt
> +if(NOT PY_LIBRARY_NAME)
done

2023-03-30 01:55 UTC, CoolKbh commented on streamer/CMakeLists.txt
> +# find python3
done

2023-03-30 01:55 UTC, CoolKbh commented on streamer/python/setup.py
> +setup_configs["PY_LIBRARY_NAME"] = PACKAGE_NAME + "_main"
done

2023-03-30 06:21 UTC, wang-xinyu approved these changes

2023-03-30 06:22 UTC, merged