[PaddlePaddle Hackathon4 No.184] Add PaddleDetection Models Deployment Rust Examples
PaddlePaddle/FastDeploy pull request #1717
Opened 2023-03-27 10:24 UTC by wanziyu

### PR types(PR类型)
Model

### Description
在FastDeploy C API的基础上，使用rust完成PaddleDetection部署
使用Rust通过调用FastDeploy C API，完成PP-YOLOE, YOLOv8, YOLOv5模型的部署适配代码，及对应的中英文文档

### PR changes
examples/application/rust

### 关联Issue
https://github.com/PaddlePaddle/community/pull/481

2023-03-27 10:27 UTC, wanziyu commented
PPYOLOE模型预测结果:

![vis_result_ppyoloe](https://user-images.githubusercontent.com/73475321/227915798-0a8b3fc2-e1e9-4d73-8dca-e228d1df609e.jpg)

YOLOv5模型预测结果:
![vis_result_yolov5](https://user-images.githubusercontent.com/73475321/227915836-7e43469a-cfb6-4ef2-af1b-107edb4e2fe6.jpg)

YOLOv8模型预测结果:
![vis_result_yolov8](https://user-images.githubusercontent.com/73475321/227915900-475d01e6-6317-4276-9f42-e6bc4b7f3a7b.jpg)

2023-03-28 06:31 UTC, DefTruth requested changes

2023-03-28 06:31 UTC, DefTruth commented on examples/application/go/ppyoloe/README.md
> +cp -r fastdeploy-linux-x64-0.0.0/include/fastdeploy_capi .
这里还有一份go的代码，我看go已经有一个pr了，这个pr就单独提rust的吧

2023-03-29 00:41 UTC, wanziyu commented on examples/application/go/ppyoloe/README.md
> +cp -r fastdeploy-linux-x64-0.0.0/include/fastdeploy_capi .
Done

2023-03-30 12:49 UTC, DefTruth approved these changes

2023-03-30 12:49 UTC, DefTruth commented
LGTM~

2023-04-03 03:19 UTC, merged