[Model] add function for setting anchor rknpu2
PaddlePaddle/FastDeploy pull request #1728
Opened 2023-03-28 09:05 UTC by Zheng-Bicheng

### PR types(PR类型)
Other

2023-03-28 09:07 UTC, Zheng-Bicheng commented
## 关联Issues

* https://github.com/PaddlePaddle/FastDeploy/issues/1487

2023-03-28 09:47 UTC, Zheng-Bicheng commented
## 主要改动

* 新增python下 rkyolo对anchor的配置
* 新增python下对rkyolox 和 rkyolov7模型的支持

2023-04-03 05:47 UTC, DefTruth requested changes

2023-04-03 05:47 UTC, DefTruth commented on c_api/fastdeploy_capi/core/config.h
> +/* #undef ENABLE_TEXT */
c_api这个宏改动的原因是什么？

2023-04-04 02:28 UTC, Zheng-Bicheng commented on c_api/fastdeploy_capi/core/config.h
> +/* #undef ENABLE_TEXT */
这个宏定义应该是之前测别的东西的时候遗留的，已经恢复了

2023-04-04 12:29 UTC, DefTruth approved these changes

2023-04-04 12:30 UTC, DefTruth commented
LSTM

2023-04-04 12:33 UTC, merged