[CVCUDA]add cvcuda support in ppseg
PaddlePaddle/FastDeploy pull request #1761
Opened 2023-04-03 06:52 UTC by GodIsBoom

### PR types(PR类型)

CVCUDA
### Description

- PaddleSegPreprocessor继承ProcessorManager
- 移除PaddleSegPreprocessor::Run()
- 实现PaddleSegPreprocessor::Apply()
- 支持开启CVCUDA

2023-04-03 09:20 UTC, wang-xinyu commented
@GodIsBoom PR里面贴一下对比测试的数据吧，可参考https://github.com/PaddlePaddle/FastDeploy/pull/1493

2023-04-03 09:26 UTC, wang-xinyu requested changes

2023-04-03 09:26 UTC, wang-xinyu commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
>        max_height = std::max(max_height, ((*images)[i]).Height());
Resize::Run也需要替换成resize_op_的形式，否则不能用CV-CUDA

2023-04-03 09:26 UTC, wang-xinyu commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
最终get output tensor的逻辑也得改一下，不能用function::concat，也不能用std::move，可参考其他几个实现

2023-04-04 06:13 UTC, GodIsBoom commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
>        max_height = std::max(max_height, ((*images)[i]).Height());
done

2023-04-04 06:13 UTC, GodIsBoom commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
done

2023-04-04 06:40 UTC, wang-xinyu commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +    std::shared_ptr<Resize> pre_resize_op =
这个op可以放在成员变量，每次调用前setWidthHeight

2023-04-07 05:56 UTC, GodIsBoom commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +    std::shared_ptr<Resize> pre_resize_op =
done

2023-04-07 08:55 UTC, GodIsBoom commented
> @GodIsBoom PR里面贴一下对比测试的数据吧，可参考#1493

已完成

2023-04-09 02:37 UTC, wang-xinyu approved these changes

2023-04-09 02:38 UTC, merged