[Backend] Refactoring RKNPU2 Backend code
PaddlePaddle/FastDeploy pull request #1772
Opened 2023-04-06 05:39 UTC by Zheng-Bicheng

### PR types(PR类型)
Backend

### Description
重构RKNPU2后段代码

2023-04-06 05:41 UTC, Zheng-Bicheng commented
## 简介

* 解耦部分函数
* 修复定义一个rknpu2 model但是没有执行predict操作时会释放未定义内存的问题
* 修改注释样式，方便clion等编译器查看

2023-04-06 05:47 UTC, Zheng-Bicheng commented
## 关联PR

* https://github.com/PaddlePaddle/FastDeploy/issues/1762

2023-04-09 04:01 UTC, DefTruth requested changes

2023-04-09 04:01 UTC, DefTruth commented on fastdeploy/runtime/backends/rknpu2/rknpu2_backend.cc
> +  if (!this->RuntimeOptionIsApplicable(runtime_option)) {
这些类内的成员变量或函数的调用，都统一不使用this关键字，保持和FD整体的编程风格一致。其余同理

2023-04-09 04:01 UTC, DefTruth commented on fastdeploy/runtime/backends/rknpu2/rknpu2_backend.h
> +  rknn_input_output_num io_num{0, 0};
成员变量使用下滑线后缀

2023-04-13 04:25 UTC, Zheng-Bicheng commented
@DefTruth 大佬，我做了一波更新哈，你再看看，CI有部分没过，但是应该和我的PR没有太大关系。

2023-04-13 08:35 UTC, DefTruth approved these changes

2023-04-13 08:35 UTC, DefTruth commented
LGTM ~

2023-04-13 08:35 UTC, DefTruth approved these changes

2023-04-13 08:37 UTC, merged