[PaddlePaddle Hackathon4 No.185] Add PaddleDetection Models Deployment Java Examples
PaddlePaddle/FastDeploy pull request #1782
Opened 2023-04-08 13:50 UTC by Tomoko-hjf

### PR types
Model

### PR changes
examples/application/java

### Description
在Java层，通过JNI调用FastDeploy C++ API，完成PP-YOLOE, PaddleYOLOv8, PaddleYOLOv5等模型的部署。

### 关联PR
[#377]https://github.com/PaddlePaddle/community/pull/377

2023-04-09 06:47 UTC, Tomoko-hjf commented
yolov8 结果
![yolov8](https://user-images.githubusercontent.com/53164956/230758678-784faafb-65b2-4aea-a229-57166fa40dee.jpg)

yolov5 结果
![yolov5](https://user-images.githubusercontent.com/53164956/230758692-0466cbe3-3ad5-40ef-8f04-077f037de121.jpg)

ppyoloe 结果
![ppyoloe](https://user-images.githubusercontent.com/53164956/230758700-291a59d2-2959-48e4-ab32-ab1756a46fb9.jpg)

2023-04-09 09:11 UTC, DefTruth requested changes

2023-04-09 09:11 UTC, DefTruth commented on examples/application/java/ppyoloe/cpp/CMakeLists.txt
> +set(FastDeploy_DIR "/home/hjyp/data/fastdeploy-linux-x64-1.0.4/")
这个DIR不要写成绝对路径，需要可以让用户指定，可以参考fd已有examples的写法。如：https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/classification/paddleclas/cpu-gpu/cpp/CMakeLists.txt

2023-04-09 09:11 UTC, DefTruth commented on examples/application/java/ppyoloe/cpp/InferDemo.cc
> +#include "InferDemo.h"
C++代码文件统一命名风格为小写加下划线，如infer_demo.h，其余同理

2023-04-09 09:11 UTC, DefTruth commented on examples/application/java/ppyoloe/cpp/InferDemo.cc
> +  // 模型推理的配置信息
代码中的注释改成英文

2023-04-09 09:11 UTC, DefTruth commented on examples/application/java/ppyoloe/java/InferDemo.java
> +    private final static String JNI_LIB_NAME = "/home/hjyp/code/DeepLearning/FastDeploy/examples/application/java/ppyoloe/cpp/build/libinferDemo.so";
不要写成绝对路径，需要修改成相对这个案例代码目录的相对路径。否则其他用户无法跑通。

2023-04-09 09:12 UTC, DefTruth commented
感谢您的贡献，还需要按要求修改一下哈~

2023-04-10 01:54 UTC, Tomoko-hjf commented
您好，已按要求修改~

2023-04-10 02:12 UTC, Fancy-hjyp commented on examples/application/java/ppyoloe/cpp/CMakeLists.txt
> +set(FastDeploy_DIR "/home/hjyp/data/fastdeploy-linux-x64-1.0.4/")
done

2023-04-10 02:12 UTC, Fancy-hjyp commented on examples/application/java/ppyoloe/cpp/InferDemo.cc
> +#include "InferDemo.h"
done

2023-04-10 02:12 UTC, Fancy-hjyp commented on examples/application/java/ppyoloe/cpp/InferDemo.cc
> +  // 模型推理的配置信息
done

2023-04-10 02:48 UTC, DefTruth approved these changes

2023-04-10 02:48 UTC, DefTruth commented
LGTM~

2023-04-10 13:23 UTC, DefTruth approved these changes

2023-04-10 13:23 UTC, merged