[Hackthon_4th 177] Support PP-YOLOE-R with BM1684
PaddlePaddle/FastDeploy pull request #1809
Opened 2023-04-12 16:01 UTC by thunder95

### PR types(PR类型)

Model

### Description

将PP-YOLOE-R在算能BM1684部署

2023-04-12 16:13 UTC, thunder95 commented
@DefTruth 巨佬，麻烦指导一下
只验证了gpu下的精度和速度， 和sophon的精度 
labels diff, max: 0, min: 0, mean: 0
scores diff, max: 0.000332654, min: 1.07288e-06, mean: 4.85186e-05
boxes diff, max: 0.107788, min: 0, mean: 0.00350611
但是设备上benchmark是0ms

2023-04-13 02:31 UTC, DefTruth commented
LGTM~

2023-04-13 02:31 UTC, DefTruth commented
@thunder95 辛苦提供下预测后的可视化结果图哈

2023-04-13 03:55 UTC, thunder95 commented
> @thunder95 辛苦提供下预测后的可视化结果图哈，直接贴到PR的comments即可

![infer_sophgo](https://user-images.githubusercontent.com/22673612/231646709-66576ac7-a43c-4a8a-a0b9-3e85612ca60d.jpg)

2023-04-13 03:57 UTC, thunder95 commented
> @thunder95 辛苦提供下预测后的可视化结果图哈，直接贴到PR的comments即可

@DefTruth 老师 已贴图

2023-04-13 11:32 UTC, DefTruth requested changes

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +void showDiffStats(const std::vector<float>& data, const std::string& title) {
函数首字母大写

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +  max = *max_element(data.begin(), data.end());
标准库的使用均使用std限制，类型转换采用c++的风格 static_cast

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +void sortBoxes(vision::DetectionResult* result, std::vector<int>* indices) {
同上

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +  auto model_ppyoloe_r = vision::detection::PPYOLOE_R(
c++类名不采用下划线分隔，需要修改成 PPYOLOER

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +  if (config_info["precision_compare"] == "true") {
这段精度验证的逻辑可以先删除或留空，后续FD这边会统一增加这段精度的逻辑。将该精度验证代码在PR中说明即可。

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r_sophgo.cc
> +void showDiffStats(const std::vector<float>& data, const std::string& title) {
同上

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r_sophgo.cc
> +    std::string det_result_path = "ppyoloe_r_result.txt";
同上，精度验证先不保留，后续由FD统一添加

2023-04-13 11:32 UTC, DefTruth commented on benchmark/cpp/benchmark_ppyoloe_r_sophgo.cc
> +      FLAGS_model + sep + "ppyoloe_r_crn_s_3x_dota_1684x_f32.bmodel";
这里模型的获取可以参考这个写法进行自动获取，让UpdateModelResourceName根据推理后端自动获取bmodel，避免hardcode在代码中

https://github.com/PaddlePaddle/FastDeploy/blob/953ccca660ff1d44733aea88163411d066afffdb/benchmark/cpp/flags.h#L165

2023-04-13 11:32 UTC, DefTruth commented on examples/vision/detection/paddledetection/sophgo/cpp/infer_ppyoloe_r.cc
> +  option.UseSophgo();
这里不需要调用option.UseSophgoBackend()吗

2023-04-13 11:32 UTC, DefTruth commented on fastdeploy/vision/common/result.h
> +  std::vector<std::array<float, 8>> rotated_boxes;
这个成员的注释说明不正确，需要修正为rotated_boxes的说明

2023-04-13 11:32 UTC, DefTruth commented on fastdeploy/vision/detection/ppdet/model.h
> +  PPYOLOE_R(const std::string& model_file, const std::string& params_file,
类名 PPYOLOE_R -> PPYOLOER

2023-04-13 11:32 UTC, DefTruth commented on fastdeploy/vision/detection/ppdet/multiclass_nms_rotated.cc
> +T polygon_area(const Point<T> (&q)[24], const int& m) {
模板函数也遵循首字母大写驼峰法，其他函数同理

2023-04-13 11:32 UTC, DefTruth commented on fastdeploy/vision/detection/ppdet/postprocessor.cc
> +bool PaddleDetPostprocessor::ProcessPPYOLOE_R(
函数名ProcessPPYOLOE_R->ProcessPPYOLOE_R

2023-04-13 11:32 UTC, DefTruth commented on fastdeploy/vision/detection/ppdet/postprocessor.h
> +  // Process PPYOLOE_R
参考SetNMSOption，需要增加SetNMSRotatedOption方法

2023-04-13 11:32 UTC, DefTruth commented on fastdeploy/vision/visualize/detection.cc
> +    printf("result score: %f, %f\n", result.scores[i], score_threshold);
这句log删除

2023-04-13 11:32 UTC, DefTruth commented on fastdeploy/vision/visualize/detection.cc
> +  for (size_t i = 0; i < result.rotated_boxes.size(); ++i) {
这段逻辑看起来和后边的新增的是一样的，处理的是有什么区别吗？

2023-04-13 11:32 UTC, DefTruth commented on python/fastdeploy/vision/detection/ppdet/__init__.py
> +class PPYOLOE_R(PPYOLOE):
类名 PPYOLOE_R -> PPYOLOER

2023-04-13 11:35 UTC, DefTruth commented
关于benchmark耗时为0的问题，是因为fd目前还没支持sophgo后端的benchmark功能。可以参考Paddle Lite后端中的写法，增加推理benchmark宏，对推理块进行包裹。   
https://github.com/PaddlePaddle/FastDeploy/blob/b30f62af360e90c48863aa912658c07210500784/fastdeploy/runtime/backends/lite/lite_backend.cc#L202

2023-04-13 14:39 UTC, thunder95 commented on fastdeploy/vision/visualize/detection.cc
> +  for (size_t i = 0; i < result.rotated_boxes.size(); ++i) {
@DefTruth 逻辑是相同的，这里参考boxes简单拷贝了一份逻辑在两个不同的函数里。下面的函数支持传自定义标签const std::vector<std::string>& labels

2023-04-13 15:48 UTC, thunder95 commented
> 

@DefTruth 在sophgo设备上运行成功benchmark
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert	BGR2RGB and Normalize are fused to Normalize with swap_rb=1
[WARNING] fastdeploy/fastdeploy_model.cc(48)::IsSupported	In benchmark mode, we don't check to see if the backend [Backend::SOPHGOTPU] is supported for current model!
[BMRT][bmcpu_setup:349] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1027] INFO:Loading bmodel from [ppyoloe_r_crn_s_3x_dota//ppyoloe_r_crn_s_3x_dota_1684x_f32.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:991] INFO:pre net num: 0, load net num: 1
[INFO] fastdeploy/runtime/runtime.cc(347)::CreateSophgoNPUBackend	Runtime initialized with Backend::SOPHGO in Device::SOPHGOTPUD.
[INFO] fastdeploy/runtime/backends/sophgo/sophgo_backend.cc(202)::Infer	Running profiling for Runtime without H2D and D2H, Repeats: 200, Warmup: 50
Runtime(ms): 70.2644ms.
Visualized result saved in ./vis_result.jpg

2023-04-13 15:55 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +void showDiffStats(const std::vector<float>& data, const std::string& title) {
已完成

2023-04-13 15:55 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +  max = *max_element(data.begin(), data.end());
已完成

2023-04-13 15:56 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +void sortBoxes(vision::DetectionResult* result, std::vector<int>* indices) {
已完成

2023-04-13 15:56 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +  if (config_info["precision_compare"] == "true") {
已完成

2023-04-13 15:56 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r.cc
> +  auto model_ppyoloe_r = vision::detection::PPYOLOE_R(
已完成

2023-04-13 15:56 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r_sophgo.cc
> +void showDiffStats(const std::vector<float>& data, const std::string& title) {
已完成

2023-04-13 15:56 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r_sophgo.cc
> +    std::string det_result_path = "ppyoloe_r_result.txt";
已完成

2023-04-13 15:56 UTC, thunder95 commented on benchmark/cpp/benchmark_ppyoloe_r_sophgo.cc
> +      FLAGS_model + sep + "ppyoloe_r_crn_s_3x_dota_1684x_f32.bmodel";
已完成

2023-04-13 15:56 UTC, thunder95 commented on fastdeploy/vision/common/result.h
> +  std::vector<std::array<float, 8>> rotated_boxes;
已完成

2023-04-13 15:57 UTC, thunder95 commented on fastdeploy/vision/detection/ppdet/postprocessor.cc
> +bool PaddleDetPostprocessor::ProcessPPYOLOE_R(
已完成

2023-04-13 15:57 UTC, thunder95 commented on fastdeploy/vision/detection/ppdet/multiclass_nms_rotated.cc
> +T polygon_area(const Point<T> (&q)[24], const int& m) {
已完成

2023-04-13 15:57 UTC, thunder95 commented on fastdeploy/vision/detection/ppdet/model.h
> +  PPYOLOE_R(const std::string& model_file, const std::string& params_file,
已完成

2023-04-13 15:57 UTC, thunder95 commented on examples/vision/detection/paddledetection/sophgo/cpp/infer_ppyoloe_r.cc
> +  option.UseSophgo();
已完成

2023-04-13 15:57 UTC, thunder95 commented on fastdeploy/vision/detection/ppdet/postprocessor.h
> +  // Process PPYOLOE_R
已完成

2023-04-13 15:57 UTC, thunder95 commented on fastdeploy/vision/visualize/detection.cc
> +    printf("result score: %f, %f\n", result.scores[i], score_threshold);
已完成

2023-04-13 15:57 UTC, thunder95 commented on python/fastdeploy/vision/detection/ppdet/__init__.py
> +class PPYOLOE_R(PPYOLOE):
已完成

2023-04-14 03:48 UTC, DefTruth commented on fastdeploy/vision/visualize/detection.cc
> +  for (size_t i = 0; i < result.rotated_boxes.size(); ++i) {
好的

2023-04-14 03:49 UTC, DefTruth commented
LGTM~

2023-04-14 03:57 UTC, DefTruth requested changes

2023-04-14 03:57 UTC, DefTruth commented on fastdeploy/vision/detection/ppdet/postprocessor.h
> +  void SetNMSRotatedOption(const NMSRotatedOption& option) {
这个接口需要在ppdet_pybind中绑定下，以便在python中调用。同理NMSRotatedOption，也需要在pybind中绑定下。

2023-04-14 05:40 UTC, thunder95 commented on fastdeploy/vision/detection/ppdet/postprocessor.h
> +  void SetNMSRotatedOption(const NMSRotatedOption& option) {
@DefTruth 已完成

2023-04-14 06:56 UTC, DefTruth commented
@thunder95 CI似乎都挂了，需要检查下pybind的逻辑，看起来是有头文件没有被引用

2023-04-14 10:28 UTC, thunder95 commented
> @thunder95 CI似乎都挂了，需要检查下pybind的逻辑，看起来是命名空间没索引正确。
> 
> <img alt="image" width="1212" src="https://user-images.githubusercontent.com/31974251/231967455-a9da0fd5-afb0-40d7-8b2f-50e9b738f418.png">

@DefTruth 已完成修改

2023-04-19 12:37 UTC, DefTruth approved these changes

2023-04-20 03:19 UTC, DefTruth requested changes

2023-04-20 03:19 UTC, DefTruth commented on fastdeploy/vision/detection/ppdet/postprocessor.cc
> +    if (tensors[0].Shape()[2] == 8) {  // PPYOLOER
这个shape是否一定是3维度？picodet等的输出tensor一般是2个维度，索引2会取到一个随机值

2023-04-21 02:44 UTC, DefTruth approved these changes

2023-04-21 02:48 UTC, merged

2023-07-27 08:34 UTC, 851532562 commented
@thunder95 您好，请问下您使用的ppyoloe_r模型提交到算能model_zoo了吗，我找了好久没找到，您方便发我一下吗？发邮箱（851532562@qq.com）也行。非常感谢！

2023-07-27 14:02 UTC, thunder95 commented
> 

@851532562 您好，我试着找了下，没有找到该模型，之前借的设备也还了。这个转模型过程相对也比较简单，先导出onnx，然后用最新版mlir转bmodel，老版本的可能会遇到部分算子不支持。

2023-07-28 02:10 UTC, 851532562 commented
> > 
> 
> @851532562 您好，我试着找了下，没有找到该模型，之前借的设备也还了。这个转模型过程相对也比较简单，先导出onnx，然后用最新版mlir转bmodel，老版本的可能会遇到部分算子不支持。

嗯，我按照文档指示能完成模型转换过程，在bm1684x上也能跑起来，不过结果有一些问题，该识别出来的没识别到，有些不对的框置信度还挺高，您遇到过这样的问题吗？
![微信图片_20230728](https://github.com/PaddlePaddle/FastDeploy/assets/23048211/c85b8a82-0a07-4eed-9203-f2b750d3095b)

2023-07-28 05:43 UTC, 851532562 commented
@thunder95 麻烦帮忙看看哦，感谢！

2023-07-28 06:27 UTC, thunder95 commented
@851532562 这是自己训练的模型吗，有跟python跑出的结果进行对比吗？之前我测试官网的模型，是有轻微的差别，主要原因是模型移植过程中模型本身会有轻微精度损失，另外，旋转框后处理的实现上也有差别，官网原始实现是有一个cuda算子，具体名称忘记了，我参考的是deploy里numpy处理的逻辑进行移植到fastdeploy。

2023-07-28 06:57 UTC, 851532562 commented
@thunder95 您说的python跑的结果是指用paddledetection跑的吗，我等下对比一下。我这个用的是paddledetection导出的，不是自己训练的，导出的时候去掉了最后的multiclass_nms算子，其他的都是按fastdeploy  sophgo文档操作的