Modify PPMatting backend and docs
PaddlePaddle/FastDeploy pull request #182
Opened 2022-09-01 06:41 UTC by ziqi-jin

2022-09-01 07:35 UTC, DefTruth requested changes

2022-09-01 07:35 UTC, DefTruth commented on examples/vision/matting/ppmatting/cpp/infer.cc
> -void GpuInfer(const std::string& model_dir, const std::string& image_file,
这里保留GpuInfer，但是设置一下backend为paddle
```c++
option.UsePaddleBackend()
```

2022-09-01 07:35 UTC, DefTruth commented on examples/vision/matting/ppmatting/cpp/infer.cc
>    if (std::atoi(argv[4]) == 0) {
同上，保留gpu推理案例

2022-09-01 07:35 UTC, DefTruth commented on examples/vision/matting/ppmatting/python/README.md
> -python infer.py --model PP-Matting-512 --image matting_input.jpg --bg matting_bgr.jpg --device gpu
同上

2022-09-01 07:35 UTC, DefTruth commented on examples/vision/matting/ppmatting/cpp/README.md
> -./infer_demo PP-Matting-512 matting_input.jpg matting_bgr.jpg 1
这里保留GpuInfer，但是设置一下backend为paddle

2022-09-01 15:01 UTC, DefTruth approved these changes

2022-09-03 08:29 UTC, jiangjiajun requested changes

2022-09-03 08:29 UTC, jiangjiajun commented on csrc/fastdeploy/vision/matting/ppmatting/ppmatting.cc
> +        int target_size = 512;
为啥要给默认值

2022-09-03 08:29 UTC, jiangjiajun commented on csrc/fastdeploy/vision/matting/ppmatting/ppmatting.cc
> +                  << max_short << std::endl;
日志输出改为FDINFO

LimitShort, height 单词拼错了

改为`Detected LimitShort processing step in yaml file, if the model is exported from PaddleSeg, please make sure the input of your model is fixed with a square shape, and equal to " << max_short << "." << std::endl;`

2022-09-03 08:29 UTC, jiangjiajun commented on csrc/fastdeploy/vision/matting/ppmatting/ppmatting.cc
> +        std::vector<float> value = {114, 114, 114};
为啥是114， 114的这个默认值是PaddleSeg里面默认的吗？

2022-09-05 02:57 UTC, DefTruth requested changes

2022-09-05 02:57 UTC, DefTruth commented on csrc/fastdeploy/vision/matting/ppmatting/ppmatting.cc
> +      FDASSERT(input_h == input_w,
这里用FDASSERT，用户输入的如果不是方形的，是不是会直接报错了？我看到这个input_h/w，是从输入的mat获取的，并不是从模型输入的shape获取的，但是报错提示的是"model"的input_shape必须是方形的

2022-09-05 02:57 UTC, DefTruth commented on csrc/fastdeploy/vision/matting/ppmatting/ppmatting.cc
> +    int pad_h = pad_to_size->second[0];
这里pad_h和pad_w获取后并没有用上，所以这两个值的具体作用是什么

2022-09-05 02:57 UTC, DefTruth commented on csrc/fastdeploy/vision/matting/ppmatting/ppmatting.cc
> +      FDASSERT(input_h >= max_short && input_w >= max_short,
同上，这里获取的是输入的input_h和input_w，并不是模型的

2022-09-05 02:57 UTC, DefTruth commented on examples/vision/matting/ppmatting/python/infer.py
> +        if args.use_trt:
这个paddle gpu的判断，应该不用缩进一个层级，可以这样(gpu下，如果不指定trt，默认就用paddle推)
```python
def build_option(args):
    option = fd.RuntimeOption()

    if args.device.lower() == "gpu":
        option.use_gpu()
        option.use_paddle_backend()

     if args.use_trt:
         option.use_trt_backend()
         option.set_trt_input_shape("img", [1, 3, 512, 512])
      
    return option
```

2022-09-05 02:57 UTC, DefTruth commented on csrc/fastdeploy/vision/common/processors/resize_by_long.h
> +  double GenerateScale(const int origin_w, const int origin_h);
naive 值传递 不需要 const限制

2022-09-05 07:20 UTC, DefTruth commented on csrc/fastdeploy/vision/matting/ppmatting/ppmatting.cc
> +      FDASSERT(input_h == input_w,
```c++
if (option.backend == Backend::PDINFER) {
    if (option.device == Device::CPU) {
         FDWARN << "" << std::endl;
        // some ops
    } 
}  else {
   FDWARN << "" << std::endl;
   // resize op
}
```

2022-09-06 13:12 UTC, DefTruth approved these changes

2022-09-07 08:13 UTC, merged