【Hackthon_4th 180】在FastDeploy中集成地平线推理引擎
PaddlePaddle/FastDeploy pull request #1822
Opened 2023-04-14 06:57 UTC by seyosum

### PR types(PR类型)
Add Horizon backend

### Description
1、Add Horizon backend
2、Clas model inference
3、PPYOLOE inference

2023-04-17 12:54 UTC, seyosum commented
@DefTruth 有空可以帮review下嘛

2023-04-18 02:20 UTC, DefTruth commented
> @DefTruth 有空可以帮review下嘛

好的，这两天会整体review一下哈，感谢您的贡献~

2023-04-19 13:39 UTC, DefTruth requested changes

2023-04-19 13:39 UTC, DefTruth commented on FastDeploy.cmake.in
> +  set(DNN_PATH "~/.horizon/ddk/xj3_aarch64/dnn/")
这个路径不能是绝对路径，可以参考paddlelite.cmake的处理。不属于系统so的，需要从云端下载，并安装到用户的编译环境。可以打包一下成tgz提供给我们哈

2023-04-19 13:39 UTC, DefTruth commented on FastDeploy.cmake.in
> +  set(APPSDK_PATH "~/.horizon/ddk/xj3_aarch64/appsdk/appuser/")
同上

2023-04-19 13:39 UTC, DefTruth commented on cmake/horizon.cmake
> +set(DNN_PATH "~/.horizon/ddk/xj3_aarch64/dnn/")
同上，不能是绝对路径，请参考paddlelite.cmake的处理

2023-04-19 13:39 UTC, DefTruth commented on cmake/horizon.cmake
> +include_directories(${DNN_PATH}/include
这里需要使用 ExternalProject_Add 的方式进行下载和配置

2023-04-19 13:39 UTC, DefTruth commented on examples/vision/classification/paddleclas/horizon/cpp/CMakeLists.txt
> +set(FASTDEPLOY_INSTALL_DIR "/home/xuhao/Hackathon/FastDeploy/build/fastdeploy-0.0.0")
这个路径不能hardcode，参考其他examples的写法，可以让用户设置

2023-04-19 13:39 UTC, DefTruth commented on examples/vision/classification/paddleclas/horizon/cpp/CMakeLists.txt
> +add_executable(sunrise_test infer.cc)
统一使用 infer_demo，和其他推理引擎的案例保持一致

2023-04-19 13:39 UTC, DefTruth commented on examples/vision/classification/paddleclas/horizon/cpp/CMakeLists.txt
> +        ${FastDeploy_LIBS} pthread rt dl
rt dl是必须链接的吗

2023-04-19 13:39 UTC, DefTruth commented on examples/vision/detection/paddledetection/horizon/cpp/CMakeLists.txt
> +set(FASTDEPLOY_INSTALL_DIR "/home/xuhao/Hackathon/FastDeploy/build/fastdeploy-0.0.0")
同上，不能hardcode这个路径

2023-04-19 13:39 UTC, DefTruth commented on fastdeploy/runtime/enum_variables.cc
> +#ifdef ENABLE_HORIZON_BACKEND
这个宏也需要在fastdeploy/core/config.h.in中增加下，可参考已有写法。

2023-04-19 13:39 UTC, DefTruth commented on fastdeploy/runtime/backends/horizon/horizon_backend.cc
> +    if (!this->LoadModel((char*)runtime_option.model_file.data())) {
FastDeploy统一不使用this关键字

2023-04-19 13:39 UTC, DefTruth commented on fastdeploy/runtime/backends/horizon/horizon_backend.cc
> +    if(!this->infer_init){
类私有成员使用下划线结尾

2023-04-19 13:39 UTC, DefTruth commented on fastdeploy/runtime/backends/horizon/horizon_backend.cc
> +        for(uint32_t i = 0; i < input_count; i++){
可以参考Paddle Lite后端中的写法，增加推理benchmark宏，以支持benchmark功能，对推理块进行包裹。   
https://github.com/PaddlePaddle/FastDeploy/blob/b30f62af360e90c48863aa912658c07210500784/fastdeploy/runtime/backends/lite/lite_backend.cc#L202

更详细的说明，还可以参考这个PR：
- https://github.com/PaddlePaddle/FastDeploy/pull/1201  

编译带benchmark功能的SDK，需要-DENABLE_BENCHMARK=ON

2023-04-19 13:39 UTC, DefTruth commented on fastdeploy/runtime/runtime_option.cc
> +void RuntimeOption::UseHorizon(){
UseHorizon()是指硬件的含义？是否应该提供UseHorizonNPUBackend() API设置backend=Backend::HORIZONNPU？可以参考Sophgo/RKNPU2的写法。

2023-04-21 11:14 UTC, seyosum commented on fastdeploy/runtime/runtime_option.cc
> +void RuntimeOption::UseHorizon(){
UseHorizon()这块指的是使用地平线backends，我理解之后会有不同的芯片，目前还没有改这部分，之后如果有新增的话可以考虑加参数。

2023-04-21 11:15 UTC, seyosum commented on cmake/horizon.cmake
> +include_directories(${DNN_PATH}/include
这块目前我还没搞清楚ExternalProject_Add这个的用法，之前没用过😂😂😂，我了解下之后更新吧

2023-04-21 11:15 UTC, seyosum commented on FastDeploy.cmake.in
> +  set(DNN_PATH "~/.horizon/ddk/xj3_aarch64/dnn/")
系统的package和编译器都打包好了，我怎么发你呢

2023-04-21 12:27 UTC, DefTruth commented on FastDeploy.cmake.in
> +  set(DNN_PATH "~/.horizon/ddk/xj3_aarch64/dnn/")
@seyosum 贴个下载链接到这个地址即可

2023-04-23 02:49 UTC, DefTruth commented on fastdeploy/runtime/runtime_option.cc
> +void RuntimeOption::UseHorizon(){
如果是使用具体的推理后端，需要提供类似UseHorizonNPUBackend()来明确语义，Backend强调的是推理后端，比如UseCpu(), UseGpu(), UseKunlunXin()这些则是强调硬件（CPU/GPU/昆仑芯XPU等），强调硬件的接口会执行一些和硬件相关的初始化配置，比如UseGpu(), UseKunlunXin()需要指定device_id，UseKunlunXin()还需要指定L3 Cache size等。带Backend后缀的接口，则强调的是使用哪个推理后端，比如UsePaddleInferBackend(), UsePaddleLiteBackend()等。硬件配置 + 后端配置，形成一个完整的推理条件组合。举个例子：  
```c++
// CPU + Paddle Inference
option.UseCpu();
option.UsePaddleInferBackend();
// CPU + OpenVINO
option.UseCpu();
option.UseOpenVINOBackend();
// GPU + Paddle Inference
option.UseGpu(); // device_id默认为0
option.UsePaddleInferBackend();
```  
因此建议把硬件API和推理后端API区分开来，在地平线：  
```c++
option.UseHorizon();  // 一般理解这个指定是硬件
option.UseHorizonNPUBackend(); // 指的是使用哪个推理后端
```

2023-04-23 08:03 UTC, seyosum commented on fastdeploy/runtime/runtime_option.cc
> +void RuntimeOption::UseHorizon(){
这块我大致理解了，增加了这部分内容，infer demo也同步改啦

2023-04-23 08:13 UTC, DefTruth commented on fastdeploy/runtime/runtime_option.cc
> +void RuntimeOption::UseHorizon(){
@seyosum LGTM ~

2023-04-27 09:16 UTC, DefTruth requested changes

2023-04-27 09:16 UTC, DefTruth commented on FastDeploy.cmake.in
> +  include_directories(${DNN_PATH}/include
这个include路径，在编译FD SDK后使用，是必须的吗？如果是必须的需要添加到FASTDEPLOY_INCS中，不是单独include_directories，参考：
```cmake
list(APPEND FASTDEPLOY_INCS ${LITE_DIR}/include)
```

2023-04-27 09:16 UTC, DefTruth commented on examples/vision/classification/paddleclas/horizon/cpp/infer.cc
> +
代码风格，需要先安装pre-commit check一下。  
```bash  
cd FastDeploy  
sh ./commit-prepare.sh 
# then commit your codes
```

2023-04-27 09:16 UTC, DefTruth commented on examples/vision/classification/paddleclas/horizon/cpp/infer.cc
> +  // std::cout << res.Str() << std::endl;
删除无用代码

2023-04-27 09:16 UTC, DefTruth commented on examples/vision/detection/paddledetection/horizon/cpp/infer_ppyoloe_demo.cc
> +  for(int i = 0; i < 100; i++){
案例中不需要保留测速代码

2023-04-27 09:16 UTC, DefTruth commented on fastdeploy/fastdeploy_model.cc
> +  }else if (runtime_option.device == Device::TIMVX) {
代码风格，else if前需要空格

2023-04-27 11:30 UTC, seyosum commented on FastDeploy.cmake.in
> +  include_directories(${DNN_PATH}/include
这个是非必须的，我改下这块

2023-05-06 06:12 UTC, DefTruth approved these changes

2023-05-06 08:10 UTC, merged