[Model] Support Paddle3D PETR v2 model
PaddlePaddle/FastDeploy pull request #1863
Opened 2023-04-24 07:57 UTC by CoolKbh

Support PETR v2

模型链接：https://paddle3d.bj.bcebos.com/models/petr/petrv2_exported_model.tar

2023-05-12 02:44 UTC, DefTruth requested changes

2023-05-12 02:44 UTC, DefTruth commented on examples/vision/perception/paddle3d/petr/cpp/README_CN.md
> +<img width="640" src="https://user-images.githubusercontent.com/30516196/230387825-53ac0a09-4137-4e49-9564-197cbc30ff08.png">
PETR已经支持可视化了吗？这个是不是smoke 3d的？如果PETR还没支持可视化，这个图先删除吧

2023-05-12 02:44 UTC, DefTruth commented on examples/vision/perception/paddle3d/petr/python/README.md
> +Smoke model loading and initialization.
这里还是smoke的文档，更新成petr的吧

2023-05-12 02:44 UTC, DefTruth commented on examples/vision/perception/paddle3d/petr/python/README_CN.md
> +# Smoke Python 部署示例
同上，文档更新成petr的

2023-05-12 02:44 UTC, DefTruth commented on examples/vision/perception/paddle3d/petr/python/infer.py
> +model = fd.vision.perception.Smoke(
这里还是smoke的，python案例也更新成petr的

2023-05-12 02:44 UTC, DefTruth commented on examples/vision/perception/paddle3d/petr/serving/README.md
> +# Smoke service deployment example
服务化还没测试过，先删除服务化的案例吧

2023-05-12 02:44 UTC, DefTruth commented on fastdeploy/vision/perception/paddle3d/petr/preprocessor.h
> +  void normalize(cv::Mat *im, const std::vector<float> &mean,
函数风格采用首字符大写驼峰法

2023-05-16 08:25 UTC, CoolKbh commented on examples/vision/perception/paddle3d/petr/cpp/README_CN.md
> +<img width="640" src="https://user-images.githubusercontent.com/30516196/230387825-53ac0a09-4137-4e49-9564-197cbc30ff08.png">
done

2023-05-16 08:28 UTC, CoolKbh commented on examples/vision/perception/paddle3d/petr/python/README.md
> +Smoke model loading and initialization.
done

2023-05-16 08:28 UTC, CoolKbh commented on examples/vision/perception/paddle3d/petr/python/README_CN.md
> +# Smoke Python 部署示例
done

2023-05-16 08:29 UTC, CoolKbh commented on examples/vision/perception/paddle3d/petr/python/infer.py
> +model = fd.vision.perception.Smoke(
done

2023-05-16 08:30 UTC, CoolKbh commented on examples/vision/perception/paddle3d/petr/serving/README.md
> +# Smoke service deployment example
done

2023-05-16 08:31 UTC, CoolKbh commented on fastdeploy/vision/perception/paddle3d/petr/preprocessor.h
> +  void normalize(cv::Mat *im, const std::vector<float> &mean,
done

2023-05-18 12:16 UTC, DefTruth approved these changes
LGTM~

2023-05-19 02:44 UTC, DefTruth approved these changes

2023-05-19 02:45 UTC, merged