FDTensor support GPU device
PaddlePaddle/FastDeploy pull request #190
Opened 2022-09-05 09:11 UTC by heliqi

### PR types
New features

### PR changes
APIs

### Describe
1. FDTensor 支持GPU
2. FDTensor新增Resize、~FDTensor等接口
3. Paddle Backend输入数据支持传入GPU FDTenor， 还差TRT Backend未支持

2022-09-06 04:08 UTC, jiangjiajun requested changes

2022-09-06 04:08 UTC, jiangjiajun commented on csrc/fastdeploy/backends/ort/ort_backend.cc
> +    memcpy(static_cast<void*>(tensor->Data()), value.GetTensorData<void*>(),
将MutableData改为Data的原因是？

2022-09-06 04:08 UTC, jiangjiajun commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +                               TrtDataTypeSize(outputs_desc_[i].dtype));
全部统一使用`Resize`

2022-09-06 04:08 UTC, jiangjiajun commented on csrc/fastdeploy/core/fd_tensor.h
> +  void Resize(size_t nbytes);
删除这个函数

2022-09-06 04:08 UTC, jiangjiajun commented on csrc/fastdeploy/backends/ort/ort_backend.cc
> +    memcpy(static_cast<void*>(tensor->Data()), value.GetTensorData<void*>(),
当前默认是Data()访问的是只读数据， MutableData()则是返回可读写的指针

2022-09-06 13:33 UTC, heliqi commented on csrc/fastdeploy/backends/ort/ort_backend.cc
> +    memcpy(static_cast<void*>(tensor->Data()), value.GetTensorData<void*>(),
Done 改错了

2022-09-06 13:34 UTC, heliqi commented on csrc/fastdeploy/backends/ort/ort_backend.cc
> +    memcpy(static_cast<void*>(tensor->Data()), value.GetTensorData<void*>(),
已改

2022-09-07 07:21 UTC, jiangjiajun requested changes

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/backends/ort/ort_backend.cc
> +  memcpy(tensor->MutableData(), value.GetTensorData<void*>(), numel);
输出tensor没有赋值name

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +                 "[ERROR] TRT don't support INT64 input on GPU, "
这里可以删除[ERROR] 这个前辍了, FDASSERT后面修改了输出格式，自动添加了`[ERROR] `这个前辍字符串

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +      }
这里两处日志同上

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +  data_ptr = nullptr;
这个data_ptr没看到有引用

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/core/fd_tensor.cc
>  }
这个函数不需要的话直接删除，不要存在多种api分配方式

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/core/fd_tensor.cc
> +                      const FDDataType& data_type, const Device& new_device) {
加入一个name默认参数，替代原有的Allocate函数

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +                                     output_dims.d + output_dims.nbDims);
这里改成`(*outputs)[ori_idx].Resize(shape, dtype, device, name)` 后面在开发时，我们也尽量使用都使用这一行api。  之后要逐步删除单独访问成员变量的代码

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/core/allocate.h
> +#include "fastdeploy/utils/utils.h"
代码添加`fastdeploy`命名空间

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/core/fd_tensor.h
>    // this function weill return a pointer to cpu memory
上面有个错别字，顺便也改下， `weill` -> `will`

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/core/fd_tensor.h
> +  const void* MutableData() const;
这个函数的场景是在什么情况下，理论上对于只读的情况下，我们使用Data()函数

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/core/fd_tensor.h
> +                const Device& new_device = Device::CPU);
删除这个函数

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/pybind/fastdeploy_runtime.cc
> +               inputs[index].Resize(data_shape);
与前面类似，统一成`inputs[index].Resize(data_shape, dtype, Device::CPU, name)`

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/pybind/main.cc.in
> +    tensor->Resize(data_shape);
与前同类似，统一成`inputs[index].Resize(data_shape, dtype, Device::CPU, name)`

2022-09-07 07:21 UTC, jiangjiajun commented on csrc/fastdeploy/pybind/main.h
> +    inputs[i].Resize(data_shape);
与前同类似，统一成`inputs[index].Resize(data_shape, dtype, Device::CPU, name)

2022-09-07 07:25 UTC, heliqi commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +                 "[ERROR] TRT don't support INT64 input on GPU, "
Done

2022-09-07 07:25 UTC, heliqi commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +      }
Done

2022-09-07 07:25 UTC, heliqi commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +  data_ptr = nullptr;
Done

2022-09-07 07:27 UTC, heliqi commented on csrc/fastdeploy/core/fd_tensor.cc
>  }
暂时需要，后面再提代码统一把Allocate改成Resize

2022-09-07 07:37 UTC, heliqi commented on csrc/fastdeploy/core/fd_tensor.cc
> +                      const FDDataType& data_type, const Device& new_device) {
Done

2022-09-07 07:39 UTC, heliqi commented on csrc/fastdeploy/core/allocate.h
> +#include "fastdeploy/utils/utils.h"
Done

2022-09-07 07:40 UTC, heliqi commented on csrc/fastdeploy/core/fd_tensor.h
>    // this function weill return a pointer to cpu memory
Done

2022-09-07 08:09 UTC, heliqi commented on csrc/fastdeploy/core/fd_tensor.h
> +  const void* MutableData() const;
已删

2022-09-07 08:10 UTC, heliqi commented on csrc/fastdeploy/core/fd_tensor.h
> +                const Device& new_device = Device::CPU);
后面统一提PR删除，现在太多地方用

2022-09-07 08:57 UTC, heliqi commented on csrc/fastdeploy/pybind/fastdeploy_runtime.cc
> +               inputs[index].Resize(data_shape);
Done

2022-09-07 09:03 UTC, heliqi commented on csrc/fastdeploy/pybind/main.cc.in
> +    tensor->Resize(data_shape);
Done

2022-09-07 09:04 UTC, heliqi commented on csrc/fastdeploy/pybind/main.h
> +    inputs[i].Resize(data_shape);
Done

2022-09-07 09:08 UTC, heliqi commented on csrc/fastdeploy/backends/tensorrt/trt_backend.cc
> +                                     output_dims.d + output_dims.nbDims);
done

2022-09-07 09:08 UTC, heliqi commented on csrc/fastdeploy/backends/ort/ort_backend.cc
> +  memcpy(tensor->MutableData(), value.GetTensorData<void*>(), numel);
done

2022-09-08 03:19 UTC, jiangjiajun approved these changes

2022-09-08 08:36 UTC, jiangjiajun approved these changes

2022-09-08 08:53 UTC, merged