[Hackthon_4th 244] Added Paddle Lite GPU Backend
PaddlePaddle/FastDeploy pull request #1907
Opened 2023-05-06 16:29 UTC by unseenme

### PR types(PR类型)

Backend 

### Description

Android GPU (OpenCL) inference by Paddle Lite Backend has been enabled.

2023-05-08 13:33 UTC, DefTruth requested changes

2023-05-08 13:33 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +    config_.set_model_dir(runtime_option.model_file);
FD是需要使用`model_file`和和`param_file`的形式，这里需要保持原来的逻辑。可以使用FD提供的PaddleClas的模型进行验证：
- https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/classification/paddleclas/cpu-gpu

2023-05-08 13:33 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +    config_.set_model_dir(runtime_option.model_file);
需要提供结果正确性的验证说明，比如使用FD已集成的分类或目标检测模型，在启用OpenCL后，得到正确的结果。目标检测可以输出可视化结果。

2023-05-08 13:33 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +    config_.set_model_dir(runtime_option.model_file);
另外，FD默认提供的Lite库是不支持opencl的，因此，需要修改cmake/paddlelite.cmake，提供opencl版本的lite full_publish库。我们已经预编译好armv7, armv8 android库，请修改cmake/paddlelite.cmake，根据ABI和WITH_OPENCL选择对应的库进行下载。  
```bash
# Android
https://bj.bcebos.com/fastdeploy/third_libs/lite-android-arm64-v8a-fp16-opencl-0.0.0.ab000121e.tgz
https://bj.bcebos.com/fastdeploy/third_libs/lite-android-armeabi-v7a-opencl-0.0.0.ab000121e.tgz
```
- WITH_OPENCL需要添加到FastDeploy.cmake.in中

2023-05-08 13:33 UTC, DefTruth commented on cmake/check.cmake
> +    set(WITH_GPU OFF)
这行是多余的，FATAL_ERROR直接就终止编译了

2023-05-08 13:33 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/configure_hardware.cc
> +      paddle::lite_api::Place{TARGET(kOpenCL), PRECISION(kFP16), DATALAYOUT(kImageDefault)},
这里要根据option.enable_fp16来决定是否添加kFP16相关的设置，FD统一默认采用FP32推理，无论是CPU还是GPU

2023-05-08 13:35 UTC, DefTruth commented
@unseenme 感谢您的贡献，有几处地方需要尽快修改和完善下才能合入哈~

2023-05-08 13:47 UTC, DefTruth commented on fastdeploy/runtime/backends/lite/configure_hardware.cc
> +      paddle::lite_api::Place{TARGET(kOpenCL), PRECISION(kFP16), DATALAYOUT(kImageDefault)},
如： 
```c++
if (option.enable_fp16) {
      valid_places.emplace_back(
        Place{TARGET(kOpenCL), PRECISION(kFP16), DATALAYOUT(kImageDefault)});
      valid_places.emplace_back(
        Place{TARGET(kOpenCL), PRECISION(kFP16), DATALAYOUT(kImageFolder)});
      config_.set_opencl_precision(CL_PRECISION_FP16);
    }
```

2023-05-08 22:33 UTC, unseenme commented
> @unseenme 感谢您的贡献，有几处地方需要尽快修改和完善下才能合入哈~

感谢Review，我会尽快修改完善。

2023-05-09 13:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=1907) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: unseenme<br/>:white_check_mark: DefTruth<br/>:x: shinkounen<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=1907) it.</sub>

2023-05-09 13:34 UTC, unseenme commented on fastdeploy/runtime/backends/lite/configure_hardware.cc
> +      paddle::lite_api::Place{TARGET(kOpenCL), PRECISION(kFP16), DATALAYOUT(kImageDefault)},
已经增加 fp16 判断。

2023-05-09 13:35 UTC, unseenme commented on cmake/check.cmake
> +    set(WITH_GPU OFF)
删除了三处 FATAL_ERROR 后的 set。

2023-05-09 13:37 UTC, unseenme commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +    config_.set_model_dir(runtime_option.model_file);
修改了模型加载方式。
增加了预编译库下载。
添加了编译开关。

2023-05-09 13:39 UTC, unseenme commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +    config_.set_model_dir(runtime_option.model_file);
模型加载方式修改后，需要用新模型重新验证。验证进行中。

2023-05-10 06:29 UTC, DefTruth approved these changes

2023-05-10 06:30 UTC, DefTruth commented
LGTM~ @unseenme 还需要再PR的comment中提供下编译说明和测试结果哈

2023-05-11 11:39 UTC, DefTruth requested changes

2023-05-11 11:39 UTC, DefTruth commented on fastdeploy/text/uie/model.cc
> +                        Backend::LITE};
先不需要修改UIE

2023-05-11 12:23 UTC, unseenme commented on fastdeploy/text/uie/model.cc
> +                        Backend::LITE};
UIE相关修改已经撤销了。

2023-05-11 12:59 UTC, unseenme commented
# 编译说明

编译选项 DWITH_OPENCL 设置为 ON 时，FastDeploy 将支持 Paddle Lite GPU 后端。  
例：

    cmake -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE} -DCMAKE_BUILD_TYPE=MinSizeRel -DANDROID_ABI=${ANDROID_ABI} -DANDROID_NDK=${ANDROID_NDK} -DANDROID_PLATFORM=${ANDROID_PLATFORM} -DANDROID_STL=${ANDROID_STL} -DANDROID_TOOLCHAIN=${ANDROID_TOOLCHAIN} -DENABLE_LITE_BACKEND=ON -DENABLE_VISION=ON -DCMAKE_INSTALL_PREFIX=${FASDEPLOY_INSTALL_DIR} -Wno-dev -DWITH_OPENCL=ON ../../..

# 测试结果

CPU 结果与 GPU 结果一致。

## Android CPU

```
nio:/data/local/tmp/2023/2023 $ ./infer_demo ResNet50_vd_infer ILSVRC2012_val_00000010.jpeg 3
[FastDeploy][INFO] fastdeploy/runtime/runtime.cc(328)::CreateLiteBackend	Runtime initialized with Backend::PDLITE in Device::CPU.
ClassifyResult(
label_ids: 153, 
scores: 0.686230, 
)
```

## Android GPU

```
nio:/data/local/tmp/2023/2023 $ ./infer_demo ResNet50_vd_infer ILSVRC2012_val_00000010.jpeg 8                                                                                                             
[FastDeploy][INFO] fastdeploy/runtime/runtime.cc(328)::CreateLiteBackend	Runtime initialized with Backend::PDLITE in Device::GPU.
ClassifyResult(
label_ids: 153, 
scores: 0.686230, 
)
```

2023-05-11 13:02 UTC, unseenme commented on fastdeploy/runtime/backends/lite/lite_backend.cc
> +    config_.set_model_dir(runtime_option.model_file);
正确性验证已经提供。

2023-05-11 13:17 UTC, DefTruth commented
LGTM~

2023-05-12 06:23 UTC, DefTruth requested changes

2023-05-12 06:23 UTC, DefTruth commented on fastdeploy/runtime/runtime_option.cc
> +#if defined(WITH_GPU) || defined(WITH_OPENCL)
这个函数需要修改一下，设置lite option的device，只这样设置，我在测试机上测试并没有成功使用gpu.  
```C++
void RuntimeOption::UseGpu(int gpu_id) {
#if defined(WITH_GPU) || defined(WITH_OPENCL)
  device = Device::GPU;
  device_id = gpu_id;  

#if defined(WITH_OPENCL) && defined(ENABLE_LITE_BACKEND)
  paddle_lite_option.device = device;
#endif

#else
  FDWARNING << "The FastDeploy didn't compile with GPU, will force to use CPU."
            << std::endl;
  device = Device::CPU;
#endif
}
```

2023-05-12 11:44 UTC, DefTruth approved these changes

2023-05-12 11:44 UTC, merged