[XPU] Add gm_default_size -> Backend::LITE
PaddlePaddle/FastDeploy pull request #1934
Opened 2023-05-11 15:03 UTC by linkk08

### PR types(PR类型)

### Description

适配多个模型的业务中gm default size无法做到针对性适配的问题，新增该参数后，可以一个context对应一个default size，该参数对性能优化有着比较重要的作用。

2023-05-12 08:30 UTC, DefTruth requested changes

2023-05-12 08:30 UTC, DefTruth commented on fastdeploy/runtime/runtime_option.h
> +                    int gm_default_size = 0,
这个gm_default_size参数，需要改成放在参数列表的最后，避免和已有的用法冲突

2023-05-12 08:30 UTC, DefTruth commented on fastdeploy/runtime/runtime_option.h
> +                    int gm_default_size = 0,
另外，可以在PR comment补充下说明设置这个参数后XPU或Lite会发生什么改变吗？

2023-05-15 08:06 UTC, linkk08 commented on fastdeploy/runtime/runtime_option.h
> +                    int gm_default_size = 0,
done

2023-05-15 09:32 UTC, DefTruth approved these changes
LGTM

2023-05-16 06:31 UTC, merged