[Hackathon 181] Add TVM support for FastDeploy on macOS
PaddlePaddle/FastDeploy pull request #1969
Opened 2023-05-19 11:35 UTC by Zheng-Bicheng

### PR types(PR类型)
Backend

### Description

Add TVM support for FastDeploy on macOS

2023-05-21 14:04 UTC, DefTruth requested changes

2023-05-21 14:04 UTC, DefTruth commented on third_party/dmlc-core/include/dmlc/array_view.h
> +#include <array>
这部分third_party的代码，是否可以改成下载的方式，放在tvm.cmake的逻辑中。如果开启tvm后端则下载，而非直接提交到FD。

2023-05-23 06:24 UTC, DefTruth requested changes

2023-05-23 06:24 UTC, DefTruth commented on examples/vision/detection/paddledetection/tvm/cpp/infer_ppyoloe_demo.cc
> +  tc.Start();
统计耗时的逻辑可以删掉

2023-05-23 06:24 UTC, DefTruth commented on fastdeploy/runtime/backends/tvm/tvm_backend.cc
> +    FDERROR << "TVMBackend doesn't support this model format or device."
这个报错写具体的信息，<< model_format  以及 << device，其他FDERROR类似，避免使用模糊的信息。

2023-05-23 06:24 UTC, DefTruth commented on fastdeploy/runtime/enum_variables.cc
> +#ifdef ENABLE_TVM_BACKEND
ENABLE_TVM_BACKEND在fastdeploy/core/config.h.in中增加一下

2023-05-23 06:24 UTC, DefTruth commented on fastdeploy/vision/detection/ppdet/model.h
> +                          Backend::TVM};
这里TVMBackend是已经支持GPU了吗？

2023-05-23 06:24 UTC, DefTruth commented on tools/tvm/convert_model.py
> +import paddle
这个工具脚本改成paddle2tvm.py吧

2023-05-23 06:24 UTC, DefTruth commented on examples/vision/detection/paddledetection/tvm/README.md
> +```bash
该目录下还需要提供一下详细的模型转换文档

2023-05-24 07:31 UTC, Zheng-Bicheng commented on fastdeploy/vision/detection/ppdet/model.h
> +                          Backend::TVM};
暂时还没有，已经删除

2023-05-24 08:05 UTC, DefTruth requested changes

2023-05-24 08:05 UTC, DefTruth commented on fastdeploy/runtime/runtime_option.cc
> +  backend = TVM;
使用Backend::TVM写法

2023-05-25 11:56 UTC, DefTruth commented
LGTM

2023-05-25 11:57 UTC, DefTruth approved these changes

2023-05-25 11:59 UTC, merged