[Backend] Add pybind for tvm. Add python example for paddledetection on TVM Backend
PaddlePaddle/FastDeploy pull request #1998
Opened 2023-05-29 01:58 UTC by Zheng-Bicheng

### PR types(PR类型)
Backend

2023-05-29 12:50 UTC, DefTruth requested changes

2023-05-29 12:50 UTC, DefTruth commented on examples/vision/detection/paddledetection/tvm/cpp/infer_ppyoloe_demo.cc
> +  auto params_file = "tvm_model.params";
这里是否要加上model_dir：
```C++
params_file = model_dir + "/tvm_model.params";
```

2023-05-30 02:28 UTC, Zheng-Bicheng commented on examples/vision/detection/paddledetection/tvm/cpp/infer_ppyoloe_demo.cc
> +  auto params_file = "tvm_model.params";
Done

2023-05-31 03:13 UTC, DefTruth approved these changes
LGTM

2023-06-04 05:26 UTC, merged