[Bug Fix] fixed fd server use_paddle parameter parse policy
PaddlePaddle/FastDeploy pull request #2044
Opened 2023-06-20 03:17 UTC by DefTruth

### PR types(PR类型)

### Description

- fixed fd server use_paddle parameter parse policy

2023-06-20 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=2044) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=2044) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: DefTruth<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=2044) it.</sub>

2023-06-20 03:26 UTC, heliqi approved these changes
LGTM

2023-06-20 05:07 UTC, jiangjiajun requested changes

2023-06-20 05:07 UTC, jiangjiajun commented on serving/src/fastdeploy_runtime.cc
> +                  runtime_options_->EnablePaddleToTrt();
这里是不是可以统一一下，都使用

```
runtime_option_->UsePaddleInferBackend();
runtime_options_->paddle_infer_option.enable_trt = true;  
```

2023-06-21 03:21 UTC, DefTruth commented on serving/src/fastdeploy_runtime.cc
> +                  runtime_options_->EnablePaddleToTrt();
done

2023-06-21 07:44 UTC, merged