add yolox c++/pybind and model_zoo demo
PaddlePaddle/FastDeploy pull request #21
Opened 2022-07-18 06:18 UTC by DefTruth

* add yolox c++/pybind and model_zoo demo
* move some helpers to private in yolov6、yolov5 and ppcls/model
* fixed CMakeLists.txt typos

2022-07-18 12:08 UTC, jiangjiajun requested changes

2022-07-18 12:08 UTC, jiangjiajun commented on fastdeploy/vision/megvii/yolox.cc
> +                          std::vector<YOLOXAnchor> &anchors) {
这里我们统一下风格，所有写入的参数使用指针传入，所以这里我们统一定义为
```
void GenerateYOLOXAnchors(const std::vector<int>& size, 
                          const std::vector<int> &downsample_strides, 
                          std::vector<YOLOXAnchor>* anchors)
```
另外在.clang_format中已经定义所有的符号靠左对齐，理论上应该提交时会自动格式化，但这里目前是靠右对齐的

2022-07-18 12:08 UTC, jiangjiajun commented on fastdeploy/vision/megvii/yolox.cc
> +void PreProc(Mat* mat, std::vector<int> size, std::vector<float> color) {
感觉这个函数，像是下面那个`Preprocess`的缩写，命名上看是否能根据实际操作的含义进行重命名。

另外传入参数，如果是只读，则使用`const T&`， 写入参数传入`T*`

2022-07-18 12:08 UTC, jiangjiajun commented on fastdeploy/vision/megvii/yolox.cc
> +void PreProc(Mat* mat, std::vector<int> size, std::vector<float> color) {
目前我们统一在代码采用此风格，在调用函数时，也可快速判断哪些参数只被读，只被写
```
void Func(const T& a, const T& b, T* c);

T a, b, c;
Func(a, b, &c);
```

2022-07-18 12:10 UTC, DefTruth commented on fastdeploy/vision/megvii/yolox.cc
> +                          std::vector<YOLOXAnchor> &anchors) {
好的

2022-07-18 12:11 UTC, DefTruth commented on fastdeploy/vision/megvii/yolox.cc
> +void PreProc(Mat* mat, std::vector<int> size, std::vector<float> color) {
这个函数的命名是参考YOLOX中python预处理的函数preproc

2022-07-19 01:54 UTC, jiangjiajun approved these changes

2022-07-19 01:55 UTC, merged