[vision] support PaddleDetection/MaskRCNN model
PaddlePaddle/FastDeploy pull request #218
Opened 2022-09-12 05:34 UTC by DefTruth

### PR types

New features

### PR changes

APIs

### Describe

- 支持PaddleDetection/MaskRCNN实例分割模型推理
- 更新VisDetection函数，支持instance mask可视化
- 更新DetectionResult、增加Mask数据结构，支持实例分割
- 增加MaskRCNN C++和Python使用案例及更新案例文档
- 更新detection_result.md文档，增加实例分割mask属性说明
- C++/Python 推理后端测试情况 （该模型目前仅支持Paddle后端推理）

| C++ Paddle-CPU | C++ Paddle-GPU |Python3.7 Paddle-CPU|Python3.7 Paddle-GPU|  
|:---:|:---:|:---:|:---:|  
|测试通过|测试通过|测试通过|不通过，cuBLAS报错|  

因此，MaskRCNN的Python目前案例先跳过GPU推理，会回退到CPU推理

- 可视化样例  

<img width="640" alt="image" src="https://user-images.githubusercontent.com/31974251/189580135-df9ac833-c9a8-4176-b608-47bf8ba2b8f4.png">

2022-09-12 11:04 UTC, jiangjiajun requested changes

2022-09-12 11:04 UTC, jiangjiajun commented on csrc/fastdeploy/vision/detection/ppdet/mask_rcnn.cc
> +  processors_.push_back(std::make_shared<HWC2CHW>());
这里代码是共享的，可以全部写到ppyoloe里面

2022-09-12 11:05 UTC, jiangjiajun requested changes

2022-09-12 11:05 UTC, jiangjiajun commented on csrc/fastdeploy/vision/detection/ppdet/mask_rcnn.cc
> +}
maskrcnn是否还需要重复写这些，应该是与rcnn在前面的预处理包括数据准备完全一致，除了后处理多了一个mask的处理

2022-09-12 11:29 UTC, DefTruth commented on csrc/fastdeploy/vision/detection/ppdet/mask_rcnn.cc
> +}
实现的时候没有注意到rcnn和maskrcnn之间的关联，我继承rcnn重新实现下maskrcnn

2022-09-14 02:50 UTC, jiangjiajun approved these changes

2022-09-14 02:50 UTC, merged

2022-09-14 03:11 UTC, jiangjiajun commented
Relate with this issue https://github.com/PaddlePaddle/FastDeploy/issues