YOLOv7
PaddlePaddle/FastDeploy pull request #23
Opened 2022-07-18 10:29 UTC by ziqi-jin

2022-07-18 10:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=23) <br/>All committers have signed the CLA.

2022-07-18 10:59 UTC, jiangjiajun requested changes

2022-07-18 10:59 UTC, jiangjiajun commented on fastdeploy/vision/wongkinyiu/yolov7.cc
> +#include "fastdeploy/vision/wongkinyiu/yolov7.h"
copyright

2022-07-18 11:59 UTC, DefTruth reviewed
fastdeploy/vision/wongkinyiu/yolov7.h  
```c++
private:
  // 初始化函数，包括初始化后端，以及其它模型推理需要涉及的操作
  virtual bool Initialize();
```
private限制下的virtual关键字应该可以考虑去掉

2022-07-19 02:31 UTC, jiangjiajun requested changes

2022-07-19 02:31 UTC, jiangjiajun commented on fastdeploy/vision/wongkinyiu/yolov7.cc
> +void LetterBox(Mat* mat, std::vector<int> size, std::vector<float> color,
改为
```
void LetterBox(Mat* mat, const std::vector<int>& size, const std::vector<float>& color, bool _auto, bool scale_fill = false, bool scale_up = true, nt stride = 32)
```

2022-07-19 02:31 UTC, jiangjiajun commented on model_zoo/vision/yolov7/README.md
> +- 从PaddlePaddle获取
这里没有内容的话，就先删除好了

2022-07-19 02:31 UTC, jiangjiajun commented on model_zoo/vision/yolov7/cpp/README.md
> +- 从PaddlePaddle获取
同上

2022-07-19 02:35 UTC, ziqi-jin commented on fastdeploy/vision/wongkinyiu/yolov7.cc
> +void LetterBox(Mat* mat, std::vector<int> size, std::vector<float> color,
好的

2022-07-19 02:39 UTC, ziqi-jin commented on model_zoo/vision/yolov7/README.md
> +- 从PaddlePaddle获取
好的

2022-07-19 03:05 UTC, ziqi-jin commented on fastdeploy/vision/wongkinyiu/yolov7.cc
> +void LetterBox(Mat* mat, std::vector<int> size, std::vector<float> color,
已修改 并编译测试通过

2022-07-19 03:17 UTC, jiangjiajun approved these changes

2022-07-19 03:17 UTC, merged