Update ppseg with eigen functions
PaddlePaddle/FastDeploy pull request #238
Opened 2022-09-15 11:32 UTC by felixhjh

### PR types

Function optimization
### PR changes

 APIs   APIs 
### Describe

ppseg replace old argmax softmax max function with eigen operators

2022-09-16 01:26 UTC, jiangjiajun requested changes

2022-09-16 01:26 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/cpp/infer.cc
> +  model.apply_softmax = true;
示例代码中不添加这一行。 我们示例代码尽量简洁一些，一般而言，demo里面的代码就是大部分用户最终的使用形态

现有的Seg部署中，apploy_softmax感觉并不是一个通用理解的操作

2022-09-16 01:26 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/FDTensor2CVMat.cc
> +                     "--apply_softmax."
删除预测过程中的warning， 在模型加载时已经知道是否已经export with argmax，如果需要输出日志，可以在加载时就给出提醒

2022-09-16 01:26 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/FDTensor2CVMat.cc
> +void FDTensor2FP32CVMat(cv::Mat* mat, FDTensor& infer_result,
FDTensor到Mat应该还是一个比较通用的操作。
我们在这里统一加一个接口吧https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/common/processors/mat.h
接口定义
```
Mat CreateFromTensor(const FDTensor& tensor);
```
使用用法
```
Mat mat = CreateFromTensor(tensor);
```

2022-09-16 01:26 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  if (cfg["Deploy"]["with_argmax"]) {
为了兼容老版本模型的，这个参数改为如果存在则读取，不存在就直接设定默认值 with_argmax = false, with_softmax = false

2022-09-16 01:26 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +    FDTensor* infer_result, SegmentationResult* result,
infer_result能否改成只读，其它模型的后处理，这里的infer_result应该都是只读的

2022-09-16 01:26 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.h
>    bool is_resized = false;
为了接下来的Triton集成，我们代码中的预处理和后处理需要保证独立性，实现时我们去除成员变量的依赖。

可以将im_info中记录为
`im_info["input_shape"]`

如果最终结果不是`input_shape`，则resize回去即可

2022-09-16 02:16 UTC, felixhjh commented on examples/vision/segmentation/paddleseg/cpp/infer.cc
> +  model.apply_softmax = true;
行 那我去掉 现在fastdeploy用的模型 就是with_argmax = false 和 with_softmax = false。 也就是如果想要得到softmax的结果，两种办法，第一、去模型库重新导出带softmax的模型
第二、设置apply_softmax这个参数

2022-09-16 02:37 UTC, felixhjh commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  if (cfg["Deploy"]["with_argmax"]) {
老版本的话  按照paddleseg的官方导出文档 默认是 is_with_softmax = false; is_with_argmax = true; 这边这个if 条件就是判断yaml文件是否有cfg["Deploy"]["with_argmax"] 参数，没有就使用默认值is_with_softmax = false; is_with_argmax = true;

2022-09-16 02:39 UTC, felixhjh commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +    FDTensor* infer_result, SegmentationResult* result,
这里还没办法改成只读，因为比如需要对结果进行transpose softmax之类的操作， 然后重新拷贝会infer_result 
std::memcpy(infer_result->MutableData(), transpose_infer_result.MutableData(), num * chw * sizeof(float_t));
所以暂时没办法只读

2022-09-18 07:52 UTC, felixhjh commented on fastdeploy/vision/segmentation/ppseg/FDTensor2CVMat.cc
> +void FDTensor2FP32CVMat(cv::Mat* mat, FDTensor& infer_result,
已添加

2022-09-22 13:21 UTC, merged

2022-09-26 03:05 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.h
>    bool is_resized = false;
- is_resized 移除，避免preprocess & postprocess读写类内成员变量
- shape固定的问题
- - seg导出的模型是[-1, 3, -1, -1] 正常处理
- - seg导出了固定shape的模型[-1, 3, h, w]， yaml会有一个字段`input_shape`， 手动resize

2022-09-26 03:05 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.h
>    bool is_resized = false;
如果是-1, -1的，支持的backend是paddle inference + openvino;
如果是h, w的，支持的backend就是paddle inference + openvino + ort + trt
valid_cpu_backend, valid_gpu_backend