Add PP-ModNet and PP-HumanMatting Support
PaddlePaddle/FastDeploy pull request #240
Opened 2022-09-15 14:46 UTC by ziqi-jin

### PR types

### PR changes

### Describe

add PP-HumanMatting\ ModNet-MobileNetV2\ ModNet-ResNet50_vd\ ModNet-HRNet_w18 
add the process of input_shape  for PPMatting
add LimitLong function

2022-09-16 07:02 UTC, DefTruth requested changes

2022-09-16 07:02 UTC, DefTruth commented on fastdeploy/vision/common/processors/limit_long.cc
> +  int im_size_max = std::min(origin_w, origin_h);
这里的逻辑和CpuRun不一致，这里用了`std::min()`, 是不是用错了？

2022-09-16 07:02 UTC, DefTruth commented on fastdeploy/vision/common/processors/limit_long.h
> +  int GetMaxLong() { return max_long_; }
如果这个函数不修改`max_long_` 的话，可以用const限制，这样某些const LimitLong的情形也可以用
```c++
int GetMaxLong() const { return max_long_; }
```

2022-09-16 07:02 UTC, DefTruth commented on fastdeploy/vision/common/processors/resize_by_input_shape.h
> +  ResizeByInputShape(int width, int height, int interp = 1) {
这些新加的processor可否在头文件中添加简单的文档说明具体的用处，以便于模型开发进行复用。可以参考convert.h或者normalize.h

2022-09-16 07:05 UTC, DefTruth commented
@ziqi-jin 另外比较建议参考ppdet的方式，modnet, humanmatting，hrnet等模型可以继承ppmatting再进行一层简单的封装，这样既方便用户可以通过类名直接调用到关心的模型，也可以在后续的维护中只单独修改某个模型的逻辑

2022-09-19 02:33 UTC, DefTruth approved these changes

2022-09-20 02:20 UTC, jiangjiajun requested changes

2022-09-20 02:20 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/resize_by_input_shape.cc
> +bool ResizeByInputShape::CpuRun(Mat* mat) {
LimitSize

2022-09-20 02:20 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/resize_to_int_mult.h
> +  // Resize Mat* mat to make the size divisible by mult_int_.
LimitByStride

2022-09-20 02:20 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/resize_by_input_shape.h
> +class ResizeByInputShape : public Processor {
LimitBySize

2022-10-07 13:43 UTC, jiangjiajun approved these changes

2022-10-07 13:43 UTC, jiangjiajun commented on fastdeploy/core/fd_tensor.cc
> +}
此处需判断这一维必须为1，才能squeeze

2022-10-07 13:44 UTC, merged