Add openvino mac
PaddlePaddle/FastDeploy pull request #267
Opened 2022-09-22 07:21 UTC by joey12300

### PR types

Others
### PR changes

Others
### Describe

Add openvino mac

2022-09-25 06:21 UTC, jiangjiajun requested changes

2022-09-25 06:21 UTC, jiangjiajun commented on FastDeploy.cmake.in
> +  list(APPEND FASTDEPLOY_LIBS ${OPENVINO_LIBS})
这部分逻辑可以写在openvino.cmake里面吗，保持主CMakeList的逻辑更清晰一点

2022-09-25 08:30 UTC, joey12300 commented on FastDeploy.cmake.in
> +  list(APPEND FASTDEPLOY_LIBS ${OPENVINO_LIBS})
可以，我在openvino.cmake中增加一个变量看看

2022-09-25 10:52 UTC, joey12300 commented on FastDeploy.cmake.in
> +  list(APPEND FASTDEPLOY_LIBS ${OPENVINO_LIBS})
新增了一个`FastDeployUtils.cmake`文件，定义了`get_openvino_libs`方法。这个方法可以在`openvino.cmake` 和`FastDeploy.cmake`调用。调用时只需传入openvino runtime path，即可得到openvino libs路径。

2022-09-26 01:49 UTC, jiangjiajun requested changes

2022-09-26 01:49 UTC, jiangjiajun commented on FastDeployUtils.cmake
> +endfunction()
已经有个utils.cmake了，合到这个里面吧 https://github.com/joey12300/FastDeploy/blob/add_openvino_mac/cmake/utils.cmake

2022-09-26 03:26 UTC, jiangjiajun approved these changes

2022-09-26 04:35 UTC, merged