Add stable diffusion model based on fastdeploy
PaddlePaddle/FastDeploy pull request #297
Opened 2022-09-28 08:40 UTC by joey12300

### PR types

New features
### PR changes

Others
### Describe

Add stable diffusion model based on fastdeploy

2022-09-28 15:46 UTC, ZeyuChen commented on examples/pipelines/stable_diffusion/export_model.py
> +# Licensed under the Apache License, Version 2.0 (the "License");
后面注意这里的license不能是这个。
目录改为
examples/multimodal/stable_diffusion

2022-11-08 06:00 UTC, jiangjiajun requested changes

2022-11-08 06:00 UTC, jiangjiajun commented on examples/multimodal/stable_diffusion/README.md
> +
如刚才沟通
- 提供预训练模型
- 拆分成独立的export.md

2022-11-10 06:17 UTC, joey12300 commented on examples/multimodal/stable_diffusion/README.md
> +
Done

2022-11-10 06:58 UTC, jiangjiajun approved these changes

2022-11-10 06:58 UTC, jiangjiajun commented on examples/multimodal/stable_diffusion/README.md
> +pip install paddlenlp paddlepaddle-gpu
后期将FastTokenizer接口也封装一份在FastDeploy，避免引入过多依赖

2022-11-10 06:59 UTC, merged