AdaFace
PaddlePaddle/FastDeploy pull request #301
Opened 2022-09-28 10:11 UTC by Zheng-Bicheng

### PR types
New features

### PR changes
APIs

### Describe
为FastDeploy新增AdaFace模型

2022-09-28 11:10 UTC, Zheng-Bicheng commented
python example log
`
(PaddleDetection) zhengbicheng@zhengbichengdeMacBook-Pro remove1 % python infer_adaface.py --model ./mobile_face_net_ada_face_112x112.onnx --face test_lite_focal_arcface_0.JPG --face_positive test_lite_focal_arcface_1.JPG --face_negative test_lite_focal_arcface_2.JPG --device cpu
objc[76132]: Class CaptureDelegate is implemented in both /Users/zhengbicheng/PycharmProjects/FastDeploy/python/.setuptools-cmake-build/third_libs/install/opencv/lib/libopencv_videoio.3.4.16.dylib (0x102b54860) and /Users/zhengbicheng/miniconda3/envs/PaddleDetection/lib/python3.8/site-packages/cv2/cv2.abi3.so (0x11c0063d8). One of the two will be used. Which one is undefined.
objc[76132]: Class CVWindow is implemented in both /Users/zhengbicheng/PycharmProjects/FastDeploy/python/.setuptools-cmake-build/third_libs/install/opencv/lib/libopencv_highgui.3.4.16.dylib (0x102ad4a68) and /Users/zhengbicheng/miniconda3/envs/PaddleDetection/lib/python3.8/site-packages/cv2/cv2.abi3.so (0x11c006428). One of the two will be used. Which one is undefined.
objc[76132]: Class CVView is implemented in both /Users/zhengbicheng/PycharmProjects/FastDeploy/python/.setuptools-cmake-build/third_libs/install/opencv/lib/libopencv_highgui.3.4.16.dylib (0x102ad4a90) and /Users/zhengbicheng/miniconda3/envs/PaddleDetection/lib/python3.8/site-packages/cv2/cv2.abi3.so (0x11c006450). One of the two will be used. Which one is undefined.
objc[76132]: Class CVSlider is implemented in both /Users/zhengbicheng/PycharmProjects/FastDeploy/python/.setuptools-cmake-build/third_libs/install/opencv/lib/libopencv_highgui.3.4.16.dylib (0x102ad4ab8) and /Users/zhengbicheng/miniconda3/envs/PaddleDetection/lib/python3.8/site-packages/cv2/cv2.abi3.so (0x11c006478). One of the two will be used. Which one is undefined.
[INFO] fastdeploy/runtime.cc(283)::Init Runtime initialized with Backend::ORT in Device::CPU.
FaceRecognitionResult: [Dim(512), Min(-0.133213), Max(0.148838), Mean(0.000293)]
FaceRecognitionResult: [Dim(512), Min(-0.102777), Max(0.120130), Mean(0.000615)]
FaceRecognitionResult: [Dim(512), Min(-0.116685), Max(0.142919), Mean(0.001595)]
Cosine 01:  0.7483505506964364
Cosine 02:  -0.09605773855893639
RuntimeOption(
  backend : Backend.ORT 
  cpu_thread_num : -1   
  device : Device.CPU   
  device_id : 0 
  model_file : ./mobile_face_net_ada_face_112x112.onnx  
  model_format : ModelFormat.ONNX       
  ort_execution_mode : -1       
  ort_graph_opt_level : -1      
  ort_inter_op_num_threads : -1 
  params_file :         
  trt_enable_fp16 : False       
  trt_enable_int8 : False       
  trt_max_batch_size : 32       
  trt_max_shape : {}    
  trt_max_workspace_size : 1073741824   
  trt_min_shape : {}    
  trt_opt_shape : {}    
  trt_serialize_file :  
)

`

2022-09-28 11:13 UTC, Zheng-Bicheng commented
cpp example log
(base) zhengbicheng@zhengbichengdeMacBook-Pro demo_image_inference % ./demo_image_inference mobile_face_net_ada_face_112x112.onnx test_lite_focal_arcface_0.JPG test_lite_focal_arcface_1.JPG test_lite_focal_arcface_2.JPG 0 

[INFO] fastdeploy/runtime.cc(283)::Init Runtime initialized with Backend::ORT in Device::CPU.
Prediction Done!
--- [Face 0]:FaceRecognitionResult: [Dim(512), Min(-0.648382), Max(0.724431), Mean(0.001426)]
--- [Face 1]:FaceRecognitionResult: [Dim(512), Min(-0.548208), Max(0.640769), Mean(0.003282)]
--- [Face 2]:FaceRecognitionResult: [Dim(512), Min(-0.590414), Max(0.723158), Mean(0.008072)]
Detect Done! Cosine 01: 0.74835, Cosine 02:-0.0960577

2022-09-28 11:16 UTC, DefTruth requested changes

2022-09-28 11:16 UTC, DefTruth commented on examples/vision/faceid/README.md
> +| [paddleclas/AdaFace](./adaface)        | AdaFace 系列模型   | ONNX | [CommitID:babb9a5](https://github.com/deepinsight/insightface/commit/babb9a5) |
CommitID需要修改成paddleclas的commit id，或者换成对应的release版本，可以参考examples/vision/detection/paddledetection中的写法

2022-09-28 11:16 UTC, DefTruth commented on examples/vision/faceid/adaface/README.md
> +| [AdaFace-MobileFacenet](https://bj.bcebos.com/fastdeploy/models/onnx/mobile_face_net_ada_face_112x112.onnx) | 3.2MB | 95.5          |
模型文件需要上传一下，文件比较小，应该可以直接pr的comment传上来

2022-09-28 11:16 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/README.md
> +./infer_adaface_demo mobile_face_net_ada_face_112x112.onnx test_lite_focal_arcface_0.JPG test_lite_focal_arcface_1.JPG test_lite_focal_arcface_2.JPG 2
测试图片也可以通过pr的comment上传一下

2022-09-28 11:16 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/README.md
> +> > * **nms_iou_threshold**: NMS处理过程中iou阈值
这行可以删掉，人脸识别应该不需要设置nms阈值？另外我看到Predict也有个nms_iou_threshold，这个对于人脸识别具体的作用是？

2022-09-28 11:16 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer_adaface.cc
> +/***************************************************************************
这里面是否有暂时不支持的推理后端？如果有，示例文档中说明下即可。

2022-09-28 11:16 UTC, DefTruth commented on examples/vision/faceid/adaface/python/README.md
> +# PaddleClas Python部署示例
这里修改成具体的 AdaFace Python部署示例

2022-09-28 11:16 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/adaface.py
> +from ..contrib.insightface_rec import InsightFaceRecognitionModel
这里import InsightFaceRecognitionModel进来，但没用上，这行是不是可以删除？

2022-09-28 11:17 UTC, Zheng-Bicheng commented on examples/vision/faceid/adaface/README.md
> +| [AdaFace-MobileFacenet](https://bj.bcebos.com/fastdeploy/models/onnx/mobile_face_net_ada_face_112x112.onnx) | 3.2MB | 95.5          |
这个模型不是上传到百度云服务器上了吗

2022-09-28 11:21 UTC, Zheng-Bicheng commented on python/fastdeploy/vision/faceid/contrib/adaface.py
> +from ..contrib.insightface_rec import InsightFaceRecognitionModel
已经删除

2022-09-28 11:22 UTC, DefTruth commented
LGTM

2022-09-28 11:28 UTC, Zheng-Bicheng commented on examples/vision/faceid/adaface/cpp/README.md
> +> > * **nms_iou_threshold**: NMS处理过程中iou阈值
这个是我参考ArcFace的文档编写的，可能ArcFace文档也有问题？😨我一起修改一下吧

2022-09-28 11:34 UTC, Zheng-Bicheng commented on examples/vision/faceid/adaface/cpp/README.md
> +> > * **nms_iou_threshold**: NMS处理过程中iou阈值
已经修改了

2022-09-28 11:34 UTC, Zheng-Bicheng commented on examples/vision/faceid/README.md
> +| [paddleclas/AdaFace](./adaface)        | AdaFace 系列模型   | ONNX | [CommitID:babb9a5](https://github.com/deepinsight/insightface/commit/babb9a5) |
已经修改为release版本

2022-09-28 11:34 UTC, Zheng-Bicheng commented on examples/vision/faceid/adaface/cpp/infer_adaface.cc
> +/***************************************************************************
模型用的是ONNX推理，应该是都可以用的

2022-09-28 11:35 UTC, Zheng-Bicheng commented on examples/vision/faceid/adaface/python/README.md
> +# PaddleClas Python部署示例
已经修改

2022-09-28 11:40 UTC, Zheng-Bicheng reviewed
修改了这部分内容

2022-09-28 11:42 UTC, Zheng-Bicheng reviewed
大佬有时间帮忙通过一下

2022-09-28 12:16 UTC, DefTruth approved these changes

2022-09-29 13:09 UTC, Zheng-Bicheng commented
模型用微信群的，pre-commit限制了我提交模型

2022-09-30 02:30 UTC, DefTruth requested changes

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/CMakeLists.txt
> +add_executable(infer_by_onnx ${PROJECT_SOURCE_DIR}/infer_by_onnx.cc)
1. 不需要 infer_by_onnx.cpp 和 infer_py_paddle.cpp 两个示例，只需要一个 infer.cc 即可。
2. 文档中注意修改成 infer.cc
3. 示例的CMakeLists中是.cc后缀名，但是你这里源文件的后缀名是cpp，都统一成.cc吧

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer_by_onnx.cpp
> +/***************************************************************************
这个源文件的代码是不是多余的，我看到和另一份基本一样，只需要保留paddle模型推理的一个infer.cc即可

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer_by_paddle.cpp
> +/***************************************************************************
改成 infer.cc

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/python/infer_adaface.py
> +import fastdeploy as fd
因为只有一个模型，改成infer.py即可

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/README.md
> +以AdaFace为例提供`infer_adaface.cc`快速完成AdaFace在CPU/GPU，以及GPU上通过TensorRT加速部署的示例。
改成infer.cc

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer_by_paddle.cpp
> +        << "Usage: infer_by_paddle path/to/model path/to/image run_option, "
这里不要用infer_by_xxx ，修改成 infer_demo，和CMakeLists指定的可执行文件对应

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/CMakeLists.txt
> +target_link_libraries(infer_by_paddle ${FASTDEPLOY_LIBS})
可执行文件target需要重新命名为 infer_demo，只保留paddle模型文件推理的demo即可

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/README.md
> +        const ModelFormat& model_format = ModelFormat::ONNX)
文档里参数的默认值要和代码对应，这里model_format需要改成PADDLE

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/models/onnx/mobile_face_net_ada_face_112x112.onnx
默认下载的模型文件也改成paddle的

2022-09-30 02:30 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/README.md
> +./infer_by_onnx mobile_face_net_ada_face_112x112.onnx test_lite_focal_arcface_0.JPG test_lite_focal_arcface_1.JPG test_lite_focal_arcface_2.JPG 0
只需要保留paddle模型的demo

2022-09-30 02:30 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/adaface.py
> +    # 多数是预处理相关，可通过修改如model.size = [112, 112]改变预处理时resize的大小（前提是模型支持）
中文注释都先删掉吧，以后也是需要删掉的

2022-10-01 00:23 UTC, Zheng-Bicheng commented
运行cpp example gpu命令
```text
[WARNING] fastdeploy/runtime.cc(162)::UseGpu    The FastDeploy didn't compile with GPU, will force to use CPU.
[INFO] fastdeploy/runtime.cc(290)::Init Runtime initialized with Backend::ORT in Device::CPU.
Prediction Done!
--- [Face 0]:FaceRecognitionResult: [Dim(512), Min(-0.648382), Max(0.724431), Mean(0.001426)]
--- [Face 1]:FaceRecognitionResult: [Dim(512), Min(-0.548207), Max(0.640769), Mean(0.003282)]
--- [Face 2]:FaceRecognitionResult: [Dim(512), Min(-0.590414), Max(0.723158), Mean(0.008072)]
Detect Done! Cosine 01: 0.74835, Cosine 02:-0.0960577
```

2022-10-01 00:24 UTC, Zheng-Bicheng commented
运行cpp example cpu命令
```text
use CpuInfer
[INFO] fastdeploy/runtime.cc(290)::Init Runtime initialized with Backend::ORT in Device::CPU.
Prediction Done!
--- [Face 0]:FaceRecognitionResult: [Dim(512), Min(-0.648382), Max(0.724431), Mean(0.001426)]
--- [Face 1]:FaceRecognitionResult: [Dim(512), Min(-0.548207), Max(0.640769), Mean(0.003282)]
--- [Face 2]:FaceRecognitionResult: [Dim(512), Min(-0.590414), Max(0.723158), Mean(0.008072)]
Detect Done! Cosine 01: 0.74835, Cosine 02:-0.0960577
```

2022-10-01 01:37 UTC, Zheng-Bicheng commented
目前存在的问题：
```text
python在编译的时候，model_format会设置为ONNX，但是我在fastdeploy/vision/faceid/contrib/adaface.h中已经将model_format配置为ModelFormat::PADDLE了。
```

2022-10-07 15:21 UTC, DefTruth requested changes

2022-10-07 15:21 UTC, DefTruth commented on examples/vision/faceid/adaface/python/README.md
> +python infer.py --model mobile_face_net_ada_face_112x112.onnx --face test_lite_focal_arcface_0.JPG --face_positive test_lite_focal_arcface_1.JPG --face_negative test_lite_focal_arcface_2.JPG --device
这里的案例似乎没有统一为paddle模型格式？我看到GPU和TRT还是onnx的，保留paddle格式的案例即可

2022-10-07 15:21 UTC, DefTruth commented on examples/vision/faceid/adaface/python/README.md
> +fastdeploy.vision.faceid.AdaFace(model_file, params_file=None, runtime_option=None, model_format=ModelFormat.ONNX)
同上，这里也改成paddle格式，python文档中的API说明需要和C++文档中的API说明对应上

2022-10-07 15:21 UTC, DefTruth commented on examples/vision/faceid/adaface/python/README.md
> +> * **model_format**(ModelFormat): 模型格式，默认为ONNX
同上

2022-10-07 15:21 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/adaface.py
> +                 model_format=ModelFormat.ONNX):
这个默认格式也修改成paddle的，这样C++和python的API就统一了

2022-10-08 02:55 UTC, Zheng-Bicheng commented
python gpu 推理结果
```
aistudio@jupyter-790375-4633226:~/work/FastDeploy/examples/vision/faceid/adaface/python$ python infer.py --model mobilefacenet_adaface/mobilefacenet_adaface.pdmodel \
>                 --params_file mobilefacenet_adaface/mobilefacenet_adaface.pdiparams \
>                 --face test_lite_focal_arcface_0.JPG \
>                 --face_positive test_lite_focal_arcface_1.JPG \
>                 --face_negative test_lite_focal_arcface_2.JPG \
>                 --device gpu
[INFO] fastdeploy/runtime.cc(335)::Init Runtime initialized with Backend::PDINFER in Device::GPU.
FaceRecognitionResult: [Dim(512), Min(-0.133213), Max(0.148838), Mean(0.000293)]
FaceRecognitionResult: [Dim(512), Min(-0.102777), Max(0.120130), Mean(0.000615)]
FaceRecognitionResult: [Dim(512), Min(-0.116684), Max(0.142919), Mean(0.001595)]
Cosine 01:  0.748350598153477
Cosine 02:  -0.09605774716467468
RuntimeOption(
  backend : Backend.PDINFER
  cpu_thread_num : -1
  device : Device.GPU
  device_id : 0
  model_file : mobilefacenet_adaface/mobilefacenet_adaface.pdmodel
  model_format : ModelFormat.PADDLE
  ort_execution_mode : -1
  ort_graph_opt_level : -1
  ort_inter_op_num_threads : -1
  params_file : mobilefacenet_adaface/mobilefacenet_adaface.pdiparams
  trt_enable_fp16 : False
  trt_enable_int8 : False
  trt_max_batch_size : 32
  trt_max_shape : {}
  trt_max_workspace_size : 1073741824
  trt_min_shape : {}
  trt_opt_shape : {}
  trt_serialize_file : 
)
```

2022-10-08 02:56 UTC, Zheng-Bicheng commented
python cpu 推理结果
```
aistudio@jupyter-790375-4633226:~/work/FastDeploy/examples/vision/faceid/adaface/python$ python infer.py --model mobilefacenet_adaface/mobilefacenet_adaface.pdmodel \
>                 --params_file mobilefacenet_adaface/mobilefacenet_adaface.pdiparams \
>                 --face test_lite_focal_arcface_0.JPG \
>                 --face_positive test_lite_focal_arcface_1.JPG \
>                 --face_negative test_lite_focal_arcface_2.JPG \
>                 --device cpu
[INFO] fastdeploy/runtime.cc(335)::Init Runtime initialized with Backend::PDINFER in Device::CPU.
FaceRecognitionResult: [Dim(512), Min(-0.133213), Max(0.148838), Mean(0.000293)]
FaceRecognitionResult: [Dim(512), Min(-0.102777), Max(0.120130), Mean(0.000615)]
FaceRecognitionResult: [Dim(512), Min(-0.116685), Max(0.142919), Mean(0.001595)]
Cosine 01:  0.7483505459860448
Cosine 02:  -0.09605775122416899
RuntimeOption(
  backend : Backend.PDINFER
  cpu_thread_num : -1
  device : Device.CPU
  device_id : 0
  model_file : mobilefacenet_adaface/mobilefacenet_adaface.pdmodel
  model_format : ModelFormat.PADDLE
  ort_execution_mode : -1
  ort_graph_opt_level : -1
  ort_inter_op_num_threads : -1
  params_file : mobilefacenet_adaface/mobilefacenet_adaface.pdiparams
  trt_enable_fp16 : False
  trt_enable_int8 : False
  trt_max_batch_size : 32
  trt_max_shape : {}
  trt_max_workspace_size : 1073741824
  trt_min_shape : {}
  trt_opt_shape : {}
  trt_serialize_file : 
)
```

2022-10-08 11:07 UTC, DefTruth requested changes

2022-10-08 11:07 UTC, DefTruth commented on examples/vision/faceid/adaface/README.md
> +| [AdaFace-MobileFacenet](https://bj.bcebos.com/fastdeploy/models/onnx/mobile_face_net_ada_face_112x112.onnx) | 3.2MB | 95.5          |
这里模型下载的地址，也修改成paddle的模型，和使用文档保持一致

2022-10-08 11:40 UTC, DefTruth approved these changes

2022-10-09 02:58 UTC, DefTruth requested changes

2022-10-09 02:58 UTC, DefTruth commented on examples/vision/faceid/adaface/README.md
> +## 导出ONNX模型
这里的标题还是ONNX，把文档里面都检查一下？

2022-10-09 02:58 UTC, DefTruth commented on examples/vision/faceid/adaface/README.md
> +## 下载预训练ONNX模型
这里也是需要改成Paddle模型

2022-10-09 08:33 UTC, DefTruth approved these changes

2022-10-11 01:55 UTC, jiangjiajun approved these changes

2022-10-11 01:55 UTC, merged