Improve OCR Readme
PaddlePaddle/FastDeploy pull request #326
Opened 2022-10-08 06:44 UTC by yunyaoXYY

在OCR文档中，说明FastDeploy提供的模型输入shape和PaddleOCR提供的模型有差异.
并给出用户自行使用PaddleUtils来修改输入shape的示例.

2022-10-08 07:16 UTC, jiangjiajun requested changes

2022-10-08 07:16 UTC, jiangjiajun commented on examples/vision/ocr/README.md
> +                             --input_shape_dict="{'x':[-1,3,-1,-1]}"
只需要处理OCRv3的det模型吗？ 其余模型需要处理吗，包括cls， 以及ocrv2

2022-10-09 04:23 UTC, jiangjiajun requested changes

2022-10-09 04:23 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_system_v2.cc
> +    return false;
代码是不是没有格式化， 运算符前后需要有空格

2022-10-09 04:46 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/ppocr_system_v2.cc
> +    return false;
我检查一下

2022-10-09 09:31 UTC, jiangjiajun approved these changes

2022-10-09 09:31 UTC, merged