[vision] add pptracking model
PaddlePaddle/FastDeploy pull request #357
Opened 2022-10-13 00:51 UTC by ChaoII

### PR types
New features 

### PR changes
Others

### Describe
新增pptracking JDE模型
模型效果：
<img width="958" alt="222" src="https://user-images.githubusercontent.com/44053467/195473968-28cd31a5-b8cc-4f0e-b3be-c9e31230950f.png">

2022-10-13 01:35 UTC, ChaoII commented
@jiangjiajun 系统提供的opencv 是没有吧卡尔曼滤波相关(`cv::KalmanFilter::correct`...)编进去还是版本太低了么有呀

2022-10-13 01:44 UTC, jiangjiajun commented
Hi, @ChaoII 我看ci仍然没有通过，如果有需要帮助的地方，可以随时联系我

2022-10-13 01:46 UTC, ChaoII commented
> Hi, @ChaoII 我看ci仍然没有通过，如果有需要帮助的地方，可以随时联系我

好的，我已经发现问题了，我再试试

2022-10-13 07:38 UTC, jiangjiajun requested changes
这个PR很棒！有一些小建议可以再改下，有问题可微信随时跟我讨论哈

2022-10-13 07:38 UTC, jiangjiajun commented on fastdeploy/vision/common/result.h
> +  ResultType type = ResultType::MOT;
MOTResult和DetectionResult会有什么差别吗，看这里的定义基本是跟DetectionResult一致的

2022-10-13 07:38 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/lapjv.cc
> +//   Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
copyright都更新为2022

2022-10-13 07:38 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.cc
> +
此处两行空行可删除

2022-10-13 07:38 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.h
> +};
此代码移到`pptracking/letter_box.h`和`pptracking/letter_box.cc`提升可读性

2022-10-13 07:38 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.h
> +};
另外ImplByOpenCV里面，就默认调用OpenCV即可，或者是
```
Resize::Run(mat,new_shape_w,new_shape_h, ProcLib::OPENCV)
```

2022-10-13 07:38 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.h
> +  virtual bool Predict(cv::Mat* img, MOTResult* result);
此处3个public函数，采用doxygen语法写上注释，便于FastDeploy自动生成C++ API文档, 可参考PPYOLOE头文件的注释

本地生成文档
参考https://github.com/PaddlePaddle/FastDeploy/tree/develop/.new_docs/api_docs

2022-10-13 08:45 UTC, ChaoII commented on fastdeploy/vision/common/result.h
> +  ResultType type = ResultType::MOT;
MOTResult 和DetectionResult 不同主要在于除了label_id 还多了一个id 类似于 reid

2022-10-13 08:45 UTC, ChaoII commented on fastdeploy/vision/tracking/pptracking/lapjv.cc
> +//   Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
已更新

2022-10-13 08:45 UTC, ChaoII commented on fastdeploy/vision/tracking/pptracking/model.cc
> +
已删除

2022-10-13 08:46 UTC, ChaoII commented on fastdeploy/vision/tracking/pptracking/model.h
> +};
重新组织结构，到那时为了保证前处理的一致性，还是继承Processor （重载ImplByOpenCV）

2022-10-13 08:46 UTC, ChaoII commented on fastdeploy/vision/tracking/pptracking/model.h
> +  virtual bool Predict(cv::Mat* img, MOTResult* result);
增加doxygen 注释

2022-10-26 05:58 UTC, jiangjiajun approved these changes

2022-10-26 05:58 UTC, jiangjiajun commented on fastdeploy/vision/common/result.h
需添加注释（下一个PR完成）

2022-10-26 05:58 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/letter_box.cc
> +bool LetterBoxResize::ImplByOpenCV(Mat* mat){
这个需要修改下（下个PR，会使得切换其它预处理库时出错）

2022-10-26 05:58 UTC, jiangjiajun commented on python/fastdeploy/vision/tracking/pptracking/__init__.py
> +    def predict(self, input_image):
添加注释（下个PR）

2022-10-26 06:26 UTC, jiangjiajun approved these changes

2022-10-26 06:26 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.cc
> +  // this is a trick operation for ppyoloe while inference on trt
这个模型没有NMS之类的操作，可以删除以下的代码
```
  GetNmsInfo();
  runtime_option.remove_multiclass_nms_ = true;
  runtime_option.custom_op_info_["multiclass_nms3"] = "MultiClassNMS";
```

2022-10-26 06:26 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.cc
> +  if (has_nms_ && runtime_option.backend == Backend::TRT) {
同理，这个判断可以删除

2022-10-26 06:27 UTC, merged