新增RKNPU2后端
PaddlePaddle/FastDeploy pull request #368
Opened 2022-10-14 06:44 UTC by Zheng-Bicheng

### PR types
New features

### PR changes
Others

### Describe
新增rknn backend

2022-10-15 14:14 UTC, Zheng-Bicheng commented
scrfd模型测试(屏蔽nhwc转nchw的代码)，几乎不存在误差
onnx推理结果
![scrfd_cpu_result](https://user-images.githubusercontent.com/58363586/195991169-b79408d3-febf-4e45-badd-e0ec3f2ee267.jpg)
rknn推理结果
![scrfd_rknn_vis_result](https://user-images.githubusercontent.com/58363586/195991173-a271ec0f-ca77-41ba-9634-002a33550726.jpg)

2022-10-15 14:16 UTC, Zheng-Bicheng commented
yolov5模型测试(onnx模型为yolov5 6.0固定shape为(1,3,640,640)),rknn模型存在比较大的误差

onnx模型推理结果
![yolov5s_cpu_vis_result](https://user-images.githubusercontent.com/58363586/195991259-c1ea32e8-08f8-4df9-a13f-5e7cd58b1e08.jpg)
rknn模型推理结果
![yolov5s_rknn_vis_result](https://user-images.githubusercontent.com/58363586/195991271-cdb67aa3-74ae-4914-a675-43a2c3d5f730.jpg)

2022-10-15 14:18 UTC, Zheng-Bicheng commented
arcface模型测试(使用的模型为ms1mv3_arcface_r100 固定输入shape为(1,3,112,112))，存在一定误差，但是并不明显
onnx推理结果
```
--- [Face 0]:FaceRecognitionResult: [Dim(512), Min(-2.309219), Max(2.372197), Mean(0.016987)]
--- [Face 1]:FaceRecognitionResult: [Dim(512), Min(-2.288257), Max(1.995103), Mean(-0.003400)]
--- [Face 2]:FaceRecognitionResult: [Dim(512), Min(-3.243412), Max(3.875865), Mean(-0.030682)]
Detect ArcFace In Cpu Done! Cosine 01: 0.814385, Cosine 02: -0.059388
```

rknn 推理结果
```
--- [Face 0]:FaceRecognitionResult: [Dim(512), Min(-2.310547), Max(2.371094), Mean(0.016962)]
--- [Face 1]:FaceRecognitionResult: [Dim(512), Min(-2.287109), Max(1.996094), Mean(-0.003369)]
--- [Face 2]:FaceRecognitionResult: [Dim(512), Min(-3.242188), Max(3.873047), Mean(-0.030661)]
Detect ArcFace In Cpu Done! Cosine 01: 0.814365, Cosine 02: -0.0594706
```

2022-10-15 14:35 UTC, Zheng-Bicheng commented
yolov5问题初步判断是方框部分推理出现问题。

判断过程如下：

我输出了nms前的label和confidence，发现并无明显差异（误差1%以内），因此基本排除是label和confidence部分出错。

onnx nms前label和confidence

[before_nms_onnx.txt](https://github.com/PaddlePaddle/FastDeploy/files/9792306/before_nms_onnx.txt)

rknn nms前label和confidence

[before_nms_rknn.txt](https://github.com/PaddlePaddle/FastDeploy/files/9792308/before_nms_rknn.txt)

我输出了nms后的方框信息，发现存在较大差距，且体现在定位上，因此基本上可以认为是方框部分推理不准确，导致nms并没有过滤掉这部分本该“重叠”的方框。

onnx nms后的方框信息
[after_nms_onnx.txt](https://github.com/PaddlePaddle/FastDeploy/files/9792314/after_nms_onnx.txt)

rknn nms后的方框信息
[after_nms_rknn.txt](https://github.com/PaddlePaddle/FastDeploy/files/9792319/after_nms_rknn.txt)

2022-10-18 14:36 UTC, Zheng-Bicheng commented
目前测试出来的推理Bug的模型(2022-10-18)，等3588板子到了以后排查:

* yolov5 6.0（坐标点计算出现问题）
* MobileNetV3_small_x0_35_ssld（计算不准）

目前测试出来的需要重写后处理的模型(2022-10-18)

* PaddleDetection系列（导出时集成了NMS等后处理操作，RKNPU2不支持，需要重写后处理）

2022-10-26 02:31 UTC, jiangjiajun requested changes

2022-10-26 02:31 UTC, jiangjiajun commented on docs/cn/build_and_install/rknpu2.md
> +RKNPU2不支持直接使用ONNX模型进行推导，因此我们首先需要把ONNX模型转换为RKNN模型。为了简化流程了，我新建了一个仓库负责这部分的抓换，详情请查看[LuFeng](https://github.com/Zheng-Bicheng/LuFeng)
这里的示例，展示的是ONNX->RKNN的过程，但在当前的项目中，我们需要指引用户如何从源模型，到最终部署。ONNX只是中间的一个过程。

2022-10-26 02:31 UTC, jiangjiajun commented on docs/cn/build_and_install/rknpu2.md
> +## RKNPU2已经支持的模型列表
这里可以是一个表格，链接到相应的examples目录下， build_and_install仅用于介绍如何编译安装

2022-10-26 02:31 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +#include "fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.h"
添加copyright

2022-10-26 02:31 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.h
> +#pragma once
添加 copy right

2022-10-26 02:31 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.h
> +  // ctx句柄，每读取一个新的模型，需要重新创建句柄
代码中不要有中文字符，会导致Windows上编译问题

2022-10-26 02:31 UTC, jiangjiajun commented on fastdeploy/runtime.h
> +typedef enum _rknpu2_core_mask {
这个枚举类型是暴露给用用户使用的吗，如果是，枚举类型我们改统一采用类的命名方式，驼峰命名法。 如果不暴露，则不用使用doxgen语法进行注释，最终不展现在自动生成的c++ api文档中

2022-10-26 02:31 UTC, jiangjiajun commented on fastdeploy/vision/facedet/contrib/scrfd.h
> +  // This function is used to close normalize and hwc2chw operations in preprocessing.
This function will disable normalize and hwc2chw in preprocessing step

2022-10-26 02:31 UTC, jiangjiajun commented on fastdeploy/vision/facedet/contrib/scrfd.h
> +  bool switch_of_nor_and_per = true;
bool disable_normalize_and_permute = false;  这个变量本身也是private的，直接采用全称更容易理解

2022-10-26 02:31 UTC, jiangjiajun commented on fastdeploy/vision/faceid/contrib/insightface_rec.h
> +  bool switch_of_nor_and_per = true;
同上

2022-10-26 07:44 UTC, Zheng-Bicheng commented on docs/cn/build_and_install/rknpu2.md
> +RKNPU2不支持直接使用ONNX模型进行推导，因此我们首先需要把ONNX模型转换为RKNN模型。为了简化流程了，我新建了一个仓库负责这部分的抓换，详情请查看[LuFeng](https://github.com/Zheng-Bicheng/LuFeng)
那我再加上一个paddle模型到onnx模型的流程。以paddleseg为例子，你觉得怎么样？

2022-10-26 07:48 UTC, Zheng-Bicheng commented on docs/cn/build_and_install/rknpu2.md
> +## RKNPU2已经支持的模型列表
done

2022-10-26 07:49 UTC, Zheng-Bicheng commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +#include "fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.h"
done

2022-10-26 07:49 UTC, Zheng-Bicheng commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.h
> +#pragma once
done

2022-10-26 07:58 UTC, Zheng-Bicheng commented on fastdeploy/runtime.h
> +typedef enum _rknpu2_core_mask {
这个枚举类型是暴露给用用户使用的。关于命名方式，这个有点矛盾，因为rk的头文件命名为rknn_core_mask这种形式，因此我也使用类似的命名方式。我已经修改了，我再测试一遍。

2022-10-29 07:52 UTC, closed without merging