Yolo cuda preprocessing util and yolov5 cuda preprocessing
PaddlePaddle/FastDeploy pull request #370
Opened 2022-10-14 11:21 UTC by wang-xinyu

### PR types
Performance optimization

### PR changes
Others - preprocessing

### Describe
- Add a YOLO CUDA preprocessing util
- Yolov5: integrate CUDA preprocessing
- cmake changes to support CUDA source files compile

2022-10-14 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=370) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=370) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=370) it.</sub>

2022-10-18 12:39 UTC, wang-xinyu commented
Latency includes preprocessing, inference and postprocessing, in milliseconds.
Tested on P40, TensorRT8.4.

| Model |  Latency(CPU preprocessing)   |  Latency(CUDA preprocessing)   | Optimization |
|:---- |:----- |:----- |:----- |
| yolov5s | 41 | 28 | 31.7% $\downarrow$ |
| yolov5lite | 40 | 22 | 45% $\downarrow$ |
| yolov6s | 25 | 11 | 56% $\downarrow$ |
| yolov7 | 47 | 32 | 31.9% $\downarrow$ |
| yolov7_e2e | 27 | 16 | 40.7% $\downarrow$ |

2022-10-19 02:37 UTC, jiangjiajun requested changes

2022-10-19 02:37 UTC, jiangjiajun commented on CMakeLists.txt
> +option(BUILD_CUDA_SRC "Whether to build CUDA source files in fastdeploy" OFF)
是指只能在CPU上推理时使用； GPU上推理使用时只能是TensorRT后端吗？

2022-10-19 02:37 UTC, jiangjiajun commented on fastdeploy/vision/detection/contrib/yolov5.cc
> +    FDERROR << "Upsupported arguments for CUDA preprocess." << std::endl;
有个错别字，这里给个明确的提示，例如
```
FDERROR << "Preprocessing with CUDA is only available when the arguments satisfy (is_mini_pad=false, is_no_pad=false, is_scale_up=true)." << std::endl;
```
另外几个模型同理

2022-10-19 03:31 UTC, wang-xinyu commented
This CUDA preprocessing for YOLO is using warp affine method to do resizing, which is slightly different from cv::resize().
Hence the mAP is slightly different.
Below mAP results were tested on coco_val_2017, 5000 images, with TensorRT model.

| Model |  mAP(CPU preprocessing)   |  mAP(CUDA preprocessing)   |
|:---- |:----- |:----- |
| yolov5s | 0.372 | 0.368 |
| yolov6s | 0.424 | 0.418 |
| yolov7 | 0.514 | 0.498 |

2022-10-19 05:59 UTC, wang-xinyu commented on fastdeploy/vision/detection/contrib/yolov5.cc
> +    FDERROR << "Upsupported arguments for CUDA preprocess." << std::endl;
Fixed

2022-10-19 06:01 UTC, wang-xinyu commented on CMakeLists.txt
> +option(BUILD_CUDA_SRC "Whether to build CUDA source files in fastdeploy" OFF)
Verified with ORT also. Comments are refined.

2022-10-19 06:34 UTC, jiangjiajun approved these changes

2022-10-19 06:36 UTC, jiangjiajun approved these changes
Windows的兼容下个PR再补充上

2022-10-19 08:04 UTC, merged