[Serving]add an serving example of tts
PaddlePaddle/FastDeploy pull request #384
Opened 2022-10-17 08:28 UTC by HexToString

### PR types(PR类型)

Serving
The title of this pull request should be `[PR type] Description of this pull request`, e.g `[Model] PP-Matting deployment support`    
  
PR的标题应该为 `[PR type] Description of this pull request`, 例如 `[Model] PP-Matting deployment support`  

### Describe

add an serving example of tts
- Support new model PP-Matting
- Add new data structure `MattingResult`

2022-10-17 08:53 UTC, jiangjiajun requested changes

2022-10-17 08:53 UTC, jiangjiajun commented on examples/audio/streaming_tts_serving_fastdeploy/streaming_tts_serving/1/model.py
> +import codecs
添加copy right

2022-10-17 08:53 UTC, jiangjiajun commented on examples/audio/streaming_tts_serving_fastdeploy/streaming_tts_serving/stream_client.py
> +    print("PASS: stream_client")
下面的图可以改成纯文本的模式写在文档里，不用截图

2022-10-17 08:53 UTC, jiangjiajun commented on examples/audio/streaming_tts_serving_fastdeploy/streaming_tts_serving/1/model.py
> +from paddlespeech.server.utils.util import denorm
这里用到了paddlespeech，需要引入什么前置依赖吗？文档里是不是需要写一下

2022-10-17 15:58 UTC, ZeyuChen reviewed
模型目录改为
examples/audio/pp-tts/

然后里面只放serving目录即可，后续再考虑补充python/cpp相关工作

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +([简体中文](./README_cn.md)|English)
目录层级改为
exmaples/audio/pp-tts/
- README.md
- serving/README.md

重点突出模型为pp-tts，这个代号就特指流式语音合成

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/README_cn.md
> +# 流式语音合成服务
PP-TTS流式语音合成服务化部署

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +
不要上传png图片到repo，改用在issues或者PR中用图床链接的方式来呈现，避免因为图片使repo增大过快影响下载速度

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +# Streaming Speech Synthesis Service
PP-TTS Streaming Text-to-Speech Serving

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/streaming_tts_serving/config.pbtxt
> +name: "streaming_tts_serving"
streaming_pp_tts

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +#### 1.2 Installation(inside the docker)
英文文档标准格式括号与前面的字母需要有个空格
Installation (inside the docer)

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +#### 1.3 Download models(inside the docker)
同上

2022-10-17 15:58 UTC, ZeyuChen commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +([简体中文](./README_cn.md)|English)
PP-TTS代指飞桨发布的特色语音合成系统

2022-10-18 02:19 UTC, HexToString commented on examples/audio/streaming_tts_serving_fastdeploy/streaming_tts_serving/1/model.py
> +from paddlespeech.server.utils.util import denorm
已经在readme中写了，需要安装那个paddlespeech

2022-10-18 02:19 UTC, HexToString commented on examples/audio/streaming_tts_serving_fastdeploy/streaming_tts_serving/stream_client.py
> +    print("PASS: stream_client")
嗯，也可以。

2022-10-18 02:19 UTC, HexToString commented on examples/audio/streaming_tts_serving_fastdeploy/streaming_tts_serving/1/model.py
> +import codecs
好的。

2022-10-18 02:20 UTC, HexToString commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +([简体中文](./README_cn.md)|English)
好的。

2022-10-18 02:20 UTC, HexToString commented on examples/audio/streaming_tts_serving_fastdeploy/README.md
> +
好的，我改成文字吧。

2022-10-18 15:36 UTC, ZeyuChen reviewed
没有大的问题，但readme没看到paddlespeech的安装，这块怎么确保一定能跑起来呢？

2022-10-18 15:36 UTC, ZeyuChen commented on examples/audio/pp-tts/serving/streaming_pp_tts/stream_client.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
这里的目录名是config.pbtxt一定保持一致是吗？
如果是的话可能整体统一为pp-tts比较好

2022-10-19 06:37 UTC, HexToString commented on examples/audio/pp-tts/serving/streaming_pp_tts/stream_client.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
是的。

2022-10-19 06:39 UTC, ZeyuChen approved these changes

2022-10-19 06:40 UTC, merged