Visualize function resize mask back to original image size
PaddlePaddle/FastDeploy pull request #39
Opened 2022-07-25 12:59 UTC by felixhjh

1. 可视化的时候将mask resize回原图大小

2022-08-03 03:35 UTC, jiangjiajun requested changes

2022-08-03 03:35 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppseg/model.cc
>                 Str(const_cast<fastdeploy::FDDataType&>(infer_result.dtype)) +
这里是不是可以直接写成`Str(infer_result.dtype)`

2022-08-03 03:35 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppseg/model.cc
> +    }
这个hwc2chw是不是可以直接改成opencv的操作

2022-08-03 03:35 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppseg/model.cc
> +              static_cast<float_t>(infer_result_buffer[index++]);
processor的这个函数建议按照功能模块拆一下，提升可读性

2022-08-03 05:31 UTC, jiangjiajun requested changes

2022-08-03 05:31 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppseg/model.cc
> +      temp_mat = cv::Mat(height, width, CV_32FC(channel));
int64出来的结果，转为了float的来进行后面的resize处理，这个部署的结果是否跟PaddleSeg对齐了？

2022-08-03 05:57 UTC, felixhjh commented on csrcs/fastdeploy/vision/ppseg/model.cc
> +      temp_mat = cv::Mat(height, width, CV_32FC(channel));
这么做的原因有二：
1. int64的结果出来的是类别的mask矩阵，对于pp-human系列也就是0,1矩阵（其他也就是0-num_classes的矩阵）。opencv没有64位的矩阵变量，因此必须要转。
2. 转为float是因为，resize的插值方式双线性策略（inter=1，也是前处理所使用的策略）只支持float类型opencv mat（不支持int、uint8精度缺失）。为保持前后处理一致所以统一转为float。
3. PaddleSeg给到的三张示例图片，正常人像、竖屏人像、横屏人像fastdeploy结果与PaddleSeg是一致的，后续evaluation模块开发完成（正在去除Paddle依赖）会跑全量

2022-08-03 07:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppseg/model.cc
> +      temp_mat = cv::Mat(height, width, CV_32FC(channel));
第3点， 先确认输出的值(numpy) 与 PaddleSeg是一致的，并做到与Seg结果一致

2022-08-05 01:07 UTC, jiangjiajun approved these changes

2022-08-05 01:10 UTC, jiangjiajun commented
- WARNING日志的关闭，当前在infer里面每次都会输出提示，需让用户能够关闭
- NHWC2CHW的实现应该为FDTensor的基础操作，需集成Eigen库来解决，后续需替换

2022-08-05 01:11 UTC, merged