[Backend] TRT backend uses pinned memory
PaddlePaddle/FastDeploy pull request #403
Opened 2022-10-20 09:05 UTC by wang-xinyu

### PR types(PR类型)

Backend

### Describe

- Introduced [pinned host memory](https://developer.nvidia.com/blog/how-optimize-data-transfers-cuda-cc/)
- Add a new buffer type `FDDeviceHostBuffer`
- Integrate `FDDeviceHostBuffer` into `FDTensor`
- TRT backend optimization with `FDDeviceHostBuffer`

2022-10-20 09:13 UTC, wang-xinyu commented
After integrating pinned memory, the inference latency is comparable with trtexec. It mainly optimized the D2H latency.

The latency includes H2D, GPU inference and D2H.

Tested on P40.

The reason why yolov6s has only a little improvement is the output tensor shape of yolov6s(8400x85) is much smaller than yolov5s(2x25200x85) and yolov7(2x25200x85).

|model| before | after | trtexec|
|:--|:--|:--|:--|
|yolov5s | 11.0566ms | 7.34001ms | 6.76131ms|
|yolov6s |  7.17801ms | 6.483ms | 5.69616ms |
|yolov7 | 25.7099ms | 19.9956ms | 19.8108ms |

2022-10-20 10:06 UTC, jiangjiajun requested changes

2022-10-20 10:06 UTC, jiangjiajun commented on fastdeploy/core/fd_tensor.cc
> +  if (is_pinned_memory) {
`is_pinned_memory`仍然是CPU内存，那看起来应该放在Device的判断之后，跟现有的CPU的代码逻辑在同一个地方

2022-10-20 10:06 UTC, jiangjiajun commented on fastdeploy/core/fd_tensor.cc
> +  if (is_pinned_memory) {
同`CopyBuffer`函数的处理逻辑

2022-10-20 13:48 UTC, wang-xinyu commented on fastdeploy/core/fd_tensor.cc
> +  if (is_pinned_memory) {
fixed

2022-10-20 13:48 UTC, wang-xinyu commented on fastdeploy/core/fd_tensor.cc
> +  if (is_pinned_memory) {
fixed

2022-10-21 05:49 UTC, jiangjiajun requested changes

2022-10-21 05:49 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +void RuntimeOption::EnableTrtPinnedMemory() { trt_enable_pinned_memory = true; }
接口改为`EnablePinedMemory()`  (对应里面的`trt_enable_pinned_memory`，也改为`enable_pinned_memory`)

2022-10-21 06:05 UTC, wang-xinyu commented on fastdeploy/runtime.cc
> +void RuntimeOption::EnableTrtPinnedMemory() { trt_enable_pinned_memory = true; }
Done

2022-10-21 06:07 UTC, wang-xinyu commented
Also verified pinned memory in Paddle Inference GPU backend, tested on PPYoloE. The latency is almost the same as before. Because the output size is small(7200 + 4).

2022-10-21 06:11 UTC, jiangjiajun approved these changes

2022-10-21 10:51 UTC, merged