[Backend] GPU cast int64 to int32
PaddlePaddle/FastDeploy pull request #426
Opened 2022-10-24 09:42 UTC by wang-xinyu

### PR types(PR类型)

Backend

### Describe

- Add a CUDA cast function, implemented with CUDA kernel.
- TRT backend: cast GPU input int64 to int32
- Verified on text/uie/cpp demo, the inference result of GPU int64 input is same as CPU int64 input

2022-10-27 12:06 UTC, jiangjiajun requested changes

2022-10-27 12:06 UTC, jiangjiajun commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +    inputs_desc_[i].original_dtype = ReaderDtypeToFDDtype(onnx_reader.inputs[i].dtype);
GetInputInfo(), GetOutputInfo()应该也是返回真实的dtype，当前仍然会返回`int32`

2022-10-27 12:06 UTC, jiangjiajun commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +                     "casted to INT32" << std::endl;
这行WARNING可以删除，看起来是每次Infer都会输出出来

2022-10-27 13:55 UTC, wang-xinyu commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +    inputs_desc_[i].original_dtype = ReaderDtypeToFDDtype(onnx_reader.inputs[i].dtype);
fixed

2022-10-27 13:55 UTC, wang-xinyu commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +                     "casted to INT32" << std::endl;
deleted

2022-10-28 05:36 UTC, jiangjiajun approved these changes

2022-10-28 05:38 UTC, merged