[Model] yolo use external stream, avoid reallocating output tensors
PaddlePaddle/FastDeploy pull request #447
Opened 2022-10-27 09:47 UTC by wang-xinyu

### PR types(PR类型)

Model

### Describe

- Avoid reallocating output tensors
- Use external stream when using cuda preprocessing, avoid reallocating cuda streams
- Applied the getting CUDA architectures logic in CMake, and eliminated the CMake no CUDA_ARCHITECTURES error.

2022-10-27 09:49 UTC, wang-xinyu commented
Yolov5s Predict() latency(P40, TRT 8.4.3.1, 640x640):

Currently, when UseCudaPreprocessing & EnablePinnedMemory
41ms

After moving output tensors to class member,  which can avoid reallocating output buffers.
25ms

After using external stream, which can avoid reallocating cuda streams.
still 25ms, means allocating cuda stream dosen't take long time.

2022-10-28 09:17 UTC, heliqi commented on fastdeploy/vision/detection/contrib/yolov7.cc
> +  if (!Infer(input_tensors, &output_tensors_)) {
input_tesnors 也可以放入class中作为成员变量， Predict接口反复调用时也会不断销毁创建

2022-10-28 09:17 UTC, heliqi commented on fastdeploy/vision/detection/contrib/yolov7.h
> +  std::vector<FDTensor> output_tensors_;
input、output_tensors 反复创建问题应该适用大部分模型， 这个两个成员变量可以放入到基类FastDeployModel 中

2022-10-28 09:23 UTC, wang-xinyu commented on fastdeploy/vision/detection/contrib/yolov7.cc
> +  if (!Infer(input_tensors, &output_tensors_)) {
input tensor每次推理都是直接去承接preproess输出的指针，没有重复分配buffer，所以重复创建影响不大

2022-10-28 09:28 UTC, wang-xinyu commented on fastdeploy/vision/detection/contrib/yolov7.h
> +  std::vector<FDTensor> output_tensors_;
有道理，但是现在FastDeployModel的Infer函数的参数是input、output tensor，如果把他们加入基类FastDeployModel 中，那Infer的参数就没意义了

2022-10-31 02:44 UTC, heliqi commented on fastdeploy/vision/detection/contrib/yolov7.cc
> +  if (!Infer(input_tensors, &output_tensors_)) {
对性能的提升确实不大，但从代码风格和统一上还是很有必要。 只有output成员变量没有input，代码阅读上会让人奇怪。

2022-10-31 02:46 UTC, heliqi commented on fastdeploy/vision/detection/contrib/yolov7.h
> +  std::vector<FDTensor> output_tensors_;
这个PR可以不管。 
可以后面单独提PR统一修改所有的模型，这个修改提升还是比较大，值得全部改一遍。 佳军觉得呢？ @jiangjiajun

2022-10-31 07:00 UTC, wang-xinyu commented on fastdeploy/vision/detection/contrib/yolov7.cc
> +  if (!Infer(input_tensors, &output_tensors_)) {
已移到FastDeployModel

2022-10-31 07:00 UTC, wang-xinyu commented on fastdeploy/vision/detection/contrib/yolov7.h
> +  std::vector<FDTensor> output_tensors_;
已移到FastDeployModel

2022-10-31 08:21 UTC, jiangjiajun requested changes

2022-10-31 08:21 UTC, jiangjiajun commented on fastdeploy/fastdeploy_model.h
> +  std::vector<FDTensor> input_tensors;
这个改成private变量， 命名改成`input_tensors_`

`input_tensors`和`output_tensors`这个在很多继承的派生类里都用到了

2022-10-31 08:21 UTC, jiangjiajun commented on fastdeploy/fastdeploy_model.cc
> +bool FastDeployModel::Infer(std::vector<FDTensor>& _input_tensors,
对应上面的review，这里可以保留原样

2022-10-31 09:35 UTC, wang-xinyu commented on fastdeploy/fastdeploy_model.h
> +  std::vector<FDTensor> input_tensors;
fixed

2022-10-31 09:35 UTC, wang-xinyu commented on fastdeploy/fastdeploy_model.cc
> +bool FastDeployModel::Infer(std::vector<FDTensor>& _input_tensors,
fixed

2022-11-01 12:16 UTC, jiangjiajun requested changes

2022-11-01 12:16 UTC, jiangjiajun commented on fastdeploy/fastdeploy_model.h
> +    reused_output_tensors.clear();
vector释放应该是用 std::vector<FDTensor>.swap(reused_input_tensors) ?

2022-11-01 12:29 UTC, wang-xinyu commented on fastdeploy/fastdeploy_model.h
> +    reused_output_tensors.clear();
fixed

2022-11-02 01:52 UTC, jiangjiajun approved these changes

2022-11-02 01:52 UTC, merged