[Serving]Add basepreprocess && basepostprocess class for serving
PaddlePaddle/FastDeploy pull request #450
Opened 2022-10-28 02:44 UTC by felixhjh

### PR types(PR类型)

Serving

### Describe

- Add basepreprocess && basepostprocess class for serving

2022-10-28 03:07 UTC, HexToString commented on fastdeploy/vision/common/pre_post_process_base.h
> +  virtual bool BuildPreprocessPipelineFromConfig();
建议把BuildConfig函数，和Run函数都干掉。
直接在构造里面把事都做了。
这样pybind后，python端用户 直接 tensor = DetectionPreprocess(config)即可。更简单明了。

2022-10-30 09:51 UTC, jiangjiajun requested changes

2022-10-30 09:51 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.h
> +  static bool is_with_softmax_;
谨慎添加所有的静态成员变量，在使用后，那么同一个进程下加载多个模型时，模型之间可能会出现冲突问题

2022-10-30 09:51 UTC, jiangjiajun commented on fastdeploy/vision/common/pre_post_process_base.cc
> +  if (!BuildPreprocessPipelineFromConfig()) {
移到构造函数去构建

2022-10-30 09:51 UTC, jiangjiajun commented on fastdeploy/vision/common/pre_post_process_base.h
> +class FASTDEPLOY_DECL BasePostprocess{
Poseprocess::Run(std::vector<FDTensor>& infer_results, std::map<string, std::array<float, 2>, SegResult* result)

2022-10-30 09:51 UTC, jiangjiajun commented on fastdeploy/vision/common/pre_post_process_base.h
> +  std::map<std::string, std::array<int, 2>> im_info_;
放到Run函数中使用
```
auto preprocessor = fastdeploy::vision::PaddleSegPreprocessor(string configfile);

std::vector<FDTensor> out_tensors;
std::map<std::string, std::array<float, 2>> im_info;

auto postprocessor = fastdeploy::vision::PaddleSegProprocessor(bool vertical);
::Run(std::vecotr<fdtensor>, im_info, &segresult)


preprocessor.Run(&mat, &out_tenor, &im_info);
```

2022-10-30 09:51 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +bool PaddleSegPreprocess::is_with_argmax_ = true;
放到Run函数里面，它有默认值

2022-10-30 09:51 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  utils::ChangeValidBackends(config_file, &valid_cpu_backends, &valid_gpu_backends);
这个是Seg独有的，不用放到公共utils目录

2022-11-21 03:09 UTC, closed without merging