[Serving] Modify OCR related model functions to support Serving
PaddlePaddle/FastDeploy pull request #451
Opened 2022-10-28 06:04 UTC by HexToString

### PR types(PR类型)

[Serving] Modify OCR related model functions to support Serving
### Describe

1.Modify OCR related model functions to support Serving
2.Add new pybind interface for preprocess and postprocess

2022-10-31 03:16 UTC, jiangjiajun requested changes

2022-10-31 03:16 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
这里删除了一些参数，没有在preprocess函数中传入

2022-10-31 03:16 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/dbdetector.h
> +  // 所有预处理参数，包含完
代码中不添加中文字符（除demo示例外），会影响Windows上的编译

2022-10-31 06:13 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/dbdetector.h
> +  // 所有预处理参数，包含完
好的

2022-10-31 06:13 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/classifier.h
直接是局部变量

2022-10-31 07:54 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
局部变量也就不能支持用户自定义修改了。 我们改成类的实现后，应该还是要可以支持用户下面的方式来设置均值
```
model.preprocessor.SetMean({0.1, 0.2, 0.3})
```

2022-11-02 09:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=451) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=451) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: yunyaoXYY<br/>:white_check_mark: jiangjiajun<br/>:white_check_mark: HexToString<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=451) it.</sub>

2022-11-17 17:13 UTC, closed without merging