[Backend] Add RKNPU2 backend support
PaddlePaddle/FastDeploy pull request #456
Opened 2022-10-29 07:54 UTC by Zheng-Bicheng

### PR types(PR类型)
Backend

### Describe
新增RKNPU2引擎代码

2022-10-30 10:13 UTC, jiangjiajun requested changes

2022-10-30 10:13 UTC, jiangjiajun commented on docs/cn/build_and_install/rknpu2.md
> +请查看[RKNPU2部署模型教程](~/examples/rknpu2/README.md)
examples放到对应的，如examples/vision/segmenation/paddleseg/rknpu2目录下

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/README.md
> +## ONNX模型转换为RKNN模型
如下的模型，我们的技术出发地应该是 Paddle模型，而非（ONNX模型）。 这里的example最终起到的作用是指导用户如何导出一个Paddle模型，并完成在RKNN的部署，并不单纯只是完成已经提供的下面模型的部署。

所以在examples中的文档要说明以下几点（首先需要拆分到examples/vision/detection/paddledetection/rknpu2这个目录下）

1. 适配的是PaddleDetection哪个分支，哪些模型
2. 导出模型参考XXX文档，同时需注意在导出时要有哪些额外参数（例如exclude_nms）
3. 将模型转换为ONNX模型（Paddle2ONNX需要哪个版本，转换命令是怎样，更好的方式是让用户安装好RKNN2的环境后，执行一个脚本完成Paddle直接到RKNN的转换，这个脚本可以提供在detection/paddledetection/rknpu2目录下)
4. 部署时由于模型的输入格式要求，所以需要注意xxx

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/README.md
> +## RKNPU2 Backend推理使用教程
rknpu2的一些更详细使用教程文档，添加在docs/cn/faq/rknpu2.md里面，然后在examples中添加超链文档到这个文档上去

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/cpp/README.md
> +- [如何切换模型推理后端引擎](../../../../../docs/cn/faq/how_to_change_backend.md)
PR中看到上传了一张图片，我们目前不在repo中直接存放图片，避免造成repo越来越大。可视化的结果直接在此PR的comment中上传后，便可得到一个图片链接，使用此图片链接即可

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/cpp/infer_cpu_npu.cc
> +fastdeploy::RuntimeOption get_option(const std::string &device) {
FD中函数命名统一采用驼峰命名，如GetOption()，同时指针等符号靠左对齐
```
fastdeploy::RuntimeOption GetOption(const std::string& devcie)
```

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/cpp/infer_cpu_npu.cc
> +fastdeploy::ModelFormat get_format(const std::string &device) {
同上

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/cpp/infer_cpu_npu.cc
> +    return format;
这个示例不是仅用于推理RKNPU吗，为啥还需要分为ONNX和RKNN?

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/cpp/infer_cpu_npu.h
> +#endif //RKNPU_TEST_INFER_CPU_NPU_H
示例代码就直接写成一个.cc文件更简洁

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/cpp/main.cc
> +}
同上

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/python/README.md
> +- 2. FastDeploy Python whl包安装，参考[FastDeploy Python安装](../../../../../docs/cn/build_and_install/download_prebuilt_libraries.md)
目前没有预编译的库下载的话，就直接链到build_and_install_rknn.md文档

2022-10-30 10:13 UTC, jiangjiajun commented on examples/rknpu/rknpu2/segmentation/python/README.md
> +- [如何切换模型推理后端引擎](../../../../../docs/cn/faq/how_to_change_backend.md)
如何切换模型推理后端可以删除，因为RKNN上就只有一个。 这个文档主要还是针对CPU/GPU推理使用

2022-10-30 10:13 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +                                 const std::string& params_file,
`params_file`没看到有使用，那么也无需这个参数

2022-10-30 10:13 UTC, jiangjiajun commented on docs/cn/build_and_install/rknpu2.md
> +| ONNX&nbsp;Runtime | RK356X   <br> RK3588 | ONNX   | 编译开关`ENABLE_ORT_BACKEND`为ON或OFF控制，默认OFF    |
这里的ONNX Runtime，是指RK平台的CPU吗？还是包括RKNN2

2022-10-30 10:13 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  if(this->disable_normalize_and_permute){
这里应该是if (!this->disable_normalize_and_permute)？

2022-10-30 10:13 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +        if(this->disable_normalize_and_permute){
这里应该是if(!this->disable_normalize_and_permute)?

2022-10-30 10:13 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  this->disable_normalize_and_permute = false;
从字面意思，这里应该是this->disable_normalize_and_permute = true

2022-10-30 10:13 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.h
> +  bool disable_normalize_and_permute = true;
默认是false

2022-10-30 11:21 UTC, Zheng-Bicheng commented
![human_pp_humansegv2_lite_cpu_result](https://user-images.githubusercontent.com/58363586/198875853-72821ad1-d4f7-41e3-b616-bef43027de3c.jpg)

2022-10-30 11:43 UTC, Zheng-Bicheng commented on examples/rknpu/rknpu2/README.md
> +## ONNX模型转换为RKNN模型
第1，2都已经完成。第3点，Paddle模型转ONNX模型部分，一般都在各自的repo中有体现，一般都使用最新版本的Paddle2ONNX。转换脚本的话，如果用户使用的是自己训练的PaddleSeg模型，转换时的配置文件是不一致的，因此转换脚本并不是通用的。第4点，在API接口处有体现。

2022-10-30 11:46 UTC, Zheng-Bicheng commented on docs/cn/build_and_install/rknpu2.md
> +| ONNX&nbsp;Runtime | RK356X   <br> RK3588 | ONNX   | 编译开关`ENABLE_ORT_BACKEND`为ON或OFF控制，默认OFF    |
ONNX指的是在RK平台上用CPU来跑

2022-10-30 11:53 UTC, Zheng-Bicheng commented on examples/rknpu/rknpu2/segmentation/cpp/infer_cpu_npu.cc
> +    return format;
有的时候用户需要测试一下ONNX模型和RKNN模型的速度比较，就需要使用到ONNX模型

2022-10-31 10:06 UTC, jiangjiajun requested changes

2022-10-31 10:06 UTC, jiangjiajun commented on docs/cn/build_and_install/rknpu2.md
> +**方法2: 通过gittee安装**
gitee

2022-10-31 10:06 UTC, jiangjiajun commented on docs/cn/build_and_install/rknpu2.md
> +请查看[RKNPU2部署模型教程](~/examples/rknpu2/README.md)
这个路径 ~/examples/rknpu2/README.md的路径得修改下

2022-10-31 10:06 UTC, jiangjiajun commented on docs/cn/faq/rknpu2.md
> +RKNPU2不支持直接使用ONNX模型进行推导，因此我们首先需要把ONNX模型转换为RKNN模型。为了简化流程了，我新建了一个仓库负责这部分的抓换，详情请查看[LuFeng](https://github.com/Zheng-Bicheng/LuFeng)
进行部署， 抓换->转换

这里的这个额外的repo是用于说明如何做转换吗？如果是的话，应该也需要整合到FD里面，例如加到FastDeploy/tools/rknpu2

2022-10-31 10:06 UTC, jiangjiajun commented on docs/cn/build_and_install/rknpu2.md
> +链接:https://pan.baidu.com/s/1yNww64gQnvwiCfNhELtkwQ?pwd=easy 提取码:easy 复制这段内容后打开百度网盘手机App，操作更方便哦
改成使用服务器链接下载，文件提供下，我来上传

2022-10-31 10:06 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/README.md
> +    *   对于Paddle动态图模型 -> Paddle静态图模型 -> ONNX模型的过程，请参考其文档说明([模型导出](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/model_export_cn.md))。
注意文档的专业性，避免出现博客式的用词，如“我”

可以说明需要准备PaddleSeg ONNX模型模型。 PaddleSeg的ONNX模型导出方式参考XXX，避免引导到AIStudio或者其它Github Repo，带来文档不可控的影响

2022-10-31 10:06 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/README.md
> +        ```
同理，config.yaml和tools/export.py，也可以直接放在这个目录下

2022-10-31 10:06 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/README.md
> +为了方便开发者的测试，下面提供了PaddleSeg导出的部分模型（导出方式为：**指定**`--input_shape`，**指定**`--output_op none`，**指定**`--without_argmax`，**指定**`--with_softmax`），开发者可直接下载使用。
上面提到不要--with_softmax，但此处又写明--with_softmax

2022-10-31 10:06 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/cpp/README.md
> +转换为RKNN后的模型文件也需要拷贝至model，我这里提供了转换好的文件，输入以下命令下载使用(模型文件为RK3588，RK3568需要重新转换模型)。
避免用"我"， “为了便于测试，本教程中已提供转换好的RKNN模型文件，使用如下命令下载即可（模型文件针对RK3588，如若需要部署至3588，需重新转换模型）” 

此处似乎少了说明怎么转出到3588

2022-10-31 10:06 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/cpp/README.md
> +cmake -DTARGET_SOC=RK3588 ..
这个TARGET_SOC没看到在上面的demo中的CMakeList中发现，反而是在FastDeploy的CMakeList中出现了？ 

如若FastDeploy编译时编译的不是rk3588, 此处指定3588会有问题吗？

2022-10-31 10:06 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/cpp/README.md
> +
这里倒可以不用再写C++ API，不过有一个注意事情需要额外说明的，这里没有强调

RKNPU上对模型的输入要求是使用NHWC格式，且图片归一化操作会在转RKNN模型时，内嵌到模型中，因此我们在使用FastDeploy部署时，需要先调用`DisableNormalizePermute`(C++)或`disable_normalize_permute(Python)，在预处理阶段禁用归一化以及数据格式的转换

2022-10-31 10:06 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/python/README.md
> +
此处也不用再写Python接口文档，但也需要像C++中，添加注意事情，说明输入数据和normalize的问题

2022-10-31 12:24 UTC, jiangjiajun requested changes

2022-10-31 12:24 UTC, jiangjiajun commented on docs/cn/build_and_install/README.md
> +| DRKNN2_TARGET_SOC              | ENABLE_RKNPU2_BACKEND时才需要使用这个编译选项。无默认值, 可输入值为RK3588/RK356X, 必须填入，否则 将编译失败 |
多了一个D

2022-10-31 12:24 UTC, jiangjiajun commented on cmake/rknpu2.cmake
> +
这里最好加上RKNN2_TARGET_SOC的判断，如果没有设置，编译出错

2022-10-31 12:24 UTC, jiangjiajun commented on FastDeploy.cmake.in
> +    message(FATAL_ERROR "TARGET_SOC is not set, ref value: RK356X or RK3588")
不是TARGET_SOC，而是RKNN2_TARGET_SOC

2022-10-31 12:24 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/README.md
> +        # 请在fastdeploy根目录下执行代码
这里这句注释，可能很多人看不明白，建议改成
```
python /path/to/fastDeploy/toosl/export.py --config_path=/path/to/fastdeploy/tools/rknpu2/config/ppset_config.yaml
```

2022-10-31 12:24 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rknpu2/cpp/README.md
> +cmake -DTARGET_SOC=RK3588 ..
这个TARGET_SOC应该是已经不再需要用到了？

2022-10-31 12:24 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> + *  @brief      设置运行的 NPU 核心
代码中不要存在中文注释，会导致部分平台编译失败

2022-10-31 12:24 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +  // cpu默认设置为RK3588
同上

2022-10-31 12:24 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +  // 获取sdk 和 驱动的版本
同上

2022-10-31 12:24 UTC, jiangjiajun commented on fastdeploy/pybind/main.cc.in
> +//#endif
这一段注释代码如果不用到，则直接移除

2022-10-31 12:24 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +void RuntimeOption::DisableLiteFP16() { lite_enable_fp16 = false; }
为什么需要额外移除EnableLiteInt8()和DisableLiteInt8()

2022-10-31 12:24 UTC, jiangjiajun commented on fastdeploy/runtime.h
>    /**
同上

2022-10-31 12:24 UTC, jiangjiajun commented on tools/rknpu2/export.py
> +import os
添加copy right

2022-10-31 12:55 UTC, jiangjiajun requested changes

2022-10-31 12:55 UTC, jiangjiajun commented on python/fastdeploy/vision/segmentation/ppseg/__init__.py
> +        print("disable_normalize_and_permute")
删除debug日志

2022-10-31 12:55 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +  // FDINFO << "========== RKNNInputTensorInfo ==========" << std::endl;
删除debug代码

2022-10-31 12:55 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +    // DumpTensorAttr(input_attrs[i]);
删除debug代码

2022-10-31 12:55 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +  for (uint32_t i = 0; i < io_num.n_output; i++) {
同上

2022-10-31 12:55 UTC, jiangjiajun commented on fastdeploy/backends/rknpu/rknpu2/rknpu2_backend.cc
> +    // DumpTensorAttr(output_attrs[i]);
同上

2022-11-01 03:13 UTC, jiangjiajun approved these changes

2022-11-01 03:14 UTC, merged