[Model] add tracking trail on vis_mot
PaddlePaddle/FastDeploy pull request #461
Opened 2022-10-31 00:32 UTC by ChaoII

### PR types(PR类型)
Model

### Describe

- 添加多目标跟踪可视化轨迹的显示
效果如下：
<img width="733" alt="image" src="https://user-images.githubusercontent.com/44053467/198909816-f7665490-028e-40c4-b4c2-5fac3eee692f.png">

2022-11-02 02:28 UTC, jiangjiajun requested changes

2022-11-02 02:28 UTC, jiangjiajun commented on python/fastdeploy/vision/visualize/__init__.py
> +            print("[WARNING] <trails> must be a global dict, when <is_draw_trail> is True ,trails will be hidden!")
改用logging.warn

2022-11-02 02:28 UTC, jiangjiajun commented on examples/vision/tracking/pptracking/cpp/infer.cc
>    capture.release();
在for循环后，显式调用一行`model.UnBindRecorder();` 便于用户直接了解

2022-11-02 02:28 UTC, jiangjiajun commented on examples/vision/tracking/pptracking/python/infer.py
>  cap.release()
也显式调用一行model.unbind_trail_recorder()

2022-11-02 02:28 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.h
> +  records[id] = record;
这里逻辑跟之前的不同

之前是遍历每个boxes，然后同时从map中查找到id，往id对应的vec push数据，现在是直接赋值，是一样的吗？

2022-11-02 02:28 UTC, jiangjiajun commented on fastdeploy/vision/tracking/pptracking/model.h
> +  void UnBindRecorder();
Unbind是一个单词，驼峰时给单词首字母大写即可，这里改成`UnbindRecorder()`

2022-11-02 02:28 UTC, jiangjiajun commented on python/fastdeploy/vision/tracking/pptracking/__init__.py
> +class TrailRecorder(C.vision.tracking.TrailRecorder):
不要使用这种继承的方式，这样会导致FastDeploy在编译时，如果没有ENABLE_VISION的情况下，在`import fastdeploy`时，会提示找不到`C.vision`

2022-11-02 02:28 UTC, jiangjiajun commented on python/fastdeploy/vision/tracking/pptracking/__init__.py
可以改成
```
try:
    TrailRecorder = C.TrailRecorder
except:
    pass
```
这样在python层面可以直接用`fastdeploy.vision.tracking.TrailRecorder` 无需再创建一个类

2022-11-02 03:49 UTC, ChaoII commented on python/fastdeploy/vision/visualize/__init__.py
> +            print("[WARNING] <trails> must be a global dict, when <is_draw_trail> is True ,trails will be hidden!")
已经去掉python中不必要的逻辑

2022-11-02 03:49 UTC, ChaoII commented on examples/vision/tracking/pptracking/cpp/infer.cc
>    capture.release();
添加显示调用

2022-11-02 03:49 UTC, ChaoII commented on examples/vision/tracking/pptracking/python/infer.py
>  cap.release()
添加显示调用

2022-11-02 03:49 UTC, ChaoII commented on fastdeploy/vision/tracking/pptracking/model.h
> +  records[id] = record;
调整逻辑，与起初沟通逻辑一致

2022-11-02 03:49 UTC, ChaoII commented on fastdeploy/vision/tracking/pptracking/model.h
> +  void UnBindRecorder();
调整变量命名

2022-11-02 03:49 UTC, ChaoII commented on python/fastdeploy/vision/tracking/pptracking/__init__.py
> +class TrailRecorder(C.vision.tracking.TrailRecorder):
已移除

2022-11-02 03:49 UTC, ChaoII commented on python/fastdeploy/vision/tracking/pptracking/__init__.py
已按要求调整

2022-11-02 03:56 UTC, jiangjiajun requested changes

2022-11-02 03:56 UTC, jiangjiajun commented on python/fastdeploy/vision/tracking/pptracking/__init__.py
> +                    "so 'TrailRecorder' can not be loaded")
这行提示不用打出来，就单纯pass即可，否则在没有ENABLE_VISION的时候，import fastdeploy会打出来上面这行提示

2022-11-02 03:57 UTC, jiangjiajun commented
有个代码冲突需解决下

2022-11-03 01:57 UTC, jiangjiajun approved these changes

2022-11-03 01:57 UTC, merged