Serving and Runtime support Clone
PaddlePaddle/FastDeploy pull request #464
Opened 2022-10-31 09:06 UTC by heliqi

### PR types(PR类型)

Backend
Serving

### Describe
1. OpenVINO and Option support num_streams 
2. Runtime(PaddleBackend and OpenVINOBackend) support Clone , TRT and ORT wait for the next PR
3. Serving create multiple Instances use Runtime*->Clone

Multiple Runtime NO Clone Example:
```
fastdeploy::Runtime runtime;
runtime.Init(runtime_option);

fastdeploy::Runtime runtime2;
runtime2.Init(runtime_option2);
```

Multiple Runtime NO Clone Example:
```
fastdeploy::Runtime runtime;
runtime.Init(runtime_option);

auto* runtime2 = runtime.Clone();
```

2022-10-31 09:12 UTC, heliqi commented
Clone带来的内存提升:
模型: ResNet50_vd
配置: 开启CPU、4线程
| 实例数  | Clone模式  | 不Clone模式 |
| ------------- | ------------- | ------------- |
| 1 |  301M  |  301M  |
| 2 | 301M  |   424M  |
| 2 | 301M  |   646M  |

2022-10-31 09:20 UTC, heliqi commented
OpenVINO使用Clone+设置num_stream(参数实例数量一致) 可以显著提升性能:

并发数 | OpenVINO(优化后) | OpenVINO(优化前) | 对比
-- | -- | -- | --
  | 2实例 2streams设置16线程 | 2实例设置16线程 |  
1 | 79.622 ms | 77.828 ms | -2.3%
3 | 78.774 ms | 99.420 ms | 20.76%
5 | 105.108 ms | 160.446 ms | 30.49%

2022-11-02 03:11 UTC, jiangjiajun requested changes

2022-11-02 03:11 UTC, jiangjiajun commented on fastdeploy/backends/backend.h
> +    FDERROR << "Clone no support" << std::endl;
这个提示有点简陋。 在BaseBackend里面增加一个纯虚函数Name()，然后每个后端增加对应的名字

这里就给个明确的提示`FDERROR << "Backend: " << Name() << " dosen't support clone." << std::endl;`

2022-11-02 03:11 UTC, jiangjiajun commented on fastdeploy/backends/openvino/ov_backend.h
>    int cpu_thread_num = 8;
这里不知道啥时候改成了8，但这个应该默认是-1， 在用户不主动设置 set_num_thread的时候，默认应该是-1，也就是让推理引擎自己选择默认的线程设置

看了下上面代码的逻辑，这里应该直接改成-1就可以了

2022-11-02 03:11 UTC, jiangjiajun commented on fastdeploy/backends/backend.h
> +    FDERROR << "Clone no support" << std::endl;
另外是否可以做到每个backend都支持clone，不支持内存共享的，可以重新加载一次

2022-11-02 06:25 UTC, heliqi commented on fastdeploy/backends/backend.h
> +    FDERROR << "Clone no support" << std::endl;
一般情况是不会走到这，不支持的在runtime的clone接口拦截了，会创建一个全新的

2022-11-02 06:29 UTC, heliqi commented on fastdeploy/backends/openvino/ov_backend.h
>    int cpu_thread_num = 8;
Done 。 其实这里的默认参数没用，改不改影响都不大，默认参数是由RuntimeOption控制的

2022-11-02 06:30 UTC, heliqi commented on fastdeploy/backends/backend.h
> +    FDERROR << "Clone no support" << std::endl;
这个提示都可以删除了，只是暂时还不能改成纯虚函数

2022-11-03 11:11 UTC, heliqi commented
TRT Backend 
模型: Yolov5 
配置: 开启GPU TRT
2个实例

| 资源消耗  | Clone模式(同一张卡)  | 不Clone模式 |
| ------------- | ------------- | ------------- |
| 内存 | 1.3G  |   1.4G  |
| 内存 | 663M  |  981M  |

2022-11-04 03:30 UTC, jiangjiajun requested changes

2022-11-04 03:30 UTC, jiangjiajun commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +              "Clone model from Paddle failed while initliazing TrtBackend.");
initialize

2022-11-04 03:30 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +    runtime->Init(option);
这行上面加一行提示
```
FDWARNING << "Only OpenVINO/Paddle Inference/TensorRT support clone engine to  reduce CPU/GPU memory usage now. For " << option.backend   << ", FastDeploy will create a new engine which will not share memory  with the current runtime." << std::endl;
```

2022-11-04 03:30 UTC, jiangjiajun commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +  if(device_id > 0 && device_id != option_.gpu_id) {
加一行提示
```
FDWARNING << "The target device id:" << device_id << " is different from current device id:" << option_.gpu_id << ", cannot share memory with current engine." << std::endl;
```
```

2022-11-04 04:03 UTC, heliqi commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +              "Clone model from Paddle failed while initliazing TrtBackend.");
Done

2022-11-04 04:03 UTC, heliqi commented on fastdeploy/runtime.cc
> +    runtime->Init(option);
Done

2022-11-04 04:03 UTC, heliqi commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +  if(device_id > 0 && device_id != option_.gpu_id) {
Done

2022-11-04 06:26 UTC, jiangjiajun approved these changes

2022-11-04 09:16 UTC, merged