[Add Model]Add RKPicodet
PaddlePaddle/FastDeploy pull request #495
Opened 2022-11-04 04:17 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Describe
新增RKPicodet模型

2022-11-04 12:59 UTC, DefTruth approved these changes

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +inline float fast_exp(float x) {
函数名都统一用大写字母+驼峰法开头，并且不要放在全局空间中。放在当前cc文件的namespace detection里，并用static做约束。

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +inline float sigmoid(float x) { return 1.0f / (1.0f + fast_exp(-x)); }
同上

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +int activation_function_softmax(const Tp* src, Tp* dst, int length) {
同上。这个只用到了float的实例化，并且应该只在当前cc文件中有效，不需要写成模板。改成显式的float*类型输入函数。

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +  return 0;
这个return 0没有意义，后面没有用到。改成void

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +  if ((model_format == ModelFormat::RKNN) or (model_format == ModelFormat::ONNX)) {
这里不用使用 or 或 and这种标记符，因为不确保所有版本的编译器都支持这种语法，改成常规的 && 或 ||

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +    std::vector<std::vector<BoxInfo>> box_infos;
这个BoxInfo只在当前cc用到，把他从头文件移过来放在detection命名空间下吧

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +                                                           nms_threshold);
这里不能直接用PicoDetNms吗？并且这个函数名也不太规范，PicodetNms改成PicoDetNms吧，注意下这些大小写

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +                           int stride, float threshold,
注意下这种参数对齐的问题

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +          this->DisPred2Bbox(bbox_pred, cur_label, score, col, row, stride));
类内调用自己的方法都不要用this

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +  float xmin = (std::max)(ct_x - dis_pred[0], .0f);
这个语法在MSVC编译器不一定支持，请使用std::min()常规用法

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +  float ymax = (std::min)(ct_y + dis_pred[3], (float)this->input_size_);
不要用C的强制转换语法，请使用C++的显式转换语法，static_cast<float>(...);其余同理

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +      float xx1 = (std::max)(input_boxes[i].x1, input_boxes[j].x1);
std::min, std::max语法问题，同上。这个NMS函数，可以考虑需要修改成FD已有的NMS函数

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.h
> +typedef struct BoxInfo {
这个移到cc文件

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.h
> +  void DecodeInfer(const float*& cls_pred, const float*& dis_pred, int stride,
以下这三个函数都移到cc文件，作为 detection 命名空间下的 static 函数。不需要在类中保留这种静态函数
```C++
DecodeInfer();
DisPredBox();
PicoDetNms();
```  
尽可能不要在头文件中暴露太多用户用不上的代码；

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.h
> +  BoxInfo DisPred2Bbox(const float*& dfl_det, int label, float score, int x,
这里为什么要用 float*& 这种语法？不可以替换成 float* 或 float& 吗，尽量避免增加维护的难度

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.cc
> +      this->DecodeInfer(cls_pred, dis_pred, strides[out_idx], score_threshold,
不要用this

2022-11-04 12:59 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.h
> +  std::vector<double> ptr{};
这个属性名具体的含义是啥？尽量避免无意义的缩写，请使用全称

2022-11-04 12:59 UTC, DefTruth commented on examples/vision/detection/rknpu2detection/paddledetection/cpp/infer_picodet.cc
> +  auto dur = (double) (end - start);
改成C++的写法，static_cast

2022-11-04 12:59 UTC, DefTruth commented on examples/vision/detection/rknpu2detection/paddledetection/cpp/CMakeLists.txt
> +install(PROGRAMS ${FASTDEPLOY_LIBS} DESTINATION lib)
为啥还要安装？include(FastDeploy.cmake)后，依赖库的关系已经被处理好了，可以参考下 examples/vision/detection/paddledetection/cpp/CMakeLists.txt的写法

2022-11-04 13:00 UTC, DefTruth requested changes
感谢您的贡献，以上评论可以先修改下哈

2022-11-05 09:08 UTC, DefTruth requested changes

2022-11-05 09:08 UTC, DefTruth commented on examples/vision/detection/rknpu2detection/paddledetection/python/README.md
> +- [PaddleSeg 模型介绍](..)
错别字，修改成RKPicoDet，这里应该不是PaddleSeg

2022-11-05 09:08 UTC, DefTruth commented on fastdeploy/vision/detection/rknpu2/rkpicodet.h
> +  std::vector<float> scale_factor{1, 1};
初始化的值也改成浮点型1.0f

2022-11-05 09:08 UTC, DefTruth commented on examples/vision/detection/rknpu2detection/paddledetection/README.md
> +## 准备PaddleSeg部署模型以及转换模型
错别字，不是PaddleSeg

2022-11-05 09:08 UTC, DefTruth commented on examples/vision/detection/rknpu2detection/paddledetection/README.md
> +下面以Picodet-npu为例子,教大家如何转换PPSeg模型到RKNN模型。
错别字，同上

2022-11-05 10:11 UTC, DefTruth approved these changes

2022-11-05 10:11 UTC, DefTruth commented on examples/vision/detection/rknpu2detection/paddledetection/python/README.md
> +cd FastDeploy/examples/vision/segmentation/paddleseg/python
这里还有错别字，这里改成 examples/vision/detection/paddledetection/rknpu2 吧

2022-11-05 10:11 UTC, DefTruth commented on examples/vision/detection/rknpu2detection/paddledetection/python/infer.py
> +        "--model_file", required=True, help="Path of PaddleSeg model.")
错别字

2022-11-06 09:28 UTC, jiangjiajun approved these changes

2022-11-06 09:29 UTC, merged