[Model]新增scrfd rknpu2代码
PaddlePaddle/FastDeploy pull request #504
Opened 2022-11-05 10:45 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Describe
新增scrfd rknpu2代码

2022-11-08 03:11 UTC, wjj19950828 requested changes

2022-11-08 03:11 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/cpp/README.md
> +fastdeploy-0.0.3目录，请移动它至thirdpartys目录下.
版本号建议改一下，目前FD最新为0.5.0，此PR跟随0.6.0发版，改为0.6.0

2022-11-08 03:11 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/python/README.md
> +# Scrfd Python部署示例
大写->SCRFD

2022-11-08 03:11 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/python/README.md
> +本目录下提供`infer.py`快速完成Scrfd在RKNPU上部署的示例。执行如下脚本即可完成
同上

2022-11-08 03:11 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/python/README.md
> +- [Scrfd 模型介绍](..)
同上

2022-11-08 03:11 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/python/README.md
> +- [Scrfd C++部署](../cpp)
同上

2022-11-08 03:11 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/python/README.md
> +- [转换Scrfd RKNN模型文档](../README.md)
同上

2022-11-08 03:11 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/python/infer.py
> +        "--model_file", required=True, help="Path of PaddleSeg model.")
FaceDet model

2022-11-08 03:11 UTC, wjj19950828 commented on fastdeploy/vision/facedet/contrib/scrfd.cc
> +    Cast::Run(mat, "float");
Cast可以放到括号外面吗？

2022-11-08 03:53 UTC, Zheng-Bicheng commented on fastdeploy/vision/facedet/contrib/scrfd.cc
> +    Cast::Run(mat, "float");
怕会有性能损失，放在外面输入是float，但是这里没进行normalize和permute，输入类型应该是int8

2022-11-09 03:16 UTC, wjj19950828 requested changes

2022-11-09 03:16 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/cpp/CMakeLists.txt
> +set(FASTDEPLOY_INSTALL_DIR "thirdpartys/fastdeploy-0.6.0")
0.6.0 -> 0.7.0

2022-11-09 03:16 UTC, wjj19950828 commented on examples/vision/facedet/scrfd/rknpu2/cpp/README.md
> +fastdeploy-0.6.0目录，请移动它至thirdpartys目录下.
0.6.0 -> 0.7.0

2022-11-09 06:06 UTC, wjj19950828 approved these changes

2022-11-09 06:43 UTC, jiangjiajun requested changes

2022-11-09 06:43 UTC, jiangjiajun commented on fastdeploy/vision/facedet/contrib/scrfd.h
> +  // This function will disable normalize and hwc2chw in preprocessing step.
注释应该是/// 三个线符合doxygen的语法才能最终生成在C++ API文档中

2022-11-09 06:43 UTC, jiangjiajun commented on fastdeploy/vision/facedet/contrib/scrfd.h
> +  bool disable_normalize_and_permute = false;
团队内部新统一了规范，所有的新加的成员变量都要追加下划线，改成
```
bool disable_normalize_and_permute_;
```
同时这里注释使用//两个斜杆是可以的，因为这个变量不需要展示在API文档中

2022-11-09 06:43 UTC, jiangjiajun commented on python/fastdeploy/vision/facedet/contrib/scrfd.py
> +    def disable_normalize_and_permute(self):
Python同样参照其它函数，增加注释，便于生成Python API文档

2022-11-09 07:15 UTC, jiangjiajun commented
ci检测到文档中存在死链，需同时检查下

2022-11-09 20:01 UTC, Zheng-Bicheng commented
> ci检测到文档中存在死链，需同时检查下

死链问题好像是因为没有合入仓库，文档所对应的链接才是404

2022-11-10 02:05 UTC, merged