[Backend] Support deployment of models which is larger than 2G in ORT and TRT backend
PaddlePaddle/FastDeploy pull request #514
Opened 2022-11-07 09:16 UTC by yeliang2258

### PR types(PR类型)

The title of this pull request should be `[PR type] Description of this pull request`, e.g `[Model] PP-Matting deployment support`    
  
PR的标题应该为 `[PR type] Description of this pull request`, 例如 `[Model] PP-Matting deployment support`  

### Describe

- Support new model PP-Matting
- Add new data structure `MattingResult`
 Support deployment of models which is larger than 2G in ORT and TRT backend

2022-11-07 09:26 UTC, heliqi commented on fastdeploy/backends/ort/ort_backend.cc
>                                 model_content_ptr + model_content_size);
model_content_ptr这个存储模型的指针没释放

2022-11-07 09:26 UTC, heliqi commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +  if(save_external_){
如上model_content_ptr没释放

2022-11-07 09:32 UTC, yeliang2258 commented on fastdeploy/backends/ort/ort_backend.cc
>                                 model_content_ptr + model_content_size);
102和103释放了

2022-11-07 09:36 UTC, heliqi approved these changes
LGTM

2022-11-07 09:36 UTC, heliqi commented on fastdeploy/backends/ort/ort_backend.cc
>                                 model_content_ptr + model_content_size);
我看错了，被代码折叠了

2022-11-07 11:52 UTC, jiangjiajun requested changes

2022-11-07 11:52 UTC, jiangjiajun commented on fastdeploy/backends/ort/ort_backend.cc
> +    std::fstream f(model_file_name, std::ios::out);
如果无法打开文件，需要有判断，同时提示错误

2022-11-07 11:52 UTC, jiangjiajun commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +    std::fstream f(model_file_name_, std::ios::out);
同上

2022-11-07 14:19 UTC, yeliang2258 commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +    std::fstream f(model_file_name_, std::ios::out);
Done

2022-11-07 14:19 UTC, yeliang2258 commented on fastdeploy/backends/ort/ort_backend.cc
> +    std::fstream f(model_file_name, std::ios::out);
Done

2022-11-08 06:24 UTC, jiangjiajun requested changes

2022-11-08 06:24 UTC, jiangjiajun commented on fastdeploy/backends/ort/ort_backend.cc
> +    Assert(f.is_open(), "Can not open file: " + model_file_name + " to save model.")
改用FDASSERT

2022-11-08 06:24 UTC, jiangjiajun commented on fastdeploy/backends/tensorrt/trt_backend.cc
> +    Assert(f.is_open(), "Can not open file: " + model_file_name_ + " to save model.")
改用FDASSERT

2022-11-09 03:04 UTC, jiangjiajun approved these changes

2022-11-09 03:14 UTC, merged