[Model] add vsr serials models
PaddlePaddle/FastDeploy pull request #518
Opened 2022-11-08 02:00 UTC by ChaoII

### PR types(PR类型)
Model
### Describe
添加VSR（视频超分）系列模型，包括
- `PP-MSVSR`
- `EDVR`
- `BasicVSR`
模型效果如下：
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/44053467/200456062-426b047a-3571-4463-94cf-c8d02ca25d16.png">

2022-11-09 03:48 UTC, wjj19950828 requested changes

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/README.md
> +# 视觉模型部署
这里的文档为什么在gan这个目录下？

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/README.md
> +- [PaddleDetection develop](https://github.com/PaddlePaddle/PaddleGAN)
PaddleDetection -> PaddleGAN

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/cpp/README.md
> +本目录下提供`infer.cc`快速完成PP-Tracking在CPU/GPU，以及GPU上通过TensorRT加速部署的示例。
PP-Tracking -> PaddleGAN，另外TRT这个模型能跑通吗

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-gpu-0.5.0.tgz
这里版本改一下，这个PR预计跟0.7.0一起发版，可以在上面加一句版本  >= 0.7.0

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/cpp/README.md
> +tar xvf fastdeploy-linux-x64-gpu-0.5.0.tgz
同上

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/cpp/README.md
> +cd fastdeploy-linux-x64-gpu-0.5.0/examples/vision/gan/vsr/cpp/
同上

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/cpp/README.md
> +cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/../../../../../../../fastdeploy-linux-x64-gpu-0.5.0
同上

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/cpp/README.md
> +./infer_demo BasicVSR_reds_x4 vsr_src.mp4 2 2
这些示例最后都有个2是什么意思

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/basicvsr/cpp/README.md
> +> BasicVSR::Predict(std::vector<cv::Mat>& imgs, std::vector<cv::Mat>& results)
vector?支持多张图片预测吗，返回结果还是一个```cv::Mat```?

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/edvr/README.md
> +- [PaddleDetection develop](https://github.com/PaddlePaddle/PaddleGAN)
PaddleDetection -> PaddleGAN

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/edvr/cpp/README.md
> +#下载SDK，编译模型examples代码（SDK中包含了examples代码）
版本号同上

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/edvr/python/infer.py
> +        "--model", required=True, help="Path of PaddleSeg model.")
PaddleSeg -> PaddleGAN

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/README.md
> +- [PaddleDetection develop](https://github.com/PaddlePaddle/PaddleGAN)
PaddleDetection -> PaddleGAN

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/cpp/README.md
> +# VSR C++部署示例
VSR -> PP-MSVSR

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/cpp/README.md
> +#下载SDK，编译模型examples代码（SDK中包含了examples代码）
版本问题同上

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/cpp/README.md
> +VSR模型加载和初始化，其中model_file为导出的Paddle模型格式。
VSR -> PP-MSVSR

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/python/README.md
> +## VSR Python接口
VSR -> PP-MSVSR

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/python/README.md
> +PPMSVSR模型加载和初始化，其中model_file和params_file为训练模型导出的Paddle inference文件，具体请参考其文档说明[模型导出](https://github.com/PaddlePaddle/PaddleGAN/blob/develop/docs/zh_CN/tutorials/video_super_resolution.md)
PP-MSVSR

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/python/README.md
> +- [VSR 模型介绍](..)
PP-MSVSR

2022-11-09 03:48 UTC, wjj19950828 commented on examples/vision/gan/ppmsvsr/python/README.md
> +- [VSR C++部署](../cpp)
PP-MSVSR

2022-11-09 03:48 UTC, wjj19950828 commented on fastdeploy/vision/gan/vsr/basicvsr.cc
> +  valid_cpu_backends = {Backend::PDINFER, Backend::OPENVINO, Backend::ORT};
不支持ORT可以去掉

2022-11-09 03:48 UTC, wjj19950828 commented on fastdeploy/vision/gan/gan_pybind.cc
> +  void BindVSR(pybind11::module& m);
这里的BindVSR可以改成BindPPGAN吗，因为其他大类以detection为例，都有PPDet和其他类的区分

2022-11-09 06:35 UTC, ChaoII commented on examples/vision/gan/README.md
> +# 视觉模型部署
目录已修改为sr

2022-11-09 06:35 UTC, ChaoII commented on examples/vision/gan/basicvsr/cpp/README.md
> +本目录下提供`infer.cc`快速完成PP-Tracking在CPU/GPU，以及GPU上通过TensorRT加速部署的示例。
支持paddle-TRT应该可以通过

2022-11-09 06:35 UTC, ChaoII commented on examples/vision/gan/basicvsr/cpp/README.md
> +./infer_demo BasicVSR_reds_x4 vsr_src.mp4 2 2
frame_nums 视频超分根军帧间信息进行超分

2022-11-13 09:35 UTC, wjj19950828 requested changes

2022-11-13 09:35 UTC, wjj19950828 commented on fastdeploy/vision/sr/vsr/basicvsr.h
>   public:
使用doxygen的语法进行注释

2022-11-13 09:35 UTC, wjj19950828 commented on fastdeploy/vision/sr/vsr/edvr.h
>  class FASTDEPLOY_DECL EDVR : public PPMSVSR{
使用doxygen的语法进行注释

2022-11-14 11:42 UTC, wjj19950828 approved these changes

2022-11-21 01:51 UTC, jiangjiajun approved these changes

2022-11-21 02:58 UTC, merged