Add PaddleOCR-DBDetector Model Support
PaddlePaddle/FastDeploy pull request #52
Opened 2022-07-28 08:13 UTC by yunyaoXYY

新增PaddleOCR的检测模型

2022-07-28 08:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=52) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=52) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=52) it.</sub>

2022-07-28 08:48 UTC, jiangjiajun requested changes

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/dbdetector.cc
> +    FDTensor& infer_result, std::vector<std::vector<std::vector<int>>>& boxes,
这个接口的第二个参数改为直接传DetectionResult吧

另外函数的只读参数一般都使用`const T&`， 需要写的参数都使用`T*`

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/common/result.h
> +};
检测模型改成DetectionResult

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/dbdetector.cc
> +  is_dynamic_input_ = false;
不需要的代码先不用加

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/dbdetector.cc
> +    std::map<std::string, std::array<float, 2>>* im_info) {
只需要一个image即可

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/dbdetector.cc
> +  output->shape.insert(output->shape.begin(), 1);
这里都可以统一成fastdeploy的处理函数

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/dbdetector.h
> +                   cv::Mat srcimg);
srcimg传入进只是用于获取原图的宽高，可以复用im_info来获取

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/dbdetector.h
> +  bool IsDynamicInput() const { return is_dynamic_input_; }
同上

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/utils/get_rotate_crop_image.cc
> +                           std::vector<std::vector<int>> box) {
传入的只读参数是用const T&

2022-07-28 08:48 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/utils/ocrpost/ocr_postprocess_op.h
> +//
OCR的utils函数，都移到ppocr/utils目录下

2022-07-31 09:09 UTC, yunyaoXYY commented on csrcs/fastdeploy/vision/common/result.h
> +};
1.OCR的检测框不是用 xmin,xmax,ymin,ymax表示的（可能不是一个规则的矩形框，可参考官方套件的预测结果 ref： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/deploy/cpp_infer/readme.md ） 

2.vector<vector<vector<int>>>的box在后处理函数中，又要读又要写.

所以目前还没用DetectionResult.

2022-08-09 12:51 UTC, jiangjiajun requested changes

2022-08-09 12:51 UTC, jiangjiajun commented on csrcs/fastdeploy/backends/paddle/paddle_backend.h
> +  std::string delete_pass_name = "";
将`delete_pass_name`改为`std::vector<std::string> delete_pass_names`

然后不用添加`bool delete_pass`这个参数了，默认就是会遍历delete_pass_names，挨个删除

2022-08-09 12:51 UTC, jiangjiajun commented on csrcs/fastdeploy/fastdeploy_runtime.cc
> +void RuntimeOption::EnablePaddleDeletePass(std::string pass_name) {
这里同理，就将函数改为`RuntimeOption::DeletePaddlePass(const std::string& pass_name)` 这个函数每调用一次，就往`delete_pass_names`里面push_back一次

2022-08-09 12:51 UTC, jiangjiajun commented on csrcs/fastdeploy/fastdeploy_runtime.cc
> +  pd_option.delete_pass_name = option.pd_delete_pass_name;
PaddleBackendOption同样也增加`delete_pass_names`这个参数，这里就直接赋过去即可

2022-08-09 12:51 UTC, jiangjiajun commented on csrcs/fastdeploy/fastdeploy_runtime.h
> +  void EnablePaddleDeletePass(std::string delete_pass_name);
见上面comment

2022-08-09 12:51 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/common/result.h
> +struct FASTDEPLOY_DECL OCRPredictResult : public BaseResult {
改为OcrResult，不加Predict了，跟type里面里面的那个OCR也对应了

2022-08-09 12:51 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/ppocrsys.cc
> +  if (use_det) {
format都删除

2022-08-09 12:51 UTC, jiangjiajun commented on csrcs/fastdeploy/vision/ppocr/ppocrsys.cc
> +PPocrsys::PPocrsys(
system放在application下面。 fastdeploy::application::OCRSystem

2022-08-09 12:51 UTC, jiangjiajun commented on examples/vision/ppocrv2_sys.cc
> +
application::PPOCRSystemv2()
application::PPOCRSystemv3()
在这里去做32/48的切换

2022-08-17 11:20 UTC, merged