[Backend] Add SetTrtMaxBatchSize function for TensorRT.
PaddlePaddle/FastDeploy pull request #526
Opened 2022-11-08 08:16 UTC by yunyaoXYY

添加SetTrtMaxBatchSize函数, 供TensorRT，Paddle-TRT使用.

2022-11-08 11:00 UTC, jiangjiajun commented
增加一个pybind实现

2022-11-08 11:50 UTC, yunyaoXYY commented
> 增加一个pybind实现

Done

2022-11-08 16:34 UTC, jiangjiajun requested changes
python代码还需添加一个接口

2022-11-09 03:00 UTC, jiangjiajun approved these changes

2022-11-09 05:57 UTC, merged