Add model YOLOv5Lite Support
PaddlePaddle/FastDeploy pull request #53
Opened 2022-07-28 08:54 UTC by ziqi-jin

- add model YOLOv5Lite model
- implement two postprocess funtions for the ONNX files with decode module or not

2022-07-28 10:04 UTC, DefTruth requested changes

2022-07-28 10:04 UTC, DefTruth commented on csrcs/fastdeploy/vision/ppogg/yolov5lite.h
> +  float anchors[3][6] = {{10.0, 13.0, 16.0, 30.0, 33.0, 23.0},
这个anchors不要在.h中初始化，写到Initialze()函数中；另外，是否可以不写死成[3][6]？可以先考虑用std::vector<std::vector<float>>，因为当用户需要改这个属性的时候，featmap和anchor的数量都是可变的。

2022-07-28 10:06 UTC, ziqi-jin commented on csrcs/fastdeploy/vision/ppogg/yolov5lite.h
> +  float anchors[3][6] = {{10.0, 13.0, 16.0, 30.0, 33.0, 23.0},
好的

2022-07-28 10:08 UTC, DefTruth commented on csrcs/fastdeploy/vision/ppogg/yolov5lite.cc
> +    Mat* mat, FDTensor* output,
FDTensor* output 和 头文件中的 FDTensor* outputs，没对上

2022-07-28 11:04 UTC, DefTruth commented on csrcs/fastdeploy/vision/ppogg/yolov5lite.cc
> +                                 std::vector<Anchor>* anchors,
这里的anchors命名和类属性的anchors产生冲突，是否可以换另一个合适的参数名称。或者把属性anchors改成另一个名称？比如 anchors_config ，这个属性应该只是配置锚点框。

2022-07-28 11:06 UTC, DefTruth commented on csrcs/fastdeploy/vision/ppogg/yolov5lite.cc
> +                                 const int num_anchors) {
值传递可以不用const

2022-07-28 11:10 UTC, DefTruth commented on model_zoo/vision/yolov5lite/api.md
> +>                 float conf_threshold = 0.25,
格式没有对齐

2022-07-28 11:11 UTC, DefTruth commented on model_zoo/vision/yolov5lite/README.md
> +└── yolov5_lite.py
改成和文件夹名称一致，yolov5lite.py

2022-07-28 11:13 UTC, DefTruth commented on model_zoo/vision/yolov5lite/README.md
> +python yolov5_lite.py
python脚本名称和c++的源文件名称没有统一，都统一成yolov5lite.cc合yolov5lite.py

2022-07-28 13:24 UTC, DefTruth approved these changes

2022-07-29 02:21 UTC, jiangjiajun approved these changes

2022-07-29 02:21 UTC, merged