[Backend] cuda normalize and permute, cuda concat
PaddlePaddle/FastDeploy pull request #546
Opened 2022-11-09 10:09 UTC by wang-xinyu

### PR types(PR类型)

Backend

### Describe

- CUDA kernel for Color convert + Normalize + Permute
- Concat support GPU

2022-11-10 08:03 UTC, wang-xinyu commented
PPClas End2end test on T4, TRT8.4
Latency in ms.

Version | Model | FP32 | FP16 | INT8
-- | -- | -- | -- | --
0.3.0 | PP-LCNetv2 | 2.23 | 1.87 | 1.78
This | PP-LCNetv2 | 1.54 | 1.03 | 0.89

2022-11-10 08:59 UTC, wang-xinyu commented
PPDet End2end test on T4, TRT8.4
Latency in ms.

.   | Model | FP32
-- | -- | --
Before | PPYOLOE | 35.05
After | PPYOLOE | 32.97

Inference is 32.6ms, so Preprocessing is 2.45ms -> 0.37ms

2022-11-10 10:45 UTC, wang-xinyu commented
PPSeg UNet  PPInfer GPU backend, T4.

Latency in ms.

 | Input size | Preprocess latency, before | after |
 | -- | -- | -- | 
 | 2048x1024 | 33.921 | 1.405 |
 | 320x160 | 0.228 | 0.194 |

2022-11-10 13:37 UTC, jiangjiajun requested changes

2022-11-10 13:37 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/model.cc
> +    : preprocessor_(config_file, (custom_option.device == Device::GPU)) {
建议先不要默认加到这个逻辑，这里可能还存在一些问题，也就是用户在开GPU时，不一定能够最终跑在GPU上，先改为用户手动打开

2022-11-10 13:37 UTC, jiangjiajun commented on fastdeploy/vision/common/processors/normalize_and_permute.cc
> +  }
这个逻辑，加到base.cc里面吧，避免太Trick的修改各个预处理操作

2022-11-10 13:37 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  }
Seg的也等建辉重构完后再加，目前测试先手动加，不用先提上来。 runtime_option.device目前可能还存在一些问题

2022-11-11 06:18 UTC, heliqi commented on fastdeploy/core/fd_tensor.cc
> +                          const Device& device, bool is_pinned_memory) {
参数名device等跟FDTensor本身成员变量重名了吧？

2022-11-11 06:18 UTC, heliqi commented on fastdeploy/vision/classification/ppcls/model.cc
> +    : preprocessor_(config_file, (custom_option.device == Device::GPU)) {
预处理部分需要增加device_id参数用于控制预处理跑在哪张卡上。
这个参数最终应该传到FDTensor里，知道显存在哪张卡。
默认参数应该跟runtime一样，为0

2022-11-11 07:07 UTC, wang-xinyu commented on fastdeploy/core/fd_tensor.cc
> +                          const Device& device, bool is_pinned_memory) {
这个CopyBuffer函数我改成了static函数，  static函数用和成员变量重名的参数，应该没事吧，因为static函数不能访问成员变量

2022-11-11 07:24 UTC, wang-xinyu commented on fastdeploy/vision/common/processors/normalize_and_permute.cc
> +  }
Done

2022-11-11 07:24 UTC, wang-xinyu commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  }
Done

2022-11-11 07:24 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/model.cc
> +    : preprocessor_(config_file, (custom_option.device == Device::GPU)) {
Done

2022-11-11 07:32 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/model.cc
> +    : preprocessor_(config_file, (custom_option.device == Device::GPU)) {
在FDTensor里面加一个device_id?

2022-11-11 07:43 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/model.cc
> +    : preprocessor_(config_file, (custom_option.device == Device::GPU)) {
我理解cudaSetDevice()是一个全局的设置，在runtime init的是时候就设定好了跑在哪张卡。
是serving的场景会把预处理和推理跑在不同的卡上吗？

2022-11-11 08:52 UTC, heliqi commented on fastdeploy/vision/classification/ppcls/model.cc
> +    : preprocessor_(config_file, (custom_option.device == Device::GPU)) {
serving场景的话是前后处理+模型推理是三个服务， 如果不控制的话，预处理的服务会默认跑在卡0上，所以需要设置cudaSetDevice()。
还就是：
如果使用model.predictor是会在runtime init的是时候就设定好了；
但是类似这样分开调用就不行: 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/34152981/201302854-c4835ea4-c05e-4b5a-9349-de999ef767a7.png">

2022-11-11 08:55 UTC, heliqi commented on fastdeploy/core/fd_tensor.cc
> +                          const Device& device, bool is_pinned_memory) {
static函数确实允许会没问题。

这里是不是应该把FDTensor改为class， 里边现在有不少功能函数，并不只是纯粹的数据结构。
改成class 然后把变量加下划线？ @jiangjiajun

2022-11-12 06:00 UTC, jiangjiajun reviewed
另外预处理设置的gpu_id，如果与runtime的gpu_id不符，还需处理ORT、Paddle、和TensorRT在接收到输入后的情况

2022-11-12 06:00 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +void PaddleClasPreprocessor::UseGpu(int gpu_id) {
看Pybind用的是UseCuda， 同时pybind没有传gpu_id这个参数？

2022-11-14 02:38 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +void PaddleClasPreprocessor::UseGpu(int gpu_id) {
fixed

2022-11-14 02:40 UTC, wang-xinyu commented
> 另外预处理设置的gpu_id，如果与runtime的gpu_id不符，还需处理ORT、Paddle、和TensorRT在接收到输入后的情况

@jiangjiajun @heliqi  我们是在三个backend里面加device id的判断和cudaMemcpyPeerAsync()吗？   还是device id不一致的时候Assert？      如果不给用户提示就直接copy到不同的device，可能会影响性能

2022-11-14 02:46 UTC, heliqi commented
> > 另外预处理设置的gpu_id，如果与runtime的gpu_id不符，还需处理ORT、Paddle、和TensorRT在接收到输入后的情况
> 
> @jiangjiajun @heliqi 我们是在三个backend里面加device id的判断和cudaMemcpyPeerAsync()吗？ 还是device id不一致的时候Assert？ 如果不给用户提示就直接copy到不同的device，可能会影响性能

我建议先Assert掉，至少给个警告。 
1. 正常使用Model这种简单接口时不推荐用户把预处理和runtime设置在不同的卡上
2. 需要在Model(比如yolov5)里处理下: 如果用户设置了RuntimeOption的device_id却没有设置预处理，这个时候预处理默认与runtime保持一致  。 有些用户只知道runtime的设置，不知道预处理也要设置，所以不特殊设置预处理就默认与runtime保持一致

2022-11-14 02:59 UTC, wang-xinyu commented
> 2. 需要在Model(比如yolov5)里处理下: 如果用户设置了RuntimeOption的device_id却没有设置预处理，这个时候预处理默认与runtime保持一致 。 有些用户只知道runtime的设置，不知道预处理也要设置，所以不特殊设置预处理就默认与runtime保持一致

@heliqi 这个逻辑不好实现呢， 因为PaddleClasPreprocessor::UseGpu(int gpu_id=0)函数来设置device id的，Preprocessor默认是不用GPU的。     只能通过传入的gpu id来设置。  或者不给这个gpu id设置默认值，让用户显式指定。

2022-11-14 03:07 UTC, heliqi commented
> 



>

2022-11-14 03:10 UTC, heliqi commented
> > 2. 需要在Model(比如yolov5)里处理下: 如果用户设置了RuntimeOption的device_id却没有设置预处理，这个时候预处理默认与runtime保持一致 。 有些用户只知道runtime的设置，不知道预处理也要设置，所以不特殊设置预处理就默认与runtime保持一致
> 
> @heliqi 这个逻辑不好实现呢， 因为PaddleClasPreprocessor::UseGpu(int gpu_id=0)函数来设置device id的，Preprocessor默认是不用GPU的。 只能通过传入的gpu id来设置。 或者不给这个gpu id设置默认值，让用户显式指定。

这个逻辑不要写在预处理里，预处理只管设置和处理，相关逻辑在我们Model那一层判断。 
比如不要写PaddleClasPreprocessor， 而是写在PaddleClasModel的构造函数。

2022-11-14 05:04 UTC, wang-xinyu commented on fastdeploy/vision/classification/ppcls/model.cc
> +    : preprocessor_(config_file, (custom_option.device == Device::GPU)) {
fixed

2022-11-14 06:15 UTC, heliqi approved these changes
LGTM

2022-11-14 06:38 UTC, jiangjiajun requested changes

2022-11-14 06:38 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +             "Input tensor and runtime have different device ids.");
有这种出错时，一般都要给个明确点的提示，例如
```
    FDASSERT(tensor.device_id < 0 || tensor.device_id == option.device_id,
             "Device id of input tensor(%d) and runtime(5d) are not same.", tensor.device_id, option.device_id);
```

2022-11-14 06:46 UTC, wang-xinyu commented on fastdeploy/runtime.cc
> +             "Input tensor and runtime have different device ids.");
done

2022-11-14 07:50 UTC, jiangjiajun approved these changes

2022-11-14 10:44 UTC, merged