[Serving]Add PPCls serving examples
PaddlePaddle/FastDeploy pull request #555
Opened 2022-11-10 07:50 UTC by heliqi

### PR types(PR类型)
Serving

Serving

### Describe

- Add DLPack  for Tensor copy-free transfer between different deep learning frameworks
- Add PPCls serving examples

2022-11-10 08:35 UTC, jiangjiajun requested changes

2022-11-10 08:35 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/serving/models/preprocess/1/model.py
> +            # output_tensor = pb_utils.Tensor(self.output_names[0], outputs[0].numpy())
注释的代码删除掉

2022-11-10 08:35 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/serving/models/preprocess/1/model.py
> +        # print("num:", len(requests), flush=True)
注释的代码删除掉

2022-11-10 08:35 UTC, jiangjiajun commented on fastdeploy/pybind/fd_tensor.cc
> +DLDataType fd_to_dlpack_type(FDDataType fd_dtype) {
函数采用驼峰命名

2022-11-10 08:35 UTC, jiangjiajun commented on fastdeploy/pybind/fd_tensor.cc
> +  FDASSERT(data_type.lanes == 1,
同上

2022-11-10 08:35 UTC, jiangjiajun commented on fastdeploy/pybind/fd_tensor.cc
> +void delete_unused_dltensor(PyObject* dlp) {
同上

2022-11-10 09:01 UTC, heliqi commented on examples/vision/classification/paddleclas/serving/models/preprocess/1/model.py
> +            # output_tensor = pb_utils.Tensor(self.output_names[0], outputs[0].numpy())
done

2022-11-10 09:02 UTC, heliqi commented on examples/vision/classification/paddleclas/serving/models/preprocess/1/model.py
> +        # print("num:", len(requests), flush=True)
done

2022-11-10 09:02 UTC, heliqi commented on fastdeploy/pybind/fd_tensor.cc
> +DLDataType fd_to_dlpack_type(FDDataType fd_dtype) {
done

2022-11-10 09:02 UTC, heliqi commented on fastdeploy/pybind/fd_tensor.cc
> +  FDASSERT(data_type.lanes == 1,
done

2022-11-10 09:02 UTC, heliqi commented on fastdeploy/pybind/fd_tensor.cc
> +void delete_unused_dltensor(PyObject* dlp) {
done

2022-11-11 05:32 UTC, jiangjiajun approved these changes

2022-11-11 05:32 UTC, merged