change ocr pre and post
PaddlePaddle/FastDeploy pull request #568
Opened 2022-11-11 07:25 UTC by HexToString

### [Model] Modify OCR to support serving and batch

[Model] Modify OCR to support serving and batch

### Describe

Modify OCR to support serving and batch

2022-11-12 05:36 UTC, jiangjiajun requested changes

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/common/result.cc
> +std::string OCRBatchResult::Str() {
当前所有接口的设计采用的都是

- XXXXResult 单张图片结果
- std::vector<XXXResult> 批量图片结果

此处引入的batch，与上面的有啥差别

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
> +  virtual bool Predict(cv::Mat& img, std::tuple<int, float>* cls_result);
const cv::Mat& img

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
> +  virtual bool Predict(cv::Mat& img, std::tuple<int, float>* cls_result);
新增doxygen注释

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
> +  virtual bool BatchPredict(const std::vector<cv::Mat>& images,
同上

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
> +  ClassifierPreprocessor preprocessor_;
改为private变量，同时新增
- `ClassifierPreprocessor& GetPreprocessor()`
- `ClassifierPostprocessor& GetPostprocessor()`
- `GetBatchSize`
- `SetBatchSize`

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_postprocessor.cc
> +  initialized_ = true;
这个initialized_在PaddleClas里面担心用没有真正加载成功yaml文件，所以增加initlaized来判断。 但在很多模型中，预处理参数都是默认的，其实不存在非initialized的情况，那这个变量可以去除，构造函数使用默认的即可

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_postprocessor.h
> +  float cls_thresh_ = 0.9;
增加函数 
- `GetThreshold`
- `SetThreshold`

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  initialized_ = true;
intialized同上，构造函数可使用默认

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +    Cast::Run(mat, "float");
上面3行代码，可以改成调用融合在一起的操作`NormalizeAndPermute`，相比这里分成3行，会提升大半的性能

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.h
> +
同上，增加函数来获取，和设置私有变量

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +                                        std::vector<FDTensor>* outputs);
这里函数注释与实际不符，改成
```
bool Run(std::vector<FDMat>* images, std::vector<FDTensor>* outputs, std::vector<std::float, 4>* det_boxes)
```
? 具体这个`det_boxes`根据`std::vector<std::array<float, 4>>`实际作用命名即可

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/dbdetector.h
> +  virtual bool Predict(cv::Mat& img,
const cv::Mat&

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/dbdetector.h
同上，增加GetXXX和SetXXX获取和设置私有成员变量

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +  recognizer_->preprocessor_.rec_image_shape_[1] = 32;
改为调用recognizer_->GetPreprocessor().SetImageShape()

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
>  bool PPOCRv2::Detect(cv::Mat* img,
Pipeline里面的Detect, classify， recognize之类的函数，目前均没有暴露给用户，只暴露了Predict。 如果不需要可以直接删除

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +bool PPOCRv2::BatchDetect(const std::vector<cv::Mat>& images, fastdeploy::vision::OCRBatchResult* batch_result){
这里跟其它的模型都统一下，避免因为Batch引入更多结果变量的定义

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +bool PPOCRv2::BatchRecognize(const std::vector<cv::Mat>& images, std::vector<std::string>* text, std::vector<float>* rec_scores){
对于Classifier, Recognizer和Detector，是不是可以直接调这些函数的Predict，为啥需要在Pipeline里面分别为他们写预测函数呢？

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +bool PPOCRv2::SetClsBatchSize(int batch_size){
括号与花括号中间要有空格

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +int PPOCRv2::GetDetBatchSize(){
现在Det支持Batch吗，周会提到目前采用的方式1 只支持单张图片

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +    return detector_->batch_size_;
当前在类外，都尽量不再直接访问成员变量，而采用GetXX和SetXX

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v3.h
> +    recognizer_->preprocessor_.rec_image_shape_[1] = 48;
同上

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v3.h
> +    recognizer_->preprocessor_.rec_image_shape_[1] = 48;
同上

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +  std::ifstream in(path);
下面的判断，可以插在这里，改在这里
```
FDASSERT(in, "Cannot open file %s to read.", path.c_str());
```

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +void OcrRecognizerResizeImage(FDMat* mat, const float& max_wh_ratio,
小于等于4字节的变量，大家一般不采用const T&，直接使用T就行，例如
```
OcrRecognizerResizeImage(FDMat* mat, float max_wh_ratio, const std::vector<int>& rec_image_shape)
```

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +    Cast::Run(mat, "float");
这里三行合为`NormalizeAndPermute`

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.h
> +  bool is_scale_ = true;
增加GetXXX, SetXXX

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/recognizer.cc
> +bool Recognizer::Predict(cv::Mat& img,
const cv::Mat&

2022-11-12 05:36 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/recognizer.h
> +  int batch_size_ = 6;
增加GetXXX

有一个地方需要注意下，目前只有对于preprocessor自定义类，我们只增加了函数
```
XXXPreprocessor& GetPreprocessor()
XXXPostprocessor& GetPostprocessr()
```

其它普通类型成员变量，则增加
```
T GetXX() const;
void SetXX();
```

2022-11-13 05:06 UTC, jiangjiajun requested changes

2022-11-13 05:06 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
> +  int batch_size_ = 6;
这个batch_size，应该是由pipeline里面来设置，所有模型只需处理一个vector，并将vector作为一个batch处理即可。 至于batch的大小由调用方（也就是用户或pipeline）来决定

2022-11-14 02:09 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/cls_postprocessor.cc
> +  initialized_ = true;
可以，但我怕后面要改动。

2022-11-14 08:39 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +int PPOCRv2::GetDetBatchSize(){
Det支持，但是后面的Rec和Cls还只能1张图的M个框一起。
如果把多个M框合并，再拆，这个还没支持。

2022-11-15 11:02 UTC, HexToString commented on fastdeploy/vision/common/result.cc
> +std::string OCRBatchResult::Str() {
已经修改

2022-11-15 11:30 UTC, jiangjiajun requested changes

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/common/result.h
> +*/
注释代码移除

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  int imgW = cls_image_shape[2];
代码命名都用小写+下划线（可待下个PR统一改）

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  if (ceilf(imgH * ratio) > imgW)
FD代码里统一下风格，改为if 后都使用花括号将要执行的语句括起来。

避免后面有新逻辑要增加到这个if分支，但没注意加花括号而出错

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.h
> +  std::vector<int> cls_image_shape_ = {3, 48, 192};
下个PR需将GetXX类函数加上（可待下个PR统一改）

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_postprocessor.h
> +  PostProcessor post_processor_;
这个PostProcessor的命名建议改下，太通用了。 DBDetectorPostprocessor里面有一个Postprocessor成员变量，不能直观理解作用是什么（可待下个PR统一改）

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.cc
> +    Cast::Run(mat, "float");
注释的代码都移除掉

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  bool initialized_ = false;
这个参数确认不用了，就移除掉即可，不用为了担心以后会不会可能用到而留一些代码逻辑，如若新人维护代码，会增加维护成本（可待下个PR统一改）

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +    if(!SingleBatchPostprocessor(tensor_data, tensor.shape, &texts->at(i_batch), &rec_scores->at(i_batch)))return false;
建议所有的if/else条件，全都都用花括号括起来。 此处代码中间缺少空格格开

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.h
> +   * \return true if the postprocess successed, otherwise false
注释与函数参数不一致

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +  imgW = rec_image_shape[2];
参数命名（可待下个PR统一改）

2022-11-15 11:30 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +  if (ceilf(imgH * ratio) > imgW)
花括号

2022-11-15 11:33 UTC, jiangjiajun requested changes

2022-11-15 11:33 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +  *result = std::move(batch_result[0]);
OCRResult参考DetectionResult实现move构造函数

2022-11-15 11:35 UTC, jiangjiajun commented
https://github.com/PaddlePaddle/FastDeploy/blob/develop/tests/models/test_pp_yolox.py#L69  参照这里的test_detection_yolox_1()函数，来确认python预处理函数、后处理函数的正确性

2022-11-16 03:05 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/ppocr_v2.cc
> +  *result = std::move(batch_result[0]);
已回复

2022-11-16 07:07 UTC, HexToString commented
FD(CPU) 51.34---->38.64
FD(GPU) 32.20---->18.39

2022-11-16 08:00 UTC, HexToString commented
> https://github.com/PaddlePaddle/FastDeploy/blob/develop/tests/models/test_pp_yolox.py#L69 参照这里的test_detection_yolox_1()函数，在相应目录下增加test_ppocr_v2.py和test_ppocr_v3.py，来确认python预处理函数、后处理函数的正确性

这个下个再加把。

2022-11-18 02:26 UTC, jiangjiajun approved these changes

2022-11-18 02:30 UTC, jiangjiajun commented
遗留TODO

- 部分comment留到下PR
- 单测tests/models
- batch的可配置化&TensorRT

2022-11-18 05:17 UTC, merged

2022-11-30 14:19 UTC, HexToString commented on fastdeploy/vision/common/result.h
> +*/
已解决

2022-11-30 14:20 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  int imgW = cls_image_shape[2];
已解决

2022-11-30 14:20 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.h
> +  std::vector<int> cls_image_shape_ = {3, 48, 192};
改起来涉及的太多啦，先不改了

2022-11-30 14:24 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/det_postprocessor.h
> +  PostProcessor post_processor_;
done

2022-11-30 14:24 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +    if(!SingleBatchPostprocessor(tensor_data, tensor.shape, &texts->at(i_batch), &rec_scores->at(i_batch)))return false;
done

2022-11-30 14:26 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.h
> +   * \return true if the postprocess successed, otherwise false
done

2022-11-30 14:26 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +  imgW = rec_image_shape[2];
done

2022-11-30 14:28 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  bool initialized_ = false;
感觉还是有点用，后续考虑直接删除默认构造。

2022-11-30 14:34 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/det_preprocessor.h
> +  bool initialized_ = false;
保留了rec_post的其他的删除了