[Serving]ppcls preprocessor support gpu
PaddlePaddle/FastDeploy pull request #615
Opened 2022-11-16 10:07 UTC by heliqi

### PR types(PR类型)
Serving

### Describe
- ppcls的预处理支持使用GPU

2022-11-16 10:56 UTC, jiangjiajun commented
性能数据怎样？

2022-11-16 11:15 UTC, heliqi commented
> 性能数据怎样？

有提升。 但没找到空闲的机器，测试数据一直有波动，就没写上来。 
理论上服务化跟直接用节省的时间是一样的，除非服务化集成没做好

2022-11-16 11:27 UTC, jiangjiajun requested changes

2022-11-16 11:27 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/serving/models/preprocess/config.pbtxt
> +    # The instance is deployed on the 0th GPU card
默认改成GPU，如若后端是CPU的OpenVINO会怎样？

2022-11-16 11:27 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/serving/models/preprocess/config.pbtxt
> +    # The instance is deployed on the 0th GPU card
为了兼容考虑，这里建议改成CPU，用户可以自己选择是否切到GPU。毕竟CPU是通用的，而GPU可能存在限制

2022-11-16 11:33 UTC, heliqi commented on examples/vision/classification/paddleclas/serving/models/preprocess/config.pbtxt
> +    # The instance is deployed on the 0th GPU card
因为runtime的例子给的是TRT的，所以这里配套给了GPU。
如果用户是cpu机器，直接启动不了，需要修改配置

2022-11-16 14:34 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/serving/models/preprocess/config.pbtxt
> +    # The instance is deployed on the 0th GPU card
建议给CPU，可以注释成可选项项，兼容性更重要(这里性能优化在服务化中的优化效果仍然不明)

2022-11-17 07:03 UTC, heliqi commented on examples/vision/classification/paddleclas/serving/models/preprocess/config.pbtxt
> +    # The instance is deployed on the 0th GPU card
Done 已改

2022-11-17 09:16 UTC, merged