Support PaddleDetection SSD Model
PaddlePaddle/FastDeploy pull request #630
Opened 2022-11-18 03:54 UTC by totorolin

### PR types(PR类型)

### Describe

2022-11-18 03:57 UTC, totorolin commented
python

2022-11-18 03:58 UTC, totorolin commented
<img width="653" alt="截屏2022-11-18 上午11 57 35" src="https://user-images.githubusercontent.com/97090522/202613600-831f9804-1804-4b8e-9f17-067808634a92.png">

2022-11-18 04:00 UTC, totorolin commented
<img width="649" alt="截屏2022-11-18 上午11 58 38" src="https://user-images.githubusercontent.com/97090522/202613671-c2f3b0bb-a79e-45d5-b5af-d75d9b392b4e.png">

2022-11-18 04:00 UTC, totorolin commented
<img width="653" alt="截屏2022-11-18 上午11 59 01" src="https://user-images.githubusercontent.com/97090522/202613821-4f655c81-04cb-43f2-aa6b-29b6c19df85e.png">

2022-11-18 04:00 UTC, totorolin commented
<img width="650" alt="截屏2022-11-18 上午11 59 12" src="https://user-images.githubusercontent.com/97090522/202613843-cfdd3e52-fc8f-44e1-b042-961dc304766f.png">

2022-11-18 04:01 UTC, totorolin commented
<img width="651" alt="截屏2022-11-18 上午11 59 23" src="https://user-images.githubusercontent.com/97090522/202613879-0cafbd66-111b-4d55-b6f5-e30045e55afc.png">

2022-11-18 04:01 UTC, totorolin commented
<img width="652" alt="截屏2022-11-18 上午11 59 33" src="https://user-images.githubusercontent.com/97090522/202613910-83cb583e-ceec-417c-bfe2-8ef9c82b738d.png">

2022-11-18 04:02 UTC, totorolin commented
C++

2022-11-18 04:03 UTC, totorolin commented
<img width="650" alt="截屏2022-11-18 下午12 01 46" src="https://user-images.githubusercontent.com/97090522/202614116-d1abae17-1c5d-4e63-825d-362a4b824205.png">

2022-11-18 04:03 UTC, totorolin commented
<img width="647" alt="截屏2022-11-18 下午12 01 59" src="https://user-images.githubusercontent.com/97090522/202614141-dd535075-89a2-45c7-bea6-2826d36329e4.png">

2022-11-18 04:03 UTC, totorolin commented
<img width="650" alt="截屏2022-11-18 下午12 02 12" src="https://user-images.githubusercontent.com/97090522/202614157-c723997b-08b5-449c-94f9-2d2c29968508.png">

2022-11-18 04:03 UTC, totorolin commented
<img width="658" alt="截屏2022-11-18 下午12 02 21" src="https://user-images.githubusercontent.com/97090522/202614188-b680039c-d960-4711-b7db-1114ebd2f2e4.png">

2022-11-18 04:04 UTC, totorolin commented
<img width="652" alt="截屏2022-11-18 下午12 02 31" src="https://user-images.githubusercontent.com/97090522/202614215-5e1c4ea5-fb72-4685-bda5-d105653d6bb9.png">

2022-11-18 04:04 UTC, totorolin commented
<img width="652" alt="截屏2022-11-18 下午12 02 41" src="https://user-images.githubusercontent.com/97090522/202614250-45428429-e419-4efc-86c2-810433770acb.png">

2022-11-18 04:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=630) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=630) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=630) it.</sub>

2022-11-21 03:05 UTC, DefTruth requested changes

2022-11-21 03:05 UTC, DefTruth commented on examples/vision/detection/paddledetection/cpp/infer_ssd.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res, 0.5);
新集成的模型都直接用： 
```C++
fastdeploy::vision::VisDetection();
```

2022-11-21 03:05 UTC, DefTruth commented on examples/vision/detection/paddledetection/cpp/infer_ssd.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res, 0.5);
新集成的模型都直接用： 
```C++
fastdeploy::vision::VisDetection();
```

2022-11-21 03:05 UTC, DefTruth commented on examples/vision/detection/paddledetection/cpp/infer_ssd.cc
> +
补充TrtInfer的测试

2022-11-21 03:06 UTC, DefTruth commented
还需要在： 
```shell
examples/vision/detection/paddledetection
```
增加文档说明

2022-11-21 07:03 UTC, totorolin commented
> <img alt="截屏2022-11-18 下午12 01 59" width="647" src="https://user-images.githubusercontent.com/97090522/202614141-dd535075-89a2-45c7-bea6-2826d36329e4.png">

2022-11-21 07:09 UTC, totorolin commented
![005](https://user-images.githubusercontent.com/97090522/202986684-036a8ae1-35ee-44fd-9415-f341a52ca248.jpg)
![004](https
![003](http
![002](http
![001](https://user-images.githubusercontent.com/97090522/202986775-b7724bc8-bc33-4f0f-bb40-1cc647207aed.jpg)
s://user-images.githubusercontent.com/97090522/202986761-a4df8fe7-b5c1-44de-b540-05f24440335c.jpg)
s://user-images.githubusercontent.com/97090522/202986742-c9d7e949-7e04-4e9c-b76c-7fba986e2f4b.jpg)
://user-images.githubusercontent.com/97090522/202986727-b74f8330-5367-4496-bc0b-dd9738717490.jpg)
重新找了五张图片测试vgg，测试结果如上

2022-11-21 07:11 UTC, totorolin commented
![005](https://user-images.githubusercontent.com/97090522/202987018-168d31a0-9af4-4f96-95d2-f2860e260b28.jpg)
![004](https://user-images.githubusercontent.com/97090522/202987074-7cad6697-372e-4bfc-a21f-71cd035e4441.jpg)
![003](https://user-images.githubusercontent.com/97090522/202987096-e45ca742-0f6d-4ec3-b2cc-962906058736.jpg)
![002](https://user-images.githubusercontent.com/97090522/202987120-f0ab46d4-4dad-4e20-8edb-06ed1a21dbfa.jpg)
![001](https://user-images.githubusercontent.com/97090522/202987134-691c2508-d06c-482f-bbdf-e99bd516ac1d.jpg)
重新找了五张图片测试vgg，测试结果如上

2022-11-22 11:55 UTC, DefTruth requested changes

2022-11-22 11:55 UTC, DefTruth commented on examples/vision/detection/paddledetection/README.md
> +| [ssd_vgg16_300_240e_voc](https://bj.bcebos.com/paddlehub/fastdeploy/ssd_vgg16_300_240e_voc.tgz) | 97.7M | Box AP 77.8%| 暂不支持ORT |
增加一个ssdlite模型的下载路径

2022-11-22 11:55 UTC, DefTruth commented on examples/vision/detection/paddledetection/python/README.md
> +
多出了一行空行，删除这个空行

2022-11-23 13:36 UTC, DefTruth requested changes

2022-11-23 13:36 UTC, DefTruth commented on examples/vision/detection/paddledetection/python/infer_ssd.py
> +    if args.use_trt:
TRT不支持，可以删除掉这部分逻辑

2022-11-25 07:41 UTC, DefTruth requested changes

2022-11-25 07:41 UTC, DefTruth commented on examples/vision/detection/paddledetection/python/infer_ssd.py
> +    parser.add_argument(
这部分trt的逻辑也要删除

2022-11-28 08:12 UTC, DefTruth approved these changes

2022-11-28 11:13 UTC, merged