[Model] Add Picodet RKNPU2
PaddlePaddle/FastDeploy pull request #635
Opened 2022-11-18 14:12 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Describe
为Picodet添加RKNPU2支持

2022-11-18 14:17 UTC, Zheng-Bicheng commented
### 代码变更详情
**base**
* 新增ApplyDecodeAndNMS()函数控制NMS以及Decode
* PPDet存在输入为1的情况，重写了判断输入个数的代码

**model.h**
* 为Picodet添加RKNPU2支持

**postprocess**
* 添加NMS操作
* 新增ApplyDecodeAndNMS()函数控制NMS以及Decode

**preprocess**
* 当配置文件不包含permute时，不再执行NHWC->NCHW

2022-11-18 14:19 UTC, Zheng-Bicheng commented
### TODO
按照原定的计划是添加utils支持decode+NMS。考虑到Picodet和PPYoloe的decode的部分可能不一致，因此暂时先不考虑decode部分，先添加NMS支持Picodet FP16部署。后期PPYOLOE量化完成后，改为utils控制decode+NMS。

2022-11-18 14:33 UTC, Zheng-Bicheng commented
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/58363586/202728663-4af0b843-d012-4aeb-8a66-626b7b87ca69.png">

2022-11-19 07:00 UTC, jiangjiajun requested changes

2022-11-19 07:00 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/base.cc
> +void PPDetBase::ApplyDecodeAndNMS() { postprocessor_.ApplyDecodeAndNMS(); }
这里不再在model定义一个新的函数，不采用`model.ApplyDecodeAndNMS()`这种外部用户方式，对于使用而言，改为调用
```
model.GetPostprocessor().ApplyDecodeAndNMS()
```
Python则是
```
model.postprocessor.apply_decode_and_nms()
```

2022-11-19 07:00 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/base.h
> +  void ApplyDecodeAndNMS();
同上

2022-11-19 07:00 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/postprocessor.cc
>    std::vector<int> num_boxes(tensors[1].shape[0]);
这里将逻辑拆成成两个子函数，来提升代码可读性吧

```
if (apply_decode_and_nms_) {
  FDASSERT(tensors.size() == n, 'xxx');
  return process_undecode_results();// 这段函数逻辑可以继续放在postprocessor.cc中作为一个单独的函数实现
} 

此前的代码逻辑都不必修改，放在后面即可
````

下面的代码逻辑不改动，这样代码的改动量看起来也更小，更便于Review

2022-11-19 12:00 UTC, Zheng-Bicheng reviewed
* 按照要求删除了base中的apply_decode_and_nms_函数，改用postprocess中的apply_decode_and_nms_函数实现后处理
* 按照要求将ProcessUnDecodeResults作为独立的函数进行处理
* 修改了example的实例代码

2022-11-19 16:13 UTC, jiangjiajun requested changes

2022-11-19 16:13 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/postprocessor.h
> +  std::vector<float> scale_factor{1.0, 1.0};
我们团队内队在此次代码重构中，对齐主流开源项目，规范两个代码风格
- 所有class的成员变量，在命名时均要以下划线结尾，即应该命名为`scale_factor_`
- 所有class的成员变量，在类外代码均不直接访问，而是通过`GetScaleFactor`和`SetScaleFactor`的方式来读写

尽可能将变量放在private中，如若要继承，可放在protected里面

2022-11-19 16:13 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/postprocessor.h
> +  void ApplyDecodeAndNMS();
增加一个`bool DecodeAndNMSEnabled()`这个接口，来判断是否apployDecodeandnms

2022-11-19 16:13 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/base.cc
> +  }
这里的代码改成
```
if (postpro.DecodeAndNMSEnabled()) {
  // 将scale_factor传给postprocessor, postprocessor.SetScaleFactor({})
}
```

2022-11-19 16:13 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/postprocessor.cc
> +    FDASSERT(tensors.size() == 2,
这里提示信息按下面的方式来提示下
```
FDASSERT(tensors.size() == 2, "While postprocessing with ApplyDecodeAndNMS, there should be 2 outputs for this model, but now it's %zu.", tensors.size());
// 由于普通导出来的模型也是有2个输出，所以建议再给一个进一步的输出提示，例如下面这种方式
FDASSERT(tensors[0].shape.size() == 4, "While postprocessing with ApplyDecodeAndNMS, the rank of the first outputs should be 4, but now it's %zu", tensors[0].shape.size())；

2022-11-19 16:13 UTC, jiangjiajun commented on fastdeploy/vision/detection/ppdet/postprocessor.h
> +  /// This function will enable decode and nms in postprocess step.
这个注释改成
```
/// Apply box decoding and nms step for the outputs for the model. This is only available for those model exported without box decoding and nms
```

2022-11-21 01:55 UTC, jiangjiajun approved these changes

2022-11-21 05:44 UTC, merged