[Other]Refactor PaddleSeg with preprocessor && postprocessor
PaddlePaddle/FastDeploy pull request #639
Opened 2022-11-21 01:07 UTC by felixhjh

### PR types(PR类型)

Other
### Describe

Refactor PaddleSeg with preprocessor && postprocessor

2022-11-21 02:55 UTC, jiangjiajun requested changes

2022-11-21 02:55 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  for (auto fd_image : fd_images) {
```
for (const auto& fd_image : fd_images)
```

2022-11-21 02:55 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/model.cc
> +  imgs_info["shape_info"] = shape_info;
由于imgs_info本身也是预处理的输出，把上面这部分塞原始图片大小的操作直接放到preprocessor.Run函数里面，这样服务化调用时，直接return出来的结果就是整个imgs_info

2022-11-21 02:55 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +  FDASSERT(ReadFromConfig(config_file), "Failed to create PaddleDetPreprocessor.");
Failed to create PaddleSegPostprocessor

2022-11-21 02:55 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    if(is_store_score_map_) {
if后面空格

2022-11-21 02:55 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +        if(!(this->disable_normalize_and_permute_)){
不需要调用this, 直接if (!disable_normalize_and_permute_)

2022-11-21 02:55 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +  }
这里这个，按照之前的说法，创建一个ResizeByDirection在ppseg目录下

2022-11-21 02:55 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +        std::make_shared<Resize>(max_height, max_height));
为什么是插入到倒数第二个，而不是放在第1个

2022-11-23 07:01 UTC, jiangjiajun requested changes

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +  initialized_ = true;
Failed to create PaddleSegPostprocessor

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    if (!is_with_argmax_ && is_store_score_map_) {
代码命名里的`IsXXX`在Seg里面是状态，还是动作需要统一。 看前面用的是`apply_softmax`， 那这里就改成`store_score_map_`

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +  }
1. 处理出来是score的模型
2. 处理出来是argmax的模型

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    result->Clear();
Clear会增加耗时

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    is_transform = true;
is_transform就是!is_with_argmax

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    }
针对argmax和不argmax的结果，取出中间每个图片的预测结果

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +bool PaddleSegPostprocessor::CopyFromInferResults(const FDTensor& infer_results,
infer_results [b, class, h, w]

[b, h, w]
[b, 90, h, w]

[1, h, w]
[1, 90, h, w]

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +                           fp32_copy_result_buffer);
```
// 取出指针的开始位置，不用拷贝，直接Share
const ptr = start + offset
infer_result.SetExternalData(infer_result_shape, transform_infer_results.dtype,  ptr)
```

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +                           fp32_copy_result_buffer);
同上

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    Mat* mat = nullptr;
FD的Mat都改为FDMat

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +          static_cast<int64_t*>(infer_result.Data());
CpuData()

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    std::vector<uint8_t>* uint8_result_buffer = nullptr;
已经得到infer_result是batch中某个sample的 [h, w, 1], [h, w, c]

FDMat mat;
if (infer_result.dtype == INT64 || infer_reuslt.dtype == INT32) {
  int8_tensor = Cast(infer_result, 'int8');
  mat = Create(int8_tensor);
  Resize::Run(&mat, shape);
} else {
  mat = Create(infer_result);
  Reisze::Run(&mat, shape);
}

FDTensor result;
mat->ShareWithTensor(&result);

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.cc
> +    score_infer_result_buffer = static_cast<float_t*>(max_score_result.Data());
float* score_infer_result_buffer = reinterpret_cast<float*>(max_score_result.CpuData());

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/postprocessor.h
> +  void SetApplySoftmax(const bool value) {
不用const

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +  }
移到最开始

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +        std::make_shared<Resize>(max_height, max_height));
逻辑存在问题，会重复insert

2022-11-23 07:01 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/preprocessor.cc
> +        std::make_shared<Resize>(max_height, max_height));
evalutation增加支持batch_size， 跑一遍验证

2022-11-24 09:28 UTC, joey12300 requested changes

2022-11-24 09:28 UTC, joey12300 commented on fastdeploy/utils/utils.h
> +      FD_PRIVATE_CASE_TYPE(NAME, ::fastdeploy::FDDataType::UINT8, uint8_t,    \
这个宏主要遍历function的输入type。UINT8类型暂时只作为segmentation task的label输出类型，无须加到FD_VISIT_INT_FLOAT_TYPES中

2022-11-24 09:28 UTC, joey12300 commented on fastdeploy/utils/utils.h
> +      FD_PRIVATE_CASE_TYPE(NAME, ::fastdeploy::FDDataType::UINT8, uint8_t,    \
同上

2022-11-25 07:41 UTC, felixhjh commented on fastdeploy/utils/utils.h
> +      FD_PRIVATE_CASE_TYPE(NAME, ::fastdeploy::FDDataType::UINT8, uint8_t,    \
这个和舜杰确认过，还是应当改下

2022-11-28 07:47 UTC, jiangjiajun approved these changes

2022-11-28 07:47 UTC, jiangjiajun commented on fastdeploy/vision/segmentation/ppseg/ppseg_pybind.cc
> +             self.Predict(&mat, &res);
不再调用Deprecated接口，改为调用Predict(mat, &res)

2022-11-28 07:50 UTC, merged