[Backend] Add yolov5 and ppyoloe for RK1126
PaddlePaddle/FastDeploy pull request #647
Opened 2022-11-21 12:29 UTC by yeliang2258

### PR types(PR类型)

Backend

### Describe

Add yolov5 and ppyoloe for RK1126

2022-11-30 06:30 UTC, jiangjiajun requested changes

2022-11-30 06:30 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/rv1126/README.md
> +在 RV/home/yeliang/develop/FastDeploy/examples/vision/classification/paddleclas/rv1126/README.md1126 上只支持 C++ 的部署。
这一长串路径是不是打错了

2022-11-30 06:30 UTC, jiangjiajun commented on docs/cn/build_and_install/rv1126.md
> +RV1126 上部署 PaddleClas 分类模型请参考：[PaddleClas RV1126开发板 C++ 部署示例](../../../examples/vision/classification/paddleclas/rv1126/README.md)
Yolov5/ppyoloe/pp-liteseg的也在这里加上

2022-11-30 06:30 UTC, jiangjiajun requested changes

2022-11-30 06:30 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/README.md
> +- 2. 用户可以先试用 PaddleDetection 自行导出 Float32 模型，注意导出模型模型时设置参数：，更多细节请参考：[PPYOLOE](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/ppyoloe)
试用->使用。 “注意导出模型时设置参数：“ 具体是要怎么注意？

2022-11-30 06:40 UTC, jiangjiajun requested changes

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/README.md
> +- 3. 在导出 Float32 模型之后，用户使用 FastDeploy 提供的[一键模型自动化压缩工具](../../../../../../tools/auto_compression/)，自行进行模型量化, 并使用产出的量化模型进行部署。(注意: 推理量化后的分类模型仍然需要FP32模型文件夹下的 inference_cls.yaml 文件, 自行量化的模型文件夹内不包含此 yaml 文
这个`auto_compression`目录云尧改了目录，确认下新的目录，改一下（如果之前其它文档引用到了，也对应改一下）

Detection中的配置文件叫`infer_cfg.yml`， 分类的是`inference_cls.yaml`

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/README.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=../fastdeploy-tmivx/timvx.cmake -DFASTDEPLOY_INSTALL_DIR=fastdeploy-tmivx ..
编译示例时，也需要这个CMAKE_TOOLCHAIN_FILE吗，看这个cmake只是一些判断而已，而在FASTDEPLOY_INSTALL_DIR已经有FastDeploy.cmake了

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/infer_ppyoloe.cc
> +  auto im_bak = im.clone();
新的示例删除`auto im_bak = im.clone();`这行代码

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/infer_ppyoloe.cc
> +  if (!model.Predict(&im, &res)) {
`Predict(&im, &res)`改为`Predict(im, &res)`

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/infer_ppyoloe.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res, 0.5);
im_bak 改为im

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/README.md
> +/home/yeliang/develop/FastDeploy/examples/vision/detection/yolov5/rv1126/README.md# YoloV5 量化模型在 rv1126 上的部署
这里又出现了这一长串路径

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/cpp/README.md
> +## 在 rv1126 上部署量化后的 Yolov5 检测模型
所有的模型命名检查下，PP-YOLOE YOLOv5

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/cpp/README.md
> +## 在 rv1126 上部署量化后的 Yolov5 检测模型
另外rv1126官网是叫RV1126还是rv1126，也需要确认保持一致

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/cpp/README.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=../fastdeploy-tmivx/timvx.cmake -DFASTDEPLOY_INSTALL_DIR=fastdeploy-tmivx ..
同上，cmake_toolchain_file是否有必要

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/cpp/infer.cc
> +  auto im_bak = im.clone();
此示例代码改动，同PP-YOLOE的infer.cc

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rv1126/README.md
> +# PaddleSeg 量化模型在 rv1126 上的部署
这个应该只是PP-LiteSeg模型？

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rv1126/cpp/README.md
> +## 在 rv1126 上部署量化后的 PP_LiteSeg 分割模型
PP-LiteSeg

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rv1126/cpp/README.md
> +5. 基于 adb 工具部署 PP_LiteSeg 分割模型到 Rockchip RV1126，可使用如下命令：
这里是RV1126，但大部分地方是rv1126，保持与官方的说法一致

2022-11-30 06:40 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rv1126/cpp/infer.cc
> +  auto im_bak = im.clone();
此示例改动，同PP-YOLOE的infer.cc

2022-11-30 07:16 UTC, yeliang2258 commented on examples/vision/detection/paddledetection/rv1126/cpp/README.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=../fastdeploy-tmivx/timvx.cmake -DFASTDEPLOY_INSTALL_DIR=fastdeploy-tmivx ..
示例也需要交叉编译

2022-11-30 07:35 UTC, yeliang2258 commented on examples/vision/detection/paddledetection/rv1126/cpp/README.md
> +- 3. 在导出 Float32 模型之后，用户使用 FastDeploy 提供的[一键模型自动化压缩工具](../../../../../../tools/auto_compression/)，自行进行模型量化, 并使用产出的量化模型进行部署。(注意: 推理量化后的分类模型仍然需要FP32模型文件夹下的 inference_cls.yaml 文件, 自行量化的模型文件夹内不包含此 yaml 文
全局都改了

2022-11-30 07:36 UTC, yeliang2258 commented on examples/vision/detection/yolov5/rv1126/cpp/README.md
> +## 在 rv1126 上部署量化后的 Yolov5 检测模型
全改为RV1126

2022-12-01 08:35 UTC, jiangjiajun requested changes

2022-12-01 08:35 UTC, jiangjiajun commented on cmake/paddlelite.cmake
> +    set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_armhf_1130.tgz")
这个库是自己编译的？ Lite编译库时是否需要有什么环境要求，例如像Linux需要manylinux这样？

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/README.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=../fastdeploy-tmivx/timvx.cmake -DFASTDEPLOY_INSTALL_DIR=fastdeploy-tmivx ..
路径改成统一的

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/infer_ppyoloe.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im, res, 0.5);
改用接口 `fastdeploy::vision::VisDetection`

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/detection/paddledetection/rv1126/cpp/infer_ppyoloe.cc
> +                 "on gpu with TensorRT backend. "
这个demo中0和1有区别么

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/cpp/README.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=../fastdeploy-tmivx/timvx.cmake -DFASTDEPLOY_INSTALL_DIR=fastdeploy-tmivx ..
路径统一

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/cpp/infer.cc
> +              << std::endl;
同上，这个demo参数看起来并没有用，增加的0看起来也没用

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/detection/yolov5/rv1126/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im, res);
改成`astdeploy::vision::VisDetection`

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rv1126/cpp/README.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=../fastdeploy-tmivx/timvx.cmake -DFASTDEPLOY_INSTALL_DIR=fastdeploy-tmivx ..
路径统一，确保用户按照文档命令一路执行下来是work的

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rv1126/cpp/infer.cc
> +  std::cout << res.Str() << std::endl;
这个也调用可视化函数将结果画出来

2022-12-01 08:35 UTC, jiangjiajun commented on examples/vision/segmentation/paddleseg/rv1126/cpp/infer.cc
> +                 "on gpu with TensorRT backend. "
这些代码注释使用方式没有改

2022-12-01 09:46 UTC, yeliang2258 commented on cmake/paddlelite.cmake
> +    set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_armhf_1130.tgz")
我自己编译的，在搭建好的交叉编译环境里面编译就可以

2022-12-05 08:47 UTC, jiangjiajun approved these changes

2022-12-05 08:48 UTC, merged