[Model] Support YOLOv7-face Model
PaddlePaddle/FastDeploy pull request #651
Opened 2022-11-22 05:26 UTC by CoolKbh

### Describe
1.增加支持Yolov7-face模型
2.该模型来自 https://github.com/derronqi/yolov7-face ，是在YOLOv7基础上对人脸识别进行了优化

### New feature

* Dynamic keypoints
* WingLoss
* Efficient backbones
* EIOU and SIOU

| Method           |  Test Size | Easy  | Medium | Hard  | FLOPs (B) @640 | Link  |
| -----------------| ---------- | ----- | ------ | ----- | -------------- | ----- |
| yolov7-lite-e    | 640        | 91.8  | 88.6   | 71.8  |  2.6           | [google](https://drive.google.com/file/d/1hvjQ43lrhYWslCiiNoKDmkso98tgdG7P/view?usp=sharing) |
| yolov7-tiny-leak | 640        | 93.2  | 91.3   | 83.0  |  16.6          | [google](https://drive.google.com/file/d/1B2F5YuERfMEfJeRXfz5oMxI8wcZLmvFJ/view?usp=sharing) |
| yolov7s          | 640        | 94.8  | 93.1   | 85.2  |  16.8          | [google](https://drive.google.com/file/d/1_ZjnNF_JKHVlq41EgEqMoGE2TtQ3SYmZ/view?usp=sharing) |
| yolov7-w6        | 960        | 96.4  | 95.0   | 88.3  |  89.0          | [google](https://drive.google.com/file/d/1U_kH7Xa_9-2RK2hnyvsyMLKdYB0h4MJS/view?usp=sharing) |
| yolov7-w6+TTA    | 1280       | 96.9  | 95.8   | 90.4  |  89.0          | [google](https://drive.google.com/file/d/1U_kH7Xa_9-2RK2hnyvsyMLKdYB0h4MJS/view?usp=sharing) |

性能测试
 
原repo：
| Device      | thread nums   | end to end time average time(ms) | run average time(ms)|
| -----------------| ---------- | -------------- | ----- |
| cpu_ort | 1 | 131.74 | 108.12  |
| cpu_ort | 8 | 82.22  | 51.63  |
| gpu_ort | - | 23.79 | 7.64  |

FastDeploy测试：
| Device      | thread nums   | end to end time average time(ms) | run average time(ms)|
| -----------------| ---------- | -------------- | ----- |
| cpu_fd_ort | 1 | 105.92 | 102.66  |
| cpu_fd_ort | 8 | 65.38  | 56.62  |
| gpu_fd_ort | - | 10.94 | 7.75  |
| tensorRT_fp16_GPU | - | 7.77 | 4.29 |
| tensorRT_GPU | - | 7.87 | 4.32 |

2022-11-22 05:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=651) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=651) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: kongbohua<br/>:x: CoolKbh<br/><hr/>**kongbohua** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=651) it.</sub>

2022-12-05 09:01 UTC, jiangjiajun commented
为PR增加一个好的描述说明。 包括模型来源，模型类型，模型效果（例如性能和精度）

2022-12-07 08:07 UTC, wjj19950828 requested changes

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/README.md
> +wget https://https://bj.bcebos.com/paddlehub/fastdeploy/cpp/fastdeploy-linux-x64-gpu-0.7.0.tgz
修改版本号，0.7.0并没有YOLOv7-Face，更改为x.x.x，然后注明：x.x.x >= 1.0.2

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/README.md
> +tar xvf fastdeploy-linux-x64-0.7.0.tgz
同上

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/README.md
> +cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-0.7.0
同上

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/README.md
> +https://github.com/hpc203/yolov7-detect-face-onnxrun-cpp-py
修改下路径，https://bj.bcebos.com/paddlehub/fastdeploy/模型名

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/README.md
> +<img width="640" src="https://user-images.githubusercontent.com/67993288/184301839-a29aefae-16c9-4196-bf9d-9c6cf694f02d.jpg">
这个可视化结果也更新为自己的链接

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/README.md
> +> YOLOv5Face::Predict(cv::Mat* im, FaceDetectionResult* result,
YOLOv7Face

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  // // batchPredict
注释代码全部去掉

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisFaceDetection(im_bak1, res);
fastdeploy::vision::Visualize::VisFaceDetection会废弃

使用fastdeploy::vision::VisFaceDetection

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisFaceDetection(im_bak, res);
同上

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisFaceDetection(im_bak, res);
同上

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/python/README.md
> +cd examples/vision/facedet/yolov5face/python/
yolov7face

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/python/README.md
> +wget https://bj.bcebos.com/paddlehub/fastdeploy/yolov5s-face.onnx
yolov7-tiny-face.onnx

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/python/README.md
> +https://github.com/hpc203/yolov7-detect-face-onnxrun-cpp-py
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on examples/vision/facedet/yolov7face/python/README.md
> +> > * **landmarks_per_face**(int): 指定当前模型检测的人脸所带的关键点个数，默认为5.
目前预处理是有这些参数吗

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.cc
> +  std::cout <<"batch size:" << batch << std::endl;
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.cc
> +    //std::cout << "Before: "<< (*results)[bs].Str() << std::endl;
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.cc
> +    //std::cout << "After NMS: "<< (*results)[bs].Str() << std::endl;
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /** \brief Process the result of runtime and fill to DetectionResult structure
DetectionResult->FaceDetectionResult

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Set conf_threshold, default 0.25
看实现默认为0.7

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +#include "yaml-cpp/yaml.h"
不需要的头文件去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +    std::cout << "mat: " << mat->Height() << " " << mat->Width() << std::endl;
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +    Resize::Run(mat, resize_w, resize_h, -1, -1, interp);
参照最新YOLOv5实现，在letter_box中做resize，这里reszie考虑到性能去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  std::cout << "resize mat: " << mat->Height() << " " << mat->Width() << std::endl;
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  Cast::Run(mat, "float");
这里合成一个OP，ConvertAndPermute，减少内存拷贝，参考YOLOv5

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // std::cout << resize_h << " " << resize_w << std::endl;
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // std::cout << pad_h << " " << pad_w << std::endl;
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +/*! @brief YOLOv7Face model object used when to load a YOLOv5Face model exported by YOLOv5Face.
YOLOv7Face

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/yolov7face_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in Yolov7FacePostprocessor.')");
pybind11::eval会有问题，改成throw std::runtime_error，参考YOLOv5

2022-12-07 08:07 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/yolov7face_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in Yolov7FacePostprocessor.')");
同上

2022-12-07 08:07 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        # 调用基函数进行backend_option的初始化
中文注释全部去掉

2022-12-07 08:07 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def batch_predict(self, images):
判断下images的len，如果>1，跑出异常，提示用户仅支持bs=1

2022-12-07 08:07 UTC, wjj19950828 commented on python/infer.py
> +import pickle
去掉

2022-12-07 08:07 UTC, wjj19950828 commented on python/infer.py
> +# input_url1 = "https://gitee.com/paddlepaddle/PaddleDetection/raw/release/2.4/demo/000000014439.jpg"
去掉注释

2022-12-07 08:07 UTC, wjj19950828 commented on tests/models/test_yolov7face.py
> +    model_url = "https://bj.bcebos.com/paddlehub/fastdeploy/yolov7.onnx"
名字统一改为对应onnx name

2022-12-07 08:07 UTC, wjj19950828 commented on tests/models/test_yolov7face.py
> +        print("result1:", result1)
print去掉

2022-12-07 08:30 UTC, wjj19950828 requested changes

2022-12-07 08:30 UTC, wjj19950828 commented on python/infer.py
> +import fastdeploy as fd
这个infer.py去掉，放在example即可

2022-12-07 10:40 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/README.md
> +tar xvf fastdeploy-linux-x64-0.7.0.tgz
done

2022-12-07 10:40 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/README.md
> +cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-0.7.0
done

2022-12-07 10:42 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/README.md
> +https://github.com/hpc203/yolov7-detect-face-onnxrun-cpp-py
done

2022-12-07 11:59 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/README.md
> +<img width="640" src="https://user-images.githubusercontent.com/67993288/184301839-a29aefae-16c9-4196-bf9d-9c6cf694f02d.jpg">
done

2022-12-07 11:59 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/README.md
> +> YOLOv5Face::Predict(cv::Mat* im, FaceDetectionResult* result,
done

2022-12-07 13:04 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  // // batchPredict
done

2022-12-07 13:04 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisFaceDetection(im_bak1, res);
done

2022-12-07 13:05 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisFaceDetection(im_bak, res);
done

2022-12-07 13:05 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisFaceDetection(im_bak, res);
done

2022-12-07 13:30 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/python/README.md
> +cd examples/vision/facedet/yolov5face/python/
done

2022-12-07 13:31 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/python/README.md
> +wget https://bj.bcebos.com/paddlehub/fastdeploy/yolov5s-face.onnx
done

2022-12-07 13:31 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/python/README.md
> +https://github.com/hpc203/yolov7-detect-face-onnxrun-cpp-py
done

2022-12-07 13:32 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/python/README.md
> +> > * **landmarks_per_face**(int): 指定当前模型检测的人脸所带的关键点个数，默认为5.
对

2022-12-07 13:33 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.cc
> +  std::cout <<"batch size:" << batch << std::endl;
done

2022-12-07 13:34 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.cc
> +    //std::cout << "Before: "<< (*results)[bs].Str() << std::endl;
done

2022-12-07 13:34 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.cc
> +    //std::cout << "After NMS: "<< (*results)[bs].Str() << std::endl;
done

2022-12-07 13:36 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /** \brief Process the result of runtime and fill to DetectionResult structure
done

2022-12-07 13:36 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Set conf_threshold, default 0.25
done

2022-12-07 13:38 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +#include "yaml-cpp/yaml.h"
done

2022-12-07 13:38 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +    std::cout << "mat: " << mat->Height() << " " << mat->Width() << std::endl;
done

2022-12-07 13:41 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +    Resize::Run(mat, resize_w, resize_h, -1, -1, interp);
done

2022-12-07 13:41 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  std::cout << "resize mat: " << mat->Height() << " " << mat->Width() << std::endl;
done

2022-12-07 13:45 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // std::cout << resize_h << " " << resize_w << std::endl;
done

2022-12-07 13:47 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // std::cout << pad_h << " " << pad_w << std::endl;
done

2022-12-07 13:48 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +/*! @brief YOLOv7Face model object used when to load a YOLOv5Face model exported by YOLOv5Face.
done

2022-12-08 08:13 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  Cast::Run(mat, "float");
done

2022-12-08 08:15 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in Yolov7FacePostprocessor.')");
done

2022-12-08 08:20 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in Yolov7FacePostprocessor.')");
done

2022-12-08 08:21 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        # 调用基函数进行backend_option的初始化
done

2022-12-08 08:22 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def batch_predict(self, images):
加在了C++中

2022-12-08 08:34 UTC, CoolKbh commented on python/infer.py
> +import pickle
推错文件了，已经删掉

2022-12-08 08:34 UTC, CoolKbh commented on python/infer.py
> +# input_url1 = "https://gitee.com/paddlepaddle/PaddleDetection/raw/release/2.4/demo/000000014439.jpg"
推错文件了，已经删掉

2022-12-08 08:47 UTC, CoolKbh commented on tests/models/test_yolov7face.py
> +    model_url = "https://bj.bcebos.com/paddlehub/fastdeploy/yolov7.onnx"
done

2022-12-08 08:47 UTC, CoolKbh commented on tests/models/test_yolov7face.py
> +        print("result1:", result1)
done

2022-12-08 08:47 UTC, CoolKbh commented on python/infer.py
> +import fastdeploy as fd
上面已经去掉

2022-12-12 12:09 UTC, wjj19950828 requested changes

2022-12-12 12:09 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +                              std::array<float, 2>>>& ims_info);
这行缩进是不是没对齐

2022-12-12 12:09 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // 3. HWC->CHW
注释换成ConvertAndPermute

2022-12-12 12:09 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // Compute `result = mat * alpha + beta` directly by channel
上面注释都去掉

2022-12-12 12:09 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +   * \param[in] conf_threshold confidence threashold for postprocessing, default is 0.25
default is 0.7

2022-12-12 12:09 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +                       float conf_threshold = 0.25,
default 0.7

2022-12-12 12:09 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/yolov7face_pybind.cc
> +          pybind11::eval("raise Exception('Failed to preprocess the input data in PaddleClasPreprocessor.')");
pybind11::eval修改

2022-12-12 12:09 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        confidence threshold for postprocessing, default is 0.25
0.7

2022-12-12 12:09 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        # 初始化后的option保存在self._runtime_option
中文注释去掉

2022-12-12 12:09 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        # 通过self.initialized判断整个模型的初始化是否成功
中文注释去掉

2022-12-12 12:09 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image, conf_threshold=0.3, nms_iou_threshold=0.5):
conf_threshold=0.7

2022-12-12 12:09 UTC, wjj19950828 commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        :param conf_threshold: confidence threashold for postprocessing, default is 0.3
0.7

2022-12-12 12:09 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.cc
> +  FDASSERT(images.size() == 1, "Only support batch =1 now.");
batch =1 -> batch = 1

2022-12-12 12:32 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +                              std::array<float, 2>>>& ims_info);
done

2022-12-12 12:33 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // 3. HWC->CHW
done

2022-12-12 12:34 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/preprocessor.cc
> +  // Compute `result = mat * alpha + beta` directly by channel
done

2022-12-12 12:34 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +   * \param[in] conf_threshold confidence threashold for postprocessing, default is 0.25
done

2022-12-12 12:35 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +                       float conf_threshold = 0.25,
done

2022-12-12 12:36 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face_pybind.cc
> +          pybind11::eval("raise Exception('Failed to preprocess the input data in PaddleClasPreprocessor.')");
done

2022-12-12 12:36 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        confidence threshold for postprocessing, default is 0.25
done

2022-12-12 12:37 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        # 初始化后的option保存在self._runtime_option
done

2022-12-12 12:37 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        # 通过self.initialized判断整个模型的初始化是否成功
done

2022-12-12 12:38 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image, conf_threshold=0.3, nms_iou_threshold=0.5):
done

2022-12-12 12:38 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +        :param conf_threshold: confidence threashold for postprocessing, default is 0.3
done

2022-12-12 12:39 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.cc
> +  FDASSERT(images.size() == 1, "Only support batch =1 now.");
done

2022-12-13 02:42 UTC, wjj19950828 requested changes

2022-12-13 02:42 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Set nms_threshold, default 0.5
0.45

2022-12-13 02:42 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Get nms_threshold, default 0.5
0.45

2022-12-13 02:42 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Set conf_threshold, default 0.7
0.5

2022-12-13 02:42 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Get conf_threshold, default 0.7
0.5

2022-12-13 02:42 UTC, wjj19950828 commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +                             std::array<float, 2>>>& ims_info);
缩进问题

2022-12-13 03:27 UTC, wjj19950828 approved these changes

2022-12-13 03:39 UTC, jiangjiajun requested changes

2022-12-13 03:39 UTC, jiangjiajun commented on examples/vision/facedet/yolov7face/cpp/CMakeLists.txt
> +# 指定下载解压后的fastdeploy库路径
新代码中所有中文的注释，都改为英文

2022-12-13 03:39 UTC, jiangjiajun commented on examples/vision/facedet/yolov7face/cpp/README.md
> +以Linux上CPU推理为例，在本目录执行如下命令即可完成编译测试
这里列的是CPU，但下面下载的包是GPU的

2022-12-13 03:39 UTC, jiangjiajun commented on examples/vision/facedet/yolov7face/python/infer.py
> +# 配置runtime，加载模型
改为英文注释

2022-12-13 03:39 UTC, jiangjiajun commented on examples/vision/facedet/yolov7face/python/infer.py
> +result = model.predict(im.copy())
新的代码里，我们都不再添加im.copy， 而是直接im

2022-12-13 03:39 UTC, jiangjiajun commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.cc
> +bool YOLOv7Face::Predict(cv::Mat* im, FaceDetectionResult* result, float conf_threshold, float nms_threshold){
新模型无需再提供这个函数，这个函数在老模型中，为了兼容老代码，才保留。 新模型，我们只需要下面的两个Predict接口即可

2022-12-13 03:39 UTC, jiangjiajun commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +  virtual bool Predict(cv::Mat* im, FaceDetectionResult* result,
同上

2022-12-13 03:39 UTC, jiangjiajun commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image, conf_threshold=0.5, nms_iou_threshold=0.45):
不再保留这个接口，只有`predict(self, input_image)`，如果需要修改后处理参数，则需要是`model.postprocessor.conf_threshold=0.5`这样来修改

2022-12-13 03:39 UTC, jiangjiajun commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
同上面对Predict的comment，调用新接口， 即`Predict(const cv::Mat&, ...)`

2022-12-13 03:39 UTC, jiangjiajun commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto im_bak = im.clone();
新代码里不再写im_bak = im.clone()这行代码

2022-12-13 03:39 UTC, jiangjiajun commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::VisFaceDetection(im_bak, res);
此处也将im_bak改为im

2022-12-13 07:07 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Set nms_threshold, default 0.5
done

2022-12-13 07:07 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Get nms_threshold, default 0.5
done

2022-12-13 07:07 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Set conf_threshold, default 0.7
done

2022-12-13 07:07 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/postprocessor.h
> +  /// Get conf_threshold, default 0.7
done

2022-12-13 07:48 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/CMakeLists.txt
> +# 指定下载解压后的fastdeploy库路径
done

2022-12-13 07:48 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/README.md
> +以Linux上CPU推理为例，在本目录执行如下命令即可完成编译测试
done

2022-12-13 07:53 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/python/infer.py
> +# 配置runtime，加载模型
done

2022-12-13 07:58 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/python/infer.py
> +result = model.predict(im.copy())
done

2022-12-13 08:00 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.cc
> +bool YOLOv7Face::Predict(cv::Mat* im, FaceDetectionResult* result, float conf_threshold, float nms_threshold){
done

2022-12-13 08:01 UTC, CoolKbh commented on fastdeploy/vision/facedet/yolov7-face/yolov7face.h
> +  virtual bool Predict(cv::Mat* im, FaceDetectionResult* result,
done

2022-12-13 08:15 UTC, CoolKbh commented on python/fastdeploy/vision/facedet/contrib/yolov7face.py
> +    def predict(self, input_image, conf_threshold=0.5, nms_iou_threshold=0.45):
done

2022-12-13 08:21 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::VisFaceDetection(im_bak, res);
done

2022-12-13 08:21 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  auto im_bak = im.clone();
done

2022-12-13 08:22 UTC, CoolKbh commented on examples/vision/facedet/yolov7face/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
done

2022-12-14 11:10 UTC, jiangjiajun approved these changes

2022-12-14 11:14 UTC, merged