[Model] add detection model : fasestdet
PaddlePaddle/FastDeploy pull request #656
Opened 2022-11-22 08:31 UTC by GodIsBoom

### [Model]

### Describe

add detection model : fasestdet [debugging]

2022-11-22 11:06 UTC, wjj19950828 requested changes

2022-11-22 11:06 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +        // 前景概率
注释统一改为英文

2022-12-07 08:32 UTC, wjj19950828 requested changes

2022-12-07 08:32 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/README.md
> +# YOLOv5 C++部署示例
名字修改，下面全局搜下，统一FastestDet

2022-12-07 08:32 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.6.0.tgz
修改版本号，0.7.0并没有FastestDet，更改为x.x.x，然后注明：x.x.x >= 1.0.2

2022-12-07 08:32 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/README.md
> +> > * **stride**(int): 配合`stris_mini_pad`成员变量使用, 默认值为`stride=32`
确认下预处理是否是这些参数

2022-12-07 08:32 UTC, wjj19950828 commented on fastdeploy/vision.h
> -#include "fastdeploy/vision/detection/contrib/yolov7/yolov7.h"
这里为什么要修改

2022-12-07 08:32 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          pybind11::eval("raise Exception('Failed to preprocess the input data in PaddleClasPreprocessor.')");
pybind11::eval会有问题，改成throw std::runtime_error，参考YOLOv5

2022-12-07 08:32 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/README.md
> +<img width="640" src="https://user-images.githubusercontent.com/67993288/184309358-d803347a-8981-44b6-b589-4608021ad0f4.jpg">
可视化结果更新为自己的链接

2022-12-07 08:32 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in FastestDetPostprocessor.')");
同上

2022-12-07 08:32 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.h
> +  /// Set conf_threshold, default 0.25
看实现默认值为0.65

2022-12-07 08:32 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.h
> +  /// Set nms_threshold, default 0.5
看实现默认值为0.45

2022-12-07 08:32 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  /**
注释去掉

2022-12-07 08:32 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        confidence threshold for postprocessing, default is 0.25
确认下默认值

2022-12-07 08:32 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        # 调用基函数进行backend_option的初始化
中文注释全部去掉

2022-12-07 08:32 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def batch_predict(self, images):
判断下images的len，如果>1，跑出异常，提示用户仅支持bs=1

2022-12-07 11:17 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/README.md
> +# YOLOv5 C++部署示例
Done

2022-12-07 11:23 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.6.0.tgz
Done

2022-12-07 11:23 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/README.md
> +> > * **stride**(int): 配合`stris_mini_pad`成员变量使用, 默认值为`stride=32`
Done

2022-12-07 11:45 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          pybind11::eval("raise Exception('Failed to preprocess the input data in PaddleClasPreprocessor.')");
Done

2022-12-07 11:46 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in FastestDetPostprocessor.')");
Done

2022-12-07 11:47 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.h
> +  /// Set conf_threshold, default 0.25
Done

2022-12-07 11:47 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.h
> +  /// Set nms_threshold, default 0.5
Done

2022-12-07 11:50 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  /**
Done

2022-12-07 11:51 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        confidence threshold for postprocessing, default is 0.25
Done

2022-12-07 11:53 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        # 调用基函数进行backend_option的初始化
Done

2022-12-07 12:05 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def batch_predict(self, images):
Done

2022-12-07 12:15 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/README.md
> +<img width="640" src="https://user-images.githubusercontent.com/67993288/184309358-d803347a-8981-44b6-b589-4608021ad0f4.jpg">
Done

2022-12-07 12:52 UTC, GodIsBoom commented on fastdeploy/vision.h
> -#include "fastdeploy/vision/detection/contrib/yolov7/yolov7.h"
猜测是我这个分支某次拉取原仓库更新时git误操作导致，当前问题更改后放到了新PR：https://github.com/PaddlePaddle/FastDeploy/pull/826

2022-12-09 05:59 UTC, closed without merging