[Backend] Add AdaptivePool2d for TensorRT plugin
PaddlePaddle/FastDeploy pull request #668
Opened 2022-11-22 16:23 UTC by yeliang2258

### PR types(PR类型)

Backend

### Describe

Add AdaptivePool2d for TensorRT plugin

2022-11-23 05:36 UTC, jiangjiajun requested changes

2022-11-23 05:36 UTC, jiangjiajun commented on fastdeploy/backends/tensorrt/ops/adaptivepool2d.cu
> +  if(is_avg){
有一些代码风格现在不知道为啥ci检查不到，本地使用clang-format或vscode格式化一下试试

2022-11-25 01:08 UTC, jiangjiajun requested changes

2022-11-25 01:08 UTC, jiangjiajun commented on fastdeploy/backends/op_cuda_kernels/adaptive_pool2d.cu
> +#include "fastdeploy/backends/tensorrt/ops/adaptive_pool2d.h"
这个代码还会依赖ort backend吗？ 如果编译时不包含ort backend是否会出错？

2022-11-25 02:33 UTC, yeliang2258 commented on fastdeploy/backends/op_cuda_kernels/adaptive_pool2d.cu
> +#include "fastdeploy/backends/tensorrt/ops/adaptive_pool2d.h"
已经修复，验证编译都没问题

2022-11-25 09:36 UTC, jiangjiajun approved these changes

2022-11-25 09:36 UTC, merged