[Backend] Add Ascend NPU deploy support through PaddleLite CANN
PaddlePaddle/FastDeploy pull request #683
Opened 2022-11-23 13:17 UTC by yunyaoXYY

1.添加华为昇腾NPU的部署支持.
2.完成分类模型的demo.(测过ResNet50和MobileNetV2)
3.完成相关文档.
4.完成paddledetection（PPYOLOE)/ YOLOv5/v6/v7的支持
5.添加PaddleSeg/ PPOCRv3的支持

2022-11-24 06:46 UTC, yeliang2258 requested changes

2022-11-24 06:46 UTC, yeliang2258 commented on fastdeploy/backends/lite/lite_backend.cc
> +  }else if(option_.enable_cann){
注意格式

2022-11-24 07:01 UTC, yunyaoXYY commented on fastdeploy/backends/lite/lite_backend.cc
> +  }else if(option_.enable_cann){
Done

2022-11-24 08:28 UTC, yeliang2258 approved these changes
LGTM

2022-11-25 01:32 UTC, jiangjiajun requested changes

2022-11-25 01:32 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/ascend/cpp/CMakeLists.txt
> +option(FASTDEPLOY_INSTALL_DIR "./fastdeploy-cann/")
CANN需要交叉编译吗？是否需要运行时将这些库都拷贝到目录，还是复用cpu/gpu上部署的现有方式？

2022-11-25 02:37 UTC, yunyaoXYY commented on examples/vision/classification/paddleclas/ascend/cpp/CMakeLists.txt
> +option(FASTDEPLOY_INSTALL_DIR "./fastdeploy-cann/")
1.目前我用的机器是arm64+NPU，不需要交叉编译.  如果有用户是X86+NPU的话，需要交叉编译. 也就是说，目前FD中，在编译时下载的CANN的包, 只支持arm64+NPU.  X86+NPU的还不支持. 

2.找叶梁确认了一下他之前copy的目的.  昇腾上的部署，可以不需要拷贝，按照原有的编译和部署方式就OK, 这个接下来我再改一下

2022-11-25 02:38 UTC, yunyaoXYY commented on examples/vision/classification/paddleclas/ascend/cpp/CMakeLists.txt
> +option(FASTDEPLOY_INSTALL_DIR "./fastdeploy-cann/")
> CANN需要交叉编译吗？是否需要运行时将这些库都拷贝到目录，还是复用cpu/gpu上部署的现有方式？

1.目前我用的机器是arm64+NPU，不需要交叉编译. 如果有用户是X86+NPU的话，需要交叉编译. 也就是说，目前FD中，在编译时下载的CANN的包, 只支持arm64+NPU. X86+NPU的还不支持.

2.找叶梁确认了一下他之前copy的目的. 昇腾上的部署，可以不需要拷贝，按照原有的编译和部署方式就OK, 这个接下来我再改一下

2022-11-25 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=683) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=683) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yunyaoXYY<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=683) it.</sub>

2022-11-30 07:18 UTC, closed without merging