[Functions] Add quantile function
PaddlePaddle/FastDeploy pull request #700
Opened 2022-11-25 03:32 UTC by joey12300

### PR types(PR类型)

Functions
### Describe

Add fdtensor function:

- quantile
- sort & argsort

2022-11-27 06:10 UTC, jiangjiajun requested changes

2022-11-27 06:10 UTC, jiangjiajun commented on fastdeploy/core/fd_tensor.cc
> +template FDTensor::FDTensor(const double&);
这些函数的用法注释说明一下。 另外针对低于4节点的变量无需使用`const T&`，直接使用func(T value)即可。 引用这个类型本身就占4个字节

2022-11-27 10:35 UTC, joey12300 commented on fastdeploy/core/fd_tensor.cc
> +template FDTensor::FDTensor(const double&);
这些函数主要是为了将一个标量转化为FDTensor。例如`FDTensor tensor(1.0);`,将1这个值转换成一个FDTensor。目前已经添加了`Scalar`结构体，用来存储标量，并且添加了一个`FDTensor(const Scalar&)`函数，用以替换这几个函数

2022-11-28 01:51 UTC, jiangjiajun approved these changes

2022-11-28 01:51 UTC, merged