[Serving][Backend] Backend support zero_copy_infer and Serving reduce the output memory copy
PaddlePaddle/FastDeploy pull request #703
Opened 2022-11-25 07:32 UTC by heliqi

### PR types(PR类型)
Serving
Backend

### Describe
Backend support zero_copy_infer and Serving reduce the output memory copy

2022-11-25 07:41 UTC, heliqi commented
<img width="776" alt="image" src="https://user-images.githubusercontent.com/34152981/203926905-c3d9b459-6a5a-4938-b06b-2f3a009c26ea.png">
在模型输出较大时，加速效果明显。

2022-11-25 09:49 UTC, jiangjiajun requested changes

2022-11-25 09:49 UTC, jiangjiajun commented on fastdeploy/backends/backend.h
> +  /// else share memory to FDTensor(only Paddle、ORT、TRT、OpenVINO support it)
取消

2022-11-25 09:49 UTC, jiangjiajun commented on fastdeploy/backends/ort/ort_backend.cc
> +void OrtBackend::OrtVlaueToFDTensor(const Ort::Value& value, FDTensor* tensor,
OrtValue

2022-11-25 09:49 UTC, jiangjiajun commented on fastdeploy/backends/paddle/util.cc
> +    fd_tensor->SetExternalData(
确认下IPU逻辑

2022-11-25 09:49 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +FDTensor* Runtime::GetOutputTensor(std::string name) {
const std::string&

2022-11-25 09:49 UTC, jiangjiajun commented on fastdeploy/runtime.h
> +  /** \brief Get output FDTensor by name
也得说明share

2022-11-25 10:06 UTC, heliqi commented on fastdeploy/backends/backend.h
> +  /// else share memory to FDTensor(only Paddle、ORT、TRT、OpenVINO support it)
done

2022-11-25 10:07 UTC, heliqi commented on fastdeploy/backends/ort/ort_backend.cc
> +void OrtBackend::OrtVlaueToFDTensor(const Ort::Value& value, FDTensor* tensor,
done

2022-11-25 10:12 UTC, heliqi commented on fastdeploy/backends/paddle/util.cc
> +    fd_tensor->SetExternalData(
done

2022-11-25 10:13 UTC, heliqi commented on fastdeploy/runtime.cc
> +FDTensor* Runtime::GetOutputTensor(std::string name) {
done

2022-11-25 10:13 UTC, heliqi commented on fastdeploy/runtime.h
> +  /** \brief Get output FDTensor by name
done

2022-11-25 10:27 UTC, jiangjiajun approved these changes

2022-11-25 12:35 UTC, wjj19950828 commented on fastdeploy/backends/backend.h
> +                     bool copy_to_fd = true) = 0;
这个改成```is_zero_copy```是不是更合理点，```copy_to_fd```总感觉怪怪的

2022-11-25 12:35 UTC, wjj19950828 commented on fastdeploy/runtime.cc
> +void Runtime::BindInputTensor(const std::string& name, FDTensor& input) {
从FDModel层面考虑有必要再穿入一个name吗，在model.infer之前，FDTensor的name一定会赋值，如下

```c++
reused_input_tensors_[0].name = InputInfoOfRuntime(0).name;
```

2022-11-25 12:35 UTC, wjj19950828 commented on fastdeploy/runtime.cc
> +    input_tensors_.emplace_back(std::move(new_tensor));
FDTensor有自己定义的移动构造函数，是不是直接这么写就行？

```c++
input_tensors_.emplace_back(std::move(input));
```

2022-11-28 02:48 UTC, heliqi commented on fastdeploy/runtime.cc
> +    input_tensors_.emplace_back(std::move(new_tensor));
不行，直接move  input都不是一个功能。用户绑定完input后，传入的input被你直接清空了

2022-11-28 02:48 UTC, heliqi commented on fastdeploy/runtime.cc
> +void Runtime::BindInputTensor(const std::string& name, FDTensor& input) {
这里佳军说接口要跟onnxruntime的bind接口对齐，就多传入了name

2022-11-28 02:52 UTC, heliqi commented on fastdeploy/backends/backend.h
> +                     bool copy_to_fd = true) = 0;
之前也想用zero_copy，但是我们的输入都是zero_copy的。如果zero_copy=false，我们还是有个0拷贝的操作

2022-11-28 06:07 UTC, jiangjiajun approved these changes

2022-11-28 06:07 UTC, merged