Add RKYOLOv5 RKYOLOX RKYOLOV7
PaddlePaddle/FastDeploy pull request #709
Opened 2022-11-26 08:41 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Describe

新增rkyolov5,rkyolox,rkyolov7

2022-11-26 08:44 UTC, Zheng-Bicheng commented
* FDTensor 新增zp scale 用于全量化
* rknpu2_backend 支持全量化
* 新增RKYOLO，支持YOLOV5,YOLOV7,YOLOX

2022-12-01 07:23 UTC, Zheng-Bicheng commented
新代码做出如下改变:

* 量化参数变量合并为std::pair<int32_t, std::vector<float>> quantized_parameter_
* 提供SetQuantizationInfo(int32_t &zero_point, std::vector<float> &scale)接口和const std::pair<int32_t, std::vector<float>> GetQuantizationInfo() const接口
* RKYOLO修复置信度设置失败的bug

2022-12-04 05:28 UTC, Zheng-Bicheng commented
新增RKYOLOV5 cpp + python example

2022-12-05 02:27 UTC, jiangjiajun requested changes

2022-12-05 02:27 UTC, jiangjiajun commented on fastdeploy/core/fd_tensor.h
> +  void SetQuantizationInfo(int32_t &zero_point, std::vector<float> &scale);
`const std::vector<float>& scale` 指针符号靠左对齐。  字节数低于4字节的，无需传引用，改为
```
void SetQuantizationInfo(int32_t zero_point, const std::vector<float>& scale);
```

2022-12-05 02:27 UTC, jiangjiajun commented on fastdeploy/vision/detection/contrib/rknpu2/rkyolo.h
> +  virtual bool Predict(cv::Mat* im, DetectionResult* result,
原本的YOLOv5，因为有历史遗留问题，所以兼容这个老接口。新实现的模型无需再加这个。 下面的两个接口即可

2022-12-09 09:58 UTC, jiangjiajun approved these changes

2022-12-10 07:44 UTC, merged