[Backend] Add XPU deploy support
PaddlePaddle/FastDeploy pull request #747
Opened 2022-11-29 14:06 UTC by yeliang2258

### PR types(PR类型)

Backend

### Describe

1. Add XPU deploy support
2. Add paddleclas support
3. Add Yolov5 support

2022-11-29 14:32 UTC, ZeyuChen reviewed
中文文档前XPU加上昆仑芯三个字

2022-11-29 14:32 UTC, ZeyuChen commented on CMakeLists.txt
> +option(ENABLE_XPU "Whether to compile for XPU deploy." OFF)
KunlunXin XPU 加上KunlunXin 这个关键字

2022-11-29 14:32 UTC, ZeyuChen commented on CMakeLists.txt
> +option(ENABLE_XPU "Whether to compile for XPU deploy." OFF)
helper文字里面加即可

2022-11-29 14:32 UTC, ZeyuChen commented on docs/cn/build_and_install/README.md
>  - [瑞芯微RK1126部署环境](rk1126.md)
昆仑芯XPU

2022-11-29 14:32 UTC, ZeyuChen commented on docs/cn/build_and_install/README.md
>  - [瑞芯微RK1126部署环境](rk1126.md)
所有XPU文档文字前面加上昆仑芯三个字

2022-11-29 14:32 UTC, ZeyuChen commented on docs/cn/build_and_install/README.md
> +| ENABLE_XPU              | 默认OFF，当在XPU上部署时，需设置为ON                                                     |
昆仑芯

2022-11-29 14:32 UTC, ZeyuChen commented on docs/cn/build_and_install/xpu.md
> +# XPU 部署环境编译安装
昆仑芯XPU

2022-11-30 02:28 UTC, jiangjiajun requested changes

2022-11-30 02:28 UTC, jiangjiajun commented on cmake/xpu.cmake
> +        message(WARNING "While compiling with -DWITH_XPU=ON, will force to set -DENABLE_LITE_BACKEND=ON")
这个xpu.cmake与timvx.cmake，以及昇腾的pu.cmake，几乎是一样的。 把这几个cmake文件统一成 nnadapter.cmake吧

2022-11-30 02:28 UTC, jiangjiajun commented on CMakeLists.txt
> +option(ENABLE_XPU "Whether to compile for KunlunXin XPU deploy." OFF)
此前GPU, IPU，都是WITH_XX，咱们也全部统一下。把跟硬件相关的，全改成WITH_XXX， 这里改成WITH_XPU，上面的ENABLE_TIMVX也全局grep一下，替换为WITH_TIMVX

2022-11-30 02:28 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/xpu/README.md
> +在昆仑芯 XPU 上目前支持 C++ 的部署。
不能支持python吗？

2022-11-30 02:28 UTC, jiangjiajun commented on docs/cn/build_and_install/xpu.md
> +      -Wno-dev ..
-Wno-dev为啥需要添加？

2022-11-30 02:28 UTC, jiangjiajun commented on docs/cn/build_and_install/xpu.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=./../cmake/xpu.cmake \
确认是否需要CMAKE_TOOLCHAIN_FILE

2022-11-30 02:28 UTC, jiangjiajun commented on cmake/xpu.cmake
> +    set(TARGET_ABI amd64)
确认下这里的这段设置是否有必要

2022-11-30 02:28 UTC, jiangjiajun commented on fastdeploy/backends/lite/lite_backend.cc
> +        FDINFO << "Your device is supported fp16 ! Lite::Backend will "
FDINFO << "The device supports FP16,  Lite::Backend will inference with FP16 precision." << std::endl;

2022-11-30 02:28 UTC, jiangjiajun commented on fastdeploy/backends/lite/lite_backend.cc
> +      }
FDWARNING << "The device doesn't support FP16, will fallback to FP32." << std::endl;

2022-11-30 02:28 UTC, jiangjiajun commented on fastdeploy/runtime.cc
>    UseLiteBackend();
应该不需要显示调用UseLiteBackend()， 当指定为TIMVX或XPU时，会自动去valid_xpu_backend查找backend

2022-11-30 09:08 UTC, yeliang2258 commented on cmake/xpu.cmake
> +    set(TARGET_ABI amd64)
要用来区分amd64和aarch64

2022-12-05 03:05 UTC, jiangjiajun requested changes

2022-12-05 03:05 UTC, jiangjiajun commented on cmake/paddlelite.cmake
> +    set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_1129.tgz")
这里的判断条件，以及包名，没有体现对应的硬件信息。 给未来的维护带来很大风险，改为 elseif(WITH_TIMVX) elseif(WITH_XPU)类似的形式。

包名，则要对应改为 lite-linux-armhf-timvx-20220920形式

2022-12-05 03:05 UTC, jiangjiajun commented on CMakeLists.txt
> +      set(TARGET_ABI amd64)
这里确认一下TARGET_ABI的作用，如无需要，也无需这个警告和默认设置

2022-12-05 03:05 UTC, jiangjiajun commented on examples/vision/detection/yolov5/python/infer.py
> +    model = fd.vision.detection.YOLOv5(model, runtime_option=runtime_option)
这里的demo，不需要写if else， 理论上所有的配置选项都已经在runtime_option中配置好了，无需再添加判断

2022-12-05 03:05 UTC, jiangjiajun commented on examples/vision/detection/yolov5/xpu/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im, res);
改用`fastdeploy::vision::VisDetection`

2022-12-05 08:47 UTC, jiangjiajun commented
增加TIMVX的英文文档

2022-12-05 09:23 UTC, yeliang2258 commented on cmake/paddlelite.cmake
> +    set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_1129.tgz")
Done

2022-12-15 07:54 UTC, jiangjiajun requested changes

2022-12-15 07:54 UTC, jiangjiajun commented on CMakeLists.txt
> +  if(NOT ${ENABLE_LITE_BACKEND})
这个if条件后面的字符串，需要加${}吗，看其它cmake条件都没这个

2022-12-15 07:54 UTC, jiangjiajun commented on CMakeLists.txt
> +  endif()
添加一个对系统平台的判断
```
if (not linux or platform == x64) 
   message(FATAL_ERROR "XPU is only supported on Linux x64 platform") 
endif()
```

2022-12-15 07:54 UTC, jiangjiajun commented on FastDeploy.cmake.in
> +endif()
XPU在C++部署时，不需要额外链接xpu的动态库吗？

2022-12-15 07:54 UTC, jiangjiajun commented on docs/cn/build_and_install/xpu.md
> +## 基于 PaddleLite 的 C++ FastDeploy 库编译
这里先前改动了CPU/GPU在Linux下的编译方式，优先推荐用户apt-get install opencv，这里编译文档也跟cpu/gpu同步下

2022-12-15 07:54 UTC, jiangjiajun commented on examples/vision/detection/yolov5/cpp/infer.cc
> +void CpuInfer(const std::string& model_dir, const std::string& image_file) {
这个代码改完后，变成只支持Paddle格式了，原本的ONNX格式没支持了。

改成在这个目录下新增一个infer_paddle_model.cc吧

2022-12-15 07:54 UTC, jiangjiajun commented on examples/vision/detection/yolov5/python/README.md
> +wget https://bj.bcebos.com/paddlehub/fastdeploy/yolov5s_infer.tar
同C++, 增加infer_paddle_model.cc 。 然后文档简单说明下这个目录中`infer.cc`和`infer_paddle_model.cc`的差别

2022-12-15 08:14 UTC, yeliang2258 commented on FastDeploy.cmake.in
> +endif()
链接到Lite里面了，这里就不需要了

2022-12-15 13:17 UTC, jiangjiajun approved these changes

2022-12-15 13:17 UTC, merged