[Backend] Add Huawei Ascend NPU deploy using PaddleLite CANN.
PaddlePaddle/FastDeploy pull request #757
Opened 2022-11-30 08:11 UTC by yunyaoXYY

1.添加华为昇腾NPU的部署支持.
2.添加分类模型example.

2022-12-01 13:18 UTC, jiangjiajun requested changes

2022-12-01 13:18 UTC, jiangjiajun commented on cmake/cann.cmake
> +if (NOT DEFINED TARGET_ABI)
这个文件不需要。

如果NPU是一台Linux x64系统，理论上下面禁用的任何后端都不需要（机器可能同时有各种硬件），也无需设置TARGET_ABI等交叉编译的参数

2022-12-01 13:18 UTC, jiangjiajun commented on cmake/paddlelite.cmake
> +      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_1121.tgz")
CANN是只有aarch64吗

2022-12-01 13:18 UTC, jiangjiajun commented on docs/cn/build_and_install/huawei_ascend.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=./../cmake/cann.cmake \
不是交叉编译，也无需设置 -DCMAKE_TOOLCHAIN_FILE

2022-12-01 13:18 UTC, jiangjiajun commented on docs/cn/build_and_install/huawei_ascend.md
> +      -Wno-dev ..
这行-Wno-dev为啥要添加

2022-12-01 13:18 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/ascend/cpp/infer.cc
> +    std::cout << "Usage: infer_demo path/to/quant_model "
这里这个quant_model?

2022-12-01 13:18 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/ascend/cpp/run.sh
> +export ASCEND_GLOBAL_LOG_LEVEL=3
这个run.sh是一定需要的吗？ 他能像cpu/gpu那样来用吗？

2022-12-01 13:18 UTC, jiangjiajun commented on fastdeploy/backends/lite/lite_backend.h
> +  std::string nnadapter_mixed_precision_quantization_config_buffer = "";
为啥新增了这么多参数

2022-12-01 13:18 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +  UseLiteBackend();
这行UseLiteBackend()无需手动调用

2022-12-01 13:18 UTC, jiangjiajun commented on fastdeploy/runtime.cc
> +  UseLiteBackend();
话说为啥额外增加enable_cann这个参数，而不是直接使用device，我看gpu，也没有use_gpu这个参数

2022-12-05 04:55 UTC, yunyaoXYY commented on cmake/cann.cmake
> +if (NOT DEFINED TARGET_ABI)
已删除

2022-12-05 04:55 UTC, yunyaoXYY commented on cmake/paddlelite.cmake
> +      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_1121.tgz")
还有X86_64的, 后面会加上

2022-12-05 04:57 UTC, yunyaoXYY commented on docs/cn/build_and_install/huawei_ascend.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=./../cmake/cann.cmake \
已改

2022-12-05 04:58 UTC, yunyaoXYY commented on docs/cn/build_and_install/huawei_ascend.md
> +      -Wno-dev ..
已改

2022-12-05 04:58 UTC, yunyaoXYY commented on examples/vision/classification/paddleclas/ascend/cpp/infer.cc
> +    std::cout << "Usage: infer_demo path/to/quant_model "
已改

2022-12-05 05:00 UTC, yunyaoXYY commented on examples/vision/classification/paddleclas/ascend/cpp/run.sh
> +export ASCEND_GLOBAL_LOG_LEVEL=3
问了檀越，说跑C++的demo确实需要这样export一下, 他们目前的demo也是需要这样export.
除开export，run.sh里的运行demo命令已改成 ./build/infer_demo ResNet50_vd_infer ILSVRC2012_val_00000010.jpeg 这样

2022-12-05 05:02 UTC, yunyaoXYY commented on fastdeploy/backends/lite/lite_backend.h
> +  std::string nnadapter_mixed_precision_quantization_config_buffer = "";
供用户使用的nnadapter接口

2022-12-05 05:09 UTC, yunyaoXYY commented on fastdeploy/runtime.cc
> +  UseLiteBackend();
> enable_cann

这个的目的是在lite_backend.cc 做一个判断，看lite支持的多个硬件中，具体使用的是哪个硬件, 然后再进行相关设置.

2022-12-07 05:37 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/ascend/cpp/run.sh
> +export ASCEND_GLOBAL_LOG_LEVEL=3
这个export干啥的，需要搞清楚。如果之后用户忘了export，会出什么错

2022-12-08 08:07 UTC, shentanyue commented on fastdeploy/backends/lite/lite_backend.h
> +  std::string nnadapter_subgraph_partition_config_buffer = "";
这些参数都需要在lite_backend.cc里去设置，
如subgraph_partition_config：
  if (!option_.nnadapter_subgraph_partition_config_path.empty()) {
....
}

2022-12-08 08:10 UTC, shentanyue commented on cmake/paddlelite.cmake
> +    elseif(WITH_CANN_PY)
建议宏改名为WITH_PYTHON或ENABLE_CANN_PYTHON
然后逻辑为：
 if(WITH_CANN)
     if(ENABLE_CANN_PYTHON) 
         set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_python_1207.tgz")
     else()
      set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/test/lite-linux_arm64_huawei_ascend_npu_1121.tgz")
     endif()
endif()

2022-12-08 08:12 UTC, shentanyue commented on examples/vision/classification/paddleclas/ascend/cpp/run.sh
> +export ASCEND_GLOBAL_LOG_LEVEL=3
这些环境变量是昇腾官方提供的，需要显式export，用于调用Ascend硬件能力，如果不export，调用Ascend CANN会挂掉。

2022-12-20 04:43 UTC, jiangjiajun requested changes

2022-12-20 04:43 UTC, jiangjiajun commented on CMakeLists.txt
> +option(WITH_ASCEND_PYTHON "Whether to compile for Huawei Ascend deploy using python." OFF)
这个开关应该没必要增加

if (WITH_ASCEND && BUILD_FASTDEPLOY_PYTHON)就可以完成这个开关的判断

2022-12-20 04:43 UTC, jiangjiajun commented on CMakeLists.txt
> +if (WITH_ASCEND)
把这部分新增的逻辑移到cmake/ascend.cmake里面，避免主CMakeList后面越来越长

2022-12-20 04:43 UTC, jiangjiajun commented on cmake/summary.cmake
> +  message(STATUS "  WITH_ASCEND_PYTHON              : ${WITH_ASCEND_PYTHON}")
同上

2022-12-20 04:43 UTC, jiangjiajun commented on docs/cn/build_and_install/README.md
> +| WITH_ASCEND_PYTHON      | 默认OFF，当在华为昇腾NPU上,并使用Python部署时, 需要设置为ON                                  |
同上

2022-12-20 04:43 UTC, jiangjiajun commented on docs/cn/build_and_install/huawei_ascend.md
> +export WITH_ASCEND_PYTHON=ON
同上

2022-12-20 04:43 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/ascend/README.md
> +- [Python部署](./python)
这个看xpu是直接跟原本的cpp/python放在一起的，npu是不是也可以一样处理

2022-12-20 04:43 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/dbdetector.cc
> +
这里看起来是debug的代码

2022-12-20 04:43 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +#if defined(WITH_ASCEND) || defined(WITH_ASCEND_PYTHON)
不要这样在模型里面判断，而是改为开发者主动通过前后处理的参数去配置。因为固定Shape的用处可能不止是NPU一个

2022-12-20 04:43 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/recognizer.cc
> +  }
debug日志

2022-12-20 04:43 UTC, jiangjiajun commented on python/setup.py
> +setup_configs["WITH_ASCEND_PYTHON"] = os.getenv("WITH_ASCEND_PYTHON", "OFF")
同上

2022-12-20 11:00 UTC, yunyaoXYY commented on CMakeLists.txt
> +option(WITH_ASCEND_PYTHON "Whether to compile for Huawei Ascend deploy using python." OFF)
Done

2022-12-20 11:00 UTC, yunyaoXYY commented on CMakeLists.txt
> +if (WITH_ASCEND)
Done

2022-12-20 11:00 UTC, yunyaoXYY commented on cmake/summary.cmake
> +  message(STATUS "  WITH_ASCEND_PYTHON              : ${WITH_ASCEND_PYTHON}")
Done

2022-12-20 11:01 UTC, yunyaoXYY commented on docs/cn/build_and_install/README.md
> +| WITH_ASCEND_PYTHON      | 默认OFF，当在华为昇腾NPU上,并使用Python部署时, 需要设置为ON                                  |
Done

2022-12-20 11:01 UTC, yunyaoXYY commented on docs/cn/build_and_install/huawei_ascend.md
> +export WITH_ASCEND_PYTHON=ON
Done

2022-12-20 11:03 UTC, yunyaoXYY commented on examples/vision/classification/paddleclas/ascend/README.md
> +- [Python部署](./python)
Python的我觉得可以.  
C++的主要离不开 run.sh里面的一些export， 放一起的话，需要单独新增一个给昇腾跑的run.sh,  会不会有点多余

2022-12-20 11:03 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/dbdetector.cc
> +
已删

2022-12-20 11:05 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/rec_preprocessor.cc
> +#if defined(WITH_ASCEND) || defined(WITH_ASCEND_PYTHON)
修改后. C++的demo里，用户通过 rec_model.preprocessor_.static_shape_ = true; 开启静态shape推理
Python里 ，通过 rec_model.preprocessor.static_shape = True 开启静态shape推理

2022-12-20 11:05 UTC, yunyaoXYY commented on fastdeploy/vision/ocr/ppocr/recognizer.cc
> +  }
已删

2022-12-20 11:05 UTC, yunyaoXYY commented on python/setup.py
> +setup_configs["WITH_ASCEND_PYTHON"] = os.getenv("WITH_ASCEND_PYTHON", "OFF")
Done

2022-12-20 12:01 UTC, yunyaoXYY commented on fastdeploy/backends/lite/lite_backend.h
> +  std::string nnadapter_subgraph_partition_config_buffer = "";
已加

2022-12-25 08:32 UTC, jiangjiajun approved these changes

2022-12-25 08:32 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/ascend/cpp/run.sh
> +HUAWEI_ASCEND_TOOLKIT_HOME="/usr/local/Ascend/ascend-toolkit/latest"
```
export HUAWEI_ASCEND_TOOLKIT_HOME=/newpath/
export HUAWEI_DRIVER_PATH=/asdfas/

source /path/to/fastdeploy_sdk/fastdeploy_init.sh
```

2022-12-25 08:33 UTC, jiangjiajun commented
@yunyaoXYY 需要解决一下英文文档冲突

2022-12-25 13:40 UTC, yunyaoXYY commented
> @yunyaoXYY 需要解决一下英文文档冲突

Done

2022-12-25 13:41 UTC, yunyaoXYY commented on examples/vision/classification/paddleclas/ascend/cpp/run.sh
> +HUAWEI_ASCEND_TOOLKIT_HOME="/usr/local/Ascend/ascend-toolkit/latest"
Done.

2022-12-26 02:18 UTC, merged