[Bug Fix] add ocr new feature and fix codestyle
PaddlePaddle/FastDeploy pull request #764
Opened 2022-11-30 16:05 UTC by HexToString

### PR types(PR类型)

Bug Fix
### Describe

1、逐层增加了新的接口，允许用户设置cls_batch_size 和 rec_batch_size，但只在OCR类中暴露设置，pybind也只在ocr中。
2、增加新的pybind接口，允许用户直接单独调用det、cls、rec，且允许用户访问和修改属性。
3、修复了遗留的codestyle，以及冗余代码问题。
4、增加了单元测试。
5、修改了Serving示例中的config，默认使用paddle

2022-12-01 13:08 UTC, jiangjiajun reviewed
增加单测，测试需要覆盖到以下case

测试包括PPOCR-v2 & PPOCR-v3
- for循环以下流程2次
- - 读入第一张图，采用默认OCR串联识别，结果符合预期
- - 读入第二张图，采用默认OCR串联识别，并将cls_batch_size设为2， rec_batch_size设为2，结果符合预期

- 增加无cls模型的单测
- - 读入第一张图，采用默认OCR串联识别，结果符合预期
- - 读入第二张图，采用默认OCR串联识别，并将rec_batch_size设为2，结果符合预期

2022-12-01 13:08 UTC, jiangjiajun commented on examples/vision/ocr/PP-OCRv3/serving/models/cls_runtime/config.pbtxt
> +        parameters { key: "use_mkldnn" value: "0" }
use_mkldnn默认打开1效果更好？

2022-12-01 13:08 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_postprocessor.cc
> +    FDERROR << "index error." << std::endl;
错误提示一版给详细一些，避免出错时，看到错误信息不全，又得重新查。

改成
```
FDERROR << "Index error, require start_index < 0 or (start_index + batch) > total_size), but now the start_index=" << start_index << ", batch=" << batch << ", total_size=" << total_size << "." << std::endl;
```

2022-12-01 13:08 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
>      FDERROR << "The size of input images should be greater than 0." << std::endl;
同上，拆成三个if来判断，并给出详细的出错信息

2022-12-01 13:08 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/cls_preprocessor.cc
> +  size_t tensor_size = end_index-start_index;
-号前后空格

2022-12-01 13:08 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/rec_postprocessor.cc
> +    FDERROR << "index error." << std::endl;
同上，提示信息不全

2022-12-01 13:08 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/recognizer.h
> +  virtual bool Predict(cv::Mat* img, std::string* text, float* rec_score);
Classifier，Detector， Recgnizer，增加的Predict，都改为
```
virtual bool Predict(const cv::Mat& img, std::string* text, float* rec_score);
```
这种，之前有遗留问题，所以存在传指针现象。其实这个img是只读的

2022-12-01 14:14 UTC, HexToString commented on fastdeploy/vision/ocr/ppocr/recognizer.h
> +  virtual bool Predict(cv::Mat* img, std::string* text, float* rec_score);
ok

2022-12-07 11:31 UTC, jiangjiajun requested changes
遗留的问题要解决

2022-12-07 11:31 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.cc
> +bool Classifier::Predict(cv::Mat& img, int32_t* cls_label, float* cls_score) {
这个接口应该是const cv::Mat&

2022-12-07 11:31 UTC, jiangjiajun commented on fastdeploy/vision/ocr/ppocr/classifier.h
>    /** \brief BatchPredict the input image and get OCR classification model cls_result.
同上

2022-12-07 11:31 UTC, merged