[Other] Add Model Clone function for PaddleClas && PaddleDet && PaddleSeg
PaddlePaddle/FastDeploy pull request #791
Opened 2022-12-04 17:43 UTC by felixhjh

### PR types(PR类型)

Other
### Describe

> Multiple PaddleClas NO Clone Example:
> 
> ```
> auto model = fastdeploy::vision::classification::PaddleClasModel(model_file, params_file, config_file, option);
> 
> auto model2 = fastdeploy::vision::classification::PaddleClasModel( model_file, params_file, config_file, option);
> 
> ```
> 
> Multiple PaddleClas Clone Example:
> 
> ```
> auto model = fastdeploy::vision::classification::PaddleClasModel(model_file, params_file, config_file, option);
> 
>auto model2 = model.Clone();
> ```

> PaddleClas	Clone模式	不Clone模式
> 1	322M	322M
> 2	322M	549M
> 3	322M	744M

2022-12-05 01:57 UTC, jiangjiajun commented
这里说明的内存的变化，是在什么后端，什么硬件上的信息

2022-12-05 07:24 UTC, felixhjh commented
> 这里说明的内存的变化，是在什么后端，什么硬件上的信息

done

2022-12-06 02:09 UTC, jiangjiajun requested changes
增加FastDeploy/tutorials目录，在里面增加 multi_threads目录，在里面增加README.md， 说明
- 多线程的实现方式
- clone的原理，支持哪些后端
- 通过clone后的实验数据对比（最好是包含CPU/GPU）

2022-12-06 02:09 UTC, jiangjiajun commented on fastdeploy/fastdeploy_model.h
> +    FDERROR << "Clone no support" << std::endl;
改为
```
FDERROR << ModelName() << " doesn't support Cone() now." << std::endl;
```

2022-12-12 03:39 UTC, jiangjiajun commented
@felixhjh Tutorials目录缺少一个README.md说明multithread的用法，效果，以及支持的模型列表

2022-12-13 07:19 UTC, jiangjiajun approved these changes

2022-12-13 07:19 UTC, merged