[Backend] A311D support
PaddlePaddle/FastDeploy pull request #825
Opened 2022-12-07 12:31 UTC by yeliang2258

### PR types(PR类型)

Backend

### Description

A311D support
ResNet50 
MobileNet
PP-YOLOE 
YOLOv5 
PP-LiteSeg

2022-12-07 12:36 UTC, yeliang2258 commented
英文文档：https://github.com/PaddlePaddle/FastDeploy/pull/747

2022-12-11 09:09 UTC, jiangjiajun requested changes

2022-12-11 09:09 UTC, jiangjiajun commented on cmake/opencv.cmake
> +        set(OPENCV_FILENAME "opencv-linux-aarch64-A311D-npu")
这个opencv，跟普通opencv-linux-aarch64的opencv有啥差别

2022-12-11 09:09 UTC, jiangjiajun commented on cmake/opencv.cmake
> +    if(NOT OPENCV_FILENAME)
这个逻辑看起来只是对aarch64生效，改成 if(NOT OPENCV_URL)这种形式，不局限于哪个平台

2022-12-11 09:09 UTC, jiangjiajun commented on cmake/paddlelite.cmake
> +      message(FATAL_ERROR "Only support Linux aarch64 now, x64 is not supported with backend Paddle Lite.")
这里同上， 让PADDLE_LITE_URL这种形式，在所有平台都生效

2022-12-12 11:40 UTC, jiangjiajun requested changes

2022-12-12 11:40 UTC, jiangjiajun commented on cmake/toolchain.cmake
> +        set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux_armhf_1130.tgz")
包的命名保持固定的规律
这里是
```
https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-armhf-1130.tgz
```
下面是
```
https://bj.bcebos.com/fastdeploy/third_libs/lite_linux_timvx_armv8.tgz
```
我记得这俩都是timvx，那就分别命名为 `lite-linux-armhf-timvx-1130.tgz` 和`lite-linux-aarch64-timvx-xxxx.tgz`

2022-12-12 11:40 UTC, jiangjiajun commented on cmake/toolchain.cmake
> +        set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux_armhf_1130.tgz")
另外这里应该是
```
if(WITH_TIMVX)
  set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux_armhf_1130.tgz")
else()
  message(FATAL_ERROR "PaddleLite is only available in armhf Linux while ENABLE_TIMVX=ON.")
endif()
```

2022-12-12 11:40 UTC, jiangjiajun commented on cmake/toolchain.cmake
> +        set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite_linux_timvx_armv8.tgz")
这里跟上面一样
另外这里应该是，表明交叉编译时，如果开启了TIMVX则使用TIMVX的包，如若不然，则使用纯CPU的包
```
if (WITH_TIMVX)
  set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-aarch64-timvx-1130.tgz")
else()
  set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite-linux-aarch64-1130.tgz")
endif()
```

2022-12-13 01:56 UTC, yeliang2258 commented on cmake/toolchain.cmake
> +        set(PADDLELITE_URL "https://bj.bcebos.com/fastdeploy/third_libs/lite_linux_timvx_armv8.tgz")
这里应该不需要这个判断了，如果不指定交叉编译，就不会用到我这个cmake了

2022-12-13 02:54 UTC, jiangjiajun approved these changes

2022-12-13 03:53 UTC, merged