[Paddle Lite] Support stable-diffusion model
PaddlePaddle/FastDeploy pull request #830
Opened 2022-12-08 07:11 UTC by shentanyue

### PR types(PR类型)

Other
### Description

PaddleLite + Python 支持 stable diffusion 模型

2022-12-08 07:14 UTC, shentanyue commented on fastdeploy/backends/lite/lite_backend.cc
> +    FDASSERT(false, "[LiteBackend] Size of inputs(%d) should keep same "
FDERROR不会中断程序，导致后续会比较难定位程序出错的具体位置。
建议是FDERROR宏内部增加std::abort()，这里为了改动影响面小，我是改为FDASSERT来抛出错误，中断程序。

2022-12-08 07:15 UTC, shentanyue commented on fastdeploy/backends/lite/lite_backend.cc
> +      tensor->CopyFromCpu<float, paddle::lite_api::TargetType::kHost>(
kHost兼容ARM和X86

2022-12-08 08:32 UTC, jiangjiajun requested changes

2022-12-08 08:32 UTC, jiangjiajun commented on fastdeploy/backends/lite/lite_backend.cc
> +    FDASSERT(false, "[LiteBackend] Size of inputs(%d) should keep same "
这里目前不建议这样改，因为当前所有FD所有的后端这里都是采上return false和true来判断infer是否成功，统一了行为

如果只是为了要中断，可以在外部调用这个接口时去中断，例如
```
FDASSERT(runtime->Infer(inputs, &outputs), "Failed to Infer");
```

2022-12-08 08:32 UTC, jiangjiajun commented on fastdeploy/backends/lite/lite_backend.cc
> +      FDASSERT(false, "Cannot find input with name: %s in loaded model.", inputs[i].name);
同上

2022-12-08 08:41 UTC, shentanyue commented on fastdeploy/backends/lite/lite_backend.cc
> +    FDASSERT(false, "[LiteBackend] Size of inputs(%d) should keep same "
我看大部分fastdeploy example都是直接调用runtime->Infer(inputs, &outputs)，没有去check bool，对于串行模型的话，难感知中间是否有模型运行失败

2022-12-08 08:46 UTC, shentanyue commented on fastdeploy/backends/lite/lite_backend.cc
> +    FDASSERT(false, "[LiteBackend] Size of inputs(%d) should keep same "
我就是这里踩了定位错误的坑.....  
我先恢复原样吧，不过还是建议 FDERROR 增加个 std::abort() 来中断程序，这样可以及时发现错误。

2022-12-08 10:05 UTC, DefTruth requested changes

2022-12-08 10:05 UTC, DefTruth commented on fastdeploy/pybind/main.h
> +    return FDDataType::FP64;
这里返回的数据类型是否应该是INT8

2022-12-08 10:10 UTC, shentanyue commented on fastdeploy/pybind/main.h
> +    return FDDataType::FP64;
是的，抱歉，忘改了

2022-12-09 05:20 UTC, jiangjiajun approved these changes

2022-12-09 05:20 UTC, merged