[Model] add detection model : FastestDet
PaddlePaddle/FastDeploy pull request #842
Opened 2022-12-09 05:44 UTC by GodIsBoom

### [Model]

### Describe

add detection model : FastestDet

2022-12-14 12:27 UTC, wjj19950828 requested changes

2022-12-14 12:27 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +    int output_w = 22; // out map weight
不能写死

2022-12-14 12:27 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +        int obj_score_index = (0 * output_h * output_w) + (h * output_w) + w;
```0 * output_h * output_w```意义在哪

2022-12-14 12:27 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +    float img_height=ipt_h;
上面参数没用到都去掉

2022-12-14 12:27 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +            cy + box_height / 2.0f + category * max_wh_});
```category * max_wh_```去掉

2022-12-14 12:33 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +    int output_w = 22; // out map weight
done

2022-12-14 12:51 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +        int obj_score_index = (0 * output_h * output_w) + (h * output_w) + w;
debug过程未整理，已移除

2022-12-14 12:54 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +    float img_height=ipt_h;
done

2022-12-14 12:57 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +            cy + box_height / 2.0f + category * max_wh_});
done

2022-12-23 04:39 UTC, wjj19950828 requested changes

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/README.md
> +> > * **stride**(int): 配合`stris_mini_pad`成员变量使用, 默认值为`stride=32`
上面没有的预处理参数全部去掉

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto im_bak = im.clone();
新代码中直接用im，去掉clone

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet.cc
> +bool FastestDet::Predict(cv::Mat* im, DetectionResult* result, float conf_threshold, float nms_threshold) {
新模型无需再提供这个函数，这个函数在老模型中，为了兼容老代码，才保留。 新模型，我们只需要下面的两个Predict接口即可

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
调用新接口， 即Predict(const cv::Mat&, ...)，传引用即可，不用传指针

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res);
使用fastdeploy::vision::VisDetection

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto im_bak = im.clone();
去掉

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
同上

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res);
同上

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto im_bak = im.clone();
同上

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
同上

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res);
同上

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/python/README.md
> +> FastestDet.predict(image_data, conf_threshold=0.65, nms_iou_threshold=0.45)
使用新接口

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/python/README.md
> +> > * **nms_iou_threshold**(float): NMS处理过程中iou阈值
conf_threshold、nms_iou_threshold去掉

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/python/README.md
> +> > * **stride**(int): 配合`stris_mini_padide`成员变量使用, 默认值为`stride=32`
同上

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/python/infer.py
> +result = model.predict(im.copy())
去掉copy

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet.h
> +  virtual bool Predict(cv::Mat* im, DetectionResult* result,
同上，去掉

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          throw std::runtime_error("raise Exception('Failed to preprocess the input data in PaddleClasPreprocessor.')");
PaddleClasPreprocessor？

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in FastestDetPostprocessor.')");
pybind11::eval修改成throw std::runtime_error

2022-12-23 04:39 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        assert len(images) == 1,"FastestDet is not support batch predict"
这里提示应该为不支持图片数量>1的batch_predict

2022-12-23 04:39 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/CMakeLists.txt
> +# 指定下载解压后的fastdeploy库路径
新代码中所有中文的注释，都改为英文

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +        int class_num = 80;
改成shape[1]-5，shape纬度都不要写死

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  Convert::Run(mat, alpha, beta);
上面2和3步合成一个大OP，ConvertAndPermute

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  //FDINFO << "view preprocess output" << std::endl;
去掉

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  output->PrintInfo("output");
去掉

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.h
> +  /// Set target size, tuple of (width, height), default size = {640, 640}
默认size看代码是{352, 352}

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.h
> +  /// Get target size, tuple of (width, height), default size = {640, 640}
同上

2022-12-23 04:39 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.h
> +  // target size, tuple of (width, height), default size = {640, 640}
同上

2022-12-23 04:39 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        Argument for image preprocessing step, the preprocess image size, tuple of (width, height), default size = [640, 640]
同上

2022-12-23 04:39 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def padding_value(self):
去掉

2022-12-23 04:39 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def padding_value(self, value):
去掉

2022-12-23 04:39 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def multi_label(self):
去掉

2022-12-23 04:39 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def multi_label(self, value):
去掉

2022-12-23 04:39 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def predict(self, input_image, conf_threshold=0.65, nms_iou_threshold=0.45):
去掉，只保留两个predict接口就行

2022-12-23 07:39 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/CMakeLists.txt
> +# 指定下载解压后的fastdeploy库路径
done

2022-12-23 07:40 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/README.md
> +> > * **stride**(int): 配合`stris_mini_pad`成员变量使用, 默认值为`stride=32`
done

2022-12-23 07:54 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto im_bak = im.clone();
done

2022-12-23 07:54 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
done

2022-12-23 07:58 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res);
done

2022-12-23 08:01 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto im_bak = im.clone();
done

2022-12-23 08:01 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
done

2022-12-23 08:01 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res);
done

2022-12-23 08:01 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto im_bak = im.clone();
done

2022-12-23 08:02 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  if (!model.Predict(&im, &res)) {
done

2022-12-23 08:02 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  auto vis_im = fastdeploy::vision::Visualize::VisDetection(im_bak, res);
done

2022-12-23 08:06 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/python/README.md
> +> FastestDet.predict(image_data, conf_threshold=0.65, nms_iou_threshold=0.45)
done

2022-12-23 08:06 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/python/README.md
> +> > * **nms_iou_threshold**(float): NMS处理过程中iou阈值
done

2022-12-23 08:07 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/python/README.md
> +> > * **stride**(int): 配合`stris_mini_padide`成员变量使用, 默认值为`stride=32`
done

2022-12-23 08:07 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/python/infer.py
> +result = model.predict(im.copy())
done

2022-12-23 08:27 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet.cc
> +bool FastestDet::Predict(cv::Mat* im, DetectionResult* result, float conf_threshold, float nms_threshold) {
已移除

2022-12-23 08:28 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet.h
> +  virtual bool Predict(cv::Mat* im, DetectionResult* result,
done

2022-12-23 08:29 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          throw std::runtime_error("raise Exception('Failed to preprocess the input data in PaddleClasPreprocessor.')");
已更正

2022-12-23 08:30 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/fastestdet_pybind.cc
> +          pybind11::eval("raise Exception('Failed to postprocess the runtime result in FastestDetPostprocessor.')");
done

2022-12-23 08:31 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/postprocessor.cc
> +        int class_num = 80;
done

2022-12-23 08:39 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  Convert::Run(mat, alpha, beta);
用不到ConvertAndPermute的swap_rb功能，所以接换成这样了，感觉会容易读，可以不改吗

2022-12-23 08:40 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  //FDINFO << "view preprocess output" << std::endl;
done

2022-12-23 08:40 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  output->PrintInfo("output");
done

2022-12-23 08:41 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.h
> +  /// Set target size, tuple of (width, height), default size = {640, 640}
done

2022-12-23 08:42 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.h
> +  /// Get target size, tuple of (width, height), default size = {640, 640}
done

2022-12-23 08:42 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.h
> +  // target size, tuple of (width, height), default size = {640, 640}
done

2022-12-23 08:45 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        Argument for image preprocessing step, the preprocess image size, tuple of (width, height), default size = [640, 640]
done

2022-12-23 08:47 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def padding_value(self):
done

2022-12-23 08:47 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def padding_value(self, value):
done

2022-12-23 08:47 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def multi_label(self):
done

2022-12-23 08:47 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def multi_label(self, value):
done

2022-12-23 08:48 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def predict(self, input_image, conf_threshold=0.65, nms_iou_threshold=0.45):
done

2022-12-23 08:51 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +        assert len(images) == 1,"FastestDet is not support batch predict"
done

2022-12-27 02:40 UTC, wjj19950828 requested changes

2022-12-27 02:40 UTC, wjj19950828 commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  std::cout << "test" << std::endl;
去掉

2022-12-27 02:40 UTC, wjj19950828 commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  Convert::Run(mat, alpha, beta);
ConvertAndPermute::Run(mat, alpha, beta, false);

2022-12-27 02:40 UTC, wjj19950828 commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def predict(self, input_image, conf_threshold=0.65, nms_iou_threshold=0.45):
去错了？

2022-12-27 02:58 UTC, GodIsBoom commented on examples/vision/detection/fastestdet/cpp/infer.cc
> +  std::cout << "test" << std::endl;
done

2022-12-27 02:58 UTC, GodIsBoom commented on fastdeploy/vision/detection/contrib/fastestdet/preprocessor.cc
> +  Convert::Run(mat, alpha, beta);
done

2022-12-27 03:00 UTC, GodIsBoom commented on python/fastdeploy/vision/detection/contrib/fastestdet.py
> +    def predict(self, input_image, conf_threshold=0.65, nms_iou_threshold=0.45):
已正确去除

2022-12-27 11:03 UTC, wjj19950828 approved these changes

2022-12-28 02:49 UTC, jiangjiajun approved these changes

2022-12-28 02:49 UTC, merged