[RKNPU2] Update quantitative model
PaddlePaddle/FastDeploy pull request #879
Opened 2022-12-14 04:08 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Description
详情写在下面

2022-12-14 04:12 UTC, Zheng-Bicheng commented
# 详细更新

## backends
* 输出数据的数据类型全部改为FP32

## scrfd
* 拆分disabled_normalize_and_permute为disabled_normalize 和 disabled_permute
* 更新RKNPU2 cpp example
* 更新RKNPU2 python example
* 更新文档

## rknpu2 模型转换工具
* 修复yaml文件格式问题
* 支持导出量化模型

2022-12-14 09:24 UTC, jiangjiajun requested changes

2022-12-14 09:24 UTC, jiangjiajun commented on examples/vision/facedet/scrfd/rknpu2/README.md
> +python tools/rknpu2/export.py --config_path tools/rknpu2/config/scrfd.yaml
这里的文档写明是 /Path/To/FastDeploy_Repo/tools/rknpu2/export.py 因为直接复制这行代码应该执行不了

2022-12-14 09:24 UTC, jiangjiajun commented on examples/vision/facedet/scrfd/rknpu2/cpp/README.md
> +export LD_LIBRARY_PATH=./lib
改为
`export LD_LIBRARY_PATH=${PWD}/lib:${LD_LIBRARY_PATH}`

2022-12-14 09:24 UTC, jiangjiajun commented on examples/vision/facedet/scrfd/rknpu2/python/README.md
> +需要先调用DisablePermute(C++)或`disable_permute(Python)，在预处理阶段禁用归一化以及数据格式的转换。
这里不用DisableNormalize吗？

2022-12-14 09:24 UTC, jiangjiajun commented on python/fastdeploy/vision/facedet/contrib/scrfd.py
> +        self.disable_normalize()
趁现在代码调用还少，移除掉不维护的api，避免之后要不断兼容

2022-12-19 02:03 UTC, jiangjiajun approved these changes

2022-12-19 02:03 UTC, jiangjiajun commented
@Zheng-Bicheng 有一个文件冲突

2022-12-19 05:58 UTC, merged