[Model]重构insightface代码
PaddlePaddle/FastDeploy pull request #919
Opened 2022-12-20 06:25 UTC by Zheng-Bicheng

### PR types(PR类型)
Model

### Description
重构insightface代码

2022-12-20 06:27 UTC, Zheng-Bicheng commented
# 具体更新内容
* 改变AdaFace,ArcFace,CosFace等模型的代码为继承的形式
* 重构了insightface的代码

2022-12-20 06:28 UTC, Zheng-Bicheng commented
未完成部分:

* python 未测试

2022-12-20 07:09 UTC, DefTruth commented
@Zheng-Bicheng examples里面不同模型的infer_xxx还是需要保留的，需要对每个模型都测试一下

2022-12-22 03:45 UTC, DefTruth requested changes

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.3.0.tgz
这里不用写具体的版本号，0.3.0版本很多功能是不支持的，写 成  xxx 吧，可以参考其他例子的写法

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer.cc
> +  auto model = fastdeploy::vision::faceid::AdaFace(model_file,"");
注意代码之间的空格  
```c++
fastdeploy::vision::faceid::AdaFace(model_file,"");  
// 改成
fastdeploy::vision::faceid::AdaFace(model_file, "");  
```
其他代码格式问题，同理

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer.cc
> +                 "e.g ./infer_arcface_demo ms1mv3_arcface_r100.onnx "
这里的提示说明也改成对应的 adaface 吧，其余例子同理

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer.cc
> +                 "test_lite_focal_arcface_2.JPG 0"
这个文件名一直都感觉不太合适，这次都把这个测试图片重名一下吧，然后重新上传：  
```bash
face_0.jpg, face_1.jpg, face_2.jpg
```  
文档也同步修改一下

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/adaface/cpp/infer.cc
> +                 "test_lite_focal_arcface_2.JPG 0"
其余例子同理

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/insightface/cpp/README.md
> +cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-0.3.0
案例和文档的写法还是要参考原来的，这里的 0.3.0 的版本号不合适 ，可以改回原来的方式
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/31974251/209045414-563cc773-c626-4268-a014-f772307db805.png">

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/insightface/cpp/README.md
> +cmake .. -DFASTDEPLOY_INSTALL_DIR=${PWD}/fastdeploy-linux-x64-0.3.0
文档中关于 alpha、beta、l2_normalize的使用说明要修改成最新的从preprocess中去修改，其余同理

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/insightface/python/README.md
> +python3 infer_arcface.py --model ms1mv3_arcface_r100.onnx --face test_lite_focal_arcface_0.JPG --face_positive test_lite_focal_arcface_1.JPG --face_negative test_lite_focal_arcface_2.JPG --device cpu
修改python3 -> python

2022-12-22 03:45 UTC, DefTruth commented on examples/vision/faceid/insightface/python/README.md
> +python3 infer_arcface.py --model ms1mv3_arcface_r100.onnx --face test_lite_focal_arcface_0.JPG --face_positive test_lite_focal_arcface_1.JPG --face_negative test_lite_focal_arcface_2.JPG --device cpu
同样，python文档中关于alpha，beta、l2_normalize的使用要更新成根据Preprocessor和Postprocessor来设置

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/adaface.cc
> +                                         FaceRecognitionResult* result) {
注意下代码对齐的问题。
```c++
bool AdaFace::Predict(const cv::Mat& im,
                                         FaceRecognitionResult* result) {
}
```
改成
```c++
bool AdaFace::Predict(const cv::Mat& im, FaceRecognitionResult* result) {
}
```
其余同理，注意对齐

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/adaface.cc
> +  *result = std::move(results[0]);
这里最好加个!results.empty()的判断，否则可能会导致std::move出core，或者在BatchPredict内部内确保正常推理时results非空即可

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/adaface.h
> +   * \param[in] model_file Path of model file, e.g ./arcface.onnx
arcface -> adaface，其他函数注释同理，按照实际的类型修改为对应的文件名称

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/postprocessor.cc
> +                                              std::vector<FaceRecognitionResult>* results) {
代码对齐

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/postprocessor.cc
> +    (*results)[bs].Reserve(infer_result[0].shape[1]);
这里为啥还要调用Reserve，理论上只要调用Resize即可

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/preprocessor.cc
> +  Convert::Run(mat, alpha_, beta_);
这里可以尝试改成ConvertAndPermute来做融合操作，可以参考yolov5的实现

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/preprocessor.cc
> +  output->shape.insert(output->shape.begin(), 1);  // reshape to n, h, w, c
改成使用新API  
```c++
output->ExpandDim(0);
```

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/preprocessor.cc
> +  outputs->resize(1);
这里的逻辑是否确认过？outputs resize为1，但是处理的可能是一个batch的图片，逻辑上是否要改成支持batch？现在可以先采用循环的方式。如果outputs的size一直是1，那传入多张图片后结果是否会发生错误？

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/adaface/preprocessor.cc
> +  outputs->resize(1);
如果暂时不支持batch操作的话，也先加一个assert吧：  
```c++
FDASSERT(images.size() == 1, "Only support batch = 1 now.");
```

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/insightface/base.cc
> +    valid_cpu_backends = {Backend::ORT};
这里openvino的cpu后端需要确认下，应该是能跑通的

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/insightface/postprocessor.cc
> +    (*results)[bs].Reserve(infer_result[0].shape[1]);
同上，Reserve应该可以不用？

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/insightface/preprocessor.cc
> +  Convert::Run(mat, alpha_, beta_);
同上，这里可以考虑替换成ConvertAndPermute

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/insightface/preprocessor.cc
> +  }
这里也加一个assert吧，来说明不支持batch>1

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/insightface/preprocessor.cc
> +    (*outputs)[0] = std::move(tensors[0]);
如果size!=1，是否应该return false? 对应地检查下adaface这处的逻辑

2022-12-22 03:45 UTC, DefTruth commented on fastdeploy/vision/faceid/contrib/insightface/preprocessor.h
> +  bool permute_;
文档里面这个属性还是swap_rb，我们先不删除这个属性吧，避免用户产生疑惑。

2022-12-22 03:45 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/adaface/__init__.py
> +        :return: list of ClassifyResult(If the runtime_results is predict by batched samples, the length of this list equals to the batch size)
函数说明错误：ClassifyResult -> FaceRecognitionResult，其余的都检查下

2022-12-22 03:45 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/adaface/__init__.py
> +        :param model_file: (str)Path of model file, e.g ppyoloe/model.pdmodel
ppyoloe.pdmodel -> adaface.pdmodel，这些注释文档都要尽可能清晰到对应的模型，避免用户看到产生疑惑，其余同理

2022-12-22 03:45 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/insightface/__init__.py
> +        :return: list of ClassifyResult(If the runtime_results is predict by batched samples, the length of this list equals to the batch size)
同上，ClassifyResult -> FaceRecognitionResult

2022-12-22 03:45 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/insightface/__init__.py
> +        :param model_file: (str)Path of model file, e.g ppyoloe/model.pdmodel
同上

2022-12-22 03:45 UTC, DefTruth commented on python/fastdeploy/vision/faceid/contrib/insightface/__init__.py
> +        assert self.initialized, "InsightFaceRecognitionBase model initialize failed."
这些assert的提示也改成对应的具体模型吧，不要都用 'InsightFaceRecognitionBase'

2022-12-23 09:23 UTC, Zheng-Bicheng commented on examples/vision/faceid/adaface/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.3.0.tgz
done

2022-12-26 13:01 UTC, jiangjiajun approved these changes

2022-12-26 13:01 UTC, jiangjiajun commented on examples/vision/faceid/adaface/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.3.0.tgz
这里文档不知道怎么被还原到老版本了，得改下

2022-12-26 13:01 UTC, jiangjiajun commented on examples/vision/faceid/insightface/cpp/README.md
> +wget https://bj.bcebos.com/fastdeploy/release/cpp/fastdeploy-linux-x64-0.3.0.tgz
同上

2022-12-26 13:01 UTC, jiangjiajun commented on cmake/rknpu2.cmake
> +#endif ()
为什么注释这段，而不是删除

2022-12-26 13:01 UTC, merged