[Model] add style transfer model (do not merge, examples to be added)
PaddlePaddle/FastDeploy pull request #922
Opened 2022-12-20 07:55 UTC by rainyfly

### PR types(PR类型)

Model
### Description

1. Add style transfer models in paddlehub into fastdeploy model repository.

2022-12-27 13:05 UTC, heliqi commented on fastdeploy/vision/generation/contrib/animegan.cc
> +bool AnimeGAN::Preprocess(std::vector<Mat>& images, std::vector<FDTensor>* outputs) {
需要参照YOLOV5、PaddleCls、PaddleDet等，将前后处理独立成一个类
https://github.com/PaddlePaddle/FastDeploy/tree/develop/fastdeploy/vision/detection/contrib/yolov5

2022-12-27 13:05 UTC, heliqi commented on fastdeploy/vision/generation/contrib/animegan.cc
> +      ret = Convert::Run(&images[i], {1.f / 127.5f, 1.f / 127.5f, 1.f / 127.5f}, {-1.f, -1.f, -1.f});
这几个值应该用带含义的变量

2022-12-28 02:10 UTC, rainyfly commented on fastdeploy/vision/generation/contrib/animegan.cc
> +bool AnimeGAN::Preprocess(std::vector<Mat>& images, std::vector<FDTensor>* outputs) {
这个前后处理比较简单，我看有的比较简单的前后处理都是直接放在一个类里了，https://github.com/PaddlePaddle/FastDeploy/blob/develop/fastdeploy/vision/classification/contrib/resnet.h

2022-12-28 02:28 UTC, rainyfly commented on fastdeploy/vision/generation/contrib/animegan.cc
> +      ret = Convert::Run(&images[i], {1.f / 127.5f, 1.f / 127.5f, 1.f / 127.5f}, {-1.f, -1.f, -1.f});
Done

2022-12-28 03:11 UTC, heliqi commented on fastdeploy/vision/generation/contrib/animegan.cc
> +bool AnimeGAN::Preprocess(std::vector<Mat>& images, std::vector<FDTensor>* outputs) {
那是以前的写法，新的写法都要独立成一个类，方便服务化调用。目前你这种方式，serving没法部署成服务

2022-12-29 03:21 UTC, rainyfly commented on fastdeploy/vision/generation/contrib/animegan.cc
> +bool AnimeGAN::Preprocess(std::vector<Mat>& images, std::vector<FDTensor>* outputs) {
done

2022-12-29 09:16 UTC, heliqi approved these changes
LGTM

2022-12-30 03:59 UTC, DefTruth requested changes

2022-12-30 03:59 UTC, DefTruth commented on fastdeploy/vision/generation/contrib/animegan.cc
> +  valid_gpu_backends = {Backend::PDINFER, Backend::TRT};
我看到GPU后端支持TRT，那理论上是可以转通过paddle2onnx转onnx的，所以ORT和openvino的后端是否也应该对应测试下？如果支持的话，一般来说性能会不错。

2022-12-30 03:59 UTC, DefTruth commented on examples/vision/generation/anemigan/README.md
> +## FastDeploy paddle backend部署和hub速度对比(ips)
这里速度是越高越好吗(ips)？可以加个注释，避免用户看到后产生疑惑

2022-12-30 03:59 UTC, DefTruth commented on fastdeploy/vision/generation/contrib/postprocessor.cc
> +  float* data = new float[shape[1]*shape[2]*3];
这个new出来的内存没有被释放，会导致内存泄漏。这里建议改用std::vector<float>，初始化时指定数据个数，避免内存泄露

2022-12-30 03:59 UTC, DefTruth commented on fastdeploy/vision/generation/contrib/postprocessor.cc
> +  res.copyTo(results->at(i));
另外，这个循环内的代码看起来似乎没有进行缩进，请检查下代码风格

2022-12-30 03:59 UTC, DefTruth commented on fastdeploy/vision/generation/contrib/postprocessor.cc
> +  Convert::Run(&result_mat, mean, std);
这里可以直接用Mat来创建一个零拷贝引用fp32数据，然后直接转uint8即可。  也不需要创建一个中间的data，这样会导致额外的内存创建和拷贝。
```
Mat result_mat = Mat::Create(shape[1], shape[2], 3, FDDataType::FP32, infer_result_data+i*size);
```

2022-12-30 03:59 UTC, DefTruth commented on fastdeploy/vision/vision_pybind.cc
> +void BindGenerationModel(pybind11::module& m);
这里改成BindGenertion吧，保持和其他模块写法的统一

2022-12-30 03:59 UTC, DefTruth commented on python/fastdeploy/vision/generation/contrib/anemigan.py
> +        # 调用基函数进行backend_option的初始化
删除中文注释或修改成英文，其余同理

2022-12-30 07:44 UTC, rainyfly commented on fastdeploy/vision/generation/contrib/animegan.cc
> +  valid_gpu_backends = {Backend::PDINFER, Backend::TRT};
GPU后端暂时不支持TRT，会报错，已经删除，报错原因已经提了icafe卡片，凡是需要转onnx的目前都会报错。

2022-12-30 07:44 UTC, rainyfly commented on examples/vision/generation/anemigan/README.md
> +## FastDeploy paddle backend部署和hub速度对比(ips)
done

2022-12-30 07:44 UTC, rainyfly commented on fastdeploy/vision/generation/contrib/postprocessor.cc
> +  float* data = new float[shape[1]*shape[2]*3];
done

2022-12-30 08:09 UTC, rainyfly commented on fastdeploy/vision/generation/contrib/postprocessor.cc
> +  res.copyTo(results->at(i));
done

2022-12-30 08:09 UTC, rainyfly commented on fastdeploy/vision/generation/contrib/postprocessor.cc
> +  Convert::Run(&result_mat, mean, std);
done

2022-12-30 08:09 UTC, rainyfly commented on fastdeploy/vision/vision_pybind.cc
> +void BindGenerationModel(pybind11::module& m);
done

2022-12-30 08:09 UTC, rainyfly commented on python/fastdeploy/vision/generation/contrib/anemigan.py
> +        # 调用基函数进行backend_option的初始化
done

2022-12-30 08:59 UTC, DefTruth approved these changes

2023-01-03 02:47 UTC, jiangjiajun approved these changes

2023-01-03 02:47 UTC, merged