[RKNPU2]support rknpu2 ClasModel #957
PaddlePaddle/FastDeploy pull request #964
Opened 2022-12-24 11:05 UTC by pengwei1024

### PR types(PR类型)
Model

### Description
support rknpu2 ClasModel  infer

2022-12-24 11:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=964) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/FastDeploy?pullRequest=964) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/FastDeploy?pullRequest=964) it.</sub>

2022-12-26 02:26 UTC, Zheng-Bicheng commented
Hello，感谢您提交pr。方便提供下您的模型文件吗？我这边下载测试一下

2022-12-26 07:26 UTC, Zheng-Bicheng commented
可以参考picodet，新增屏蔽normalize和permute的操作

2022-12-26 09:45 UTC, Zheng-Bicheng commented
关联issue:https://github.com/PaddlePaddle/FastDeploy/issues/957

2022-12-27 01:15 UTC, Zheng-Bicheng commented
另外，您的PR还缺少了如下部分:

* example代码，参考examples/vision/segmentation/paddleseg/rknpu2在ppcls下也新建一个rknpu2文件夹存放你的example代码
* python代码你测试了吗？按照这里面修改，python感觉应该是跑不通的。python/fastdeploy/vision/classification/ppcls/__init__.py这个文件应该也是要进行相应的修改的。也可以参考ppseg

2022-12-27 07:50 UTC, Zheng-Bicheng reviewed
按照要求修改一下哈

2022-12-27 07:50 UTC, Zheng-Bicheng commented on python/fastdeploy/vision/classification/ppcls/__init__.py
> +        assert model_format in [ModelFormat.PADDLE, ModelFormat.RKNN], "PaddleClasModel only support model format of ModelFormat.PADDLE、RKNN now."
这一行可以直接删除，不要用这种形式。因为RKNN跑的通说明ONNX也跑的通。并且理论上Openvino应该也跑的通的。

2022-12-27 07:50 UTC, Zheng-Bicheng commented on fastdeploy/vision/classification/ppcls/model.cc
> +    valid_cpu_backends = {Backend::OPENVINO, Backend::ORT,
这里不需要单独把RKNN领出来，因为model_format == ModelFormat::RKNN的情况下，其实只能跑在RKNPU上，另外两个backend会报错。可以尝试改成如下代码:
```
else {
    valid_cpu_backends = {Backend::ORT, Backend::OPENVINO};
    valid_gpu_backends = {Backend::ORT, Backend::TRT};
    valid_rknpu_backends = {Backend::RKNPU2};
  }
```

2022-12-27 07:50 UTC, Zheng-Bicheng commented on fastdeploy/vision/classification/ppcls/ppcls_pybind.cc
> +      }).def("DisableNormalize", [](vision::classification::PaddleClasPreprocessor& self) {
这里的pybind是为了让python能够调用c++的代码，在pthon中函数名字不是驼峰命名，请改成小写+下划线的形式。参考https://github.com/PaddlePaddle/FastDeploy/blob/b90a7e0fc903754bee7de5aed994e3a697f9ea64/fastdeploy/vision/segmentation/ppseg/ppseg_pybind.cc

2022-12-27 07:50 UTC, Zheng-Bicheng commented on fastdeploy/vision/classification/ppcls/ppcls_pybind.cc
> +      }).def("DisablePermute", [](vision::classification::PaddleClasPreprocessor& self) {
通上的问题。举个例子：
```
.def("DisableNormalize", [](vision::classification::PaddleClasPreprocessor& self) {
        self.DisableNormalize();
      })
```
改成
```
.def("disable_normalize", [](vision::classification::PaddleClasPreprocessor& self) {
        self.DisableNormalize();
      })
```
另外要注意你的代码要和上面对齐。每一个.def需要单独起一行写。

2022-12-27 07:50 UTC, Zheng-Bicheng commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +PaddleClasPreprocessor::PaddleClasPreprocessor(const std::string& config_file) : config_file(config_file) {
这里为什么要这么写？

2022-12-27 07:56 UTC, Zheng-Bicheng requested changes
按照要求修改下

2022-12-27 07:57 UTC, pengwei1024 commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +PaddleClasPreprocessor::PaddleClasPreprocessor(const std::string& config_file) : config_file(config_file) {
得记录下来config_file，因为 Preprocessor 在构造函数里面就初始化并加载 yaml 文件，DisableNormalize 需要刷新读取 config

2022-12-27 08:03 UTC, Zheng-Bicheng commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +PaddleClasPreprocessor::PaddleClasPreprocessor(const std::string& config_file) : config_file(config_file) {
可是这样和其他pp模型的预处理就不对齐了，改成如下案例？

* 在preprocess.h里面新增private的std::string config_file_参数;
* 在构造函数里this->config_file_ = config_file;
* 最后在BuildPreprocessPipelineFromConfig()函数里面
   ```
   cfg = YAML::LoadFile(config_file_);
   ```

2022-12-27 08:03 UTC, Zheng-Bicheng commented on fastdeploy/vision/classification/ppcls/preprocessor.cc
> +PaddleClasPreprocessor::PaddleClasPreprocessor(const std::string& config_file) : config_file(config_file) {
可以参考一下ppseg

2022-12-28 06:06 UTC, Zheng-Bicheng requested changes
您已提交的代码还存在如下问题，麻烦再修改下

2022-12-28 06:06 UTC, Zheng-Bicheng commented on examples/vision/classification/paddleclas/rknpu2/cpp/README.md
> +## 运行结果展示
这个运行结果是否正确和其他的模型对比过了吗？比如onnx模型

2022-12-28 06:06 UTC, Zheng-Bicheng commented on examples/vision/classification/paddleclas/rknpu2/cpp/infer.cc
> +           "e.g ./infer_model ./picodet_model_dir ./test.jpeg"
这里修改一下，不要用picodet_model_dir改成ppclas_model_dir吧。infer_model 也改成和cmake中同步

2022-12-28 06:06 UTC, Zheng-Bicheng commented on fastdeploy/vision/classification/ppcls/model.cc
>    } else if (model_format == ModelFormat::ONNX) {
可以考虑删除这部分代码
```c++
else if (model_format == ModelFormat::ONNX) {
    valid_cpu_backends = {Backend::ORT, Backend::OPENVINO};
    valid_gpu_backends = {Backend::ORT, Backend::TRT};
  }
```

2022-12-28 06:08 UTC, pengwei1024 commented on examples/vision/classification/paddleclas/rknpu2/cpp/README.md
> +## 运行结果展示
对比了，推理的分类是一样的，置信度差0.1以内

2022-12-28 06:09 UTC, Zheng-Bicheng commented
目前还缺少的部分为:
* 需要新增rknn模型转换配置脚本文件（请添加在tools/rknpu2/config目录下）
* 需要添加模型转换的文档，添加在example目录(examples/vision/classification/paddleclas/rknpu2)下

2022-12-28 06:38 UTC, Zheng-Bicheng requested changes
还有个小细节麻烦你能修改下

2022-12-28 06:38 UTC, Zheng-Bicheng commented on examples/vision/classification/paddleclas/rknpu2/README.md
> +# 配置文件 ResNet50_vd_infer_rknn.yaml 如下:
配置文件需要单列出来，你这样配置文件就写到bash里头了。可以新增一个配置文件的模块单独列配置文件，参考ppdet的模型转换代码

2022-12-28 07:38 UTC, Zheng-Bicheng requested changes
文档还有点小问题，再修改下。然后请在docs/cn/faq/rknpu2/rknpu2.md更新一下模型的运行速度，onnx没有测试的话不需要填。参考一下其他模型

2022-12-28 07:38 UTC, Zheng-Bicheng commented on examples/vision/classification/paddleclas/rknpu2/python/README.md
> +# ResNet50_vd Python部署示例
ResNet50_vd改成PPClas

2022-12-28 07:38 UTC, Zheng-Bicheng commented on examples/vision/classification/paddleclas/rknpu2/README.md
> +# ResNet50_vd模型部署
ResNet50_vd改成PPClas

2022-12-28 07:38 UTC, Zheng-Bicheng commented on examples/vision/classification/paddleclas/rknpu2/cpp/README.md
> +# ResNet50_vd C++部署示例
ResNet50_vd改成PPClas

2022-12-28 08:08 UTC, Zheng-Bicheng requested changes
还有一些小小小小的问题

2022-12-28 08:08 UTC, Zheng-Bicheng commented on docs/cn/faq/rknpu2/rknpu2.md
> +| PPClas           | ResNet50_vd       | ResNet50_vd                   | -/92               |
这里对应的是模型的使用场景，因此不能是PPClas,应该是Classification

2022-12-28 08:08 UTC, Zheng-Bicheng commented on examples/vision/classification/paddleclas/rknpu2/README.md
> +以转化RK3588的RKNN模型为例子，我们需要编辑tools/rknpu2/config/RK3568/ResNet50_vd_infer_rknn.yaml，来转换ONNX模型到RKNN模型。
应该是tools/rknpu2/config/ResNet50_vd_infer_rknn.yaml?

2022-12-28 08:09 UTC, Zheng-Bicheng commented on docs/cn/faq/rknpu2/rknpu2.md
> +| PPClas           | ResNet50_vd       | ResNet50_vd                   | -/92               |
第二行的ResNet50_vd应该改成ResNet

2022-12-28 08:14 UTC, Zheng-Bicheng approved these changes
LGTM

2022-12-28 08:16 UTC, Zheng-Bicheng commented
@jiangjiajun  贡献者完成了fp16的PPClas模型部署，但是还未完成全量化部署，这部分后面我来补充吧，可以先合入 。

2022-12-28 08:23 UTC, jiangjiajun requested changes
有几个注释/文档上的修改建议，其它没问题。改完即可Approve合入

2022-12-28 08:23 UTC, jiangjiajun commented on fastdeploy/vision/classification/ppcls/preprocessor.h
> +  // This function will disable normalize in preprocessing step.
注释需符合Doxygen语法，不然会无法生成API文档， 这里应该改成
```
/// This function will disable normalize in preprocessing step.
```
下面一个函数同理

2022-12-28 08:23 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/rknpu2/README.md
> +# PPClas 模型部署
标题改为 "PaddleClas 模型RKNPU2部署"

2022-12-28 08:23 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/rknpu2/python/README.md
> +# PPClas Python部署示例
标题改为 "PaddleClas Python部署示例"

2022-12-28 08:23 UTC, jiangjiajun commented on examples/vision/classification/paddleclas/rknpu2/cpp/README.md
> +# PPClas C++部署示例
标题改为 "PaddleClas C++部署示例“”

2022-12-28 08:32 UTC, pengwei1024 commented on examples/vision/classification/paddleclas/rknpu2/cpp/README.md
> +# PPClas C++部署示例
done

2022-12-28 08:33 UTC, jiangjiajun approved these changes

2022-12-28 08:33 UTC, jiangjiajun commented
Thanks for your contribution!

2022-12-28 09:58 UTC, merged