[Other] Add detection and segmentation examples for Ascend deploy.
PaddlePaddle/FastDeploy pull request #983
Opened 2022-12-27 07:47 UTC by yunyaoXYY

添加能够在昇腾上完成正确推理的 检测和分割模型examples

2022-12-30 10:27 UTC, jiangjiajun requested changes

2022-12-30 10:27 UTC, jiangjiajun commented on examples/vision/ocr/PP-OCRv2/cpp/infer.cc
> +  // rec_model.GetPreprocessor().SetStaticShapeInfer(true);
这里在跑Ascend时，需要打开这个注释是吗？

2022-12-30 10:27 UTC, jiangjiajun commented on examples/vision/ocr/PP-OCRv2/cpp/infer.cc
> +  // ppocr_v2.SetRecBatchSize(1);
同时还要打开这里的注释？

2022-12-30 10:29 UTC, yunyaoXYY commented on examples/vision/ocr/PP-OCRv2/cpp/infer.cc
> +  // rec_model.GetPreprocessor().SetStaticShapeInfer(true);
是的,目前就昇腾需要

2022-12-30 10:29 UTC, yunyaoXYY commented on examples/vision/ocr/PP-OCRv2/cpp/infer.cc
> +  // ppocr_v2.SetRecBatchSize(1);
是的，就这两个地方

2023-01-03 11:50 UTC, jiangjiajun approved these changes

2023-01-03 11:50 UTC, jiangjiajun commented on docs/cn/faq/use_sdk_on_ascend.md
> +- [FLyCV使用文档](./boost_cv_by_flycv.md)
这段应该放在build_and_install/build_on_ascend.md上

2023-01-03 11:50 UTC, jiangjiajun commented on docs/en/faq/use_sdk_on_ascend.md
> +- [Enable FlyCV](./boost_cv_by_flycv.md)
同上

2023-01-03 12:09 UTC, yunyaoXYY commented on docs/en/faq/use_sdk_on_ascend.md
> +- [Enable FlyCV](./boost_cv_by_flycv.md)
> 同上

Done

2023-01-03 12:10 UTC, yunyaoXYY commented on docs/cn/faq/use_sdk_on_ascend.md
> +- [FLyCV使用文档](./boost_cv_by_flycv.md)
> 这段应该放在build_and_install/build_on_ascend.md上

Done

2023-01-04 02:01 UTC, merged