[Other]Add FlyCV for RV1126
PaddlePaddle/FastDeploy pull request #985
Opened 2022-12-27 08:15 UTC by yeliang2258

### PR types(PR类型)

### Description

Add FlyCV for RV1126

2022-12-27 13:32 UTC, jiangjiajun requested changes

2022-12-27 13:32 UTC, jiangjiajun commented on cmake/flycv.cmake
> +      set(FLYCV_FILE "flycv-linux-armhf-${FLYCV_VERSION}.tgz")
这个CMAKE_SYSTEM_PROCESSOR判断的是宿主机还是开发板？ rv1126应该是交叉编译的？

2022-12-28 02:13 UTC, yeliang2258 commented on cmake/flycv.cmake
> +      set(FLYCV_FILE "flycv-linux-armhf-${FLYCV_VERSION}.tgz")
交叉编译的，在toolchain.cmake里面设置了CMAKE_SYSTEM_PROCESSOR，可以用这个判断是aarch64还是arm

2022-12-28 02:46 UTC, jiangjiajun approved these changes

2022-12-28 02:46 UTC, merged